"""MBT Luke 19-24 — Zacchaeus through Resurrection and Ascension. 313 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch19 = {
    1: "And He entered Jericho and was passing through.",
    2: "And behold, there was a man called by the name of Zacchaeus. And he was a chief tax-gatherer, and he was rich.",
    3: "And he was trying to see who Jesus was, and was unable on account of the crowd — because he was small in stature.",
    4: "And he ran on ahead and climbed up into a sycamore tree in order to see Him — for He was about to pass through that way.",
    5: "And when Jesus came to the place, He looked up and said to him, \"Zacchaeus, hurry and come down — for today I must stay at your house.\"",
    6: "And he hurried and came down, and received Him gladly.",
    7: "And when they saw it, they all began to grumble, saying, \"He has gone in to be the guest of a man who is a sinner.\"",
    8: "And Zacchaeus stopped and said to the Lord, \"Behold, Lord, half of my possessions I will give to the poor — and if I have defrauded anyone of anything, I will give back four times as much.\"",
    9: "And Jesus said to him, \"Today salvation has come to this house — because he, too, is a son of Abraham.",
    10: "For the Son of Man has come to seek and to save that which was lost.\"",
    11: "And while they were listening to these things, He went on to tell a parable, because He was near Jerusalem, and they supposed that the kingdom of God was going to appear immediately.",
    12: "He said therefore, \"A certain nobleman went to a distant country to receive a kingdom for himself, and then return.",
    13: "And he called ten of his slaves, and gave them ten minas, and said to them, 'Do business with this until I come back.'",
    14: "But his citizens hated him, and sent a delegation after him, saying, 'We do not want this man to reign over us.'",
    15: "And it came about that when he returned, after receiving the kingdom, he ordered that these slaves, to whom he had given the money, be called to him in order that he might know what business they had done.",
    16: "And the first appeared, saying, 'Master, your mina has made ten minas more.'",
    17: "And he said to him, 'Well done, good slave. Because you have been faithful in a very little thing, you are to be in authority over ten cities.'",
    18: "And the second came, saying, 'Your mina, master, has made five minas.'",
    19: "And he said to him also, 'And you are to be over five cities.'",
    20: "And another came, saying, 'Master, behold your mina, which I kept put away in a handkerchief.",
    21: "For I was afraid of you, because you are an exacting man. You take up what you did not lay down, and reap what you did not sow.'",
    22: "He said to him, 'By your own words I will judge you, you worthless slave. Did you know that I am an exacting man, taking up what I did not lay down, and reaping what I did not sow?",
    23: "Then why did you not put the money in the bank, and having come, I would have collected it with interest?'",
    24: "And he said to the bystanders, 'Take the mina away from him, and give it to the one who has the ten minas.'",
    25: "(And they said to him, 'Master, he has ten minas already.')",
    26: "I tell you, that to everyone who has shall more be given — but from the one who does not have, even what he does have shall be taken away.",
    27: "But these enemies of mine, who did not want me to reign over them, bring them here, and slay them in my presence.\"",
    28: "And after He had said these things, He was going on ahead, ascending to Jerusalem.",
    29: "And it came about that when He approached Bethphage and Bethany, near the mount that is called Olivet, He sent two of the disciples,",
    30: "saying, \"Go into the village ahead of you. There, as you enter, you will find a colt tied, on which no one yet has ever sat — untie it, and bring it here.",
    31: "And if anyone asks you, 'Why are you untying it?' — thus shall you speak: 'The Lord has need of it.'\"",
    32: "And those who were sent went away and found it just as He had told them.",
    33: "And as they were untying the colt, its owners said to them, \"Why are you untying the colt?\"",
    34: "And they said, \"The Lord has need of it.\"",
    35: "And they brought it to Jesus. And they threw their garments on the colt, and put Jesus on it.",
    36: "And as He was going, they were spreading their garments in the road.",
    37: "And as He was now approaching, near the descent of the Mount of Olives, the whole multitude of the disciples began to praise God joyfully with a loud voice for all the miracles which they had seen,",
    38: "saying, \"Blessed is the King who comes in the name of the Lord! Peace in heaven and glory in the highest!\"",
    39: "And some of the Pharisees in the multitude said to Him, \"Teacher, rebuke Your disciples.\"",
    40: "And He answered and said, \"I tell you, if these become silent, the stones will cry out!\"",
    41: "And when He approached, He saw the city and wept over it,",
    42: "saying, \"If you had known in this day, even you, the things which make for peace! But now they have been hidden from your eyes.",
    43: "For the days shall come upon you when your enemies will throw up a bank before you, and surround you, and hem you in on every side,",
    44: "and will level you to the ground and your children within you — and they will not leave in you one stone upon another. Because you did not recognize the time of your visitation.\"",
    45: "And He entered the temple and began to cast out those who were selling,",
    46: "saying to them, \"It is written, 'And My house shall be a house of prayer' — but you have made it a robbers' den.\"",
    47: "And He was teaching daily in the temple. But the chief priests and the scribes and the leading men among the people were trying to destroy Him,",
    48: "and they could not find anything that they might do — for all the people were hanging upon His words.",
}
ch20 = {
    1: "And it came about on one of the days while He was teaching the people in the temple, and preaching the gospel, that the chief priests and the scribes with the elders confronted Him,",
    2: "and they spoke, saying to Him, \"Tell us by what authority You are doing these things, or who is the one who gave You this authority?\"",
    3: "And He answered and said to them, \"I shall also ask you a question, and you tell Me —",
    4: "was the baptism of John from heaven or from men?\"",
    5: "And they reasoned among themselves, saying, \"If we say, 'From heaven,' He will say, 'Why did you not believe him?'",
    6: "But if we say, 'From men,' all the people will stone us to death — for they are convinced that John was a prophet.\"",
    7: "And they answered that they did not know where it came from.",
    8: "And Jesus said to them, \"Neither will I tell you by what authority I do these things.\"",
    9: "And He began to tell the people this parable: \"A man planted a vineyard and rented it out to vine-growers, and went on a journey for a long time.",
    10: "And at the harvest time he sent a slave to the vine-growers, in order that they might give him some of the produce of the vineyard. But the vine-growers beat him and sent him away empty-handed.",
    11: "And he proceeded to send another slave. And they beat him also and treated him shamefully, and sent him away empty-handed.",
    12: "And he proceeded to send a third. And this one also they wounded and cast out.",
    13: "And the owner of the vineyard said, 'What shall I do? I will send my beloved son. Perhaps they will respect him.'",
    14: "But when the vine-growers saw him, they reasoned with one another, saying, 'This is the heir. Let us kill him, that the inheritance may be ours.'",
    15: "And they threw him out of the vineyard and killed him. What, therefore, will the owner of the vineyard do to them?",
    16: "He will come and destroy these vine-growers and will give the vineyard to others.\" And when they heard it, they said, \"May it never be!\"",
    17: "But He looked at them and said, \"What then is this that is written: 'The stone which the builders rejected, this became the chief corner stone'?",
    18: "Everyone who falls on that stone will be broken to pieces — but on whomever it falls, it will scatter him like dust.\"",
    19: "And the scribes and the chief priests tried to lay hands on Him that very hour, and they feared the people. For they understood that He spoke this parable against them.",
    20: "And they watched Him, and sent spies who pretended to be righteous, in order that they might catch Him in some statement — so as to deliver Him up to the rule and the authority of the governor.",
    21: "And they questioned Him, saying, \"Teacher, we know that You speak and teach correctly, and You are not partial to any, but teach the way of God in truth.",
    22: "Is it lawful for us to pay taxes to Caesar, or not?\"",
    23: "But He detected their trickery and said to them,",
    24: "\"Show Me a denarius. Whose likeness and inscription does it have?\" And they said, \"Caesar's.\"",
    25: "And He said to them, \"Then render to Caesar the things that are Caesar's — and to God the things that are God's.\"",
    26: "And they were unable to catch Him in a saying in the presence of the people. And marveling at His answer, they became silent.",
    27: "Now there came to Him some of the Sadducees (who say that there is no resurrection),",
    28: "and they questioned Him, saying, \"Teacher, Moses wrote for us that if a man's brother dies, having a wife, and he is childless, his brother should take the wife and raise up offspring to his brother.",
    29: "Now there were seven brothers. And the first took a wife and died childless.",
    30: "And the second",
    31: "and the third took her. And in the same way all seven died, leaving no children.",
    32: "Finally the woman died also.",
    33: "In the resurrection therefore, which one's wife does the woman become? For all seven had married her.\"",
    34: "And Jesus said to them, \"The sons of this age marry, and are given in marriage —",
    35: "but those who are considered worthy to attain to that age and the resurrection from the dead, neither marry nor are given in marriage.",
    36: "For neither can they die anymore, for they are like angels, and are sons of God — being sons of the resurrection.",
    37: "But that the dead are raised, even Moses showed, in the passage about the burning bush, where he calls the Lord 'the God of Abraham, and the God of Isaac, and the God of Jacob.'",
    38: "Now He is not the God of the dead but of the living — for all live to Him.\"",
    39: "And some of the scribes answered and said, \"Teacher, You have spoken well.\"",
    40: "For they did not have courage to question Him any longer about anything.",
    41: "And He said to them, \"How is it that they say the Christ is David's son?",
    42: "For David himself says in the book of Psalms, 'The Lord said to my Lord, \"Sit at My right hand,",
    43: "until I make Your enemies a footstool of Your feet.\"'",
    44: "David therefore calls Him 'Lord' — and how is He his son?\"",
    45: "And while all the people were listening, He said to the disciples,",
    46: "\"Beware of the scribes, who like to walk around in long robes, and love respectful greetings in the market places, and chief seats in the synagogues, and places of honor at banquets —",
    47: "who devour widows' houses, and for appearance's sake offer long prayers. These will receive greater condemnation.\"",
}
ch21 = {
    1: "And He looked up and saw the rich putting their gifts into the treasury.",
    2: "And He saw a certain poor widow putting in two small copper coins.",
    3: "And He said, \"Truly I say to you, this poor widow put in more than all of them.",
    4: "For they all out of their surplus put into the offering — but she out of her poverty put in all that she had to live on.\"",
    5: "And while some were talking about the temple, that it was adorned with beautiful stones and votive gifts, He said,",
    6: "\"As for these things which you are looking at, the days will come in which there will not be left one stone upon another, which will not be torn down.\"",
    7: "And they questioned Him, saying, \"Teacher, when therefore will these things be? And what will be the sign when these things are about to take place?\"",
    8: "And He said, \"See to it that you be not misled. For many will come in My name, saying, 'I am He,' and, 'The time is at hand.' Do not go after them.",
    9: "And when you hear of wars and disturbances, do not be terrified. For these things must take place first — but the end does not follow immediately.\"",
    10: "Then He continued by saying to them, \"Nation will rise against nation, and kingdom against kingdom.",
    11: "And there will be great earthquakes, and in various places plagues and famines. And there will be terrors and great signs from heaven.",
    12: "But before all these things, they will lay their hands on you and will persecute you, delivering you to the synagogues and prisons, bringing you before kings and governors for My name's sake.",
    13: "It will lead to an opportunity for your testimony.",
    14: "So make up your minds not to prepare beforehand to defend yourselves —",
    15: "for I will give you utterance and wisdom, which none of your opponents will be able to resist or refute.",
    16: "But you will be delivered up even by parents and brothers and relatives and friends — and they will put some of you to death.",
    17: "And you will be hated by all on account of My name.",
    18: "Yet not a hair of your head will perish.",
    19: "By your endurance you will gain your lives.",
    20: "But when you see Jerusalem surrounded by armies, then recognize that her desolation is at hand.",
    21: "Then let those who are in Judea flee to the mountains. And let those who are in the midst of the city depart, and let not those who are in the country enter the city.",
    22: "Because these are days of vengeance, in order that all things which are written may be fulfilled.",
    23: "Woe to those who are with child and to those who nurse babes in those days. For there will be great distress upon the land, and wrath to this people.",
    24: "And they will fall by the edge of the sword, and will be led captive into all the nations. And Jerusalem will be trampled under foot by the Gentiles until the times of the Gentiles be fulfilled.",
    25: "And there will be signs in sun and moon and stars — and upon the earth dismay among nations, in perplexity at the roaring of the sea and the waves,",
    26: "men fainting from fear and the expectation of the things which are coming upon the world — for the powers of the heavens will be shaken.",
    27: "And then they will see the Son of Man coming in a cloud with power and great glory.",
    28: "But when these things begin to take place, straighten up and lift up your heads — because your redemption is drawing near.\"",
    29: "And He told them a parable: \"Behold the fig tree and all the trees —",
    30: "as soon as they put forth leaves, you see it and know for yourselves that summer is now near.",
    31: "Even so you, too, when you see these things happening, recognize that the kingdom of God is near.",
    32: "Truly I say to you, this generation will not pass away until all things take place.",
    33: "Heaven and earth will pass away — but My words will not pass away.",
    34: "Be on guard, that your hearts may not be weighted down with dissipation and drunkenness and the worries of life, and that day come on you suddenly like a trap —",
    35: "for it will come upon all those who dwell on the face of all the earth.",
    36: "But keep on the alert at all times, praying in order that you may have strength to escape all these things that are about to take place, and to stand before the Son of Man.\"",
    37: "Now during the day He was teaching in the temple — but at evening He would go out and spend the night on the mount that is called Olivet.",
    38: "And all the people would get up early in the morning to come to Him in the temple to listen to Him.",
}
ch22 = {
    1: "Now the Feast of Unleavened Bread, which is called the Passover, was approaching.",
    2: "And the chief priests and the scribes were seeking how they might put Him to death — for they were afraid of the people.",
    3: "And Satan entered into Judas who was called Iscariot, belonging to the number of the twelve.",
    4: "And he went away and discussed with the chief priests and officers how he might betray Him to them.",
    5: "And they were glad, and agreed to give him money.",
    6: "And he consented, and began seeking a good opportunity to betray Him to them apart from the multitude.",
    7: "Then came the day of Unleavened Bread on which the Passover lamb had to be sacrificed.",
    8: "And He sent Peter and John, saying, \"Go and prepare the Passover for us, that we may eat it.\"",
    9: "And they said to Him, \"Where do You want us to prepare it?\"",
    10: "And He said to them, \"Behold, when you have entered the city, a man will meet you carrying a pitcher of water. Follow him into the house that he enters.",
    11: "And you shall say to the owner of the house, 'The Teacher says to you, \"Where is the guest room in which I may eat the Passover with My disciples?\"'",
    12: "And he will show you a large, furnished upper room — prepare it there.\"",
    13: "And they departed and found everything just as He had told them. And they prepared the Passover.",
    14: "And when the hour had come, He reclined at the table, and the apostles with Him.",
    15: "And He said to them, \"I have earnestly desired to eat this Passover with you before I suffer.",
    16: "For I say to you, I shall never again eat it until it is fulfilled in the kingdom of God.\"",
    17: "And when He had taken a cup and given thanks, He said, \"Take this and share it among yourselves.",
    18: "For I say to you, I will not drink of the fruit of the vine from now on until the kingdom of God comes.\"",
    19: "And when He had taken some bread and given thanks, He broke it, and gave it to them, saying, \"This is My body which is given for you. Do this in remembrance of Me.\"",
    20: "And in the same way He took the cup after they had eaten, saying, \"This cup which is poured out for you is the new covenant in My blood.",
    21: "But behold, the hand of the one betraying Me is with Mine on the table.",
    22: "For indeed, the Son of Man is going as it has been determined — but woe to that man by whom He is betrayed!\"",
    23: "And they began to discuss among themselves which one of them it might be who was going to do this thing.",
    24: "And there arose also a dispute among them as to which one of them was regarded to be greatest.",
    25: "And He said to them, \"The kings of the Gentiles lord it over them — and those who have authority over them are called Benefactors.",
    26: "But not so with you — but let him who is the greatest among you become as the youngest, and the leader as the servant.",
    27: "For who is greater, the one who reclines at the table, or the one who serves? Is it not the one who reclines at the table? But I am among you as the one who serves.",
    28: "And you are those who have stood by Me in My trials.",
    29: "And just as My Father has granted Me a kingdom, I grant you",
    30: "that you may eat and drink at My table in My kingdom, and you will sit on thrones judging the twelve tribes of Israel.",
    31: "Simon, Simon, behold, Satan has demanded permission to sift you like wheat.",
    32: "But I have prayed for you, that your faith may not fail. And you, when once you have turned again, strengthen your brothers.\"",
    33: "And he said to Him, \"Lord, with You I am ready to go both to prison and to death!\"",
    34: "And He said, \"I say to you, Peter, the rooster will not crow today until you have denied three times that you know Me.\"",
    35: "And He said to them, \"When I sent you out without purse and bag and sandals, you did not lack anything, did you?\" And they said, \"No, nothing.\"",
    36: "And He said to them, \"But now, let him who has a purse take it along, likewise also a bag. And let him who has no sword sell his robe and buy one.",
    37: "For I tell you, that this which is written must be fulfilled in Me: 'And He was numbered with transgressors.' For that which refers to Me has its fulfillment.\"",
    38: "And they said, \"Lord, look — here are two swords.\" And He said to them, \"It is enough.\"",
    39: "And He came out and proceeded as was His custom to the Mount of Olives. And the disciples also followed Him.",
    40: "And when He arrived at the place, He said to them, \"Pray that you may not enter into temptation.\"",
    41: "And He withdrew from them about a stone's throw, and knelt down and began to pray,",
    42: "saying, \"Father, if You are willing, remove this cup from Me. Yet not My will, but Yours be done.\"",
    43: "Now an angel from heaven appeared to Him, strengthening Him.",
    44: "And being in agony He was praying very fervently — and His sweat became like drops of blood, falling down upon the ground.",
    45: "And when He rose from prayer, He came to the disciples and found them sleeping from sorrow.",
    46: "And He said to them, \"Why are you sleeping? Rise and pray, that you may not enter into temptation.\"",
    47: "While He was still speaking, behold, a multitude came — and the one called Judas, one of the twelve, was preceding them. And he approached Jesus to kiss Him.",
    48: "But Jesus said to him, \"Judas, are you betraying the Son of Man with a kiss?\"",
    49: "And when those who were around Him saw what was going to happen, they said, \"Lord, shall we strike with the sword?\"",
    50: "And a certain one of them struck the slave of the high priest and cut off his right ear.",
    51: "But Jesus answered and said, \"Stop! No more of this.\" And He touched his ear and healed him.",
    52: "And Jesus said to the chief priests and officers of the temple and elders who had come against Him, \"Have you come out with swords and clubs as you would against a robber?",
    53: "While I was with you daily in the temple, you did not lay hands on Me. But this hour and the power of darkness are yours.\"",
    54: "And having arrested Him, they led Him away, and brought Him to the house of the high priest. But Peter was following at a distance.",
    55: "And after they had kindled a fire in the middle of the courtyard and had sat down together, Peter was sitting among them.",
    56: "And a certain servant-girl, seeing him as he sat in the firelight, and looking intently at him, said, \"This man was with Him too.\"",
    57: "But he denied it, saying, \"Woman, I do not know Him.\"",
    58: "And a little later, another saw him and said, \"You are one of them too!\" But Peter said, \"Man, I am not!\"",
    59: "And after about an hour had passed, another man began to insist, saying, \"Certainly this man also was with Him — for he is a Galilean too.\"",
    60: "But Peter said, \"Man, I do not know what you are talking about.\" And immediately, while he was still speaking, a rooster crowed.",
    61: "And the Lord turned and looked at Peter. And Peter remembered the word of the Lord, how He had told him, \"Before a rooster crows today, you will deny Me three times.\"",
    62: "And he went out and wept bitterly.",
    63: "And the men who were holding Jesus in custody were mocking Him, and beating Him.",
    64: "And they blindfolded Him and were asking Him, saying, \"Prophesy, who is the one who hit You?\"",
    65: "And they were saying many other things against Him, blaspheming.",
    66: "And when it was day, the Council of elders of the people assembled, both chief priests and scribes — and they led Him away to their council chamber, saying,",
    67: "\"If You are the Christ, tell us.\" But He said to them, \"If I tell you, you will not believe.",
    68: "And if I ask a question, you will not answer.",
    69: "But from now on the Son of Man will be seated at the right hand of the power of God.\"",
    70: "And they all said, \"Are You the Son of God, then?\" And He said to them, \"Yes — I am.\"",
    71: "And they said, \"What further need do we have of testimony? For we have heard it ourselves from His own mouth.\"",
}
ch23 = {
    1: "Then the whole body of them arose and brought Him before Pilate.",
    2: "And they began to accuse Him, saying, \"We found this man misleading our nation, and forbidding to pay taxes to Caesar, and saying that He Himself is Christ, a King.\"",
    3: "And Pilate asked Him, saying, \"Are You the King of the Jews?\" And He answered him and said, \"It is as you say.\"",
    4: "And Pilate said to the chief priests and the multitudes, \"I find no guilt in this man.\"",
    5: "But they kept on insisting, saying, \"He stirs up the people, teaching all over Judea, starting from Galilee, even as far as this place.\"",
    6: "But when Pilate heard it, he asked whether the man was a Galilean.",
    7: "And when he learned that He belonged to Herod's jurisdiction, he sent Him to Herod, who himself also was in Jerusalem at that time.",
    8: "Now Herod was very glad when he saw Jesus — for he had wanted to see Him for a long time, because he had been hearing about Him and was hoping to see some sign performed by Him.",
    9: "And he questioned Him at some length — but He answered him nothing.",
    10: "And the chief priests and the scribes were standing there, accusing Him vehemently.",
    11: "And Herod with his soldiers, after treating Him with contempt and mocking Him, dressed Him in a gorgeous robe and sent Him back to Pilate.",
    12: "Now Herod and Pilate became friends with one another that very day — for before they had been at enmity with each other.",
    13: "And Pilate summoned the chief priests and the rulers and the people,",
    14: "and said to them, \"You brought this man to me as one who incites the people to rebellion — and behold, having examined Him before you, I have found no guilt in this man regarding the charges which you make against Him.",
    15: "No, nor has Herod — for he sent Him back to us. And behold, nothing deserving death has been done by Him.",
    16: "I will therefore punish Him and release Him.\"",
    17: "(Now he was obliged to release to them at the feast one prisoner.)",
    18: "But they cried out all together, saying, \"Away with this man, and release for us Barabbas!\"",
    19: "(He was one who had been thrown into prison for a certain insurrection made in the city, and for murder.)",
    20: "And Pilate, wanting to release Jesus, addressed them again.",
    21: "But they kept on calling out, saying, \"Crucify, crucify Him!\"",
    22: "And he said to them the third time, \"Why, what evil has this man done? I have found in Him no guilt demanding death. I will therefore punish Him and release Him.\"",
    23: "But they were insistent, with loud voices asking that He be crucified. And their voices began to prevail.",
    24: "And Pilate pronounced sentence that their demand should be granted.",
    25: "And he released the man they were asking for who had been thrown into prison for insurrection and murder — but he delivered Jesus to their will.",
    26: "And when they led Him away, they laid hold of one Simon of Cyrene, coming in from the country, and placed on him the cross to carry behind Jesus.",
    27: "And there were following Him a great multitude of the people, and of women who were mourning and lamenting Him.",
    28: "But Jesus turning to them said, \"Daughters of Jerusalem, stop weeping for Me — but weep for yourselves and for your children.",
    29: "For behold, the days are coming when they will say, 'Blessed are the barren, and the wombs that never bore, and the breasts that never nursed.'",
    30: "Then they will begin to say to the mountains, 'Fall on us!' — and to the hills, 'Cover us!'",
    31: "For if they do these things in the green tree, what will happen in the dry?\"",
    32: "And two others also, who were criminals, were being led away to be put to death with Him.",
    33: "And when they came to the place called The Skull, there they crucified Him and the criminals, one on the right and the other on the left.",
    34: "But Jesus was saying, \"Father, forgive them — for they do not know what they are doing.\" And they cast lots, dividing up His garments among themselves.",
    35: "And the people stood by, looking on. And even the rulers were sneering at Him, saying, \"He saved others — let Him save Himself if this is the Christ of God, His Chosen One.\"",
    36: "And the soldiers also mocked Him, coming up to Him, offering Him sour wine,",
    37: "and saying, \"If You are the King of the Jews, save Yourself!\"",
    38: "Now there was also an inscription above Him, \"This is the King of the Jews.\"",
    39: "And one of the criminals who were hanged there was hurling abuse at Him, saying, \"Are You not the Christ? Save Yourself and us!\"",
    40: "But the other answered, and rebuking him said, \"Do you not even fear God, since you are under the same sentence of condemnation?",
    41: "And we indeed are suffering justly, for we are receiving what we deserve for our deeds. But this man has done nothing wrong.\"",
    42: "And he was saying, \"Jesus, remember me when You come in Your kingdom!\"",
    43: "And He said to him, \"Truly I say to you, today you shall be with Me in Paradise.\"",
    44: "And it was now about the sixth hour, and darkness fell over the whole land until the ninth hour.",
    45: "The sun being obscured. And the veil of the temple was torn in two.",
    46: "And Jesus, crying out with a loud voice, said, \"Father, into Your hands I commit My spirit.\" And having said this, He breathed His last.",
    47: "Now when the centurion saw what had happened, he began praising God, saying, \"Certainly this man was innocent.\"",
    48: "And all the multitudes who came together for this spectacle, when they observed what had happened, began to return, beating their breasts.",
    49: "And all His acquaintances and the women who accompanied Him from Galilee, were standing at a distance, seeing these things.",
    50: "And behold, there was a man named Joseph, who was a member of the Council — a good and righteous man",
    51: "(he had not consented to their plan and action), a man from Arimathea, a city of the Jews — who was waiting for the kingdom of God.",
    52: "This man went to Pilate and asked for the body of Jesus.",
    53: "And he took it down and wrapped it in a linen cloth, and laid Him in a tomb cut into the rock, where no one had ever lain.",
    54: "And it was the preparation day, and the Sabbath was about to begin.",
    55: "Now the women who had come with Him out of Galilee followed after, and saw the tomb and how His body was laid.",
    56: "And they returned and prepared spices and perfumes. And on the Sabbath they rested according to the commandment.",
}
ch24 = {
    1: "But on the first day of the week, at early dawn, they came to the tomb, bringing the spices which they had prepared.",
    2: "And they found the stone rolled away from the tomb,",
    3: "but when they entered, they did not find the body of the Lord Jesus.",
    4: "And it happened that while they were perplexed about this, behold, two men suddenly stood near them in dazzling clothing.",
    5: "And as the women were terrified and bowed their faces to the ground, the men said to them, \"Why do you seek the living One among the dead?",
    6: "He is not here, but He has risen. Remember how He spoke to you while He was still in Galilee,",
    7: "saying that the Son of Man must be delivered into the hands of sinful men, and be crucified, and the third day rise again.\"",
    8: "And they remembered His words.",
    9: "And they returned from the tomb and reported all these things to the eleven and to all the rest.",
    10: "Now they were Mary Magdalene and Joanna and Mary the mother of James. Also the other women with them were telling these things to the apostles.",
    11: "And these words appeared to them as nonsense, and they would not believe them.",
    12: "But Peter arose and ran to the tomb. And stooping and looking in, he saw the linen wrappings only — and he went away to his home, marveling at that which had happened.",
    13: "And behold, two of them were going that very day to a village named Emmaus, which was about seven miles from Jerusalem.",
    14: "And they were conversing with each other about all these things which had taken place.",
    15: "And it came about that while they were conversing and discussing, Jesus Himself approached, and began traveling with them.",
    16: "But their eyes were prevented from recognizing Him.",
    17: "And He said to them, \"What are these words that you are exchanging with one another as you are walking?\" And they stood still, looking sad.",
    18: "And one of them, named Cleopas, answered and said to Him, \"Are You the only one visiting Jerusalem and unaware of the things which have happened here in these days?\"",
    19: "And He said to them, \"What things?\" And they said to Him, \"The things about Jesus the Nazarene, who was a prophet mighty in deed and word in the sight of God and all the people,",
    20: "and how the chief priests and our rulers delivered Him up to the sentence of death, and crucified Him.",
    21: "But we were hoping that it was He who was going to redeem Israel. Indeed, besides all this, it is the third day since these things happened.",
    22: "But also some women among us amazed us. When they were at the tomb early in the morning,",
    23: "and did not find His body, they came, saying that they had also seen a vision of angels, who said that He was alive.",
    24: "And some of those who were with us went to the tomb, and found it just exactly as the women also had said — but Him they did not see.\"",
    25: "And He said to them, \"O foolish men and slow of heart to believe in all that the prophets have spoken!",
    26: "Was it not necessary for the Christ to suffer these things and to enter into His glory?\"",
    27: "And beginning with Moses and with all the prophets, He explained to them the things concerning Himself in all the Scriptures.",
    28: "And they approached the village where they were going, and He acted as though He would go farther.",
    29: "And they urged Him, saying, \"Stay with us — for it is getting toward evening, and the day is now nearly over.\" So He went in to stay with them.",
    30: "And it came about that when He had reclined at the table with them, He took the bread and blessed it, and breaking it, He began giving it to them.",
    31: "And their eyes were opened and they recognized Him — and He vanished from their sight.",
    32: "And they said to one another, \"Were not our hearts burning within us while He was speaking to us on the road, while He was explaining the Scriptures to us?\"",
    33: "And they arose that very hour and returned to Jerusalem, and found gathered together the eleven and those who were with them,",
    34: "saying, \"The Lord has really risen, and has appeared to Simon.\"",
    35: "And they began to relate their experiences on the road, and how He was recognized by them in the breaking of the bread.",
    36: "And while they were telling these things, He Himself stood in their midst.",
    37: "But they were startled and frightened, and thought they were seeing a spirit.",
    38: "And He said to them, \"Why are you troubled, and why do doubts arise in your hearts?",
    39: "See My hands and My feet, that it is I Myself. Touch Me and see — for a spirit does not have flesh and bones as you see that I have.\"",
    40: "And when He had said this, He showed them His hands and His feet.",
    41: "And while they still could not believe it for joy and were marveling, He said to them, \"Have you anything here to eat?\"",
    42: "And they gave Him a piece of a broiled fish.",
    43: "And He took it and ate it before them.",
    44: "Now He said to them, \"These are My words which I spoke to you while I was still with you, that all things which are written about Me in the Law of Moses and the Prophets and the Psalms must be fulfilled.\"",
    45: "Then He opened their minds to understand the Scriptures,",
    46: "and He said to them, \"Thus it is written, that the Christ should suffer and rise again from the dead the third day,",
    47: "and that repentance for forgiveness of sins should be proclaimed in His name to all the nations, beginning from Jerusalem.",
    48: "You are witnesses of these things.",
    49: "And behold, I am sending forth the promise of My Father upon you — but you are to stay in the city until you are clothed with power from on high.\"",
    50: "And He led them out as far as Bethany, and He lifted up His hands and blessed them.",
    51: "And it came about that while He was blessing them, He parted from them and was carried up into heaven.",
    52: "And they, after worshiping Him, returned to Jerusalem with great joy,",
    53: "and were continually in the temple, praising God.",
}

CHAPTERS = {19:ch19,20:ch20,21:ch21,22:ch22,23:ch23,24:ch24}

def main():
    new_entries = {f"42_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Luke 19-24 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Luke 19-24 verses")

if __name__ == "__main__":
    main()
