"""MBT Mark 9-16 — Transfiguration through resurrection. 355 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch9 = {
    1: "And He was saying to them, \"Truly I say to you — there are some of those who are standing here who shall not taste of death, until they see the kingdom of God come with power.\"",
    2: "And six days later, Jesus took with Him Peter and James and John, and brought them up to a high mountain by themselves. And He was transfigured before them.",
    3: "And His garments became radiant — exceedingly white, as no launderer on earth can whiten them.",
    4: "And Elijah appeared to them along with Moses — and they were talking with Jesus.",
    5: "And Peter said to Jesus, \"Rabbi, it is good that we are here. Let us make three tabernacles — one for You, and one for Moses, and one for Elijah.\"",
    6: "For he did not know what to answer — for they became terrified.",
    7: "And a cloud formed, overshadowing them — and a voice came out of the cloud, \"This is My beloved Son. Listen to Him!\"",
    8: "And all at once they looked around and saw no one with them anymore — except Jesus alone.",
    9: "And as they were coming down from the mountain, He gave them orders not to relate to anyone what they had seen — until the Son of Man should rise from the dead.",
    10: "And they seized upon that statement, discussing with one another what rising from the dead might mean.",
    11: "And they asked Him, saying, \"Why is it that the scribes say that Elijah must come first?\"",
    12: "And He said to them, \"Elijah does first come and restore all things. And yet how is it written of the Son of Man, that He should suffer many things and be treated with contempt?",
    13: "But I say to you that Elijah has indeed come — and they did to him whatever they wished, just as it is written of him.\"",
    14: "And when they came back to the disciples, they saw a great multitude around them — and some scribes arguing with them.",
    15: "And immediately, when the entire crowd saw Him, they were amazed and began running up to greet Him.",
    16: "And He asked them, \"What are you discussing with them?\"",
    17: "And one of the crowd answered Him, \"Teacher, I brought You my son, possessed with a spirit which makes him mute.",
    18: "And whenever it seizes him, it dashes him to the ground — and he foams at the mouth, and grinds his teeth, and stiffens out. And I told Your disciples to cast it out — and they could not do it.\"",
    19: "And He answered them and said, \"O unbelieving generation! How long shall I be with you? How long shall I put up with you? Bring him to Me!\"",
    20: "And they brought the boy to Him. And when the spirit saw Him, immediately it threw him into a convulsion — and falling to the ground, he began rolling about, and foaming at the mouth.",
    21: "And He asked his father, \"How long has this been happening to him?\" And he said, \"From childhood.",
    22: "And it has often thrown him both into the fire and into the water to destroy him. But if You can do anything — take pity on us and help us!\"",
    23: "And Jesus said to him, \"'If You can!' All things are possible to him who believes.\"",
    24: "Immediately the boy's father cried out and was saying, \"I do believe — help my unbelief!\"",
    25: "And when Jesus saw that a crowd was rapidly gathering, He rebuked the unclean spirit, saying to it, \"You deaf and dumb spirit — I command you, come out of him! And do not enter him again!\"",
    26: "And after crying out and throwing him into terrible convulsions, it came out — and the boy became so much like a corpse, that most of them said, \"He is dead!\"",
    27: "But Jesus took him by the hand and raised him — and he got up.",
    28: "And when He had come into the house, His disciples began questioning Him privately, \"Why could we not cast it out?\"",
    29: "And He said to them, \"This kind cannot come out by anything but prayer.\"",
    30: "And from there they went out and began to go through Galilee — and He was unwilling for anyone to know about it.",
    31: "For He was teaching His disciples, and telling them, \"The Son of Man is to be delivered into the hands of men, and they will kill Him. And when He has been killed, He will rise three days later.\"",
    32: "But they did not understand this statement, and they were afraid to ask Him.",
    33: "And they came to Capernaum. And when He was in the house, He began to question them, \"What were you discussing on the way?\"",
    34: "But they kept silent — for on the way they had discussed with one another which one of them was the greatest.",
    35: "And sitting down, He called the twelve and said to them, \"If anyone wants to be first, he shall be last of all and servant of all.\"",
    36: "And taking a child, He set him before them. And taking him in His arms, He said to them,",
    37: "\"Whoever receives one such child in My name receives Me. And whoever receives Me, does not receive Me, but Him who sent Me.\"",
    38: "John said to Him, \"Teacher, we saw someone casting out demons in Your name — and we tried to prevent him, because he was not following us.\"",
    39: "But Jesus said, \"Do not hinder him — for there is no one who shall perform a miracle in My name, and be able soon afterward to speak evil of Me.",
    40: "For he who is not against us is for us.",
    41: "For whoever gives you a cup of water to drink because of your name as followers of Christ — truly I say to you, he shall not lose his reward.",
    42: "And whoever causes one of these little ones who believe to stumble — it would be better for him if, with a heavy millstone hung around his neck, he had been cast into the sea.",
    43: "And if your hand causes you to stumble, cut it off! It is better for you to enter life crippled, than having your two hands, to go into hell — into the unquenchable fire.",
    44: "(Where their worm does not die, and the fire is not quenched.)",
    45: "And if your foot causes you to stumble, cut it off! It is better for you to enter life lame, than having your two feet, to be cast into hell.",
    46: "(Where their worm does not die, and the fire is not quenched.)",
    47: "And if your eye causes you to stumble, cast it out! It is better for you to enter the kingdom of God with one eye, than having two eyes, to be cast into hell.",
    48: "Where their worm does not die, and the fire is not quenched.",
    49: "For everyone will be salted with fire.",
    50: "Salt is good. But if the salt becomes unsalty, with what will you make it salty again? Have salt in yourselves — and be at peace with one another.\"",
}

ch10 = {
    1: "And rising up, He went from there to the region of Judea, and beyond the Jordan. And crowds gathered around Him again — and according to His custom, He once more began to teach them.",
    2: "And some Pharisees came up to Him, testing Him — and began to question Him whether it was lawful for a man to divorce a wife.",
    3: "And He answered and said to them, \"What did Moses command you?\"",
    4: "And they said, \"Moses permitted a man to write a certificate of divorce and to send her away.\"",
    5: "But Jesus said to them, \"Because of your hardness of heart he wrote you this commandment.",
    6: "But from the beginning of creation, God made them male and female.",
    7: "For this cause a man shall leave his father and mother,",
    8: "and the two shall become one flesh — so that they are no longer two, but one flesh.",
    9: "What therefore God has joined together, let no man separate.\"",
    10: "And in the house the disciples began questioning Him about this again.",
    11: "And He said to them, \"Whoever divorces his wife and marries another woman commits adultery against her.",
    12: "And if she herself divorces her husband and marries another man, she is committing adultery.\"",
    13: "And they were bringing children to Him so that He might touch them — but the disciples rebuked them.",
    14: "But when Jesus saw this, He was indignant and said to them, \"Permit the children to come to Me — do not hinder them! For the kingdom of God belongs to such as these.",
    15: "Truly I say to you — whoever does not receive the kingdom of God like a child shall not enter it at all.\"",
    16: "And He took them in His arms and began blessing them, laying His hands upon them.",
    17: "And as He was setting out on a journey, a man ran up to Him and knelt before Him, and began asking Him, \"Good Teacher — what shall I do to inherit eternal life?\"",
    18: "And Jesus said to him, \"Why do you call Me good? No one is good except God alone.",
    19: "You know the commandments — 'Do not murder. Do not commit adultery. Do not steal. Do not bear false witness. Do not defraud. Honor your father and mother.'\"",
    20: "And he said to Him, \"Teacher, I have kept all these things from my youth up.\"",
    21: "And looking at him, Jesus felt a love for him, and said to him, \"One thing you lack — go and sell all you possess, and give to the poor, and you shall have treasure in heaven. And come, follow Me!\"",
    22: "But at these words his face fell, and he went away grieved — for he was one who owned much property.",
    23: "And Jesus, looking around, said to His disciples, \"How hard it will be for those who are wealthy to enter the kingdom of God!\"",
    24: "And the disciples were amazed at His words. But Jesus answered again and said to them, \"Children, how hard it is to enter the kingdom of God!",
    25: "It is easier for a camel to go through the eye of a needle than for a rich man to enter the kingdom of God.\"",
    26: "And they were even more astonished, and said to Him, \"Then who can be saved?\"",
    27: "Looking upon them, Jesus said, \"With men it is impossible — but not with God. For all things are possible with God.\"",
    28: "Peter began to say to Him, \"Behold, we have left everything and followed You.\"",
    29: "Jesus said, \"Truly I say to you — there is no one who has left house, or brothers, or sisters, or mother, or father, or children, or farms, for My sake and for the gospel's sake,",
    30: "but that he shall receive a hundred times as much now in the present age — houses, and brothers, and sisters, and mothers, and children, and farms, along with persecutions — and in the age to come, eternal life.",
    31: "But many who are first will be last, and the last, first.\"",
    32: "And they were on the road, going up to Jerusalem — and Jesus was walking on ahead of them. And they were amazed. And those who followed were fearful. And again He took the twelve aside and began to tell them what was going to happen to Him,",
    33: "saying, \"Behold, we are going up to Jerusalem — and the Son of Man will be delivered to the chief priests and the scribes. And they will condemn Him to death, and will deliver Him to the Gentiles.",
    34: "And they will mock Him, and spit upon Him, and scourge Him, and kill Him — and three days later He will rise again.\"",
    35: "And James and John, the two sons of Zebedee, came up to Him, saying to Him, \"Teacher, we want You to do for us whatever we ask of You.\"",
    36: "And He said to them, \"What do you want Me to do for you?\"",
    37: "And they said to Him, \"Grant that we may sit in Your glory — one on Your right, and one on Your left.\"",
    38: "But Jesus said to them, \"You do not know what you are asking for. Are you able to drink the cup that I drink — or to be baptized with the baptism with which I am baptized?\"",
    39: "And they said to Him, \"We are able.\" And Jesus said to them, \"The cup that I drink you shall drink — and you shall be baptized with the baptism with which I am baptized.",
    40: "But to sit on My right or on My left — this is not Mine to give. But it is for those for whom it has been prepared.\"",
    41: "And hearing this, the ten began to feel indignant with James and John.",
    42: "And calling them to Himself, Jesus said to them, \"You know that those who are recognized as rulers of the Gentiles lord it over them. And their great men exercise authority over them.",
    43: "But it is not so among you. But whoever wishes to become great among you shall be your servant.",
    44: "And whoever wishes to be first among you shall be slave of all.",
    45: "For even the Son of Man did not come to be served, but to serve — and to give His life a ransom for many.\"",
    46: "And they came to Jericho. And as He was leaving Jericho with His disciples and a great multitude, a blind beggar named Bartimaeus, the son of Timaeus, was sitting by the road.",
    47: "And when he heard that it was Jesus the Nazarene, he began to cry out and say, \"Jesus, Son of David — have mercy on me!\"",
    48: "And many were sternly telling him to be quiet. But he kept crying out all the more, \"Son of David — have mercy on me!\"",
    49: "And Jesus stopped and said, \"Call him here.\" And they called the blind man, saying to him, \"Take courage — arise! He is calling for you.\"",
    50: "And casting aside his cloak, he jumped up and came to Jesus.",
    51: "And answering him, Jesus said, \"What do you want Me to do for you?\" And the blind man said to Him, \"Rabboni — I want to regain my sight!\"",
    52: "And Jesus said to him, \"Go your way. Your faith has made you well.\" And immediately he regained his sight, and began following Him on the road.",
}

ch11 = {
    1: "And as they approached Jerusalem, at Bethphage and Bethany, near the Mount of Olives, He sent two of His disciples,",
    2: "and said to them, \"Go into the village opposite you — and immediately as you enter it, you will find a colt tied, on which no one yet has ever sat. Untie it, and bring it here.",
    3: "And if anyone says to you, 'Why are you doing this?' — say, 'The Lord has need of it.' And immediately he will send it back here.\"",
    4: "And they went away and found a colt tied at the door, outside in the street — and they untied it.",
    5: "And some of the bystanders were saying to them, \"What are you doing, untying the colt?\"",
    6: "And they spoke to them just as Jesus had told them. And they gave them permission.",
    7: "And they brought the colt to Jesus, and put their garments on it — and He sat upon it.",
    8: "And many spread their garments in the road, and others spread leafy branches which they had cut from the fields.",
    9: "And those who went before, and those who followed after, were crying out, \"Hosanna! Blessed is He who comes in the name of the Lord!",
    10: "Blessed is the coming kingdom of our father David! Hosanna in the highest!\"",
    11: "And He entered Jerusalem and came into the temple. And after looking around at everything, He departed for Bethany with the twelve — for it was already late.",
    12: "And on the next day, when they had departed from Bethany, He became hungry.",
    13: "And seeing at a distance a fig tree in leaf, He went to see if perhaps He would find anything on it. And when He came to it, He found nothing but leaves — for it was not the season for figs.",
    14: "And He answered and said to it, \"May no one ever eat fruit from you again!\" And His disciples were listening.",
    15: "And they came to Jerusalem. And He entered the temple and began to drive out those who were buying and selling in the temple — and He overturned the tables of the money changers, and the seats of those who were selling doves.",
    16: "And He would not permit anyone to carry merchandise through the temple.",
    17: "And He began to teach and say to them, \"Is it not written, 'My house shall be called a house of prayer for all the nations'? But you have made it a robbers' den.\"",
    18: "And the chief priests and the scribes heard this, and began seeking how to destroy Him — for they were afraid of Him, because all the multitude was astonished at His teaching.",
    19: "And whenever evening came, they would go out of the city.",
    20: "And as they were passing by in the morning, they saw the fig tree withered from the roots up.",
    21: "And being reminded, Peter said to Him, \"Rabbi, behold — the fig tree which You cursed has withered.\"",
    22: "And Jesus answered and said to them, \"Have faith in God.",
    23: "Truly I say to you — whoever says to this mountain, 'Be taken up and cast into the sea,' and does not doubt in his heart, but believes that what he says is going to happen, it shall be granted him.",
    24: "Therefore I say to you — all things for which you pray and ask, believe that you have received them, and they shall be granted you.",
    25: "And whenever you stand praying, forgive — if you have anything against anyone, so that your Father also who is in heaven may forgive you your transgressions.",
    26: "(But if you do not forgive, neither will your Father who is in heaven forgive your transgressions.)\"",
    27: "And they came again to Jerusalem. And as He was walking in the temple, the chief priests and the scribes and the elders came to Him,",
    28: "and began saying to Him, \"By what authority are You doing these things — or who gave You this authority to do these things?\"",
    29: "And Jesus said to them, \"I will ask you one question — and you answer Me, and then I will tell you by what authority I do these things.",
    30: "Was the baptism of John from heaven, or from men? Answer Me.\"",
    31: "And they began reasoning among themselves, saying, \"If we say, 'From heaven,' He will say, 'Then why did you not believe him?'",
    32: "But shall we say, 'From men'?\" — they were afraid of the multitude, for all considered John to have been a real prophet.",
    33: "And answering Jesus, they said, \"We do not know.\" And Jesus said to them, \"Neither will I tell you by what authority I do these things.\"",
}

ch12 = {
    1: "And He began to speak to them in parables: \"A man planted a vineyard, and put a wall around it, and dug a vat under the wine press, and built a tower — and rented it out to vine-growers and went on a journey.",
    2: "And at the harvest time he sent a slave to the vine-growers, in order to receive some of the produce of the vineyard from them.",
    3: "And they took him and beat him — and sent him away empty-handed.",
    4: "And again he sent them another slave — and they wounded him in the head and treated him shamefully.",
    5: "And he sent another, and that one they killed. And so with many others — beating some, and killing others.",
    6: "He had one more, a beloved son. He sent him last of all to them, saying, 'They will respect my son.'",
    7: "But those vine-growers said to one another, 'This is the heir. Come — let us kill him, and the inheritance will be ours!'",
    8: "And they took him, and killed him, and threw him out of the vineyard.",
    9: "What will the owner of the vineyard do? He will come and destroy the vine-growers — and will give the vineyard to others.",
    10: "Have you not even read this Scripture: 'The stone which the builders rejected — this became the chief corner stone.",
    11: "This came about from the Lord — and it is marvelous in our eyes'?\"",
    12: "And they were seeking to seize Him. And yet they feared the multitude — for they understood that He spoke the parable against them. And so they left Him and went away.",
    13: "And they sent some of the Pharisees and Herodians to Him, in order to trap Him in a statement.",
    14: "And they came and said to Him, \"Teacher, we know that You are truthful, and defer to no one. For You are not partial to any — but teach the way of God in truth. Is it lawful to pay a poll-tax to Caesar, or not?",
    15: "Shall we pay, or shall we not pay?\" But He, knowing their hypocrisy, said to them, \"Why are you testing Me? Bring Me a denarius to look at.\"",
    16: "And they brought one. And He said to them, \"Whose likeness and inscription is this?\" And they said to Him, \"Caesar's.\"",
    17: "And Jesus said to them, \"Render to Caesar the things that are Caesar's — and to God the things that are God's.\" And they were amazed at Him.",
    18: "And some Sadducees (who say that there is no resurrection) came to Him — and began questioning Him, saying,",
    19: "\"Teacher, Moses wrote for us that if a man's brother dies, and leaves behind a wife and leaves no child, his brother should marry the wife — and raise up offspring to his brother.",
    20: "There were seven brothers. And the first took a wife — and died, leaving no offspring.",
    21: "And the second one took her, and died, leaving behind no offspring — and the third likewise.",
    22: "And so all seven left no offspring. Last of all the woman also died.",
    23: "In the resurrection, when they rise again, which one's wife will she be? For all seven had her as wife.\"",
    24: "Jesus said to them, \"Is this not the reason you are mistaken — that you do not understand the Scriptures, or the power of God?",
    25: "For when they rise from the dead, they neither marry nor are given in marriage — but are like angels in heaven.",
    26: "But regarding the fact that the dead rise again — have you not read in the book of Moses, in the passage about the burning bush, how God spoke to him, saying, 'I am the God of Abraham, and the God of Isaac, and the God of Jacob'?",
    27: "He is not the God of the dead, but of the living. You are greatly mistaken.\"",
    28: "And one of the scribes came and heard them arguing, and recognized that He had answered them well — and asked Him, \"Which commandment is the foremost of all?\"",
    29: "Jesus answered, \"The foremost is, 'Hear, O Israel — the Lord our God is one Lord.",
    30: "And you shall love the Lord your God with all your heart, and with all your soul, and with all your mind, and with all your strength.'",
    31: "The second is this — 'You shall love your neighbor as yourself.' There is no other commandment greater than these.\"",
    32: "And the scribe said to Him, \"Right, Teacher! You have truly stated that He is One — and there is no one else besides Him.",
    33: "And to love Him with all the heart, and with all the understanding, and with all the strength — and to love one's neighbor as oneself, is much more than all burnt offerings and sacrifices.\"",
    34: "And when Jesus saw that he had answered intelligently, He said to him, \"You are not far from the kingdom of God.\" And after that, no one would venture to ask Him any more questions.",
    35: "And Jesus, while teaching in the temple, began to say, \"How is it that the scribes say that the Christ is the son of David?",
    36: "David himself said in the Holy Spirit — 'The Lord said to my Lord, \"Sit at My right hand, until I put Your enemies beneath Your feet.\"'",
    37: "David himself calls Him 'Lord.' And so in what sense is He his son?\" And the great crowd enjoyed listening to Him.",
    38: "And in His teaching He was saying: \"Beware of the scribes, who like to walk around in long robes, and like respectful greetings in the market places,",
    39: "and chief seats in the synagogues, and places of honor at banquets —",
    40: "who devour widows' houses, and for appearance's sake offer long prayers. These will receive greater condemnation.\"",
    41: "And He sat down opposite the treasury, and began observing how the multitude were putting money into the treasury. And many rich people were putting in large sums.",
    42: "And a poor widow came and put in two small copper coins, which amount to a cent.",
    43: "And calling His disciples to Him, He said to them, \"Truly I say to you — this poor widow put in more than all the contributors to the treasury.",
    44: "For they all put in out of their surplus. But she, out of her poverty, put in all she owned — all she had to live on.\"",
}

ch13 = {
    1: "And as He was going out of the temple, one of His disciples said to Him, \"Teacher, behold what wonderful stones and what wonderful buildings!\"",
    2: "And Jesus said to him, \"Do you see these great buildings? Not one stone shall be left upon another, which will not be torn down.\"",
    3: "And as He was sitting on the Mount of Olives opposite the temple, Peter and James and John and Andrew were questioning Him privately,",
    4: "\"Tell us — when will these things be? And what will be the sign when all these things are going to be fulfilled?\"",
    5: "And Jesus began to say to them, \"Take heed that no one misleads you.",
    6: "Many will come in My name, saying, 'I am He!' — and will mislead many.",
    7: "And when you hear of wars and rumors of wars, do not be frightened. Those things must take place — but that is not yet the end.",
    8: "For nation will arise against nation, and kingdom against kingdom. There will be earthquakes in various places. There will be famines. These things are merely the beginning of birth pangs.",
    9: "But be on your guard. For they will deliver you to the courts. And you will be flogged in the synagogues — and you will stand before governors and kings for My sake, as a testimony to them.",
    10: "And the gospel must first be preached to all the nations.",
    11: "And when they arrest you and deliver you up, do not be anxious beforehand about what you are to say. But say whatever is given you in that hour. For it is not you who speak, but it is the Holy Spirit.",
    12: "And brother will deliver brother to death, and a father his child. And children will rise up against parents, and have them put to death.",
    13: "And you will be hated by all on account of My name — but the one who endures to the end, he shall be saved.",
    14: "But when you see the abomination of desolation standing where it should not be — let the reader understand — then let those who are in Judea flee to the mountains.",
    15: "And let him who is on the housetop not go down, or enter in, to get anything out of his house.",
    16: "And let him who is in the field not turn back to get his cloak.",
    17: "But woe to those who are with child, and to those who are nursing babies in those days!",
    18: "But pray that it may not happen in the winter.",
    19: "For those days will be a time of tribulation such as has not occurred since the beginning of the creation which God created, until now — and never shall.",
    20: "And unless the Lord had shortened those days, no life would have been saved. But for the sake of the elect whom He chose, He shortened the days.",
    21: "And then if anyone says to you, 'Behold, here is the Christ!' — or, 'Behold, He is there!' — do not believe him.",
    22: "For false Christs and false prophets will arise, and will show signs and wonders, in order, if possible, to lead the elect astray.",
    23: "But take heed. Behold, I have told you everything in advance.",
    24: "But in those days, after that tribulation, the sun will be darkened, and the moon will not give its light.",
    25: "And the stars will be falling from heaven, and the powers that are in the heavens will be shaken.",
    26: "And then they will see the Son of Man coming in clouds with great power and glory.",
    27: "And then He will send forth the angels, and will gather together His elect from the four winds — from the farthest end of the earth, to the farthest end of heaven.",
    28: "Now learn the parable from the fig tree — when its branch has already become tender, and puts forth its leaves, you know that summer is near.",
    29: "Even so, you too, when you see these things happening, recognize that He is near — right at the door.",
    30: "Truly I say to you — this generation will not pass away until all these things take place.",
    31: "Heaven and earth will pass away — but My words will not pass away.",
    32: "But of that day or hour no one knows — not even the angels in heaven, nor the Son — but the Father alone.",
    33: "Take heed. Keep on the alert. For you do not know when the appointed time is.",
    34: "It is like a man, away on a journey, who upon leaving his house and putting his slaves in charge — assigning to each one his task — also commanded the doorkeeper to stay on the alert.",
    35: "Therefore, be on the alert. For you do not know when the master of the house is coming — whether in the evening, or at midnight, or when the rooster crows, or in the morning.",
    36: "Lest he come suddenly and find you asleep.",
    37: "And what I say to you, I say to all — be on the alert!\"",
}

ch14 = {
    1: "Now the Passover and Unleavened Bread were two days off. And the chief priests and the scribes were seeking how to seize Him by stealth and kill Him.",
    2: "For they were saying, \"Not during the festival — lest there be a riot of the people.\"",
    3: "And while He was in Bethany at the home of Simon the leper, reclining at table, there came a woman with an alabaster vial of very costly perfume of pure nard. She broke the vial and poured it over His head.",
    4: "But some were indignantly remarking to one another, \"Why has this perfume been wasted?",
    5: "For this perfume might have been sold for over three hundred denarii, and the money given to the poor.\" And they were scolding her.",
    6: "But Jesus said, \"Let her alone. Why do you bother her? She has done a good deed to Me.",
    7: "For the poor you always have with you, and whenever you wish, you can do them good. But you do not always have Me.",
    8: "She has done what she could. She has anointed My body beforehand for the burial.",
    9: "And truly I say to you — wherever the gospel is preached in the whole world, what this woman has done shall also be spoken of in memory of her.\"",
    10: "And Judas Iscariot, who was one of the twelve, went off to the chief priests, in order to betray Him to them.",
    11: "And when they heard it, they were glad and promised to give him money. And he began seeking how to betray Him at an opportune time.",
    12: "And on the first day of Unleavened Bread, when the Passover lamb was being sacrificed, His disciples said to Him, \"Where do You want us to go and prepare for You to eat the Passover?\"",
    13: "And He sent two of His disciples, and said to them, \"Go into the city, and a man carrying a pitcher of water will meet you. Follow him.",
    14: "And wherever he enters, say to the owner of the house, 'The Teacher says, \"Where is My guest room, in which I may eat the Passover with My disciples?\"'",
    15: "And he himself will show you a large upper room furnished and ready. And prepare for us there.\"",
    16: "And the disciples went out, and came to the city, and found it just as He had told them. And they prepared the Passover.",
    17: "And when it was evening, He came with the twelve.",
    18: "And as they were reclining at table and eating, Jesus said, \"Truly I say to you — one of you will betray Me. One who is eating with Me.\"",
    19: "They began to be grieved and to say to Him one by one, \"Surely not I?\"",
    20: "And He said to them, \"It is one of the twelve — one who dips with Me in the bowl.",
    21: "For the Son of Man is to go just as it is written of Him. But woe to that man by whom the Son of Man is betrayed! It would have been good for that man if he had not been born.\"",
    22: "And while they were eating, He took some bread, and after a blessing He broke it and gave it to them, and said, \"Take it — this is My body.\"",
    23: "And when He had taken a cup and given thanks, He gave it to them. And they all drank from it.",
    24: "And He said to them, \"This is My blood of the covenant, which is poured out for many.",
    25: "Truly I say to you — I shall never again drink of the fruit of the vine, until that day when I drink it new in the kingdom of God.\"",
    26: "And after singing a hymn, they went out to the Mount of Olives.",
    27: "And Jesus said to them, \"You will all fall away. For it is written, 'I will strike down the shepherd — and the sheep shall be scattered.'",
    28: "But after I have been raised, I will go before you to Galilee.\"",
    29: "But Peter said to Him, \"Even though all may fall away, yet I will not.\"",
    30: "And Jesus said to him, \"Truly I say to you — that you yourself this very night, before a rooster crows twice, shall three times deny Me.\"",
    31: "But Peter kept saying insistently, \"Even if I have to die with You, I will not deny You!\" And they all were saying the same thing too.",
    32: "And they came to a place named Gethsemane. And He said to His disciples, \"Sit here until I have prayed.\"",
    33: "And He took with Him Peter and James and John, and began to be very distressed and troubled.",
    34: "And He said to them, \"My soul is deeply grieved — to the point of death. Remain here, and keep watch.\"",
    35: "And He went a little beyond them, and fell to the ground, and began to pray that, if it were possible, the hour might pass Him by.",
    36: "And He was saying, \"Abba — Father! All things are possible for You. Remove this cup from Me. Yet not what I will, but what You will.\"",
    37: "And He came and found them sleeping, and said to Peter, \"Simon, are you asleep? Could you not keep watch for one hour?",
    38: "Keep watching and praying, that you may not come into temptation. The spirit is willing, but the flesh is weak.\"",
    39: "And again He went away and prayed, saying the same words.",
    40: "And again He came and found them sleeping — for their eyes were very heavy. And they did not know what to answer Him.",
    41: "And He came the third time, and said to them, \"Are you still sleeping and resting? It is enough. The hour has come. Behold, the Son of Man is being betrayed into the hands of sinners.",
    42: "Arise — let us be going. Behold, the one who betrays Me is at hand!\"",
    43: "And immediately, while He was still speaking, Judas, one of the twelve, came up, accompanied by a multitude with swords and clubs — from the chief priests and the scribes and the elders.",
    44: "Now he who was betraying Him had given them a signal, saying, \"Whomever I kiss, He is the one. Seize Him, and lead Him away under guard.\"",
    45: "And after coming, he immediately went to Him, saying, \"Rabbi!\" — and kissed Him.",
    46: "And they laid hands on Him and seized Him.",
    47: "But a certain one of those who stood by drew his sword, and struck the slave of the high priest and cut off his ear.",
    48: "And Jesus answered and said to them, \"Have you come out with swords and clubs to arrest Me, as you would against a robber?",
    49: "Every day I was with you in the temple teaching, and you did not seize Me. But this has taken place that the Scriptures may be fulfilled.\"",
    50: "And they all left Him and fled.",
    51: "And a certain young man was following Him, wearing nothing but a linen sheet over his naked body. And they seized him.",
    52: "But he left the linen sheet behind, and escaped naked.",
    53: "And they led Jesus away to the high priest. And all the chief priests, and the elders, and the scribes gathered together.",
    54: "And Peter had followed Him at a distance, right into the courtyard of the high priest. And he was sitting with the officers and warming himself at the fire.",
    55: "Now the chief priests and the whole Council kept trying to obtain testimony against Jesus to put Him to death — and they were not finding any.",
    56: "For many were giving false testimony against Him — and yet their testimony was not consistent.",
    57: "And some stood up and began to give false testimony against Him, saying,",
    58: "\"We heard Him say, 'I will destroy this temple made with hands, and in three days I will build another made without hands.'\"",
    59: "And not even in this respect was their testimony consistent.",
    60: "And the high priest stood up and came forward, and questioned Jesus, saying, \"Do You make no answer? What is it that these men are testifying against You?\"",
    61: "But He kept silent, and made no answer. Again the high priest was questioning Him, and saying to Him, \"Are You the Christ — the Son of the Blessed One?\"",
    62: "And Jesus said, \"I am! And you shall see the Son of Man sitting at the right hand of Power, and coming with the clouds of heaven.\"",
    63: "And tearing his clothes, the high priest said, \"What further need do we have of witnesses?",
    64: "You have heard the blasphemy. How does it seem to you?\" And they all condemned Him to be deserving of death.",
    65: "And some began to spit at Him, and to blindfold Him, and to beat Him with their fists, and to say to Him, \"Prophesy!\" And the officers received Him with slaps in the face.",
    66: "And as Peter was below in the courtyard, one of the servant-girls of the high priest came.",
    67: "And seeing Peter warming himself, she looked at him and said, \"You, too, were with Jesus the Nazarene.\"",
    68: "But he denied it, saying, \"I neither know nor understand what you are talking about.\" And he went out onto the porch. And a rooster crowed.",
    69: "And the maid saw him, and began once more to say to the bystanders, \"This is one of them!\"",
    70: "But again he was denying it. And after a little while the bystanders were again saying to Peter, \"Surely you are one of them, for you are a Galilean too.\"",
    71: "But he began to curse and swear, \"I do not know this man you are talking about!\"",
    72: "And immediately a rooster crowed a second time. And Peter remembered how Jesus had made the remark to him, \"Before a rooster crows twice, you will three times deny Me.\" And he began to weep.",
}

ch15 = {
    1: "And early in the morning the chief priests with the elders and scribes — and the whole Council — immediately held a consultation. And they bound Jesus and led Him away, and delivered Him up to Pilate.",
    2: "And Pilate questioned Him, \"Are You the King of the Jews?\" And answering him, He said, \"You yourself say so.\"",
    3: "And the chief priests began to accuse Him harshly.",
    4: "And Pilate was questioning Him again, saying, \"Do You make no answer? See how many charges they bring against You!\"",
    5: "But Jesus made no further answer — so that Pilate was amazed.",
    6: "Now at the feast he used to release for them any one prisoner whom they requested.",
    7: "And the man named Barabbas had been imprisoned with the insurrectionists — who had committed murder in the insurrection.",
    8: "And the multitude went up and began asking him to do as he had been accustomed to do for them.",
    9: "And Pilate answered them, saying, \"Do you want me to release for you the King of the Jews?\"",
    10: "For he was aware that the chief priests had delivered Him up because of envy.",
    11: "But the chief priests stirred up the multitude to ask him to release Barabbas for them instead.",
    12: "And answering again, Pilate was saying to them, \"Then what shall I do with Him whom you call the King of the Jews?\"",
    13: "And they shouted back, \"Crucify Him!\"",
    14: "But Pilate was saying to them, \"Why, what evil has He done?\" But they shouted all the more, \"Crucify Him!\"",
    15: "And wishing to satisfy the multitude, Pilate released Barabbas for them — and after having Jesus scourged, he delivered Him to be crucified.",
    16: "And the soldiers took Him away into the palace (that is, the Praetorium) — and they called together the whole Roman cohort.",
    17: "And they dressed Him up in purple, and after twisting a crown of thorns, they put it on Him.",
    18: "And they began to acclaim Him, \"Hail, King of the Jews!\"",
    19: "And they kept beating His head with a reed, and spitting on Him — and kneeling and bowing before Him.",
    20: "And after they had mocked Him, they took the purple off Him, and put His own garments on Him. And they led Him out to crucify Him.",
    21: "And they pressed into service a passer-by coming from the country — Simon of Cyrene, the father of Alexander and Rufus — to bear His cross.",
    22: "And they brought Him to the place Golgotha — which is translated, Place of a Skull.",
    23: "And they tried to give Him wine mixed with myrrh — but He did not take it.",
    24: "And they crucified Him, and divided up His garments among themselves, casting lots for them, to decide what each man should take.",
    25: "And it was the third hour when they crucified Him.",
    26: "And the inscription of the charge against Him read, \"The King of the Jews.\"",
    27: "And they crucified two robbers with Him — one on His right, and one on His left.",
    28: "(And the Scripture was fulfilled which says, \"And He was numbered with transgressors.\")",
    29: "And those passing by were hurling abuse at Him, wagging their heads, and saying, \"Ha! You who destroy the temple, and rebuild it in three days,",
    30: "save Yourself, and come down from the cross!\"",
    31: "In the same way the chief priests also, along with the scribes, were mocking Him among themselves and saying, \"He saved others. He cannot save Himself!",
    32: "Let this Christ — the King of Israel — come down from the cross right now, that we may see and believe.\" And those who were crucified with Him were also insulting Him.",
    33: "And when the sixth hour had come, darkness fell over the whole land until the ninth hour.",
    34: "And at the ninth hour Jesus cried out with a loud voice, \"Eloi, Eloi, lama sabachthani?\" — which is translated, \"My God, My God, why have You forsaken Me?\"",
    35: "And when some of the bystanders heard it, they began saying, \"Behold, He is calling for Elijah!\"",
    36: "And someone ran and filled a sponge with sour wine, put it on a reed, and gave Him a drink, saying, \"Let us see if Elijah will come to take Him down.\"",
    37: "And Jesus uttered a loud cry, and breathed His last.",
    38: "And the veil of the temple was torn in two from top to bottom.",
    39: "And when the centurion, who was standing right in front of Him, saw the way He breathed His last, he said, \"Truly this man was the Son of God!\"",
    40: "And there were also some women looking on from a distance — among whom were Mary Magdalene, and Mary the mother of James the Less and Joses, and Salome.",
    41: "And when He was in Galilee, they used to follow Him and minister to Him. And there were many other women who had come up with Him to Jerusalem.",
    42: "And when evening had already come, because it was the preparation day — that is, the day before the Sabbath —",
    43: "Joseph of Arimathea came, a prominent member of the Council, who himself was waiting for the kingdom of God. And he gathered up courage and went in before Pilate, and asked for the body of Jesus.",
    44: "And Pilate marveled that He was already dead. And summoning the centurion, he questioned him as to whether He was already dead.",
    45: "And finding it out from the centurion, he granted the body to Joseph.",
    46: "And Joseph bought a linen cloth. And taking Him down, he wrapped Him in the linen cloth, and laid Him in a tomb which had been hewn out in the rock — and he rolled a stone against the entrance of the tomb.",
    47: "And Mary Magdalene and Mary the mother of Joses were looking on to see where He was laid.",
}

ch16 = {
    1: "And when the Sabbath was over, Mary Magdalene, and Mary the mother of James, and Salome bought spices, that they might come and anoint Him.",
    2: "And very early on the first day of the week, they came to the tomb when the sun had risen.",
    3: "And they were saying to one another, \"Who will roll away the stone for us from the entrance of the tomb?\"",
    4: "And looking up, they saw that the stone had been rolled away. For it was extremely large.",
    5: "And entering the tomb, they saw a young man sitting at the right, wearing a white robe — and they were amazed.",
    6: "And he said to them, \"Do not be amazed. You are looking for Jesus the Nazarene, who has been crucified. He has risen! He is not here. Behold, here is the place where they laid Him.",
    7: "But go, tell His disciples and Peter, 'He is going before you into Galilee. There you will see Him — just as He said to you.'\"",
    8: "And they went out and fled from the tomb — for trembling and astonishment had gripped them. And they said nothing to anyone, for they were afraid.",
    9: "Now after He had risen early on the first day of the week, He first appeared to Mary Magdalene, from whom He had cast out seven demons.",
    10: "She went and reported to those who had been with Him, while they were mourning and weeping.",
    11: "And when they heard that He was alive, and had been seen by her, they refused to believe it.",
    12: "And after that, He appeared in a different form to two of them, while they were walking along on their way to the country.",
    13: "And they went away and reported it to the others. They did not believe them either.",
    14: "And afterward He appeared to the eleven themselves as they were reclining at the table — and He reproached them for their unbelief and hardness of heart, because they had not believed those who had seen Him after He had risen.",
    15: "And He said to them, \"Go into all the world and preach the gospel to all creation.",
    16: "He who has believed and has been baptized shall be saved. But he who has disbelieved shall be condemned.",
    17: "And these signs will accompany those who have believed: in My name they will cast out demons. They will speak with new tongues.",
    18: "They will pick up serpents — and if they drink any deadly poison, it shall not hurt them. They will lay hands on the sick, and they will recover.\"",
    19: "So then, when the Lord Jesus had spoken to them, He was received up into heaven, and sat down at the right hand of God.",
    20: "And they went out and preached everywhere — while the Lord worked with them, and confirmed the word by the signs that followed.",
}

CHAPTERS = {9:ch9,10:ch10,11:ch11,12:ch12,13:ch13,14:ch14,15:ch15,16:ch16}

def main():
    new_entries = {f"41_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Mark 9-16 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Mark 9-16 verses")

if __name__ == "__main__":
    main()
