"""MBT Luke 13-18 — Travel narrative + signature parables. 213 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch13 = {
    1: "Now on the same occasion there were some present who reported to Him about the Galileans, whose blood Pilate had mixed with their sacrifices.",
    2: "And He answered and said to them, \"Do you suppose that these Galileans were greater sinners than all other Galileans, because they suffered this fate?",
    3: "I tell you, no — but unless you repent, you will all likewise perish.",
    4: "Or do you suppose that those eighteen on whom the tower in Siloam fell and killed them, were worse culprits than all the men who live in Jerusalem?",
    5: "I tell you, no — but unless you repent, you will all likewise perish.\"",
    6: "And He began telling this parable: \"A certain man had a fig tree which had been planted in his vineyard. And he came looking for fruit on it, and did not find any.",
    7: "And he said to the vineyard-keeper, 'Behold, for three years I have come looking for fruit on this fig tree without finding any. Cut it down. Why does it even use up the ground?'",
    8: "And he answered and said to him, 'Let it alone, sir, for this year too, until I dig around it and put in fertilizer.",
    9: "And if it bears fruit next year, fine. But if not, cut it down.'\"",
    10: "And He was teaching in one of the synagogues on the Sabbath.",
    11: "And behold, there was a woman who for eighteen years had had a sickness caused by a spirit. And she was bent double, and could not straighten up at all.",
    12: "And when Jesus saw her, He called her over and said to her, \"Woman, you are freed from your sickness.\"",
    13: "And He laid His hands upon her — and immediately she was made erect again, and began glorifying God.",
    14: "And the synagogue official, indignant because Jesus had healed on the Sabbath, began saying to the multitude in response, \"There are six days in which work should be done — therefore come during them and get healed, and not on the Sabbath day.\"",
    15: "But the Lord answered him, and said, \"You hypocrites — does not each of you on the Sabbath untie his ox or his donkey from the stall and lead him away to water him?",
    16: "And this woman, a daughter of Abraham as she is, whom Satan has bound for eighteen long years, should she not have been released from this bond on the Sabbath day?\"",
    17: "And as He said this, all His opponents were being humiliated. And the entire multitude was rejoicing over all the glorious things being done by Him.",
    18: "Therefore He was saying, \"What is the kingdom of God like, and to what shall I compare it?",
    19: "It is like a mustard seed, which a man took and threw into his own garden. And it grew and became a tree — and the birds of the air nested in its branches.\"",
    20: "And again He said, \"To what shall I compare the kingdom of God?",
    21: "It is like leaven, which a woman took and hid in three pecks of meal — until it was all leavened.\"",
    22: "And He was passing through from one city and village to another, teaching, and proceeding on His way to Jerusalem.",
    23: "And someone said to Him, \"Lord, are there just a few who are being saved?\" And He said to them,",
    24: "\"Strive to enter by the narrow door — for many, I tell you, will seek to enter and will not be able.",
    25: "Once the head of the house gets up and shuts the door, and you begin to stand outside and knock on the door, saying, 'Lord, open up to us!' — then He will answer and say to you, 'I do not know where you are from.'",
    26: "Then you will begin to say, 'We ate and drank in Your presence, and You taught in our streets.'",
    27: "And He will say, 'I tell you, I do not know where you are from. Depart from Me, all you evildoers.'",
    28: "There will be weeping and gnashing of teeth there, when you see Abraham and Isaac and Jacob and all the prophets in the kingdom of God — but yourselves being cast out.",
    29: "And they will come from east and west, and from north and south, and will recline at the table in the kingdom of God.",
    30: "And behold, some are last who will be first — and some are first who will be last.\"",
    31: "Just at that time some Pharisees came up, saying to Him, \"Go away and depart from here — for Herod wants to kill You.\"",
    32: "And He said to them, \"Go and tell that fox, 'Behold, I cast out demons and perform cures today and tomorrow, and the third day I reach My goal.'",
    33: "Nevertheless I must journey on today and tomorrow and the next day — for it cannot be that a prophet should perish outside of Jerusalem.",
    34: "O Jerusalem, Jerusalem — the city that kills the prophets and stones those sent to her! How often I wanted to gather your children together, just as a hen gathers her brood under her wings — and you would not have it!",
    35: "Behold, your house is left to you desolate. And I say to you, you shall not see Me until the time comes when you say, 'Blessed is He who comes in the name of the Lord!'\"",
}
ch14 = {
    1: "And it came about, when He went into the house of one of the leaders of the Pharisees on the Sabbath to eat bread, that they were watching Him closely.",
    2: "And behold, there was in front of Him a certain man suffering from dropsy.",
    3: "And Jesus answered and spoke to the lawyers and Pharisees, saying, \"Is it lawful to heal on the Sabbath, or not?\"",
    4: "But they kept silent. And He took hold of him, and healed him, and sent him away.",
    5: "And He said to them, \"Which one of you shall have a son or an ox fall into a well, and will not immediately pull him out on a Sabbath day?\"",
    6: "And they could make no reply to this.",
    7: "And He began speaking a parable to the invited guests when He noticed how they had been picking out the places of honor at the table, saying to them,",
    8: "\"When you are invited by someone to a wedding feast, do not take the place of honor — for someone more distinguished than you may have been invited by him.",
    9: "And he who invited you both shall come and say to you, 'Give place to this man,' and then in disgrace you proceed to occupy the last place.",
    10: "But when you are invited, go and recline at the last place — so that when the one who has invited you comes, he may say to you, 'Friend, move up higher.' Then you will have honor in the sight of all who are at the table with you.",
    11: "For everyone who exalts himself shall be humbled — and he who humbles himself shall be exalted.\"",
    12: "And He also went on to say to the one who had invited Him, \"When you give a luncheon or a dinner, do not invite your friends or your brothers or your relatives or rich neighbors — lest they also invite you in return, and repayment come to you.",
    13: "But when you give a reception, invite the poor, the crippled, the lame, the blind —",
    14: "and you will be blessed, since they do not have the means to repay you. For you will be repaid at the resurrection of the righteous.\"",
    15: "And when one of those who were reclining at the table with Him heard this, he said to Him, \"Blessed is everyone who shall eat bread in the kingdom of God!\"",
    16: "But He said to him, \"A certain man was giving a big dinner, and he invited many.",
    17: "And at the dinner hour he sent his slave to say to those who had been invited, 'Come — for everything is ready now.'",
    18: "But they all alike began to make excuses. The first one said to him, 'I have bought a piece of land, and I need to go out and look at it. Please consider me excused.'",
    19: "And another one said, 'I have bought five yoke of oxen, and I am going to try them out. Please consider me excused.'",
    20: "And another one said, 'I have married a wife, and for that reason I cannot come.'",
    21: "And the slave came back and reported this to his master. Then the head of the household became angry and said to his slave, 'Go out at once into the streets and lanes of the city, and bring in here the poor and crippled and blind and lame.'",
    22: "And the slave said, 'Master, what you commanded has been done, and still there is room.'",
    23: "And the master said to the slave, 'Go out into the highways and along the hedges, and compel them to come in, that my house may be filled.",
    24: "For I tell you, none of those men who were invited shall taste of my dinner.'\"",
    25: "Now great multitudes were going along with Him. And He turned and said to them,",
    26: "\"If anyone comes to Me, and does not hate his own father and mother and wife and children and brothers and sisters, yes, and even his own life — he cannot be My disciple.",
    27: "Whoever does not carry his own cross and come after Me cannot be My disciple.",
    28: "For which one of you, when he wants to build a tower, does not first sit down and calculate the cost, to see if he has enough to complete it?",
    29: "Lest, when he has laid a foundation, and is not able to finish, all who observe it begin to ridicule him,",
    30: "saying, 'This man began to build and was not able to finish.'",
    31: "Or what king, when he sets out to meet another king in battle, will not first sit down and take counsel whether he is strong enough with ten thousand men to encounter the one coming against him with twenty thousand?",
    32: "Or else, while the other is still far away, he sends a delegation and asks terms of peace.",
    33: "So therefore, no one of you can be My disciple who does not give up all his own possessions.",
    34: "Therefore, salt is good. But if even salt has become tasteless, with what will it be seasoned?",
    35: "It is useless either for the soil or for the manure pile — it is thrown out. He who has ears to hear, let him hear.\"",
}
ch15 = {
    1: "Now all the tax-gatherers and the sinners were coming near Him to listen to Him.",
    2: "And both the Pharisees and the scribes began to grumble, saying, \"This man receives sinners, and eats with them.\"",
    3: "And He told them this parable, saying,",
    4: "\"What man among you, if he has a hundred sheep and has lost one of them, does not leave the ninety-nine in the open pasture, and go after the one which is lost, until he finds it?",
    5: "And when he has found it, he lays it on his shoulders, rejoicing.",
    6: "And when he comes home, he calls together his friends and his neighbors, saying to them, 'Rejoice with me, for I have found my sheep which was lost!'",
    7: "I tell you that in the same way, there will be more joy in heaven over one sinner who repents, than over ninety-nine righteous persons who need no repentance.",
    8: "Or what woman, if she has ten silver coins and loses one coin, does not light a lamp and sweep the house and search carefully until she finds it?",
    9: "And when she has found it, she calls together her friends and neighbors, saying, 'Rejoice with me, for I have found the coin which I had lost!'",
    10: "In the same way, I tell you, there is joy in the presence of the angels of God over one sinner who repents.\"",
    11: "And He said, \"A certain man had two sons.",
    12: "And the younger of them said to his father, 'Father, give me the share of the estate that falls to me.' And he divided his wealth between them.",
    13: "And not many days later, the younger son gathered everything together and went on a journey to a distant country. And there he squandered his estate with loose living.",
    14: "Now when he had spent everything, a severe famine occurred in that country, and he began to be in need.",
    15: "And he went and attached himself to one of the citizens of that country, and he sent him into his fields to feed swine.",
    16: "And he was longing to fill his stomach with the pods that the swine were eating — and no one was giving anything to him.",
    17: "But when he came to his senses, he said, 'How many of my father's hired men have more than enough bread, and I am dying here with hunger!",
    18: "I will get up and go to my father, and will say to him, \"Father, I have sinned against heaven, and in your sight.",
    19: "I am no longer worthy to be called your son. Make me as one of your hired men.\"'",
    20: "And he got up and came to his father. But while he was still a long way off, his father saw him, and felt compassion for him, and ran and embraced him, and kissed him.",
    21: "And the son said to him, 'Father, I have sinned against heaven, and in your sight — I am no longer worthy to be called your son.'",
    22: "But the father said to his slaves, 'Quickly bring out the best robe and put it on him, and put a ring on his hand and sandals on his feet.",
    23: "And bring the fattened calf, kill it, and let us eat and be merry.",
    24: "For this son of mine was dead, and has come to life again. He was lost, and has been found.' And they began to be merry.",
    25: "Now his older son was in the field — and when he came and approached the house, he heard music and dancing.",
    26: "And he summoned one of the servants, and began inquiring what these things might be.",
    27: "And he said to him, 'Your brother has come, and your father has killed the fattened calf, because he has received him back safe and sound.'",
    28: "But he became angry, and was not willing to go in. And his father came out and began entreating him.",
    29: "But he answered and said to his father, 'Look! For so many years I have been serving you, and I have never neglected a command of yours. And yet you have never given me a kid, that I might be merry with my friends.",
    30: "But when this son of yours came, who has devoured your wealth with harlots, you killed the fattened calf for him.'",
    31: "And he said to him, 'My child, you have always been with me, and all that is mine is yours.",
    32: "But we had to be merry and rejoice — for this brother of yours was dead and has begun to live, and was lost and has been found.'\"",
}
ch16 = {
    1: "Now He was also saying to the disciples, \"There was a certain rich man who had a steward. And this steward was reported to him as squandering his possessions.",
    2: "And he called him and said to him, 'What is this I hear about you? Give an account of your stewardship — for you can no longer be steward.'",
    3: "And the steward said to himself, 'What shall I do, since my master is taking the stewardship away from me? I am not strong enough to dig — I am ashamed to beg.",
    4: "I know what I shall do, so that when I am removed from the stewardship, they will receive me into their homes.'",
    5: "And he summoned each one of his master's debtors, and he began saying to the first, 'How much do you owe my master?'",
    6: "And he said, 'A hundred measures of oil.' And he said to him, 'Take your bill, and sit down quickly and write fifty.'",
    7: "Then he said to another, 'And how much do you owe?' And he said, 'A hundred measures of wheat.' He said to him, 'Take your bill, and write eighty.'",
    8: "And his master praised the unrighteous steward because he had acted shrewdly. For the sons of this age are more shrewd in relation to their own kind than the sons of light.",
    9: "And I say to you, make friends for yourselves by means of the mammon of unrighteousness — so that when it fails, they may receive you into the eternal dwellings.",
    10: "He who is faithful in a very little thing is faithful also in much — and he who is unrighteous in a very little thing is unrighteous also in much.",
    11: "If therefore you have not been faithful in the use of unrighteous mammon, who will entrust the true riches to you?",
    12: "And if you have not been faithful in the use of that which is another's, who will give you that which is your own?",
    13: "No servant can serve two masters. For either he will hate the one, and love the other — or else he will hold to one, and despise the other. You cannot serve God and mammon.\"",
    14: "Now the Pharisees, who were lovers of money, were listening to all these things, and they were scoffing at Him.",
    15: "And He said to them, \"You are those who justify yourselves in the sight of men, but God knows your hearts. For that which is highly esteemed among men is detestable in the sight of God.",
    16: "The Law and the Prophets were proclaimed until John. Since then the gospel of the kingdom of God is preached, and everyone is forcing his way into it.",
    17: "But it is easier for heaven and earth to pass away, than for one stroke of a letter of the Law to fail.",
    18: "Everyone who divorces his wife and marries another commits adultery — and he who marries one who is divorced from a husband commits adultery.",
    19: "Now there was a certain rich man, and he habitually dressed in purple and fine linen, gaily living in splendor every day.",
    20: "And a certain poor man named Lazarus was laid at his gate, covered with sores,",
    21: "and longing to be fed with the crumbs which were falling from the rich man's table. Besides, even the dogs were coming and licking his sores.",
    22: "Now it came about that the poor man died and he was carried away by the angels to Abraham's bosom — and the rich man also died and was buried.",
    23: "And in Hades he lifted up his eyes, being in torment, and saw Abraham far away, and Lazarus in his bosom.",
    24: "And he cried out and said, 'Father Abraham, have mercy on me, and send Lazarus, that he may dip the tip of his finger in water and cool off my tongue — for I am in agony in this flame.'",
    25: "But Abraham said, 'Child, remember that during your life you received your good things, and likewise Lazarus bad things — but now he is being comforted here, and you are in agony.",
    26: "And besides all this, between us and you there is a great chasm fixed, in order that those who wish to come over from here to you may not be able, and that none may cross over from there to us.'",
    27: "And he said, 'Then I beg you, Father, that you send him to my father's house —",
    28: "for I have five brothers — in order that he may warn them, lest they also come to this place of torment.'",
    29: "But Abraham said, 'They have Moses and the Prophets. Let them hear them.'",
    30: "But he said, 'No, Father Abraham, but if someone goes to them from the dead, they will repent!'",
    31: "But he said to him, 'If they do not listen to Moses and the Prophets, neither will they be persuaded if someone rises from the dead.'\"",
}
ch17 = {
    1: "And He said to His disciples, \"It is inevitable that stumbling blocks should come — but woe to him through whom they come!",
    2: "It would be better for him if a millstone were hung around his neck and he were thrown into the sea, than that he should cause one of these little ones to stumble.",
    3: "Be on your guard! If your brother sins, rebuke him — and if he repents, forgive him.",
    4: "And if he sins against you seven times a day, and returns to you seven times, saying, 'I repent,' forgive him.\"",
    5: "And the apostles said to the Lord, \"Increase our faith!\"",
    6: "And the Lord said, \"If you had faith like a mustard seed, you would say to this mulberry tree, 'Be uprooted and be planted in the sea,' and it would obey you.",
    7: "But which of you, having a slave plowing or tending sheep, will say to him when he has come in from the field, 'Come immediately and sit down to eat'?",
    8: "But will he not say to him, 'Prepare something for me to eat, and properly clothe yourself and serve me until I have eaten and drunk — and afterward you will eat and drink'?",
    9: "He does not thank the slave because he did the things which were commanded, does he?",
    10: "So you too, when you do all the things which are commanded you, say, 'We are unworthy slaves — we have done only that which we ought to have done.'\"",
    11: "And it came about while He was on the way to Jerusalem, that He was passing between Samaria and Galilee.",
    12: "And as He entered a certain village, ten leprous men who stood at a distance met Him.",
    13: "And they raised their voices, saying, \"Jesus, Master, have mercy on us!\"",
    14: "And when He saw them, He said to them, \"Go and show yourselves to the priests.\" And it came about that as they were going, they were cleansed.",
    15: "Now one of them, when he saw that he had been healed, turned back, glorifying God with a loud voice.",
    16: "And he fell on his face at His feet, giving thanks to Him. And he was a Samaritan.",
    17: "And Jesus answered and said, \"Were there not ten cleansed? But the nine — where are they?",
    18: "Was no one found who turned back to give glory to God, except this foreigner?\"",
    19: "And He said to him, \"Rise, and go your way. Your faith has made you well.\"",
    20: "Now having been questioned by the Pharisees as to when the kingdom of God was coming, He answered them and said, \"The kingdom of God is not coming with signs to be observed.",
    21: "Nor will they say, 'Look — here it is!' or, 'There it is!' For behold, the kingdom of God is in your midst.\"",
    22: "And He said to the disciples, \"The days shall come when you will long to see one of the days of the Son of Man, and you will not see it.",
    23: "And they will say to you, 'Look there!' or, 'Look here!' Do not go away, and do not run after them.",
    24: "For just like the lightning, when it flashes out of one part of the sky, shines to the other part of the sky — so will the Son of Man be in His day.",
    25: "But first He must suffer many things and be rejected by this generation.",
    26: "And just as it happened in the days of Noah, so it shall be also in the days of the Son of Man.",
    27: "They were eating, they were drinking, they were marrying, they were being given in marriage — until the day that Noah entered the ark, and the flood came and destroyed them all.",
    28: "It was the same as happened in the days of Lot — they were eating, they were drinking, they were buying, they were selling, they were planting, they were building.",
    29: "But on the day that Lot went out from Sodom it rained fire and brimstone from heaven and destroyed them all.",
    30: "It will be just the same on the day that the Son of Man is revealed.",
    31: "On that day, let not the one who is on the housetop, and whose goods are in the house, go down to take them away. And likewise let not the one who is in the field turn back.",
    32: "Remember Lot's wife.",
    33: "Whoever seeks to keep his life shall lose it — and whoever loses his life shall preserve it.",
    34: "I tell you, on that night there will be two men in one bed — one will be taken, and the other will be left.",
    35: "There will be two women grinding at the same place — one will be taken, and the other will be left.",
    36: "(Two men will be in the field — one will be taken, and the other will be left.)\"",
    37: "And answering they said to Him, \"Where, Lord?\" And He said to them, \"Where the body is, there also will the vultures be gathered.\"",
}
ch18 = {
    1: "Now He was telling them a parable to show that at all times they ought to pray and not to lose heart, saying,",
    2: "\"There was in a certain city a judge who did not fear God and did not respect man.",
    3: "And there was a widow in that city, and she kept coming to him, saying, 'Give me legal protection from my opponent.'",
    4: "And for a while he was unwilling. But afterward he said to himself, 'Even though I do not fear God nor respect man,",
    5: "yet because this widow bothers me, I will give her legal protection — lest by continually coming she wear me out.'\"",
    6: "And the Lord said, \"Hear what the unrighteous judge said —",
    7: "now shall not God bring about justice for His elect, who cry to Him day and night — and will He delay long over them?",
    8: "I tell you that He will bring about justice for them speedily. However, when the Son of Man comes, will He find faith on the earth?\"",
    9: "And He also told this parable to certain ones who trusted in themselves that they were righteous, and viewed others with contempt:",
    10: "\"Two men went up into the temple to pray, one a Pharisee and the other a tax-gatherer.",
    11: "The Pharisee stood and was praying thus to himself, 'God, I thank You that I am not like other people — swindlers, unjust, adulterers — or even like this tax-gatherer.",
    12: "I fast twice a week. I pay tithes of all that I get.'",
    13: "But the tax-gatherer, standing some distance away, was even unwilling to lift up his eyes to heaven. But was beating his breast, saying, 'God, be merciful to me — the sinner!'",
    14: "I tell you, this man went down to his house justified rather than the other. For everyone who exalts himself shall be humbled — but he who humbles himself shall be exalted.\"",
    15: "And they were bringing even their babies to Him so that He might touch them. But when the disciples saw it, they began rebuking them.",
    16: "But Jesus called for them, saying, \"Permit the children to come to Me, and do not hinder them — for the kingdom of God belongs to such as these.",
    17: "Truly I say to you, whoever does not receive the kingdom of God like a child shall not enter it at all.\"",
    18: "And a certain ruler questioned Him, saying, \"Good Teacher, what shall I do to inherit eternal life?\"",
    19: "And Jesus said to him, \"Why do you call Me good? No one is good except God alone.",
    20: "You know the commandments — 'Do not commit adultery, do not murder, do not steal, do not bear false witness, honor your father and mother.'\"",
    21: "And he said, \"All these things I have kept from my youth.\"",
    22: "And when Jesus heard this, He said to him, \"One thing you still lack. Sell all that you possess, and distribute it to the poor — and you shall have treasure in heaven. And come, follow Me.\"",
    23: "But when he had heard these things, he became very sad — for he was extremely rich.",
    24: "And Jesus looked at him and said, \"How hard it is for those who are wealthy to enter the kingdom of God!",
    25: "For it is easier for a camel to go through the eye of a needle, than for a rich man to enter the kingdom of God.\"",
    26: "And those who heard it said, \"Then who can be saved?\"",
    27: "But He said, \"The things impossible with men are possible with God.\"",
    28: "And Peter said, \"Behold, we have left our own homes, and followed You.\"",
    29: "And He said to them, \"Truly I say to you — there is no one who has left house or wife or brothers or parents or children, for the sake of the kingdom of God,",
    30: "who shall not receive many times as much at this time, and in the age to come, eternal life.\"",
    31: "And He took the twelve aside and said to them, \"Behold, we are going up to Jerusalem — and all things which are written through the prophets about the Son of Man will be accomplished.",
    32: "For He will be delivered up to the Gentiles, and will be mocked and mistreated and spit upon,",
    33: "and after they have scourged Him, they will kill Him. And the third day He will rise again.\"",
    34: "And they understood none of these things. And this saying was hidden from them, and they did not comprehend the things that were said.",
    35: "And it came about that as He was approaching Jericho, a certain blind man was sitting by the road, begging.",
    36: "Now hearing a multitude going by, he began to inquire what this might be.",
    37: "And they told him that Jesus of Nazareth was passing by.",
    38: "And he called out, saying, \"Jesus, Son of David, have mercy on me!\"",
    39: "And those who led the way were sternly telling him to be quiet — but he kept crying out all the more, \"Son of David, have mercy on me!\"",
    40: "And Jesus stopped, and commanded that he be brought to Him. And when he had come near, He questioned him,",
    41: "\"What do you want Me to do for you?\" And he said, \"Lord, I want to regain my sight!\"",
    42: "And Jesus said to him, \"Receive your sight! Your faith has made you well.\"",
    43: "And immediately he regained his sight, and began following Him, glorifying God. And when all the people saw it, they gave praise to God.",
}

CHAPTERS = {13:ch13,14:ch14,15:ch15,16:ch16,17:ch17,18:ch18}

def main():
    new_entries = {f"42_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Luke 13-18 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Luke 13-18 verses")

if __name__ == "__main__":
    main()
