"""MBT Matthew 8-14 — miracles, mission, parables, John's death. 288 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch8 = {
    1: "And when He had come down from the mountain, great multitudes followed Him.",
    2: "And behold, a leper came to Him, and bowed down to Him, saying, \"Lord, if You are willing, You can make me clean.\"",
    3: "And He stretched out His hand and touched him, saying, \"I am willing — be cleansed.\" And immediately his leprosy was cleansed.",
    4: "And Jesus said to him, \"See that you tell no one. But go, show yourself to the priest, and present the offering that Moses commanded — as a testimony to them.\"",
    5: "And when He had entered Capernaum, a centurion came to Him, entreating Him,",
    6: "and saying, \"Lord, my servant is lying paralyzed at home — fearfully tormented.\"",
    7: "And He said to him, \"I will come and heal him.\"",
    8: "But the centurion answered and said, \"Lord, I am not worthy for You to come under my roof. But just say the word — and my servant will be healed.",
    9: "For I, too, am a man under authority, with soldiers under me — and I say to this one, 'Go!' and he goes; and to another, 'Come!' and he comes; and to my slave, 'Do this!' and he does it.\"",
    10: "Now when Jesus heard this, He marveled, and said to those who were following, \"Truly I say to you — I have not found such great faith with anyone in Israel.",
    11: "And I say to you, that many shall come from east and west — and recline at the table with Abraham, and Isaac, and Jacob in the kingdom of heaven.",
    12: "But the sons of the kingdom shall be cast out into the outer darkness. In that place there shall be weeping and gnashing of teeth.\"",
    13: "And Jesus said to the centurion, \"Go your way — let it be done to you as you have believed.\" And the servant was healed that very hour.",
    14: "And when Jesus had come to Peter's home, He saw his mother-in-law lying sick in bed with a fever.",
    15: "And He touched her hand — and the fever left her. And she arose, and began to wait on Him.",
    16: "And when evening had come, they brought to Him many who were demon-possessed — and He cast out the spirits with a word, and healed all who were ill.",
    17: "In order that what was spoken through Isaiah the prophet might be fulfilled, saying, \"He Himself took our infirmities, and carried away our diseases.\"",
    18: "Now when Jesus saw a crowd around Him, He gave orders to depart to the other side.",
    19: "And a certain scribe came and said to Him, \"Teacher — I will follow You wherever You go.\"",
    20: "And Jesus said to him, \"The foxes have holes, and the birds of the air have nests — but the Son of Man has nowhere to lay His head.\"",
    21: "And another of the disciples said to Him, \"Lord, permit me first to go and bury my father.\"",
    22: "But Jesus said to him, \"Follow Me — and allow the dead to bury their own dead.\"",
    23: "And when He got into the boat, His disciples followed Him.",
    24: "And behold, there arose a great storm in the sea — so that the boat was covered with the waves. But He Himself was asleep.",
    25: "And they came to Him, and awoke Him, saying, \"Save us, Lord — we are perishing!\"",
    26: "And He said to them, \"Why are you timid, you men of little faith?\" Then He arose, and rebuked the winds and the sea — and it became perfectly calm.",
    27: "And the men marveled, saying, \"What kind of a man is this — that even the winds and the sea obey Him?\"",
    28: "And when He had come to the other side, into the country of the Gadarenes, two men who were demon-possessed met Him as they were coming out of the tombs — exceedingly violent, so that no one could pass by that way.",
    29: "And behold, they cried out, saying, \"What do we have to do with You, Son of God? Have You come here to torment us before the time?\"",
    30: "Now there was at a distance from them a herd of many swine feeding.",
    31: "And the demons began to entreat Him, saying, \"If You are going to cast us out, send us into the herd of swine.\"",
    32: "And He said to them, \"Go!\" And they came out, and went into the swine — and behold, the whole herd rushed down the steep bank into the sea, and perished in the waters.",
    33: "And the herdsmen ran away, and went to the city, and reported everything — including what had happened to the demoniacs.",
    34: "And behold, the whole city came out to meet Jesus — and when they saw Him, they entreated Him to depart from their region.",
}
ch9 = {
    1: "And getting into a boat, He crossed over and came to His own city.",
    2: "And behold, they were bringing to Him a paralytic, lying on a bed. And Jesus, seeing their faith, said to the paralytic, \"Take courage, My son — your sins are forgiven.\"",
    3: "And behold, certain of the scribes said to themselves, \"This fellow blasphemes!\"",
    4: "And Jesus, knowing their thoughts, said, \"Why are you thinking evil in your hearts?",
    5: "For which is easier — to say, 'Your sins are forgiven,' or to say, 'Arise, and walk'?",
    6: "But that you may know that the Son of Man has authority on earth to forgive sins\" — then He said to the paralytic — \"Arise, take up your bed, and go home.\"",
    7: "And he arose, and went home.",
    8: "But when the multitudes saw this, they were filled with awe, and glorified God — who had given such authority to men.",
    9: "And as Jesus passed on from there, He saw a man called Matthew, sitting in the tax office. And He said to him, \"Follow Me.\" And he arose, and followed Him.",
    10: "And it happened that as Jesus was reclining at the table in the house, behold many tax-gatherers and sinners came and were dining with Jesus and His disciples.",
    11: "And when the Pharisees saw this, they began saying to His disciples, \"Why is your Teacher eating with the tax-gatherers and sinners?\"",
    12: "But when He heard this, He said, \"It is not those who are healthy who need a physician, but those who are sick.",
    13: "But go and learn what this means — 'I desire compassion, and not sacrifice' — for I did not come to call the righteous, but sinners.\"",
    14: "Then the disciples of John came to Him, saying, \"Why do we and the Pharisees fast — but Your disciples do not fast?\"",
    15: "And Jesus said to them, \"The attendants of the bridegroom cannot mourn, can they, as long as the bridegroom is with them? But the days will come when the bridegroom is taken away from them — and then they will fast.",
    16: "But no one puts a patch of unshrunk cloth on an old garment — for the patch pulls away from the garment, and a worse tear results.",
    17: "Nor do men put new wine into old wineskins. Otherwise, the wineskins burst, and the wine pours out, and the wineskins are ruined. But they put new wine into fresh wineskins — and both are preserved.\"",
    18: "While He was saying these things to them, behold, there came a synagogue official, and bowed down before Him, saying, \"My daughter has just died. But come and lay Your hand on her — and she will live.\"",
    19: "And Jesus rose and began to follow him, and so did His disciples.",
    20: "And behold, a woman who had been suffering from a hemorrhage for twelve years, came up behind Him and touched the fringe of His cloak.",
    21: "For she was saying to herself, \"If I only touch His garment, I shall get well.\"",
    22: "But Jesus turning and seeing her said, \"Daughter, take courage — your faith has made you well.\" And at once the woman was made well.",
    23: "And when Jesus came into the official's house, and saw the flute-players, and the crowd in noisy disorder,",
    24: "He began to say, \"Depart — for the girl has not died, but is asleep.\" And they began laughing at Him.",
    25: "But when the crowd had been put out, He entered and took her by the hand — and the girl arose.",
    26: "And this news went out into all that land.",
    27: "And as Jesus passed on from there, two blind men followed Him, crying out and saying, \"Have mercy on us, Son of David!\"",
    28: "And after He had come into the house, the blind men came up to Him. And Jesus said to them, \"Do you believe that I am able to do this?\" They said to Him, \"Yes, Lord.\"",
    29: "Then He touched their eyes, saying, \"Be it done to you according to your faith.\"",
    30: "And their eyes were opened. And Jesus sternly warned them, saying, \"See here, let no one know about this!\"",
    31: "But they went out, and spread the news about Him in all that land.",
    32: "And as they were going out, behold, a dumb man, demon-possessed, was brought to Him.",
    33: "And after the demon was cast out, the dumb man spoke. And the multitudes marveled, saying, \"Nothing like this has ever been seen in Israel.\"",
    34: "But the Pharisees were saying, \"He casts out the demons by the ruler of the demons.\"",
    35: "And Jesus was going about all the cities and the villages, teaching in their synagogues, and proclaiming the gospel of the kingdom, and healing every kind of disease and every kind of sickness.",
    36: "And seeing the multitudes, He felt compassion for them — because they were distressed and downcast like sheep without a shepherd.",
    37: "Then He said to His disciples, \"The harvest is plentiful — but the workers are few.",
    38: "Therefore beseech the Lord of the harvest to send out workers into His harvest.\"",
}
ch10 = {
    1: "And having summoned His twelve disciples, He gave them authority over unclean spirits, to cast them out, and to heal every kind of disease and every kind of sickness.",
    2: "Now the names of the twelve apostles are these: The first, Simon, who is called Peter, and Andrew his brother; and James the son of Zebedee, and John his brother;",
    3: "Philip and Bartholomew; Thomas and Matthew the tax-gatherer; James the son of Alphaeus, and Thaddaeus;",
    4: "Simon the Zealot, and Judas Iscariot — the one who betrayed Him.",
    5: "These twelve Jesus sent out, after instructing them, saying: \"Do not go in the way of the Gentiles, and do not enter any city of the Samaritans.",
    6: "But rather go to the lost sheep of the house of Israel.",
    7: "And as you go, preach, saying, 'The kingdom of heaven is at hand.'",
    8: "Heal the sick, raise the dead, cleanse the lepers, cast out demons. Freely you received — freely give.",
    9: "Do not acquire gold, or silver, or copper for your money belts.",
    10: "Or a bag for your journey, or even two tunics, or sandals, or a staff — for the worker is worthy of his support.",
    11: "And into whatever city or village you enter, inquire who is worthy in it; and abide there until you go away.",
    12: "And as you enter the house, give it your greeting.",
    13: "And if the house is worthy, let your greeting of peace come upon it. But if it is not worthy, let your greeting of peace return to you.",
    14: "And whoever does not receive you, nor heed your words — as you go out of that house or that city, shake off the dust of your feet.",
    15: "Truly I say to you — it will be more tolerable for the land of Sodom and Gomorrah in the day of judgment, than for that city.",
    16: "Behold, I send you out as sheep in the midst of wolves. Therefore be shrewd as serpents — and innocent as doves.",
    17: "But beware of men. For they will deliver you up to the courts, and scourge you in their synagogues.",
    18: "And you shall even be brought before governors and kings for My sake — as a testimony to them, and to the Gentiles.",
    19: "But when they deliver you up, do not become anxious about how or what you will speak — for it shall be given you in that hour what you are to speak.",
    20: "For it is not you who speak — but it is the Spirit of your Father who speaks in you.",
    21: "And brother will deliver up brother to death, and a father his child. And children will rise up against parents, and cause them to be put to death.",
    22: "And you will be hated by all on account of My name — but it is the one who has endured to the end who will be saved.",
    23: "But whenever they persecute you in this city, flee to the next. For truly I say to you, you shall not finish going through the cities of Israel, until the Son of Man comes.",
    24: "A disciple is not above his teacher — nor a slave above his master.",
    25: "It is enough for the disciple that he become as his teacher, and the slave as his master. If they have called the head of the house Beelzebul, how much more the members of his household!",
    26: "Therefore do not fear them. For there is nothing covered that will not be revealed — and hidden that will not be known.",
    27: "What I tell you in the darkness, speak in the light. And what you hear whispered in your ear, proclaim upon the housetops.",
    28: "And do not fear those who kill the body, but are unable to kill the soul. But rather fear Him who is able to destroy both soul and body in hell.",
    29: "Are not two sparrows sold for a cent? And yet not one of them will fall to the ground apart from your Father.",
    30: "But the very hairs of your head are all numbered.",
    31: "Therefore do not fear — you are of more value than many sparrows.",
    32: "Everyone therefore who shall confess Me before men, I will also confess him before My Father who is in heaven.",
    33: "But whoever shall deny Me before men, I will also deny him before My Father who is in heaven.",
    34: "Do not think that I came to bring peace on the earth. I did not come to bring peace, but a sword.",
    35: "For I came to set a man against his father, and a daughter against her mother, and a daughter-in-law against her mother-in-law.",
    36: "And a man's enemies will be the members of his household.",
    37: "He who loves father or mother more than Me is not worthy of Me. And he who loves son or daughter more than Me is not worthy of Me.",
    38: "And he who does not take his cross and follow after Me is not worthy of Me.",
    39: "He who has found his life shall lose it — and he who has lost his life for My sake shall find it.",
    40: "He who receives you receives Me — and he who receives Me receives Him who sent Me.",
    41: "He who receives a prophet in the name of a prophet shall receive a prophet's reward. And he who receives a righteous man in the name of a righteous man shall receive a righteous man's reward.",
    42: "And whoever in the name of a disciple gives to one of these little ones even a cup of cold water to drink — truly I say to you, he shall not lose his reward.\"",
}
ch11 = {
    1: "And it came about that when Jesus had finished giving instructions to His twelve disciples, He departed from there to teach and preach in their cities.",
    2: "Now when John, in prison, heard of the works of Christ, he sent word by his disciples,",
    3: "and said to Him, \"Are You the Expected One — or shall we look for someone else?\"",
    4: "And Jesus answered and said to them, \"Go and report to John what you hear and see:",
    5: "the blind receive sight, and the lame walk; the lepers are cleansed, and the deaf hear; and the dead are raised up, and the poor have the gospel preached to them.",
    6: "And blessed is he who keeps from stumbling over Me.\"",
    7: "And as these were going away, Jesus began to speak to the multitudes about John, \"What did you go out into the wilderness to see? A reed shaken by the wind?",
    8: "But what did you go out to see? A man dressed in soft clothing? Behold, those who wear soft clothing are in kings' palaces.",
    9: "But why did you go out? To see a prophet? Yes, I tell you — and one who is more than a prophet.",
    10: "This is the one about whom it is written, 'Behold, I send My messenger before Your face — who will prepare Your way before You.'",
    11: "Truly, I say to you, among those born of women there has not arisen anyone greater than John the Baptist. Yet he who is least in the kingdom of heaven is greater than he.",
    12: "And from the days of John the Baptist until now, the kingdom of heaven suffers violence — and violent men take it by force.",
    13: "For all the prophets and the Law prophesied until John.",
    14: "And if you care to accept it, he himself is Elijah, who was to come.",
    15: "He who has ears to hear, let him hear.",
    16: "But to what shall I compare this generation? It is like children sitting in the market places, who call out to the other children,",
    17: "and say, 'We played the flute for you, and you did not dance. We sang a dirge, and you did not mourn.'",
    18: "For John came neither eating nor drinking, and they say, 'He has a demon.'",
    19: "The Son of Man came eating and drinking, and they say, 'Behold, a gluttonous man and a drunkard, a friend of tax-gatherers and sinners!' Yet wisdom is vindicated by her deeds.\"",
    20: "Then He began to reproach the cities in which most of His miracles were done, because they did not repent.",
    21: "\"Woe to you, Chorazin! Woe to you, Bethsaida! For if the miracles had occurred in Tyre and Sidon which occurred in you, they would have repented long ago in sackcloth and ashes.",
    22: "Nevertheless I say to you — it shall be more tolerable for Tyre and Sidon in the day of judgment than for you.",
    23: "And you, Capernaum, will not be exalted to heaven, will you? You shall descend to Hades. For if the miracles had occurred in Sodom which occurred in you, it would have remained to this day.",
    24: "Nevertheless I say to you that it shall be more tolerable for the land of Sodom in the day of judgment, than for you.\"",
    25: "At that time Jesus answered and said, \"I praise You, Father, Lord of heaven and earth, that You did hide these things from the wise and intelligent — and didst reveal them to babes.",
    26: "Yes, Father, for thus it was well-pleasing in Your sight.",
    27: "All things have been handed over to Me by My Father — and no one knows the Son, except the Father. Nor does anyone know the Father, except the Son, and anyone to whom the Son wills to reveal Him.",
    28: "Come to Me, all who are weary and heavy-laden — and I will give you rest.",
    29: "Take My yoke upon you, and learn from Me — for I am gentle and humble in heart. And you shall find rest for your souls.",
    30: "For My yoke is easy, and My load is light.\"",
}
ch12 = {
    1: "At that time Jesus went through the grainfields on the Sabbath. And His disciples became hungry, and began to pick the heads of grain and eat.",
    2: "But when the Pharisees saw it, they said to Him, \"Behold, Your disciples do what is not lawful to do on a Sabbath.\"",
    3: "But He said to them, \"Have you not read what David did, when he became hungry, he and his companions?",
    4: "How he entered the house of God, and they ate the consecrated bread, which was not lawful for him to eat — nor for those with him — but for the priests alone?",
    5: "Or have you not read in the Law, that on the Sabbath the priests in the temple break the Sabbath, and are innocent?",
    6: "But I say to you, that something greater than the temple is here.",
    7: "But if you had known what this means, 'I desire compassion, and not a sacrifice,' you would not have condemned the innocent.",
    8: "For the Son of Man is Lord of the Sabbath.\"",
    9: "And departing from there, He went into their synagogue.",
    10: "And behold, there was a man with a withered hand. And they questioned Him, saying, \"Is it lawful to heal on the Sabbath?\" — in order that they might accuse Him.",
    11: "And He said to them, \"What man shall there be among you, who shall have one sheep, and if it falls into a pit on the Sabbath, will he not take hold of it, and lift it out?",
    12: "Of how much more value then is a man than a sheep! So then, it is lawful to do good on the Sabbath.\"",
    13: "Then He said to the man, \"Stretch out your hand!\" And he stretched it out, and it was restored to normal, like the other.",
    14: "But the Pharisees went out, and counseled together against Him — as to how they might destroy Him.",
    15: "But Jesus, aware of this, withdrew from there. And many followed Him — and He healed them all,",
    16: "and warned them not to make Him known.",
    17: "In order that what was spoken through Isaiah the prophet might be fulfilled, saying,",
    18: "\"Behold, My Servant whom I have chosen — My Beloved in whom My soul is well-pleased. I will put My Spirit upon Him, and He shall proclaim justice to the Gentiles.",
    19: "He will not quarrel, nor cry out. Nor will anyone hear His voice in the streets.",
    20: "A battered reed He will not break off, and a smoldering wick He will not put out — until He leads justice to victory.",
    21: "And in His name the Gentiles will hope.\"",
    22: "Then there was brought to Him a demon-possessed man who was blind and dumb. And He healed him — so that the dumb man spoke and saw.",
    23: "And all the multitudes were amazed, and began to say, \"This man cannot be the Son of David, can he?\"",
    24: "But when the Pharisees heard it, they said, \"This man casts out demons only by Beelzebul, the ruler of the demons.\"",
    25: "And knowing their thoughts He said to them, \"Any kingdom divided against itself is laid waste. And any city or house divided against itself shall not stand.",
    26: "And if Satan casts out Satan, he is divided against himself. How then shall his kingdom stand?",
    27: "And if I by Beelzebul cast out demons, by whom do your sons cast them out? Consequently they shall be your judges.",
    28: "But if I cast out demons by the Spirit of God, then the kingdom of God has come upon you.",
    29: "Or how can anyone enter the strong man's house and carry off his property, unless he first binds the strong man? And then he will plunder his house.",
    30: "He who is not with Me is against Me — and he who does not gather with Me scatters.",
    31: "Therefore I say to you, any sin and blasphemy shall be forgiven men, but blasphemy against the Spirit shall not be forgiven.",
    32: "And whoever shall speak a word against the Son of Man, it shall be forgiven him. But whoever shall speak against the Holy Spirit, it shall not be forgiven him — either in this age, or in the age to come.",
    33: "Either make the tree good, and its fruit good — or make the tree bad, and its fruit bad. For the tree is known by its fruit.",
    34: "You brood of vipers — how can you, being evil, speak what is good? For the mouth speaks out of that which fills the heart.",
    35: "The good man brings out of his good treasure what is good. And the evil man brings out of his evil treasure what is evil.",
    36: "And I say to you, that every careless word that men shall speak — they shall render account for it in the day of judgment.",
    37: "For by your words you shall be justified — and by your words you shall be condemned.\"",
    38: "Then some of the scribes and Pharisees answered Him, saying, \"Teacher, we want to see a sign from You.\"",
    39: "But He answered and said to them, \"An evil and adulterous generation craves for a sign. And yet no sign shall be given to it but the sign of Jonah the prophet.",
    40: "For just as Jonah was three days and three nights in the belly of the sea monster — so shall the Son of Man be three days and three nights in the heart of the earth.",
    41: "The men of Nineveh shall stand up with this generation at the judgment, and shall condemn it. Because they repented at the preaching of Jonah — and behold, something greater than Jonah is here.",
    42: "The Queen of the South shall rise up with this generation at the judgment and shall condemn it. Because she came from the ends of the earth to hear the wisdom of Solomon — and behold, something greater than Solomon is here.",
    43: "Now when the unclean spirit goes out of a man, it passes through waterless places, seeking rest, and does not find it.",
    44: "Then it says, 'I will return to my house from which I came.' And when it comes, it finds it unoccupied, swept, and put in order.",
    45: "Then it goes, and takes along with it seven other spirits more wicked than itself, and they go in and live there — and the last state of that man becomes worse than the first. That is the way it will also be with this evil generation.\"",
    46: "While He was still speaking to the multitudes, behold, His mother and brothers were standing outside, seeking to speak to Him.",
    47: "And someone said to Him, \"Behold, Your mother and Your brothers are standing outside seeking to speak to You.\"",
    48: "But He answered the one who was telling Him and said, \"Who is My mother, and who are My brothers?\"",
    49: "And stretching out His hand toward His disciples, He said, \"Behold, My mother and My brothers!",
    50: "For whoever does the will of My Father who is in heaven, he is My brother, and sister, and mother.\"",
}
ch13 = {
    1: "On that day Jesus had gone out of the house, and was sitting by the sea.",
    2: "And great multitudes gathered to Him — so He got into a boat and sat down. And the whole multitude was standing on the beach.",
    3: "And He spoke many things to them in parables, saying, \"Behold, the sower went out to sow.",
    4: "And as he sowed, some seeds fell beside the road, and the birds came and ate them up.",
    5: "And others fell upon the rocky places, where they did not have much soil — and immediately they sprang up, because they had no depth of soil.",
    6: "But when the sun had risen, they were scorched. And because they had no root, they withered away.",
    7: "And others fell among the thorns — and the thorns came up and choked them out.",
    8: "And others fell on the good soil — and yielded a crop, some a hundredfold, some sixty, and some thirty.",
    9: "He who has ears, let him hear.\"",
    10: "And the disciples came and said to Him, \"Why do You speak to them in parables?\"",
    11: "And He answered and said to them, \"To you it has been granted to know the mysteries of the kingdom of heaven — but to them it has not been granted.",
    12: "For whoever has, to him shall more be given, and he shall have an abundance — but whoever does not have, even what he has shall be taken away from him.",
    13: "Therefore I speak to them in parables. Because while seeing they do not see, and while hearing they do not hear, nor do they understand.",
    14: "And in their case the prophecy of Isaiah is being fulfilled, which says: 'You will keep on hearing, but will not understand. And you will keep on seeing, but will not perceive.",
    15: "For the heart of this people has become dull, and with their ears they scarcely hear, and they have closed their eyes — lest they should see with their eyes, and hear with their ears, and understand with their heart, and return — and I should heal them.'",
    16: "But blessed are your eyes, because they see — and your ears, because they hear.",
    17: "For truly I say to you, that many prophets and righteous men desired to see what you see — and did not see it. And to hear what you hear — and did not hear it.",
    18: "Hear then the parable of the sower.",
    19: "When anyone hears the word of the kingdom, and does not understand it, the evil one comes and snatches away what has been sown in his heart. This is the one on whom seed was sown beside the road.",
    20: "And the one on whom seed was sown on the rocky places, this is the man who hears the word, and immediately receives it with joy.",
    21: "Yet he has no firm root in himself, but is only temporary. And when affliction or persecution arises because of the word, immediately he falls away.",
    22: "And the one on whom seed was sown among the thorns, this is the man who hears the word — and the worry of the world and the deceitfulness of riches choke the word, and it becomes unfruitful.",
    23: "And the one on whom seed was sown on the good soil — this is the man who hears the word and understands it. Who indeed bears fruit, and brings forth, some a hundredfold, some sixty, and some thirty.\"",
    24: "He presented another parable to them, saying, \"The kingdom of heaven may be compared to a man who sowed good seed in his field.",
    25: "But while men were sleeping, his enemy came and sowed tares also among the wheat, and went away.",
    26: "But when the wheat sprang up and bore grain, then the tares became evident also.",
    27: "And the slaves of the landowner came and said to him, 'Sir, did you not sow good seed in your field? How then does it have tares?'",
    28: "And he said to them, 'An enemy has done this!' And the slaves said to him, 'Do you want us, then, to go and gather them up?'",
    29: "But he said, 'No, lest while you are gathering up the tares, you may root up the wheat with them.",
    30: "Allow both to grow together until the harvest. And in the time of the harvest I will say to the reapers, \"First gather up the tares and bind them in bundles to burn them up. But gather the wheat into my barn.\"'\"",
    31: "He presented another parable to them, saying, \"The kingdom of heaven is like a mustard seed, which a man took and sowed in his field.",
    32: "And this is smaller than all other seeds. But when it is full grown, it is larger than the garden plants, and becomes a tree — so that the birds of the air come and nest in its branches.\"",
    33: "He spoke another parable to them, \"The kingdom of heaven is like leaven, which a woman took and hid in three pecks of meal — until it was all leavened.\"",
    34: "All these things Jesus spoke to the multitudes in parables — and He did not speak to them without a parable.",
    35: "So that what was spoken through the prophet might be fulfilled, saying, \"I will open My mouth in parables. I will utter things hidden since the foundation of the world.\"",
    36: "Then He left the multitudes, and went into the house. And His disciples came to Him, saying, \"Explain to us the parable of the tares of the field.\"",
    37: "And He answered and said, \"The one who sows the good seed is the Son of Man.",
    38: "And the field is the world. And as for the good seed, these are the sons of the kingdom. And the tares are the sons of the evil one.",
    39: "And the enemy who sowed them is the devil — and the harvest is the end of the age, and the reapers are angels.",
    40: "Therefore just as the tares are gathered up and burned with fire — so shall it be at the end of the age.",
    41: "The Son of Man will send forth His angels — and they will gather out of His kingdom all stumbling blocks, and those who commit lawlessness.",
    42: "And will cast them into the furnace of fire — in that place there shall be weeping and gnashing of teeth.",
    43: "Then the righteous will shine forth as the sun in the kingdom of their Father. He who has ears, let him hear.",
    44: "The kingdom of heaven is like a treasure hidden in the field, which a man found and hid again. And from joy over it he goes and sells all that he has, and buys that field.",
    45: "Again, the kingdom of heaven is like a merchant seeking fine pearls.",
    46: "And upon finding one pearl of great value, he went and sold all that he had, and bought it.",
    47: "Again, the kingdom of heaven is like a dragnet cast into the sea, and gathering fish of every kind.",
    48: "And when it was filled, they drew it up on the beach. And they sat down, and gathered the good fish into containers — but the bad they threw away.",
    49: "So it will be at the end of the age. The angels shall come forth, and take out the wicked from among the righteous,",
    50: "and will cast them into the furnace of fire. In that place there shall be weeping and gnashing of teeth.",
    51: "Have you understood all these things?\" They said to Him, \"Yes.\"",
    52: "And He said to them, \"Therefore every scribe who has become a disciple of the kingdom of heaven is like a head of a household — who brings forth out of his treasure things new and old.\"",
    53: "And it came about that when Jesus had finished these parables, He departed from there.",
    54: "And coming to His hometown He began teaching them in their synagogue — so that they became astonished, and said, \"Where did this man get this wisdom, and these miraculous powers?",
    55: "Is not this the carpenter's son? Is not His mother called Mary, and His brothers, James and Joseph and Simon and Judas?",
    56: "And His sisters — are they not all with us? Where then did this man get all these things?\"",
    57: "And they took offense at Him. But Jesus said to them, \"A prophet is not without honor — except in his hometown, and in his own household.\"",
    58: "And He did not do many miracles there — because of their unbelief.",
}
ch14 = {
    1: "At that time Herod the tetrarch heard the news about Jesus,",
    2: "and said to his servants, \"This is John the Baptist. He has risen from the dead — and that is why these miraculous powers are at work in Him.\"",
    3: "For when Herod had laid hold of John, he bound him, and put him in prison on account of Herodias, the wife of his brother Philip.",
    4: "For John had been saying to him, \"It is not lawful for you to have her.\"",
    5: "And although he wanted to put him to death, he feared the multitude — because they regarded him as a prophet.",
    6: "But when Herod's birthday came, the daughter of Herodias danced before them, and pleased Herod.",
    7: "So much that he promised with an oath to give her whatever she might ask.",
    8: "And having been prompted by her mother, she said, \"Give me here, on a platter, the head of John the Baptist.\"",
    9: "And although he was grieved, the king commanded it to be given because of his oaths, and because of his dinner guests.",
    10: "And he sent and had John beheaded in the prison.",
    11: "And his head was brought on a platter and given to the girl. And she brought it to her mother.",
    12: "And his disciples came and took away the body and buried it. And they went and reported to Jesus.",
    13: "Now when Jesus heard it, He withdrew from there in a boat — to a lonely place by Himself. And when the multitudes heard of this, they followed Him on foot from the cities.",
    14: "And when He went ashore, He saw a great multitude — and felt compassion for them, and healed their sick.",
    15: "And when it was evening, the disciples came to Him, saying, \"The place is desolate, and the time is already past. So send the multitudes away — that they may go into the villages and buy food for themselves.\"",
    16: "But Jesus said to them, \"They do not need to go away. You give them something to eat!\"",
    17: "And they said to Him, \"We have here only five loaves and two fish.\"",
    18: "And He said, \"Bring them here to Me.\"",
    19: "And ordering the multitudes to recline on the grass, He took the five loaves and the two fish — and looking up toward heaven, He blessed the food, and breaking the loaves He gave them to the disciples. And the disciples gave to the multitudes.",
    20: "And they all ate, and were satisfied. And they picked up what was left over of the broken pieces — twelve full baskets.",
    21: "And there were about five thousand men who ate — aside from women and children.",
    22: "And immediately He made the disciples get into the boat, and go ahead of Him to the other side — while He sent the multitudes away.",
    23: "And after He had sent the multitudes away, He went up to the mountain by Himself to pray. And when it was evening, He was there alone.",
    24: "But the boat was already many stadia away from the land, battered by the waves — for the wind was contrary.",
    25: "And in the fourth watch of the night He came to them, walking on the sea.",
    26: "And when the disciples saw Him walking on the sea, they were frightened, saying, \"It is a ghost!\" And they cried out for fear.",
    27: "But immediately Jesus spoke to them, saying, \"Take courage — it is I. Do not be afraid.\"",
    28: "And Peter answered Him and said, \"Lord, if it is You, command me to come to You on the water.\"",
    29: "And He said, \"Come!\" And Peter got out of the boat, and walked on the water, and came toward Jesus.",
    30: "But seeing the wind, he became afraid. And beginning to sink, he cried out, saying, \"Lord — save me!\"",
    31: "And immediately Jesus stretched out His hand and took hold of him, and said to him, \"O you of little faith — why did you doubt?\"",
    32: "And when they got into the boat, the wind stopped.",
    33: "And those who were in the boat worshiped Him, saying, \"You are certainly God's Son!\"",
    34: "And when they had crossed over, they came to land at Gennesaret.",
    35: "And when the men of that place recognized Him, they sent into all that surrounding district, and brought to Him all who were sick.",
    36: "And they began to entreat Him that they might just touch the fringe of His cloak — and as many as touched it were cured.",
}

CHAPTERS = {8:ch8,9:ch9,10:ch10,11:ch11,12:ch12,13:ch13,14:ch14}

def main():
    new_entries = {f"40_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Matthew 8-14 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Matthew 8-14 verses")

if __name__ == "__main__":
    main()
