"""MBT Luke 7-12 — Galilean ministry, parables, instruction. 323 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch7 = {
    1: "When He had completed all His discourse in the hearing of the people, He went to Capernaum.",
    2: "And a certain centurion's slave, who was highly regarded by him, was sick and about to die.",
    3: "And when he heard about Jesus, he sent some Jewish elders asking Him to come and save the life of his slave.",
    4: "And when they had come to Jesus, they earnestly entreated Him, saying, \"He is worthy for You to grant this to him.",
    5: "For he loves our nation, and it was he who built us our synagogue.\"",
    6: "Now Jesus started on His way with them. And when He was already not far from the house, the centurion sent friends, saying to Him, \"Lord, do not trouble Yourself further — for I am not worthy for You to come under my roof.",
    7: "For this reason I did not even consider myself worthy to come to You. But just say the word — and my servant will be healed.",
    8: "For I, too, am a man placed under authority, with soldiers under me. And I say to this one, 'Go!' and he goes; and to another, 'Come!' and he comes; and to my slave, 'Do this!' and he does it.\"",
    9: "Now when Jesus heard this, He marveled at him. And turning to the multitude that was following Him, He said, \"I tell you, not even in Israel have I found such great faith.\"",
    10: "And when those who had been sent returned to the house, they found the slave in good health.",
    11: "And it came about soon afterwards, that He went to a city called Nain. And His disciples were going along with Him, accompanied by a large multitude.",
    12: "Now as He approached the gate of the city, behold, a dead man was being carried out, the only son of his mother. And she was a widow. And a sizable crowd from the city was with her.",
    13: "And when the Lord saw her, He felt compassion for her, and said to her, \"Do not weep.\"",
    14: "And He came up and touched the coffin — and the bearers came to a halt. And He said, \"Young man, I say to you — arise!\"",
    15: "And the dead man sat up, and began to speak. And Jesus gave him back to his mother.",
    16: "And fear gripped them all, and they began glorifying God, saying, \"A great prophet has arisen among us!\" and, \"God has visited His people!\"",
    17: "And this report concerning Him went out all over Judea, and in all the surrounding district.",
    18: "And the disciples of John reported to him about all these things.",
    19: "And summoning two of his disciples, John sent them to the Lord, saying, \"Are You the Expected One, or do we look for someone else?\"",
    20: "And when the men had come to Him, they said, \"John the Baptist has sent us to You, saying, 'Are You the Expected One, or do we look for someone else?'\"",
    21: "At that very time He cured many people of diseases and afflictions and evil spirits. And He granted sight to many who were blind.",
    22: "And He answered and said to them, \"Go and report to John what you have seen and heard: the blind receive sight, the lame walk, the lepers are cleansed, and the deaf hear, the dead are raised up, the poor have the gospel preached to them.",
    23: "And blessed is he who keeps from stumbling over Me.\"",
    24: "And when the messengers of John had left, He began to speak to the multitudes about John, \"What did you go out into the wilderness to look at? A reed shaken by the wind?",
    25: "But what did you go out to see? A man dressed in soft clothing? Behold, those who are splendidly clothed and live in luxury are found in royal palaces.",
    26: "But what did you go out to see? A prophet? Yes, I say to you — and one who is more than a prophet.",
    27: "This is the one about whom it is written, 'Behold, I send My messenger before Your face, who will prepare Your way before You.'",
    28: "I say to you, among those born of women, there is no one greater than John. Yet he who is least in the kingdom of God is greater than he.\"",
    29: "And when all the people and the tax-gatherers heard this, they acknowledged God's justice, having been baptized with the baptism of John.",
    30: "But the Pharisees and the lawyers rejected God's purpose for themselves, not having been baptized by John.",
    31: "\"To what then shall I compare the men of this generation, and what are they like?",
    32: "They are like children who sit in the market place and call to one another, and they say, 'We played the flute for you, and you did not dance — we sang a dirge, and you did not weep.'",
    33: "For John the Baptist has come eating no bread and drinking no wine, and you say, 'He has a demon!'",
    34: "The Son of Man has come eating and drinking, and you say, 'Behold, a gluttonous man, and a drunkard, a friend of tax-gatherers and sinners!'",
    35: "Yet wisdom is vindicated by all her children.\"",
    36: "Now one of the Pharisees was requesting Him to dine with him. And He entered the Pharisee's house, and reclined at the table.",
    37: "And behold, there was a woman in the city who was a sinner. And when she learned that He was reclining at the table in the Pharisee's house, she brought an alabaster vial of perfume.",
    38: "And standing behind Him at His feet, weeping, she began to wet His feet with her tears, and kept wiping them with the hair of her head, and kissing His feet, and anointing them with the perfume.",
    39: "Now when the Pharisee who had invited Him saw this, he said to himself, \"If this man were a prophet, He would know who and what sort of person this woman is who is touching Him — that she is a sinner.\"",
    40: "And Jesus answered and said to him, \"Simon, I have something to say to you.\" And he replied, \"Say it, Teacher.\"",
    41: "\"A certain moneylender had two debtors — one owed five hundred denarii, and the other fifty.",
    42: "When they were unable to repay, he graciously forgave them both. Which of them therefore will love him more?\"",
    43: "Simon answered and said, \"I suppose the one whom he forgave more.\" And He said to him, \"You have judged correctly.\"",
    44: "And turning toward the woman, He said to Simon, \"Do you see this woman? I entered your house, you gave Me no water for My feet — but she has wet My feet with her tears, and wiped them with her hair.",
    45: "You gave Me no kiss — but she, since the time I came in, has not ceased to kiss My feet.",
    46: "You did not anoint My head with oil — but she anointed My feet with perfume.",
    47: "For this reason, I say to you, her sins, which are many, have been forgiven, for she loved much — but he who is forgiven little, loves little.\"",
    48: "And He said to her, \"Your sins have been forgiven.\"",
    49: "And those who were reclining at the table with Him began to say to themselves, \"Who is this man who even forgives sins?\"",
    50: "And He said to the woman, \"Your faith has saved you — go in peace.\"",
}
ch8 = {
    1: "And it came about soon afterwards, that He began going about from one city and village to another, proclaiming and preaching the kingdom of God. And the twelve were with Him,",
    2: "and also some women who had been healed of evil spirits and sicknesses: Mary who was called Magdalene, from whom seven demons had gone out,",
    3: "and Joanna the wife of Chuza, Herod's steward, and Susanna, and many others who were contributing to their support out of their private means.",
    4: "And when a great multitude was coming together, and those from the various cities were journeying to Him, He spoke by way of a parable:",
    5: "\"The sower went out to sow his seed. And as he sowed, some fell beside the road, and it was trampled under foot, and the birds of the air ate it up.",
    6: "And other seed fell on rocky soil. And as soon as it grew up, it withered away, because it had no moisture.",
    7: "And other seed fell among the thorns. And the thorns grew up with it, and choked it out.",
    8: "And other seed fell into the good soil, and grew up, and produced a crop a hundred times as great.\" As He said these things, He would call out, \"He who has ears to hear, let him hear.\"",
    9: "And His disciples began questioning Him as to what this parable might be.",
    10: "And He said, \"To you it has been granted to know the mysteries of the kingdom of God — but to the rest it is in parables, in order that seeing they may not see, and hearing they may not understand.",
    11: "Now the parable is this — the seed is the word of God.",
    12: "And those beside the road are those who have heard. Then the devil comes and takes away the word from their heart, so that they may not believe and be saved.",
    13: "And those on the rocky soil are those who, when they hear, receive the word with joy. And these have no firm root. They believe for a while, and in time of temptation fall away.",
    14: "And the seed which fell among the thorns, these are the ones who have heard. And as they go on their way, they are choked with worries and riches and pleasures of this life, and bring no fruit to maturity.",
    15: "And the seed in the good soil — these are the ones who have heard the word in an honest and good heart, and hold it fast, and bear fruit with perseverance.",
    16: "Now no one after lighting a lamp covers it over with a container, or puts it under a bed — but he puts it on a lampstand, in order that those who come in may see the light.",
    17: "For nothing is hidden that shall not become evident, nor anything secret that shall not be known and come to light.",
    18: "Therefore take care how you listen. For whoever has, to him shall more be given. And whoever does not have, even what he thinks he has shall be taken away from him.\"",
    19: "And His mother and brothers came to Him, and they were unable to get to Him because of the crowd.",
    20: "And it was reported to Him, \"Your mother and Your brothers are standing outside, wishing to see You.\"",
    21: "But He answered and said to them, \"My mother and My brothers are these who hear the word of God and do it.\"",
    22: "Now it came about on one of those days, that He and His disciples got into a boat. And He said to them, \"Let us go over to the other side of the lake.\" And they launched out.",
    23: "But as they were sailing along He fell asleep. And a fierce gale of wind descended upon the lake, and they began to be swamped and to be in danger.",
    24: "And they came to Him and woke Him up, saying, \"Master, Master — we are perishing!\" And being aroused, He rebuked the wind and the surging waves. And they stopped, and it became calm.",
    25: "And He said to them, \"Where is your faith?\" And they were fearful and amazed, saying to one another, \"Who then is this, that He commands even the winds and the water, and they obey Him?\"",
    26: "And they sailed to the country of the Gerasenes, which is opposite Galilee.",
    27: "And when He had come out onto the land, He was met by a certain man from the city who was possessed with demons — and who had not put on any clothing for a long time, and was not living in a house, but in the tombs.",
    28: "And seeing Jesus, he cried out and fell before Him, and said in a loud voice, \"What do I have to do with You, Jesus, Son of the Most High God? I beg You, do not torment me.\"",
    29: "For He had been commanding the unclean spirit to come out of the man. For it had seized him many times — and he was bound with chains and shackles and kept under guard. And yet he would burst his fetters and be driven by the demon into the desert.",
    30: "And Jesus asked him, \"What is your name?\" And he said, \"Legion\" — for many demons had entered him.",
    31: "And they were entreating Him not to command them to depart into the abyss.",
    32: "Now there was a herd of many swine feeding there on the mountain. And the demons entreated Him to permit them to enter the swine. And He gave them permission.",
    33: "And the demons came out from the man, and entered the swine. And the herd rushed down the steep bank into the lake, and were drowned.",
    34: "And when the herdsmen saw what had happened, they ran away, and reported it in the city and out in the country.",
    35: "And the people went out to see what had happened. And they came to Jesus, and found the man from whom the demons had gone out, sitting down at the feet of Jesus — clothed and in his right mind. And they became frightened.",
    36: "And those who had seen it reported to them how the man who was demon-possessed had been made well.",
    37: "And all the people of the country of the Gerasenes and the surrounding district asked Him to leave them, for they were gripped with great fear. And He got into a boat and returned.",
    38: "But the man from whom the demons had gone out was begging Him that he might accompany Him. But He sent him away, saying,",
    39: "\"Return to your house and describe what great things God has done for you.\" And he went away, proclaiming throughout the whole city what great things Jesus had done for him.",
    40: "And as Jesus returned, the multitude welcomed Him, for they had all been waiting for Him.",
    41: "And behold, there came a man named Jairus, and he was an official of the synagogue. And he fell at Jesus' feet, and began to entreat Him to come to his house.",
    42: "For he had an only daughter, about twelve years old, and she was dying. But as He went, the multitudes were pressing against Him.",
    43: "And a woman who had a hemorrhage for twelve years, and could not be healed by anyone,",
    44: "came up behind Him, and touched the fringe of His cloak. And immediately her hemorrhage stopped.",
    45: "And Jesus said, \"Who is the one who touched Me?\" And while they were all denying it, Peter said, \"Master, the multitudes are crowding and pressing upon You.\"",
    46: "But Jesus said, \"Someone did touch Me — for I was aware that power had gone out of Me.\"",
    47: "And when the woman saw that she had not escaped notice, she came trembling and fell down before Him, and declared in the presence of all the people the reason why she had touched Him, and how she had been immediately healed.",
    48: "And He said to her, \"Daughter, your faith has made you well. Go in peace.\"",
    49: "While He was still speaking, someone came from the house of the synagogue official, saying, \"Your daughter has died — do not trouble the Teacher anymore.\"",
    50: "But when Jesus heard this, He answered him, \"Do not be afraid any longer; only believe — and she shall be made well.\"",
    51: "And when He had come to the house, He did not allow anyone to enter with Him, except Peter and John and James, and the girl's father and mother.",
    52: "Now they were all weeping and lamenting for her — but He said, \"Stop weeping. For she has not died, but is asleep.\"",
    53: "And they began laughing at Him, knowing that she had died.",
    54: "He, however, took her by the hand and called, saying, \"Child, arise!\"",
    55: "And her spirit returned, and she rose immediately. And He gave orders for something to be given her to eat.",
    56: "And her parents were amazed. But He instructed them to tell no one what had happened.",
}
ch9 = {
    1: "And He called the twelve together, and gave them power and authority over all the demons, and to heal diseases.",
    2: "And He sent them out to proclaim the kingdom of God, and to perform healing.",
    3: "And He said to them, \"Take nothing for your journey, neither a staff, nor a bag, nor bread, nor money — and do not even have two tunics apiece.",
    4: "And whatever house you enter, stay there, and take your leave from there.",
    5: "And as for those who do not receive you, as you go out from that city, shake off the dust from your feet as a testimony against them.\"",
    6: "And departing, they began going about among the villages, preaching the gospel and healing everywhere.",
    7: "Now Herod the tetrarch heard of all that was happening. And he was greatly perplexed, because it was said by some that John had risen from the dead.",
    8: "And by some that Elijah had appeared, and by others, that one of the prophets of old had risen again.",
    9: "And Herod said, \"I myself had John beheaded. But who is this man about whom I hear such things?\" And he kept trying to see Him.",
    10: "And when the apostles returned, they gave an account to Him of all that they had done. And taking them with Him, He withdrew by Himself to a city called Bethsaida.",
    11: "But the multitudes were aware of this, and followed Him. And welcoming them, He began speaking to them about the kingdom of God, and curing those who had need of healing.",
    12: "And the day began to decline. And the twelve came and said to Him, \"Send the multitude away, that they may go into the surrounding villages and countryside, and find lodging and get something to eat. For here we are in a desolate place.\"",
    13: "But He said to them, \"You give them something to eat!\" And they said, \"We have no more than five loaves and two fish — unless perhaps we go and buy food for all these people.\"",
    14: "For there were about five thousand men. And He said to His disciples, \"Have them recline to eat in groups of about fifty each.\"",
    15: "And they did so, and had them all recline.",
    16: "And He took the five loaves and the two fish, and looking up to heaven, He blessed them, and broke them, and kept giving them to the disciples to set before the multitude.",
    17: "And they all ate and were satisfied. And the broken pieces which they had left over were picked up — twelve baskets full.",
    18: "And it came about that while He was praying alone, the disciples were with Him. And He questioned them, saying, \"Who do the multitudes say that I am?\"",
    19: "And they answered and said, \"John the Baptist, and others say Elijah — but others, that one of the prophets of old has risen again.\"",
    20: "And He said to them, \"But who do you say that I am?\" And Peter answered and said, \"The Christ of God.\"",
    21: "But He warned them, and instructed them not to tell this to anyone,",
    22: "saying, \"The Son of Man must suffer many things and be rejected by the elders and chief priests and scribes, and be killed, and be raised up on the third day.\"",
    23: "And He was saying to them all, \"If anyone wishes to come after Me, let him deny himself, and take up his cross daily, and follow Me.",
    24: "For whoever wishes to save his life shall lose it — but whoever loses his life for My sake, he is the one who will save it.",
    25: "For what is a man profited if he gains the whole world, and loses or forfeits himself?",
    26: "For whoever is ashamed of Me and My words, the Son of Man will be ashamed of him when He comes in His glory, and the glory of the Father and of the holy angels.",
    27: "But I say to you truthfully, there are some of those standing here who shall not taste of death until they see the kingdom of God.\"",
    28: "And it came about some eight days after these sayings, that He took along Peter and John and James, and went up to the mountain to pray.",
    29: "And while He was praying, the appearance of His face became different, and His clothing became white and gleaming.",
    30: "And behold, two men were talking with Him — and they were Moses and Elijah,",
    31: "who, appearing in glory, were speaking of His departure which He was about to accomplish at Jerusalem.",
    32: "Now Peter and his companions had been overcome with sleep. But when they were fully awake, they saw His glory, and the two men standing with Him.",
    33: "And it came about, as these were parting from Him, Peter said to Jesus, \"Master, it is good for us to be here. Let us make three tabernacles — one for You, and one for Moses, and one for Elijah\" — not realizing what he was saying.",
    34: "And while he was saying this, a cloud formed and began to overshadow them — and they were afraid as they entered the cloud.",
    35: "And a voice came out of the cloud, saying, \"This is My Son, My Chosen One — listen to Him!\"",
    36: "And when the voice had spoken, Jesus was found alone. And they kept silent, and reported to no one in those days any of the things which they had seen.",
    37: "And it came about on the next day, that when they had come down from the mountain, a great multitude met Him.",
    38: "And behold, a man from the multitude shouted out, saying, \"Teacher, I beg You to look at my son — for he is my only boy.",
    39: "And behold, a spirit seizes him, and he suddenly screams. And it throws him into a convulsion with foaming. And only with difficulty does it leave him, mauling him as it leaves.",
    40: "And I begged Your disciples to cast it out — and they could not.\"",
    41: "And Jesus answered and said, \"O unbelieving and perverted generation, how long shall I be with you and put up with you? Bring your son here.\"",
    42: "And while he was still approaching, the demon dashed him to the ground and threw him into a convulsion. But Jesus rebuked the unclean spirit, and healed the boy, and gave him back to his father.",
    43: "And they were all amazed at the greatness of God. But while everyone was marveling at all that He was doing, He said to His disciples,",
    44: "\"Let these words sink into your ears — for the Son of Man is going to be delivered into the hands of men.\"",
    45: "But they did not understand this statement, and it was concealed from them, so that they might not perceive it. And they were afraid to ask Him about this statement.",
    46: "And an argument arose among them as to which of them might be the greatest.",
    47: "But Jesus, knowing what they were thinking in their heart, took a child and stood him by His side,",
    48: "and said to them, \"Whoever receives this child in My name receives Me — and whoever receives Me receives Him who sent Me. For he who is least among all of you, this is the one who is great.\"",
    49: "And John answered and said, \"Master, we saw someone casting out demons in Your name — and we tried to prevent him because he does not follow along with us.\"",
    50: "But Jesus said to him, \"Do not hinder him — for he who is not against you is for you.\"",
    51: "And it came about, when the days were approaching for His ascension, that He resolutely set His face to go to Jerusalem.",
    52: "And He sent messengers on ahead of Him. And they went, and entered a village of the Samaritans, to make arrangements for Him.",
    53: "And they did not receive Him, because He was journeying with His face toward Jerusalem.",
    54: "And when His disciples James and John saw this, they said, \"Lord, do You want us to command fire to come down from heaven and consume them?\"",
    55: "But He turned and rebuked them.",
    56: "And they went on to another village.",
    57: "And as they were going along the road, someone said to Him, \"I will follow You wherever You go.\"",
    58: "And Jesus said to him, \"The foxes have holes, and the birds of the air have nests — but the Son of Man has nowhere to lay His head.\"",
    59: "And He said to another, \"Follow Me.\" But he said, \"Permit me first to go and bury my father.\"",
    60: "But He said to him, \"Allow the dead to bury their own dead — but as for you, go and proclaim everywhere the kingdom of God.\"",
    61: "And another also said, \"I will follow You, Lord. But first permit me to say good-bye to those at home.\"",
    62: "But Jesus said to him, \"No one, after putting his hand to the plow and looking back, is fit for the kingdom of God.\"",
}
ch10 = {
    1: "Now after this the Lord appointed seventy others, and sent them two by two ahead of Him to every city and place where He Himself was going to come.",
    2: "And He was saying to them, \"The harvest is plentiful — but the laborers are few. Therefore beseech the Lord of the harvest to send out laborers into His harvest.",
    3: "Go your ways — behold, I send you out as lambs in the midst of wolves.",
    4: "Carry no purse, no bag, no shoes. And greet no one on the way.",
    5: "And whatever house you enter, first say, 'Peace be to this house.'",
    6: "And if a man of peace is there, your peace will rest upon him. But if not, it will return to you.",
    7: "And stay in that house, eating and drinking what they give you. For the laborer is worthy of his wages. Do not keep moving from house to house.",
    8: "And whatever city you enter, and they receive you, eat what is set before you.",
    9: "And heal those in it who are sick, and say to them, 'The kingdom of God has come near to you.'",
    10: "But whatever city you enter and they do not receive you, go out into its streets and say,",
    11: "'Even the dust of your city which clings to our feet we wipe off in protest against you. Yet be sure of this, that the kingdom of God has come near.'",
    12: "I say to you, it will be more tolerable in that day for Sodom than for that city.",
    13: "Woe to you, Chorazin! Woe to you, Bethsaida! For if the miracles had been performed in Tyre and Sidon which occurred in you, they would have repented long ago, sitting in sackcloth and ashes.",
    14: "But it will be more tolerable for Tyre and Sidon in the judgment, than for you.",
    15: "And you, Capernaum, will not be exalted to heaven, will you? You will be brought down to Hades!",
    16: "The one who listens to you listens to Me — and the one who rejects you rejects Me. And he who rejects Me rejects the One who sent Me.\"",
    17: "And the seventy returned with joy, saying, \"Lord, even the demons are subject to us in Your name.\"",
    18: "And He said to them, \"I was watching Satan fall from heaven like lightning.",
    19: "Behold, I have given you authority to tread upon serpents and scorpions, and over all the power of the enemy — and nothing shall injure you.",
    20: "Nevertheless do not rejoice in this, that the spirits are subject to you — but rejoice that your names are recorded in heaven.\"",
    21: "At that very time He rejoiced greatly in the Holy Spirit, and said, \"I praise You, O Father, Lord of heaven and earth, that You have hidden these things from the wise and intelligent, and have revealed them to babes. Yes, Father, for thus it was well-pleasing in Your sight.",
    22: "All things have been handed over to Me by My Father. And no one knows who the Son is except the Father — and who the Father is except the Son, and anyone to whom the Son wills to reveal Him.\"",
    23: "And turning to the disciples, He said privately, \"Blessed are the eyes which see the things you see.",
    24: "For I say to you, that many prophets and kings wished to see the things which you see, and did not see them. And to hear the things which you hear, and did not hear them.\"",
    25: "And behold, a certain lawyer stood up and put Him to the test, saying, \"Teacher, what shall I do to inherit eternal life?\"",
    26: "And He said to him, \"What is written in the Law? How does it read to you?\"",
    27: "And he answered and said, \"You shall love the Lord your God with all your heart, and with all your soul, and with all your strength, and with all your mind — and your neighbor as yourself.\"",
    28: "And He said to him, \"You have answered correctly. Do this, and you will live.\"",
    29: "But wishing to justify himself, he said to Jesus, \"And who is my neighbor?\"",
    30: "Jesus replied and said, \"A certain man was going down from Jerusalem to Jericho, and he fell among robbers. And they stripped him and beat him, and went off leaving him half dead.",
    31: "And by chance a certain priest was going down on that road. And when he saw him, he passed by on the other side.",
    32: "And likewise a Levite also, when he came to the place and saw him, passed by on the other side.",
    33: "But a certain Samaritan, who was on a journey, came upon him. And when he saw him, he felt compassion,",
    34: "and came to him, and bandaged up his wounds, pouring oil and wine on them. And he put him on his own beast, and brought him to an inn, and took care of him.",
    35: "And on the next day he took out two denarii and gave them to the innkeeper, and said, 'Take care of him. And whatever more you spend, when I return, I will repay you.'",
    36: "Which of these three do you think proved to be a neighbor to the man who fell into the robbers' hands?\"",
    37: "And he said, \"The one who showed mercy toward him.\" Then Jesus said to him, \"Go and do the same.\"",
    38: "Now as they were traveling along, He entered a certain village. And a woman named Martha welcomed Him into her home.",
    39: "And she had a sister called Mary, who moreover was listening to the Lord's word, seated at His feet.",
    40: "But Martha was distracted with all her preparations — and she came up to Him, and said, \"Lord, do You not care that my sister has left me to do all the serving alone? Then tell her to help me.\"",
    41: "But the Lord answered and said to her, \"Martha, Martha, you are worried and bothered about so many things —",
    42: "but only a few things are necessary, really only one. For Mary has chosen the good part, which shall not be taken away from her.\"",
}
ch11 = {
    1: "And it came about that while He was praying in a certain place, after He had finished, one of His disciples said to Him, \"Lord, teach us to pray just as John also taught his disciples.\"",
    2: "And He said to them, \"When you pray, say: 'Father, hallowed be Your name. Your kingdom come.",
    3: "Give us each day our daily bread.",
    4: "And forgive us our sins, for we ourselves also forgive everyone who is indebted to us. And lead us not into temptation.'\"",
    5: "And He said to them, \"Suppose one of you shall have a friend, and shall go to him at midnight, and say to him, 'Friend, lend me three loaves —",
    6: "for a friend of mine has come to me from a journey, and I have nothing to set before him.'",
    7: "And from inside he shall answer and say, 'Do not bother me. The door has already been shut, and my children and I are in bed. I cannot get up and give you anything.'",
    8: "I tell you, even though he will not get up and give him anything because he is his friend, yet because of his persistence he will get up and give him as much as he needs.",
    9: "And I say to you, ask, and it shall be given to you. Seek, and you shall find. Knock, and it shall be opened to you.",
    10: "For everyone who asks, receives. And he who seeks, finds. And to him who knocks, it shall be opened.",
    11: "Now suppose one of you fathers is asked by his son for a fish — he will not give him a snake instead of a fish, will he?",
    12: "Or if he is asked for an egg, he will not give him a scorpion, will he?",
    13: "If you then, being evil, know how to give good gifts to your children, how much more shall your heavenly Father give the Holy Spirit to those who ask Him?\"",
    14: "And He was casting out a demon, and it was dumb. And it came about that when the demon had gone out, the dumb man spoke — and the multitudes marveled.",
    15: "But some of them said, \"He casts out demons by Beelzebul, the ruler of the demons.\"",
    16: "And others, to test Him, were demanding of Him a sign from heaven.",
    17: "But He knew their thoughts, and said to them, \"Any kingdom divided against itself is laid waste — and a house divided against itself falls.",
    18: "And if Satan also is divided against himself, how shall his kingdom stand? For you say that I cast out demons by Beelzebul.",
    19: "And if I by Beelzebul cast out demons, by whom do your sons cast them out? Consequently they shall be your judges.",
    20: "But if I cast out demons by the finger of God, then the kingdom of God has come upon you.",
    21: "When a strong man, fully armed, guards his own homestead, his possessions are undisturbed.",
    22: "But when someone stronger than he attacks him and overpowers him, he takes away from him all his armor on which he had relied, and distributes his plunder.",
    23: "He who is not with Me is against Me. And he who does not gather with Me, scatters.",
    24: "When the unclean spirit goes out of a man, it passes through waterless places seeking rest. And not finding any, it says, 'I will return to my house from which I came.'",
    25: "And when it comes, it finds it swept and put in order.",
    26: "Then it goes and takes along seven other spirits more evil than itself, and they go in and live there. And the last state of that man becomes worse than the first.\"",
    27: "And it came about while He said these things, one of the women in the crowd raised her voice, and said to Him, \"Blessed is the womb that bore You, and the breasts at which You nursed.\"",
    28: "But He said, \"On the contrary, blessed are those who hear the word of God, and observe it.\"",
    29: "And as the crowds were increasing, He began to say, \"This generation is a wicked generation. It seeks for a sign — and yet no sign shall be given to it but the sign of Jonah.",
    30: "For just as Jonah became a sign to the Ninevites, so shall the Son of Man be to this generation.",
    31: "The Queen of the South shall rise up with the men of this generation at the judgment, and condemn them — because she came from the ends of the earth to hear the wisdom of Solomon, and behold, something greater than Solomon is here.",
    32: "The men of Nineveh shall stand up with this generation at the judgment, and shall condemn it — because they repented at the preaching of Jonah, and behold, something greater than Jonah is here.",
    33: "No one, after lighting a lamp, puts it away in a cellar, nor under a peck-measure — but on the lampstand, in order that those who enter may see the light.",
    34: "The lamp of your body is your eye. When your eye is clear, your whole body also is full of light. But when it is bad, your body also is full of darkness.",
    35: "Then watch out that the light in you may not be darkness.",
    36: "If therefore your whole body is full of light, with no dark part in it, it shall be wholly illumined, as when the lamp illumines you with its rays.\"",
    37: "Now when He had spoken, a Pharisee asked Him to have lunch with him. And He went in, and reclined at the table.",
    38: "And when the Pharisee saw it, he was surprised that He had not first ceremonially washed before the meal.",
    39: "But the Lord said to him, \"Now you Pharisees clean the outside of the cup and of the platter — but inside of you, you are full of robbery and wickedness.",
    40: "You foolish ones, did not He who made the outside make the inside also?",
    41: "But give that which is within as charity, and then all things are clean for you.",
    42: "But woe to you Pharisees! For you pay tithe of mint and rue and every kind of garden herb, and yet disregard justice and the love of God. But these are the things you should have done without neglecting the others.",
    43: "Woe to you Pharisees! For you love the chief seats in the synagogues, and the respectful greetings in the market places.",
    44: "Woe to you! For you are like concealed tombs, and the people who walk over them are unaware of it.\"",
    45: "And one of the lawyers said to Him in reply, \"Teacher, when You say this, You insult us too.\"",
    46: "But He said, \"Woe to you lawyers as well! For you weigh men down with burdens hard to bear, while you yourselves will not even touch the burdens with one of your fingers.",
    47: "Woe to you! For you build the tombs of the prophets — and it was your fathers who killed them.",
    48: "Consequently, you are witnesses, and approve the deeds of your fathers. Because it was they who killed them — and you build their tombs.",
    49: "For this reason also the wisdom of God said, 'I will send to them prophets and apostles — and some of them they will kill and some they will persecute.'",
    50: "In order that the blood of all the prophets, shed since the foundation of the world, may be charged against this generation,",
    51: "from the blood of Abel to the blood of Zechariah, who perished between the altar and the house of God. Yes, I tell you, it shall be charged against this generation.",
    52: "Woe to you lawyers! For you have taken away the key of knowledge — you yourselves did not enter, and you hindered those who were entering.\"",
    53: "And when He left there, the scribes and the Pharisees began to be very hostile, and to question Him closely on many subjects.",
    54: "Plotting against Him, to catch Him in something He might say.",
}
ch12 = {
    1: "Under these circumstances, after so many thousands of the multitude had gathered together that they were stepping on one another, He began saying to His disciples first of all, \"Beware of the leaven of the Pharisees, which is hypocrisy.",
    2: "But there is nothing covered up that will not be revealed, and hidden that will not be known.",
    3: "Accordingly, whatever you have said in the dark shall be heard in the light, and what you have whispered in the inner rooms shall be proclaimed upon the housetops.",
    4: "And I say to you, My friends, do not be afraid of those who kill the body, and after that have no more that they can do.",
    5: "But I will warn you whom to fear — fear the One who, after He has killed, has authority to cast into hell. Yes, I tell you, fear Him!",
    6: "Are not five sparrows sold for two cents? And yet not one of them is forgotten before God.",
    7: "Indeed, the very hairs of your head are all numbered. Do not fear — you are of more value than many sparrows.",
    8: "And I say to you, everyone who confesses Me before men, the Son of Man shall confess him also before the angels of God.",
    9: "But he who denies Me before men shall be denied before the angels of God.",
    10: "And everyone who will speak a word against the Son of Man, it shall be forgiven him — but he who blasphemes against the Holy Spirit, it shall not be forgiven him.",
    11: "And when they bring you before the synagogues and the rulers and the authorities, do not become anxious about how or what you should speak in your defense, or what you should say.",
    12: "For the Holy Spirit will teach you in that very hour what you ought to say.\"",
    13: "And someone in the crowd said to Him, \"Teacher, tell my brother to divide the family inheritance with me.\"",
    14: "But He said to him, \"Man, who appointed Me a judge or arbiter over you?\"",
    15: "And He said to them, \"Beware, and be on your guard against every form of greed — for not even when one has an abundance does his life consist of his possessions.\"",
    16: "And He told them a parable, saying, \"The land of a certain rich man was very productive.",
    17: "And he began reasoning to himself, saying, 'What shall I do, since I have no place to store my crops?'",
    18: "And he said, 'This is what I will do — I will tear down my barns and build larger ones, and there I will store all my grain and my goods.",
    19: "And I will say to my soul, \"Soul, you have many goods laid up for many years to come. Take your ease, eat, drink, be merry.\"'",
    20: "But God said to him, 'You fool! This very night your soul is required of you. And now who will own what you have prepared?'",
    21: "So is the man who lays up treasure for himself, and is not rich toward God.\"",
    22: "And He said to His disciples, \"For this reason I say to you, do not be anxious for your life, as to what you shall eat — nor for your body, as to what you shall put on.",
    23: "For life is more than food, and the body than clothing.",
    24: "Consider the ravens, that they neither sow nor reap, and they have no storeroom nor barn. And yet God feeds them. How much more valuable you are than the birds!",
    25: "And which of you by being anxious can add a single cubit to his life's span?",
    26: "If then you cannot do even a very little thing, why are you anxious about other matters?",
    27: "Consider the lilies, how they grow — they neither toil nor spin. But I tell you, not even Solomon in all his glory clothed himself like one of these.",
    28: "But if God so arrays the grass in the field, which is alive today and tomorrow is thrown into the furnace, how much more will He clothe you, O men of little faith!",
    29: "And do not seek what you shall eat, and what you shall drink, and do not keep worrying.",
    30: "For all these things the nations of the world eagerly seek. But your Father knows that you need these things.",
    31: "But seek for His kingdom, and these things shall be added to you.",
    32: "Do not be afraid, little flock — for your Father has gladly chosen to give you the kingdom.",
    33: "Sell your possessions and give to charity. Make yourselves purses which do not wear out — an unfailing treasure in heaven, where no thief comes near, nor moth destroys.",
    34: "For where your treasure is, there will your heart be also.",
    35: "Be dressed in readiness, and keep your lamps lit.",
    36: "And be like men who are waiting for their master when he returns from the wedding feast — so that they may immediately open the door to him when he comes and knocks.",
    37: "Blessed are those slaves whom the master shall find on the alert when he comes. Truly I say to you, that he will gird himself to serve, and have them recline at the table, and will come up and wait on them.",
    38: "Whether he comes in the second watch, or even in the third, and finds them so, blessed are those slaves.",
    39: "And be sure of this, that if the head of the house had known at what hour the thief was coming, he would not have allowed his house to be broken into.",
    40: "You too, be ready — for the Son of Man is coming at an hour that you do not expect.\"",
    41: "And Peter said, \"Lord, are You addressing this parable to us, or to everyone else as well?\"",
    42: "And the Lord said, \"Who then is the faithful and sensible steward, whom his master will put in charge of his servants, to give them their rations at the proper time?",
    43: "Blessed is that slave whom his master finds so doing when he comes.",
    44: "Truly I say to you, that he will put him in charge of all his possessions.",
    45: "But if that slave says in his heart, 'My master will be a long time in coming,' and begins to beat the slaves, both men and women, and to eat and drink and get drunk —",
    46: "the master of that slave will come on a day when he does not expect him, and at an hour he does not know — and will cut him in pieces, and assign him a place with the unbelievers.",
    47: "And that slave who knew his master's will and did not get ready or act in accord with his will, shall receive many lashes.",
    48: "But the one who did not know it, and committed deeds worthy of a flogging, will receive but few. And from everyone who has been given much, much shall be required. And to whom they entrusted much, of him they will ask all the more.",
    49: "I have come to cast fire upon the earth — and how I wish it were already kindled!",
    50: "But I have a baptism to undergo — and how distressed I am until it is accomplished!",
    51: "Do you suppose that I came to grant peace on earth? I tell you, no, but rather division.",
    52: "For from now on five members in one household will be divided — three against two, and two against three.",
    53: "They will be divided, father against son, and son against father — mother against daughter, and daughter against mother — mother-in-law against daughter-in-law, and daughter-in-law against mother-in-law.\"",
    54: "And He was also saying to the multitudes, \"When you see a cloud rising in the west, immediately you say, 'A shower is coming,' and so it turns out.",
    55: "And when you see a south wind blowing, you say, 'It will be a hot day,' and it turns out that way.",
    56: "You hypocrites! You know how to analyze the appearance of the earth and the sky — but why do you not analyze this present time?",
    57: "And why do you not even on your own initiative judge what is right?",
    58: "For while you are going with your opponent to appear before the magistrate, on the way make an effort to settle with him — lest he drag you before the judge, and the judge turn you over to the constable, and the constable throw you into prison.",
    59: "I say to you, you shall not get out of there until you have paid the very last cent.\"",
}

CHAPTERS = {7:ch7,8:ch8,9:ch9,10:ch10,11:ch11,12:ch12}

def main():
    new_entries = {f"42_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Luke 7-12 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Luke 7-12 verses")

if __name__ == "__main__":
    main()
