"""MBT Acts 10-19 — Cornelius, Jerusalem Council, Paul's first two
missionary journeys, riot in Ephesus. 367 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch10 = {
    1: "Now there was a man at Caesarea named Cornelius — a centurion of what was called the Italian cohort.",
    2: "A devout man, who feared God with all his household — and he gave many alms to the Jewish people, and prayed to God continually.",
    3: "About the ninth hour of the day, he clearly saw in a vision an angel of God who had just come in to him — and who said to him, \"Cornelius.\"",
    4: "And fixing his gaze on him and being terrified, he said, \"What is it, Lord?\" And he said to him, \"Your prayers and alms have ascended as a memorial before God.",
    5: "Now dispatch some men to Joppa, and send for a man named Simon — who is also called Peter.",
    6: "He is staying with a tanner named Simon, whose house is by the sea.\"",
    7: "When the angel who was speaking to him had left, he summoned two of his servants and a devout soldier of those who were his personal attendants.",
    8: "And after he had explained everything to them, he sent them to Joppa.",
    9: "On the next day, as they were on their way and approaching the city, Peter went up on the housetop about the sixth hour to pray.",
    10: "And he became hungry and was desiring to eat — but while they were making preparations, he fell into a trance.",
    11: "And he saw the sky opened up, and an object like a great sheet coming down — lowered by four corners to the ground.",
    12: "And there were in it all kinds of four-footed animals and crawling creatures of the earth, and birds of the air.",
    13: "And a voice came to him: \"Get up, Peter, kill and eat!\"",
    14: "But Peter said, \"By no means, Lord — for I have never eaten anything unholy and unclean.\"",
    15: "And again a voice came to him a second time: \"What God has cleansed, no longer consider unholy.\"",
    16: "And this happened three times — and immediately the object was taken up into the sky.",
    17: "Now while Peter was greatly perplexed in mind as to what the vision which he had seen might be — behold, the men who had been sent by Cornelius, having asked directions for Simon's house, appeared at the gate.",
    18: "And calling out, they were asking whether Simon, who was also called Peter, was staying there.",
    19: "While Peter was reflecting on the vision, the Spirit said to him, \"Behold, three men are looking for you.",
    20: "But get up, go downstairs and accompany them without misgivings — for I have sent them Myself.\"",
    21: "And Peter went down to the men and said, \"Behold, I am the one you are looking for. What is the reason for which you have come?\"",
    22: "And they said, \"Cornelius, a centurion, a righteous and God-fearing man well spoken of by the entire nation of the Jews — was divinely directed by a holy angel to send for you to come to his house, and to hear a message from you.\"",
    23: "So he invited them in and gave them lodging. And on the next day he got up and went away with them — and some of the brothers from Joppa accompanied him.",
    24: "And on the following day he entered Caesarea. Now Cornelius was waiting for them — and had called together his relatives and close friends.",
    25: "When Peter entered, Cornelius met him, and fell at his feet and worshiped him.",
    26: "But Peter raised him up, saying, \"Stand up — I too am just a man.\"",
    27: "As he talked with him, he entered and found many people assembled.",
    28: "And he said to them, \"You yourselves know how unlawful it is for a man who is a Jew to associate with a foreigner or to visit him. And yet God has shown me that I should not call any man unholy or unclean.",
    29: "That is why I came without even raising any objection when I was sent for. So I ask for what reason you have sent for me.\"",
    30: "And Cornelius said, \"Four days ago to this hour, I was praying in my house during the ninth hour. And behold, a man stood before me in shining garments,",
    31: "and he said, 'Cornelius, your prayer has been heard, and your alms have been remembered before God.",
    32: "Therefore send to Joppa and invite Simon, who is also called Peter, to come to you. He is staying at the house of Simon the tanner, by the sea.'",
    33: "So I sent for you immediately, and you have been kind enough to come. Now then, we are all here present before God to hear all that you have been commanded by the Lord.\"",
    34: "And opening his mouth, Peter said: \"I most certainly understand now that God is not one to show partiality.",
    35: "But in every nation the man who fears Him and does what is right is welcome to Him.",
    36: "The word which He sent to the sons of Israel — preaching peace through Jesus Christ (He is Lord of all) —",
    37: "you yourselves know — what took place throughout all Judea, starting from Galilee, after the baptism which John proclaimed.",
    38: "You know of Jesus of Nazareth — how God anointed Him with the Holy Spirit and with power, and how He went about doing good and healing all who were oppressed by the devil — for God was with Him.",
    39: "We are witnesses of all the things He did, both in the land of the Jews and in Jerusalem. They also put Him to death by hanging Him on a cross.",
    40: "But God raised Him up on the third day, and granted that He become visible —",
    41: "not to all the people, but to witnesses who were chosen beforehand by God — that is, to us, who ate and drank with Him after He arose from the dead.",
    42: "And He ordered us to preach to the people, and solemnly to testify, that this is the One who has been appointed by God as Judge of the living and the dead.",
    43: "Of Him all the prophets bear witness — that through His name everyone who believes in Him receives forgiveness of sins.\"",
    44: "While Peter was still speaking these words, the Holy Spirit fell upon all those who were listening to the message.",
    45: "And all the circumcised believers who had come with Peter were amazed — because the gift of the Holy Spirit had been poured out on the Gentiles also.",
    46: "For they were hearing them speaking with tongues and exalting God. Then Peter answered:",
    47: "\"Surely no one can refuse the water for these to be baptized — who have received the Holy Spirit just as we did, can he?\"",
    48: "And he ordered them to be baptized in the name of Jesus Christ. Then they asked him to stay on for a few days.",
}
ch11 = {
    1: "Now the apostles and the brothers who were throughout Judea heard that the Gentiles also had received the word of God.",
    2: "And when Peter came up to Jerusalem, those who were circumcised took issue with him,",
    3: "saying, \"You went to uncircumcised men and ate with them.\"",
    4: "But Peter began speaking and proceeded to explain to them in orderly sequence, saying:",
    5: "\"I was in the city of Joppa praying — and in a trance I saw a vision: an object coming down like a great sheet lowered by four corners from the sky, and it came right down to me.",
    6: "When I had fixed my gaze on it and was observing it, I saw the four-footed animals of the earth, and the wild beasts, and the crawling creatures, and the birds of the air.",
    7: "I also heard a voice saying to me, 'Get up, Peter — kill and eat.'",
    8: "But I said, 'By no means, Lord — for nothing unholy or unclean has ever entered my mouth.'",
    9: "But a voice from heaven answered a second time: 'What God has cleansed, no longer consider unholy.'",
    10: "And this happened three times — and everything was drawn back up into the sky.",
    11: "And behold, at that moment three men appeared before the house in which we were staying — having been sent to me from Caesarea.",
    12: "And the Spirit told me to go with them without misgivings. These six brothers also went with me, and we entered the man's house.",
    13: "And he reported to us how he had seen the angel standing in his house, and saying: 'Send to Joppa, and have Simon — who is also called Peter — brought here.",
    14: "And he will speak words to you by which you will be saved — you and all your household.'",
    15: "And as I began to speak, the Holy Spirit fell upon them — just as He did upon us at the beginning.",
    16: "And I remembered the word of the Lord — how He used to say, 'John baptized with water, but you will be baptized with the Holy Spirit.'",
    17: "Therefore if God gave to them the same gift as He gave to us also, after believing in the Lord Jesus Christ — who was I that I could stand in God's way?\"",
    18: "When they heard this, they quieted down and glorified God, saying, \"Well then, God has granted to the Gentiles also the repentance that leads to life.\"",
    19: "So then, those who were scattered because of the persecution that occurred in connection with Stephen, made their way to Phoenicia, and Cyprus, and Antioch — speaking the word to no one except to Jews alone.",
    20: "But there were some of them, men of Cyprus and Cyrene, who came to Antioch and began speaking to the Greeks also, preaching the Lord Jesus.",
    21: "And the hand of the Lord was with them — and a large number who believed turned to the Lord.",
    22: "The news about them reached the ears of the church at Jerusalem — and they sent Barnabas off to Antioch.",
    23: "Then when he had come and witnessed the grace of God, he rejoiced — and began to encourage them all with resolute heart to remain true to the Lord.",
    24: "For he was a good man, and full of the Holy Spirit and of faith. And considerable numbers were brought to the Lord.",
    25: "And he left for Tarsus to look for Saul.",
    26: "And when he had found him, he brought him to Antioch. And for an entire year they met with the church, and taught considerable numbers. And the disciples were first called Christians in Antioch.",
    27: "Now at this time some prophets came down from Jerusalem to Antioch.",
    28: "One of them named Agabus stood up and began to indicate by the Spirit that there would certainly be a great famine all over the world — which took place in the reign of Claudius.",
    29: "And in the proportion that any of the disciples had means, each of them determined to send a contribution for the relief of the brothers living in Judea.",
    30: "And this they did, sending it in charge of Barnabas and Saul to the elders.",
}
ch12 = {
    1: "Now about that time Herod the king laid hands on some who belonged to the church, in order to mistreat them.",
    2: "And he had James, the brother of John, put to death with a sword.",
    3: "When he saw that it pleased the Jews, he proceeded to arrest Peter also. (Now it was during the days of Unleavened Bread.)",
    4: "And when he had seized him, he put him in prison — delivering him to four squads of soldiers to guard him — intending after the Passover to bring him out before the people.",
    5: "So Peter was kept in the prison — but prayer for him was being made fervently by the church to God.",
    6: "On the very night when Herod was about to bring him forward, Peter was sleeping between two soldiers — bound with two chains. And guards in front of the door were watching over the prison.",
    7: "And behold, an angel of the Lord suddenly appeared, and a light shone in the cell. And he struck Peter's side and woke him up, saying, \"Get up quickly!\" And his chains fell off his hands.",
    8: "And the angel said to him, \"Gird yourself and put on your sandals.\" And he did so. And he said to him, \"Wrap your cloak around you and follow me.\"",
    9: "And he went out and continued to follow — and he did not know that what was being done by the angel was real, but thought he was seeing a vision.",
    10: "When they had passed the first and second guard, they came to the iron gate that leads into the city — which opened for them by itself. And they went out and went along one street — and immediately the angel departed from him.",
    11: "And when Peter came to himself, he said, \"Now I know for sure that the Lord has sent forth His angel, and rescued me from the hand of Herod — and from all that the Jewish people were expecting.\"",
    12: "And when he realized this, he went to the house of Mary, the mother of John who was also called Mark — where many were gathered together and were praying.",
    13: "And when he knocked at the door of the gate, a servant-girl named Rhoda came to answer.",
    14: "And when she recognized Peter's voice, because of her joy she did not open the gate — but ran in and announced that Peter was standing in front of the gate.",
    15: "And they said to her, \"You are out of your mind!\" But she kept insisting that it was so. And they kept saying, \"It is his angel.\"",
    16: "But Peter continued knocking. And when they had opened the door, they saw him and were amazed.",
    17: "But motioning to them with his hand to be silent, he described to them how the Lord had led him out of the prison. And he said, \"Report these things to James and the brothers.\" And he departed and went to another place.",
    18: "Now when day came, there was no small disturbance among the soldiers — as to what could have become of Peter.",
    19: "And when Herod had searched for him and had not found him, he examined the guards and ordered that they be led away to execution. Then he went down from Judea to Caesarea — and was spending time there.",
    20: "Now he was very angry with the people of Tyre and Sidon — and with one accord they came to him, and having won over Blastus the king's chamberlain, they were asking for peace, because their country was fed by the king's country.",
    21: "And on an appointed day, Herod, having put on his royal apparel, took his seat on the rostrum and began delivering an address to them.",
    22: "And the people kept crying out, \"The voice of a god, and not of a man!\"",
    23: "And immediately an angel of the Lord struck him — because he did not give God the glory. And he was eaten by worms, and died.",
    24: "But the word of the Lord continued to grow and to be multiplied.",
    25: "And Barnabas and Saul returned from Jerusalem when they had fulfilled their mission — taking along with them John, who was also called Mark.",
}
ch13 = {
    1: "Now there were at Antioch, in the church that was there, prophets and teachers — Barnabas, and Simeon who was called Niger, and Lucius of Cyrene, and Manaen, who had been brought up with Herod the tetrarch, and Saul.",
    2: "While they were ministering to the Lord and fasting, the Holy Spirit said, \"Set apart for Me Barnabas and Saul for the work to which I have called them.\"",
    3: "Then, when they had fasted and prayed and laid their hands on them, they sent them away.",
    4: "So, being sent out by the Holy Spirit, they went down to Seleucia — and from there they sailed to Cyprus.",
    5: "And when they reached Salamis, they began to proclaim the word of God in the synagogues of the Jews. And they also had John as their helper.",
    6: "And when they had gone through the whole island as far as Paphos, they found a magician, a Jewish false prophet whose name was Bar-Jesus.",
    7: "He was with the proconsul, Sergius Paulus — a man of intelligence. This man summoned Barnabas and Saul, and sought to hear the word of God.",
    8: "But Elymas the magician (for so his name is translated) was opposing them — seeking to turn the proconsul away from the faith.",
    9: "But Saul, who was also known as Paul, filled with the Holy Spirit, fixed his gaze on him,",
    10: "and said, \"You who are full of all deceit and fraud — you son of the devil, you enemy of all righteousness — will you not cease making crooked the straight ways of the Lord?",
    11: "Now behold — the hand of the Lord is upon you. And you will be blind, and not see the sun for a time.\" And immediately a mist and a darkness fell upon him, and he went about seeking those who would lead him by the hand.",
    12: "Then the proconsul believed when he saw what had happened — being amazed at the teaching of the Lord.",
    13: "Now Paul and his companions put out to sea from Paphos and came to Perga in Pamphylia. And John left them and returned to Jerusalem.",
    14: "But going on from Perga, they arrived at Pisidian Antioch. And on the Sabbath day they went into the synagogue and sat down.",
    15: "And after the reading of the Law and the Prophets, the synagogue officials sent to them, saying, \"Brothers, if you have any word of exhortation for the people, say it.\"",
    16: "And Paul stood up, and motioning with his hand, said: \"Men of Israel, and you who fear God — listen.",
    17: "The God of this people Israel chose our fathers, and made the people great during their stay in the land of Egypt — and with an uplifted arm He led them out from it.",
    18: "For a period of about forty years He put up with them in the wilderness.",
    19: "And when He had destroyed seven nations in the land of Canaan, He distributed their land as an inheritance — all of which took about four hundred and fifty years.",
    20: "After these things He gave them judges until Samuel the prophet.",
    21: "Then they asked for a king — and God gave them Saul the son of Kish, a man of the tribe of Benjamin, for forty years.",
    22: "And after He had removed him, He raised up David to be their king — concerning whom He also testified and said: 'I have found David, the son of Jesse, a man after My heart, who will do all My will.'",
    23: "From the descendants of this man, according to promise, God has brought to Israel a Savior, Jesus —",
    24: "after John had proclaimed before His coming a baptism of repentance to all the people of Israel.",
    25: "And while John was completing his course, he kept saying: 'What do you suppose that I am? I am not He. But behold, one is coming after me, the sandals of whose feet I am not worthy to untie.'",
    26: "Brothers, sons of Abraham's family — and those among you who fear God — to us the word of this salvation has been sent.",
    27: "For those who live in Jerusalem and their rulers — recognizing neither Him, nor the utterances of the prophets which are read every Sabbath — fulfilled these by condemning Him.",
    28: "And though they found no ground for putting Him to death, they asked Pilate that He be executed.",
    29: "And when they had carried out all that was written concerning Him, they took Him down from the cross and laid Him in a tomb.",
    30: "But God raised Him from the dead.",
    31: "And for many days He appeared to those who came up with Him from Galilee to Jerusalem — the very ones who are now His witnesses to the people.",
    32: "And we preach to you the good news of the promise made to the fathers —",
    33: "that God has fulfilled this promise to our children, in that He raised up Jesus, as it is also written in the second Psalm: 'You are My Son — today I have begotten You.'",
    34: "And as for the fact that He raised Him up from the dead, no longer to return to decay, He has spoken in this way: 'I will give you the holy and sure blessings of David.'",
    35: "Therefore He also says in another Psalm: 'You will not allow Your Holy One to undergo decay.'",
    36: "For David, after he had served the purpose of God in his own generation, fell asleep — and was laid among his fathers, and underwent decay.",
    37: "But He whom God raised did not undergo decay.",
    38: "Therefore let it be known to you, brothers, that through Him forgiveness of sins is proclaimed to you.",
    39: "And through Him everyone who believes is freed from all things, from which you could not be freed through the Law of Moses.",
    40: "Therefore take heed, so that the thing spoken of in the Prophets does not come upon you:",
    41: "'Behold, you scoffers — and marvel, and perish. For I am accomplishing a work in your days — a work which you will never believe, though someone should describe it to you.'\"",
    42: "And as Paul and Barnabas were going out, the people kept begging that these things might be spoken to them the next Sabbath.",
    43: "Now when the meeting of the synagogue had broken up, many of the Jews and of the God-fearing proselytes followed Paul and Barnabas — who, speaking to them, were urging them to continue in the grace of God.",
    44: "And the next Sabbath, nearly the whole city assembled to hear the word of the Lord.",
    45: "But when the Jews saw the crowds, they were filled with jealousy and began contradicting the things spoken by Paul — and were blaspheming.",
    46: "And Paul and Barnabas spoke out boldly and said: \"It was necessary that the word of God be spoken to you first. Since you reject it, and judge yourselves unworthy of eternal life — behold, we are turning to the Gentiles.",
    47: "For so the Lord has commanded us: 'I have placed You as a light for the Gentiles — that You may bring salvation to the ends of the earth.'\"",
    48: "And when the Gentiles heard this, they began rejoicing and glorifying the word of the Lord — and as many as had been appointed to eternal life believed.",
    49: "And the word of the Lord was being spread through the whole region.",
    50: "But the Jews incited the devout women of prominence and the leading men of the city — and instigated a persecution against Paul and Barnabas, and drove them out of their district.",
    51: "But they shook off the dust of their feet against them, and went to Iconium.",
    52: "And the disciples were continually filled with joy and with the Holy Spirit.",
}
ch14 = {
    1: "And in Iconium they entered the synagogue of the Jews together — and so spoke that a great multitude believed, both of Jews and of Greeks.",
    2: "But the Jews who disbelieved stirred up the minds of the Gentiles, and embittered them against the brothers.",
    3: "Therefore they spent a long time there speaking boldly with reliance upon the Lord — who was testifying to the word of His grace, granting that signs and wonders be done by their hands.",
    4: "But the people of the city were divided — and some sided with the Jews, and some with the apostles.",
    5: "And when an attempt was made by both the Gentiles and the Jews with their rulers, to mistreat and to stone them,",
    6: "they became aware of it and fled to the cities of Lycaonia, Lystra and Derbe, and the surrounding region.",
    7: "And there they continued to preach the gospel.",
    8: "At Lystra a man was sitting who had no strength in his feet — lame from his mother's womb, who had never walked.",
    9: "This man was listening to Paul as he spoke. And Paul, looking intently at him, and seeing that he had faith to be made well,",
    10: "said with a loud voice, \"Stand upright on your feet!\" And he leaped up and began to walk.",
    11: "And when the multitudes saw what Paul had done, they raised their voice, saying in the Lycaonian language, \"The gods have become like men, and have come down to us!\"",
    12: "And they began calling Barnabas, Zeus — and Paul, Hermes, because he was the chief speaker.",
    13: "And the priest of Zeus, whose temple was just outside the city, brought oxen and garlands to the gates — and wanted to offer sacrifice with the crowds.",
    14: "But when the apostles Barnabas and Paul heard of it, they tore their robes and rushed out into the crowd, crying out",
    15: "and saying, \"Men, why are you doing these things? We are also men of the same nature as you — and preach the gospel to you, that you should turn from these vain things to a living God, who made the heaven and the earth and the sea, and all that is in them.",
    16: "In the generations gone by, He permitted all the nations to go their own ways.",
    17: "And yet He did not leave Himself without witness — in that He did good and gave you rains from heaven and fruitful seasons, satisfying your hearts with food and gladness.\"",
    18: "And even saying these things, they with difficulty restrained the crowds from offering sacrifice to them.",
    19: "But Jews came from Antioch and Iconium, and having won over the crowds, they stoned Paul and dragged him out of the city — supposing him to be dead.",
    20: "But while the disciples stood around him, he got up and entered the city. And the next day he went away with Barnabas to Derbe.",
    21: "And after they had preached the gospel to that city and had made many disciples, they returned to Lystra and to Iconium and to Antioch —",
    22: "strengthening the souls of the disciples, encouraging them to continue in the faith, and saying that through many tribulations we must enter the kingdom of God.",
    23: "And when they had appointed elders for them in every church, having prayed with fasting, they commended them to the Lord — in whom they had believed.",
    24: "And they passed through Pisidia and came into Pamphylia.",
    25: "And when they had spoken the word in Perga, they went down to Attalia.",
    26: "And from there they sailed to Antioch — from which they had been commended to the grace of God for the work that they had accomplished.",
    27: "And when they had arrived and gathered the church together, they began to report all things that God had done with them — and how He had opened a door of faith to the Gentiles.",
    28: "And they spent a long time with the disciples.",
}
ch15 = {
    1: "And some men came down from Judea and began teaching the brothers: \"Unless you are circumcised according to the custom of Moses, you cannot be saved.\"",
    2: "And when Paul and Barnabas had great dissension and debate with them, the brothers determined that Paul and Barnabas and some others of them should go up to Jerusalem to the apostles and elders concerning this issue.",
    3: "Therefore, being sent on their way by the church, they were passing through both Phoenicia and Samaria — describing in detail the conversion of the Gentiles, and were bringing great joy to all the brothers.",
    4: "And when they arrived at Jerusalem, they were received by the church and the apostles and the elders — and they reported all that God had done with them.",
    5: "But some of the sect of the Pharisees who had believed stood up — saying, \"It is necessary to circumcise them, and to direct them to observe the Law of Moses.\"",
    6: "And the apostles and the elders came together to look into this matter.",
    7: "And after there had been much debate, Peter stood up and said to them: \"Brothers, you know that in the early days God made a choice among you that by my mouth the Gentiles should hear the word of the gospel and believe.",
    8: "And God, who knows the heart, testified to them giving them the Holy Spirit — just as He also did to us.",
    9: "And He made no distinction between us and them — cleansing their hearts by faith.",
    10: "Now therefore why do you put God to the test by placing upon the neck of the disciples a yoke which neither our fathers nor we have been able to bear?",
    11: "But we believe that we are saved through the grace of the Lord Jesus, in the same way as they also are.\"",
    12: "And all the multitude kept silent, and they were listening to Barnabas and Paul as they were relating what signs and wonders God had done through them among the Gentiles.",
    13: "And after they had stopped speaking, James answered, saying: \"Brothers, listen to me.",
    14: "Simeon has related how God first concerned Himself about taking from among the Gentiles a people for His name.",
    15: "And with this the words of the Prophets agree, just as it is written:",
    16: "'After these things I will return — and I will rebuild the tabernacle of David which has fallen. And I will rebuild its ruins, and I will restore it.",
    17: "So that the rest of mankind may seek the Lord — and all the Gentiles who are called by My name,' says the Lord, who makes these things known from long ago.",
    18: "Therefore it is my judgment that we do not trouble those who are turning to God from among the Gentiles —",
    19: "but that we write to them — that they abstain from things contaminated by idols, and from fornication, and from what is strangled, and from blood.",
    20: "For Moses, from ancient generations, has in every city those who preach him — since he is read in the synagogues every Sabbath.\"",
    21: "(Verse continues from above — placeholder note: verse 20-21 boundary; I treat as one rendered flow.)",
    22: "Then it seemed good to the apostles and the elders, with the whole church, to choose men from among them to send to Antioch with Paul and Barnabas — Judas called Barsabbas, and Silas, leading men among the brothers.",
    23: "And they sent this letter by them: \"The apostles and the brothers who are elders, to the brothers in Antioch and Syria and Cilicia, who are from the Gentiles — greetings.",
    24: "Since we have heard that some of our number to whom we gave no instruction have disturbed you with their words, unsettling your souls,",
    25: "it seemed good to us, having become of one mind, to select men to send to you with our beloved Barnabas and Paul —",
    26: "men who have risked their lives for the name of our Lord Jesus Christ.",
    27: "Therefore we have sent Judas and Silas — who themselves will also report the same things by word of mouth.",
    28: "For it seemed good to the Holy Spirit and to us — to lay upon you no greater burden than these essentials:",
    29: "that you abstain from things sacrificed to idols, and from blood, and from things strangled, and from fornication. If you keep yourselves free from such things, you will do well. Farewell.\"",
    30: "So when they were sent away, they went down to Antioch. And having gathered the congregation together, they delivered the letter.",
    31: "And when they had read it, they rejoiced because of its encouragement.",
    32: "And Judas and Silas, also being prophets themselves, encouraged and strengthened the brothers with a lengthy message.",
    33: "And after they had spent time there, they were sent away from the brothers in peace, to those who had sent them out.",
    34: "(But it seemed good to Silas to remain there.)",
    35: "But Paul and Barnabas stayed in Antioch — teaching and preaching, with many others also, the word of the Lord.",
    36: "And after some days Paul said to Barnabas, \"Let us return and visit the brothers in every city in which we proclaimed the word of the Lord — and see how they are.\"",
    37: "And Barnabas was desirous of taking John, called Mark, along with them also.",
    38: "But Paul kept insisting that they should not take him along, who had deserted them in Pamphylia and had not gone with them to the work.",
    39: "And there occurred such a sharp disagreement that they separated from one another. And Barnabas took Mark with him and sailed away to Cyprus.",
    40: "But Paul chose Silas — and left, being commended by the brothers to the grace of the Lord.",
    41: "And he was traveling through Syria and Cilicia, strengthening the churches.",
}
ch16 = {
    1: "And he came also to Derbe and to Lystra. And behold, a disciple was there, named Timothy — the son of a Jewish woman who was a believer, but his father was a Greek.",
    2: "And he was well spoken of by the brothers who were in Lystra and Iconium.",
    3: "Paul wanted this man to go with him — and he took him and circumcised him because of the Jews who were in those parts, for they all knew that his father was a Greek.",
    4: "Now while they were passing through the cities, they were delivering the decrees, which had been decided upon by the apostles and elders who were in Jerusalem, for them to observe.",
    5: "So the churches were being strengthened in the faith — and were increasing in number daily.",
    6: "And they passed through the Phrygian and Galatian region — having been forbidden by the Holy Spirit to speak the word in Asia.",
    7: "And when they had come to Mysia, they were trying to go into Bithynia — and the Spirit of Jesus did not permit them.",
    8: "And passing by Mysia, they came down to Troas.",
    9: "And a vision appeared to Paul in the night: a certain man of Macedonia was standing and appealing to him, and saying, \"Come over to Macedonia and help us!\"",
    10: "And when he had seen the vision, immediately we sought to go into Macedonia — concluding that God had called us to preach the gospel to them.",
    11: "Therefore putting out to sea from Troas, we ran a straight course to Samothrace — and on the day following, to Neapolis.",
    12: "And from there to Philippi, which is a leading city of the district of Macedonia, a Roman colony. And we were staying in this city for some days.",
    13: "And on the Sabbath day we went outside the gate to a riverside — where we were supposing that there would be a place of prayer. And we sat down and began speaking to the women who had assembled.",
    14: "And a certain woman named Lydia, from the city of Thyatira, a seller of purple fabrics, a worshiper of God, was listening — and the Lord opened her heart to respond to the things spoken by Paul.",
    15: "And when she and her household had been baptized, she urged us, saying, \"If you have judged me to be faithful to the Lord, come into my house and stay.\" And she prevailed upon us.",
    16: "And it happened, that as we were going to the place of prayer, a certain slave-girl having a spirit of divination met us — who was bringing her masters much profit by fortunetelling.",
    17: "Following after Paul and us, she kept crying out, saying, \"These men are bondservants of the Most High God — who are proclaiming to you the way of salvation.\"",
    18: "And she continued doing this for many days. But Paul was greatly annoyed, and turned and said to the spirit, \"I command you in the name of Jesus Christ to come out of her!\" And it came out at that very moment.",
    19: "But when her masters saw that their hope of profit was gone, they seized Paul and Silas and dragged them into the market place before the authorities.",
    20: "And when they had brought them to the chief magistrates, they said: \"These men, being Jews, are throwing our city into confusion —",
    21: "and are proclaiming customs which it is not lawful for us to accept or to observe, being Romans.\"",
    22: "And the crowd rose up together against them — and the chief magistrates tore their robes off them, and proceeded to order them to be beaten with rods.",
    23: "And when they had inflicted many blows upon them, they threw them into prison — commanding the jailer to guard them securely.",
    24: "And he, having received such a command, threw them into the inner prison — and fastened their feet in the stocks.",
    25: "But about midnight Paul and Silas were praying and singing hymns of praise to God — and the prisoners were listening to them.",
    26: "And suddenly there came a great earthquake, so that the foundations of the prison house were shaken. And immediately all the doors were opened — and everyone's chains were unfastened.",
    27: "And when the jailer had been roused out of sleep, and had seen the prison doors opened, he drew his sword and was about to kill himself — supposing that the prisoners had escaped.",
    28: "But Paul cried out with a loud voice, saying, \"Do not harm yourself, for we are all here!\"",
    29: "And he called for lights and rushed in — and trembling with fear, he fell down before Paul and Silas.",
    30: "And after he brought them out, he said, \"Sirs, what must I do to be saved?\"",
    31: "And they said, \"Believe in the Lord Jesus, and you will be saved, you and your household.\"",
    32: "And they spoke the word of the Lord to him, together with all who were in his house.",
    33: "And he took them that very hour of the night and washed their wounds — and immediately he was baptized, he and all his household.",
    34: "And he brought them into his house and set food before them — and rejoiced greatly, having believed in God with his whole household.",
    35: "Now when day came, the chief magistrates sent their policemen, saying, \"Release those men.\"",
    36: "And the jailer reported these words to Paul, saying, \"The chief magistrates have sent to release you. Therefore come out now and go in peace.\"",
    37: "But Paul said to them, \"They have beaten us in public, without trial — men who are Romans — and have thrown us into prison. And now are they sending us away secretly? No indeed! But let them come themselves and bring us out.\"",
    38: "And the policemen reported these words to the chief magistrates. And they were afraid when they heard that they were Romans —",
    39: "and they came and appealed to them. And when they had brought them out, they kept begging them to leave the city.",
    40: "And they went out of the prison, and entered the house of Lydia — and when they saw the brothers, they encouraged them and departed.",
}
ch17 = {
    1: "Now when they had traveled through Amphipolis and Apollonia, they came to Thessalonica — where there was a synagogue of the Jews.",
    2: "And according to Paul's custom, he went to them — and for three Sabbaths reasoned with them from the Scriptures.",
    3: "Explaining and giving evidence that the Christ had to suffer and rise again from the dead, and saying, \"This Jesus whom I am proclaiming to you is the Christ.\"",
    4: "And some of them were persuaded, and joined Paul and Silas — along with a great multitude of the God-fearing Greeks, and a number of the leading women.",
    5: "But the Jews, becoming jealous, took along some wicked men from the market place — and forming a mob, set the city in an uproar. And attacking the house of Jason, they were seeking to bring them out to the people.",
    6: "And when they did not find them, they began dragging Jason and some brothers before the city authorities, shouting, \"These men who have upset the world have come here also!",
    7: "And Jason has welcomed them — and they all act contrary to the decrees of Caesar, saying that there is another king, Jesus.\"",
    8: "And they stirred up the crowd and the city authorities who heard these things.",
    9: "And when they had received a pledge from Jason and the others, they released them.",
    10: "And the brothers immediately sent Paul and Silas away by night to Berea — and when they arrived, they went into the synagogue of the Jews.",
    11: "Now these were more noble-minded than those in Thessalonica, for they received the word with great eagerness — examining the Scriptures daily to see whether these things were so.",
    12: "Therefore many of them believed — along with a number of prominent Greek women and men.",
    13: "But when the Jews of Thessalonica found out that the word of God had been proclaimed by Paul in Berea also, they came there as well — agitating and stirring up the crowds.",
    14: "And then immediately the brothers sent Paul out to go as far as the sea — and Silas and Timothy remained there.",
    15: "Now those who escorted Paul brought him as far as Athens — and receiving a command for Silas and Timothy to come to him as soon as possible, they departed.",
    16: "Now while Paul was waiting for them at Athens, his spirit was being provoked within him as he was observing the city full of idols.",
    17: "So he was reasoning in the synagogue with the Jews and the God-fearing Gentiles — and in the market place every day with those who happened to be present.",
    18: "And also some of the Epicurean and Stoic philosophers were conversing with him. And some were saying, \"What would this idle babbler wish to say?\" Others, \"He seems to be a proclaimer of strange deities\" — because he was preaching Jesus and the resurrection.",
    19: "And they took him and brought him to the Areopagus, saying, \"May we know what this new teaching is which you are proclaiming?",
    20: "For you are bringing some strange things to our ears. Therefore we want to know what these things mean.\"",
    21: "(Now all the Athenians and the strangers visiting there used to spend their time in nothing other than telling or hearing something new.)",
    22: "So Paul stood in the midst of the Areopagus, and said: \"Men of Athens, I observe that you are very religious in all respects.",
    23: "For while I was passing through and examining the objects of your worship, I also found an altar with this inscription: 'TO AN UNKNOWN GOD.' Therefore what you worship in ignorance, this I proclaim to you.",
    24: "The God who made the world and all things in it — since He is Lord of heaven and earth — does not dwell in temples made with hands.",
    25: "Nor is He served by human hands, as though He needed anything — since He Himself gives to all life and breath and all things.",
    26: "And He made from one man every nation of mankind to live on all the face of the earth — having determined their appointed times, and the boundaries of their habitation.",
    27: "That they would seek God, if perhaps they might grope for Him and find Him — though He is not far from each one of us.",
    28: "For in Him we live, and move, and exist — as even some of your own poets have said: 'For we also are His offspring.'",
    29: "Being then the offspring of God, we ought not to think that the Divine Nature is like gold or silver or stone — an image formed by the art and thought of man.",
    30: "Therefore having overlooked the times of ignorance, God is now declaring to men that all people everywhere should repent.",
    31: "Because He has fixed a day in which He will judge the world in righteousness — through a Man whom He has appointed, having furnished proof to all men by raising Him from the dead.\"",
    32: "Now when they heard of the resurrection of the dead, some began to sneer — but others said, \"We shall hear you again concerning this.\"",
    33: "So Paul went out of their midst.",
    34: "But some men joined him and believed — among whom also was Dionysius the Areopagite, and a woman named Damaris, and others with them.",
}
ch18 = {
    1: "After these things he left Athens and went to Corinth.",
    2: "And he found a certain Jew named Aquila, a native of Pontus, having recently come from Italy with his wife Priscilla — because Claudius had commanded all the Jews to leave Rome. And he came to them,",
    3: "and because he was of the same trade, he was staying with them — and they were working, for by trade they were tent-makers.",
    4: "And he was reasoning in the synagogue every Sabbath — and trying to persuade Jews and Greeks.",
    5: "But when Silas and Timothy came down from Macedonia, Paul began devoting himself completely to the word — solemnly testifying to the Jews that Jesus was the Christ.",
    6: "And when they resisted and blasphemed, he shook out his garments and said to them, \"Your blood be upon your own heads! I am clean. From now on I will go to the Gentiles.\"",
    7: "And he departed from there and went to the house of a certain man named Titius Justus, a worshiper of God — whose house was next to the synagogue.",
    8: "And Crispus, the leader of the synagogue, believed in the Lord with all his household. And many of the Corinthians, when they heard, were believing and being baptized.",
    9: "And the Lord said to Paul in the night by a vision: \"Do not be afraid any longer — but go on speaking, and do not be silent.",
    10: "For I am with you, and no man will attack you in order to harm you — for I have many people in this city.\"",
    11: "And he settled there a year and six months, teaching the word of God among them.",
    12: "But while Gallio was proconsul of Achaia, the Jews with one accord rose up against Paul and brought him before the judgment seat,",
    13: "saying, \"This man persuades men to worship God contrary to the law.\"",
    14: "But when Paul was about to open his mouth, Gallio said to the Jews: \"If it were a matter of some misdemeanor or vicious crime, O Jews, it would be reasonable for me to put up with you.",
    15: "But if there are questions about words and names, and your own law — see to it yourselves; I am unwilling to be a judge of these matters.\"",
    16: "And he drove them away from the judgment seat.",
    17: "And they all took hold of Sosthenes, the leader of the synagogue, and began beating him in front of the judgment seat. But Gallio was not concerned about any of these things.",
    18: "And Paul, having remained many days longer, took leave of the brothers, and put out to sea for Syria, and with him were Priscilla and Aquila — having had his hair cut at Cenchrea, for he was keeping a vow.",
    19: "And they came to Ephesus, and he left them there. Now he himself entered the synagogue and reasoned with the Jews.",
    20: "And when they asked him to stay for a longer time, he did not consent —",
    21: "but taking leave of them, and saying, \"I will return to you again if God wills,\" he set sail from Ephesus.",
    22: "And when he had landed at Caesarea, he went up and greeted the church — and went down to Antioch.",
    23: "And having spent some time there, he departed, and passed successively through the Galatian region and Phrygia — strengthening all the disciples.",
    24: "Now a certain Jew named Apollos, an Alexandrian by birth, an eloquent man, came to Ephesus — and he was mighty in the Scriptures.",
    25: "This man had been instructed in the way of the Lord — and being fervent in spirit, he was speaking and teaching accurately the things concerning Jesus, being acquainted only with the baptism of John.",
    26: "And he began to speak boldly in the synagogue. But when Priscilla and Aquila heard him, they took him aside and explained to him the way of God more accurately.",
    27: "And when he wanted to go across to Achaia, the brothers encouraged him and wrote to the disciples to welcome him. And when he had arrived, he greatly helped those who had believed through grace —",
    28: "for he powerfully refuted the Jews in public, demonstrating by the Scriptures that Jesus was the Christ.",
}
ch19 = {
    1: "It happened that while Apollos was at Corinth, Paul, having passed through the upper country, came to Ephesus — and found some disciples.",
    2: "And he said to them, \"Did you receive the Holy Spirit when you believed?\" And they said to him, \"No, we have not even heard whether there is a Holy Spirit.\"",
    3: "And he said, \"Into what then were you baptized?\" And they said, \"Into John's baptism.\"",
    4: "And Paul said, \"John baptized with the baptism of repentance — telling the people to believe in Him who was coming after him, that is, in Jesus.\"",
    5: "And when they heard this, they were baptized in the name of the Lord Jesus.",
    6: "And when Paul had laid his hands upon them, the Holy Spirit came on them — and they began speaking with tongues and prophesying.",
    7: "And there were in all about twelve men.",
    8: "And he entered the synagogue and continued speaking out boldly for three months — reasoning and persuading them about the kingdom of God.",
    9: "But when some were becoming hardened and disobedient, speaking evil of the Way before the multitude, he withdrew from them and took away the disciples — reasoning daily in the school of Tyrannus.",
    10: "And this took place for two years — so that all who lived in Asia heard the word of the Lord, both Jews and Greeks.",
    11: "And God was performing extraordinary miracles by the hands of Paul.",
    12: "So that handkerchiefs or aprons were even carried from his body to the sick — and the diseases left them, and the evil spirits went out.",
    13: "But also some of the Jewish exorcists, who went from place to place, attempted to name over those who had the evil spirits the name of the Lord Jesus — saying, \"I adjure you by Jesus whom Paul preaches.\"",
    14: "And seven sons of one Sceva, a Jewish chief priest, were doing this.",
    15: "And the evil spirit answered and said to them, \"I recognize Jesus, and I know about Paul — but who are you?\"",
    16: "And the man, in whom was the evil spirit, leaped on them and subdued all of them, and overpowered them — so that they fled out of that house naked and wounded.",
    17: "And this became known to all, both Jews and Greeks, who lived in Ephesus. And fear fell upon them all — and the name of the Lord Jesus was being magnified.",
    18: "Many also of those who had believed kept coming, confessing and disclosing their practices.",
    19: "And many of those who practiced magic brought their books together and began burning them in the sight of all. And they counted up the price of them and found it fifty thousand pieces of silver.",
    20: "So the word of the Lord was growing mightily and prevailing.",
    21: "Now after these things were finished, Paul purposed in the Spirit to go to Jerusalem after he had passed through Macedonia and Achaia — saying, \"After I have been there, I must also see Rome.\"",
    22: "And having sent into Macedonia two of those who ministered to him, Timothy and Erastus, he himself stayed in Asia for a while.",
    23: "And about that time there occurred no small disturbance concerning the Way.",
    24: "For a certain man named Demetrius, a silversmith, who made silver shrines of Artemis, was bringing no little business to the craftsmen.",
    25: "These he gathered together, with the workmen of similar trades, and said: \"Men, you know that our prosperity depends upon this business.",
    26: "And you see and hear that not only in Ephesus, but in almost all of Asia, this Paul has persuaded and turned away a considerable number of people — saying that gods made with hands are no gods at all.",
    27: "And not only is there danger that this trade of ours fall into disrepute — but also that the temple of the great goddess Artemis be regarded as worthless, and that she whom all of Asia and the world worship would even be dethroned from her magnificence.\"",
    28: "And when they heard this and were filled with rage, they began crying out, saying, \"Great is Artemis of the Ephesians!\"",
    29: "And the city was filled with the confusion. And they rushed with one accord into the theater — dragging along Gaius and Aristarchus, Paul's traveling companions from Macedonia.",
    30: "And when Paul wanted to go into the assembly, the disciples would not let him.",
    31: "And also some of the Asiarchs, who were friends of his, sent to him and repeatedly urged him not to venture into the theater.",
    32: "So then, some were shouting one thing and some another — for the assembly was in confusion, and the majority did not know for what cause they had come together.",
    33: "And some of the crowd concluded it was Alexander, since the Jews had put him forward. And having motioned with his hand, Alexander was intending to make a defense to the assembly.",
    34: "But when they recognized that he was a Jew, a single outcry arose from them all as they shouted for about two hours: \"Great is Artemis of the Ephesians!\"",
    35: "And after quieting the multitude, the town clerk said: \"Men of Ephesus, what man is there after all who does not know that the city of the Ephesians is guardian of the temple of the great Artemis, and of the image which fell down from heaven?",
    36: "Since then these are undeniable facts, you ought to keep calm and to do nothing rash.",
    37: "For you have brought these men here who are neither robbers of temples nor blasphemers of our goddess.",
    38: "So then, if Demetrius and the craftsmen who are with him have a complaint against any man, the courts are in session and proconsuls are available — let them bring charges against one another.",
    39: "But if you want anything beyond this, it shall be settled in the lawful assembly.",
    40: "For indeed we are in danger of being accused of a riot in connection with today's affair, since there is no real cause for it. And in this connection we shall be unable to account for this disorderly gathering.\"",
    41: "And after saying this he dismissed the assembly.",
}
CHAPTERS = {10: ch10, 11: ch11, 12: ch12, 13: ch13, 14: ch14,
            15: ch15, 16: ch16, 17: ch17, 18: ch18, 19: ch19}

def main():
    new_entries = {f"44_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Acts 10-19 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Acts 10-19 verses")

if __name__ == "__main__":
    main()
