"""MBT Galatians — 6 chapters, 149 verses. Book ID 48."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch1 = {
    1: "Paul, an apostle — not from men nor through any man, but through Jesus Christ and God the Father, who raised Him from the dead —",
    2: "and all the brothers who are with me, to the churches of Galatia:",
    3: "Grace to you, and peace from God our Father, and the Lord Jesus Christ —",
    4: "who gave Himself for our sins, so that He might rescue us from this present evil age, according to the will of our God and Father —",
    5: "to whom be the glory forever and ever. Amen.",
    6: "I am amazed that you are so quickly deserting Him who called you by the grace of Christ — for a different gospel,",
    7: "which is really not another. There are some who are disturbing you, and want to distort the gospel of Christ.",
    8: "But even if we, or an angel from heaven, should preach to you a gospel contrary to what we have preached to you — let him be accursed!",
    9: "As we have said before, so I now say again: if anyone is preaching to you a gospel contrary to what you received — let him be accursed!",
    10: "For am I now seeking the favor of men, or of God? Or am I striving to please men? If I were still trying to please men, I would not be a bondservant of Christ.",
    11: "I would have you know, brothers, that the gospel which was preached by me is not according to man.",
    12: "For I neither received it from man, nor was I taught it — but it came through a revelation of Jesus Christ.",
    13: "For you have heard of my former manner of life in Judaism — how I used to persecute the church of God beyond measure, and tried to destroy it.",
    14: "And I was advancing in Judaism beyond many of my contemporaries among my countrymen — being more extremely zealous for my ancestral traditions.",
    15: "But when God — who had set me apart from my mother's womb, and called me through His grace — was pleased",
    16: "to reveal His Son in me, so that I might preach Him among the Gentiles, I did not immediately consult with flesh and blood —",
    17: "nor did I go up to Jerusalem to those who were apostles before me. But I went away to Arabia, and returned once more to Damascus.",
    18: "Then three years later I went up to Jerusalem to become acquainted with Cephas — and I stayed with him fifteen days.",
    19: "But I did not see any of the other apostles — except James, the Lord's brother.",
    20: "(In what I am writing to you, behold — before God, I am not lying.)",
    21: "Then I went into the regions of Syria and Cilicia.",
    22: "I was still unknown by sight to the churches of Judea which were in Christ.",
    23: "But only — they kept hearing, \"He who once persecuted us is now preaching the faith which he once tried to destroy.\"",
    24: "And they were glorifying God because of me.",
}
ch2 = {
    1: "Then after fourteen years, I went up again to Jerusalem with Barnabas, taking Titus along also.",
    2: "And I went up because of a revelation. And I submitted to them the gospel which I preach among the Gentiles — but I did so in private to those who were of reputation, for fear that I might be running, or had run, in vain.",
    3: "But not even Titus, who was with me, was compelled to be circumcised — though he was a Greek.",
    4: "But it was because of the false brothers who had been secretly brought in — who had sneaked in to spy on our liberty which we have in Christ Jesus, in order to bring us into bondage.",
    5: "We did not yield in submission to them, even for an hour — so that the truth of the gospel would remain with you.",
    6: "But from those who were of high reputation (what they were makes no difference to me — God shows no partiality) — those of reputation contributed nothing to me.",
    7: "But on the contrary — seeing that I had been entrusted with the gospel to the uncircumcised, just as Peter had been to the circumcised",
    8: "(for He who effectively worked for Peter in his apostleship to the circumcised, also worked effectively for me to the Gentiles),",
    9: "and recognizing the grace that had been given to me — James and Cephas and John, who were considered to be pillars, gave to Barnabas and me the right hand of fellowship — that we might go to the Gentiles, and they to the circumcised.",
    10: "Only they asked us to remember the poor — the very thing I also was eager to do.",
    11: "But when Cephas came to Antioch, I opposed him to his face — because he stood condemned.",
    12: "For prior to the coming of certain men from James, he used to eat with the Gentiles. But when they came, he began to withdraw and hold himself aloof — fearing the party of the circumcision.",
    13: "And the rest of the Jews joined him in hypocrisy — so that even Barnabas was carried away by their hypocrisy.",
    14: "But when I saw that they were not straightforward about the truth of the gospel, I said to Cephas in front of them all: \"If you, being a Jew, live like the Gentiles, and not like the Jews — how is it that you compel the Gentiles to live like Jews?\"",
    15: "We are Jews by nature, and not sinners from among the Gentiles —",
    16: "knowing that a man is not justified by works of the Law, but through faith in Jesus Christ. Even we have believed in Christ Jesus — so that we may be justified by faith in Christ, and not by works of the Law. For by works of the Law no flesh will be justified.",
    17: "But if, while seeking to be justified in Christ, we ourselves have also been found sinners — is Christ then a minister of sin? Absolutely not!",
    18: "For if I rebuild what I once destroyed, I prove myself to be a transgressor.",
    19: "For through the Law I died to the Law — so that I might live to God.",
    20: "I have been crucified with Christ. And it is no longer I who live — but Christ lives in me. And the life which I now live in the flesh, I live by faith in the Son of God — who loved me and gave Himself up for me.",
    21: "I do not nullify the grace of God — for if righteousness comes through the Law, then Christ died for nothing.",
}
ch3 = {
    1: "You foolish Galatians! Who has bewitched you — before whose eyes Jesus Christ was publicly portrayed as crucified?",
    2: "This is the only thing I want to find out from you: did you receive the Spirit by the works of the Law, or by hearing with faith?",
    3: "Are you so foolish? Having begun by the Spirit, are you now being perfected by the flesh?",
    4: "Did you suffer so many things in vain — if indeed it was in vain?",
    5: "So then, does He who supplies you with the Spirit and works miracles among you, do it by the works of the Law, or by hearing with faith?",
    6: "Just as Abraham believed God — and it was reckoned to him as righteousness.",
    7: "Therefore, recognize this: that those who are of faith are sons of Abraham.",
    8: "And the Scripture, foreseeing that God would justify the Gentiles by faith, preached the gospel beforehand to Abraham, saying, \"All the nations will be blessed in you.\"",
    9: "So then, those who are of faith are blessed with Abraham, the believer.",
    10: "For all who are of the works of the Law are under a curse — for it is written, \"Cursed is everyone who does not abide by all things written in the book of the Law, to perform them.\"",
    11: "Now that no one is justified by the Law before God is evident — for, \"The righteous one shall live by faith.\"",
    12: "And the Law is not of faith. Rather, \"The one who does these things will live by them.\"",
    13: "Christ redeemed us from the curse of the Law — having become a curse for us. For it is written, \"Cursed is everyone who hangs on a tree\" —",
    14: "so that in Christ Jesus the blessing of Abraham might come to the Gentiles, and that we might receive the promise of the Spirit through faith.",
    15: "Brothers, I speak in human terms: even with a man's covenant, when it has been ratified, no one sets it aside or adds conditions to it.",
    16: "Now the promises were spoken to Abraham and to his Seed. He does not say, \"And to seeds,\" as referring to many — but rather to one: \"And to your Seed,\" who is Christ.",
    17: "What I am saying is this: the Law, which came four hundred and thirty years later, does not invalidate a covenant previously ratified by God — so as to nullify the promise.",
    18: "For if the inheritance is based on the Law, it is no longer based on a promise — but God has granted it to Abraham by means of a promise.",
    19: "Why the Law then? It was added because of transgressions — until the Seed should come, to whom the promise had been made — and it was ordained through angels by the agency of a mediator.",
    20: "Now a mediator is not for one party only — whereas God is one.",
    21: "Is the Law then contrary to the promises of God? Absolutely not! For if a law had been given which was able to impart life, then righteousness would indeed have been based on law.",
    22: "But the Scripture has shut up everyone under sin — so that the promise by faith in Jesus Christ might be given to those who believe.",
    23: "But before faith came, we were kept in custody under the Law — being shut up to the faith which was later to be revealed.",
    24: "Therefore the Law has become our tutor to lead us to Christ — so that we may be justified by faith.",
    25: "But now that faith has come, we are no longer under a tutor.",
    26: "For you are all sons of God through faith in Christ Jesus.",
    27: "For all of you who were baptized into Christ have clothed yourselves with Christ.",
    28: "There is neither Jew nor Greek; there is neither slave nor free; there is neither male nor female — for you are all one in Christ Jesus.",
    29: "And if you belong to Christ, then you are Abraham's offspring — heirs according to promise.",
}
ch4 = {
    1: "Now I say, as long as the heir is a child, he does not differ at all from a slave — although he is owner of everything,",
    2: "but he is under guardians and managers until the date set by the father.",
    3: "So we also, when we were children, were held in bondage under the elementary principles of the world.",
    4: "But when the fullness of the time came, God sent forth His Son — born of a woman, born under the Law,",
    5: "in order that He might redeem those who were under the Law — that we might receive the adoption as sons.",
    6: "And because you are sons, God has sent forth the Spirit of His Son into our hearts — crying out, \"Abba! Father!\"",
    7: "Therefore you are no longer a slave, but a son. And if a son, then an heir through God.",
    8: "However at that time — when you did not know God — you were slaves to those which by nature are no gods.",
    9: "But now that you have come to know God — or rather, to be known by God — how is it that you turn back again to the weak and worthless elementary principles, to which you desire to be enslaved all over again?",
    10: "You observe days and months and seasons and years.",
    11: "I fear for you — that perhaps I have labored over you in vain.",
    12: "I beg of you, brothers, become as I am — for I also have become as you are. You have done me no wrong;",
    13: "but you know that it was because of a bodily illness that I preached the gospel to you the first time.",
    14: "And though my bodily condition was a trial to you, you did not despise or loathe me. But you received me as an angel of God — as Christ Jesus Himself.",
    15: "Where then is that sense of blessing you had? For I bear you witness that, if possible, you would have plucked out your eyes and given them to me.",
    16: "So have I become your enemy by telling you the truth?",
    17: "They eagerly seek you — not commendably, but they want to shut you out, so that you will seek them.",
    18: "But it is good always to be eagerly sought in a commendable manner — and not only when I am present with you.",
    19: "My children, with whom I am again in labor pains until Christ is formed in you —",
    20: "I would gladly be present with you now, and to change my tone — for I am perplexed about you.",
    21: "Tell me, you who want to be under the Law — do you not listen to the Law?",
    22: "For it is written that Abraham had two sons — one by the slave woman, and one by the free woman.",
    23: "But the son by the slave woman was born according to the flesh — and the son by the free woman, through the promise.",
    24: "These things are spoken allegorically — for these women are two covenants. One is from Mount Sinai, bearing children who are to be slaves — she is Hagar.",
    25: "Now this Hagar represents Mount Sinai in Arabia — and corresponds to the present Jerusalem, for she is in slavery with her children.",
    26: "But the Jerusalem above is free — she is our mother.",
    27: "For it is written, \"Rejoice, barren woman who does not bear; break forth and shout, you who are not in labor — for more numerous are the children of the desolate, than of the one who has a husband.\"",
    28: "And we, brothers — like Isaac — are children of promise.",
    29: "But just as at that time, the one who was born according to the flesh persecuted the one who was born according to the Spirit — so it is now also.",
    30: "But what does the Scripture say? \"Cast out the slave woman and her son — for the son of the slave woman shall not be an heir with the son of the free woman.\"",
    31: "So then, brothers, we are not children of a slave woman, but of the free woman.",
}
ch5 = {
    1: "It was for freedom that Christ set us free. Therefore stand firm, and do not be subject again to a yoke of slavery.",
    2: "Behold — I, Paul, say to you that if you receive circumcision, Christ will be of no benefit to you.",
    3: "And I testify again to every man who receives circumcision, that he is under obligation to keep the whole Law.",
    4: "You who are seeking to be justified by Law have been severed from Christ — you have fallen from grace.",
    5: "For we, through the Spirit, by faith, are eagerly waiting for the hope of righteousness.",
    6: "For in Christ Jesus, neither circumcision nor uncircumcision means anything — but only faith working through love.",
    7: "You were running well; who hindered you from obeying the truth?",
    8: "This persuasion did not come from the One who calls you.",
    9: "A little leaven leavens the whole lump of dough.",
    10: "I have confidence in you in the Lord, that you will adopt no other view. But the one who is disturbing you will bear his judgment, whoever he is.",
    11: "But I, brothers — if I still preach circumcision, why am I still persecuted? Then the stumbling block of the cross has been abolished.",
    12: "I wish that those who are troubling you would even mutilate themselves!",
    13: "For you were called to freedom, brothers — only do not turn your freedom into an opportunity for the flesh, but through love serve one another.",
    14: "For the whole Law is fulfilled in one word: \"You shall love your neighbor as yourself.\"",
    15: "But if you bite and devour one another, take care that you are not consumed by one another.",
    16: "But I say, walk by the Spirit, and you will not carry out the desire of the flesh.",
    17: "For the flesh sets its desire against the Spirit, and the Spirit against the flesh — for these are in opposition to one another, so that you may not do the things you please.",
    18: "But if you are led by the Spirit, you are not under the Law.",
    19: "Now the deeds of the flesh are evident — sexual immorality, impurity, sensuality,",
    20: "idolatry, sorcery, hostilities, strife, jealousy, outbursts of anger, selfish ambition, dissensions, factions,",
    21: "envying, drunkenness, carousing, and things like these — of which I forewarn you, just as I have forewarned you, that those who practice such things will not inherit the kingdom of God.",
    22: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness,",
    23: "gentleness, self-control. Against such things there is no law.",
    24: "Now those who belong to Christ Jesus have crucified the flesh with its passions and desires.",
    25: "If we live by the Spirit, let us also walk by the Spirit.",
    26: "Let us not become boastful, challenging one another, envying one another.",
}
ch6 = {
    1: "Brothers, even if anyone is caught in any trespass, you who are spiritual restore such a one in a spirit of gentleness — looking to yourself, so that you too will not be tempted.",
    2: "Bear one another's burdens — and so fulfill the law of Christ.",
    3: "For if anyone thinks he is something, when he is nothing — he deceives himself.",
    4: "But each one must examine his own work — and then he will have reason for boasting in regard to himself alone, and not in regard to another.",
    5: "For each one will bear his own load.",
    6: "And the one who is taught the word is to share all good things with the one who teaches him.",
    7: "Do not be deceived: God is not mocked. For whatever a man sows — this he will also reap.",
    8: "For the one who sows to his own flesh will reap corruption from the flesh — but the one who sows to the Spirit will reap eternal life from the Spirit.",
    9: "Let us not lose heart in doing good. For in due time we will reap, if we do not grow weary.",
    10: "So then, while we have opportunity, let us do good to all people — and especially to those who are of the household of the faith.",
    11: "See with what large letters I am writing to you with my own hand!",
    12: "Those who desire to make a good showing in the flesh — they try to compel you to be circumcised, simply so that they will not be persecuted for the cross of Christ.",
    13: "For those who are circumcised do not even keep the Law themselves — but they desire to have you circumcised, so that they may boast in your flesh.",
    14: "But may it never be that I should boast — except in the cross of our Lord Jesus Christ — through which the world has been crucified to me, and I to the world.",
    15: "For neither is circumcision anything, nor uncircumcision — but a new creation.",
    16: "And those who will walk by this rule — peace and mercy be upon them, and upon the Israel of God.",
    17: "From now on, let no one cause trouble for me — for I bear on my body the brand-marks of Jesus.",
    18: "The grace of our Lord Jesus Christ be with your spirit, brothers. Amen.",
}
CHAPTERS = {1: ch1, 2: ch2, 3: ch3, 4: ch4, 5: ch5, 6: ch6}

def main():
    new_entries = {f"48_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Galatians total verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Galatians verses")

if __name__ == "__main__":
    main()
