"""MBT Lamentations — complete book (5 chapters, 154 verses).

Five elegies over the fall of Jerusalem in 586 BC. Four of the five
chapters are Hebrew acrostics; chapter 3 is a triple acrostic with
its famous heart: 'His compassions never fail; they are new every
morning' (3:22-23).
"""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch1 = {
    1: "How lonely sits the city that was full of people! She has become like a widow who was once great among the nations! She who was a princess among the provinces has become a forced laborer!",
    2: "She weeps bitterly in the night, and her tears are on her cheeks. She has none to comfort her among all her lovers — all her friends have dealt treacherously with her, they have become her enemies.",
    3: "Judah has gone into exile under affliction and under harsh servitude. She dwells among the nations, but she has found no rest. All her pursuers have overtaken her in the midst of distress.",
    4: "The roads of Zion are in mourning, because no one comes to the appointed feasts. All her gates are desolate, her priests are groaning, her virgins are afflicted — and she herself is bitter.",
    5: "Her adversaries have become her masters, her enemies prosper — for the LORD has caused her grief because of the multitude of her transgressions. Her little ones have gone away as captives before the adversary.",
    6: "And all her majesty has departed from the daughter of Zion. Her princes have become like deer that have found no pasture — and they have fled without strength before the pursuer.",
    7: "In the days of her affliction and homelessness, Jerusalem remembers all her precious things that were from the days of old. When her people fell into the hand of the adversary, and no one helped her, the adversaries saw her, they mocked at her ruin.",
    8: "Jerusalem sinned greatly, therefore she has become an unclean thing. All who honored her despise her because they have seen her nakedness — even she herself groans and turns away.",
    9: "Her uncleanness was in her skirts — she did not consider her future. Therefore she has fallen astonishingly — she has no comforter. \"See, O LORD, my affliction, for the enemy has magnified himself!\"",
    10: "The adversary has stretched out his hand over all her precious things — for she has seen the nations enter her sanctuary, the ones whom You commanded that they should not enter into Your congregation.",
    11: "All her people groan seeking bread — they have given their precious things for food to restore their lives themselves. \"See, O LORD, and look — for I am despised.\"",
    12: "Is it nothing to all you who pass this way? Look and see if there is any pain like my pain which was severely dealt out to me — which the LORD inflicted on the day of His fierce anger.",
    13: "From on high He sent fire into my bones — and it prevailed over them. He has spread a net for my feet, He has turned me back. He has made me desolate, faint all day long.",
    14: "The yoke of my transgressions is bound. By His hand they are knit together — they have come upon my neck. He has made my strength fail. The Lord has given me into the hands of those against whom I am not able to stand.",
    15: "The Lord has rejected all my strong men in my midst. He has called an appointed time against me to crush my young men. The Lord has trodden as in a wine press the virgin daughter of Judah.",
    16: "For these things I weep — my eyes run down with water. Because far from me is a comforter, one who restores my soul. My children are desolate, because the enemy has prevailed.",
    17: "Zion stretches out her hands — there is no one to comfort her. The LORD has commanded concerning Jacob that the ones round about him should be his adversaries. Jerusalem has become an unclean thing among them.",
    18: "The LORD is righteous, for I have rebelled against His command. Hear now, all peoples, and behold my pain. My virgins and my young men have gone into captivity.",
    19: "I called to my lovers, but they deceived me. My priests and my elders perished in the city while they sought food to restore their strength themselves.",
    20: "See, O LORD, for I am in distress — my spirit is greatly troubled. My heart is overturned within me, for I have been very rebellious. In the street the sword slays — in the house it is like death.",
    21: "They have heard that I groan — there is no one to comfort me. All my enemies have heard of my calamity — they are glad that You have done it. Oh, that You would bring the day which You have proclaimed, that they may become like me.",
    22: "Let all their wickedness come before You — and deal with them as You have dealt with me for all my transgressions. For my groans are many, and my heart is faint.",
}
ch2 = {
    1: "How the Lord has covered the daughter of Zion with a cloud in His anger! He has cast from heaven to earth the glory of Israel — and has not remembered His footstool in the day of His anger.",
    2: "The Lord has swallowed up; He has not spared all the habitations of Jacob. In His wrath He has thrown down the strongholds of the daughter of Judah. He has brought them down to the ground. He has profaned the kingdom and its princes.",
    3: "In fierce anger He has cut off all the strength of Israel. He has drawn back His right hand from before the enemy. And He has burned in Jacob like a flaming fire consuming round about.",
    4: "He has bent His bow like an enemy. He has set His right hand like an adversary, and slain all that were pleasant to the eye. In the tent of the daughter of Zion He has poured out His wrath like fire.",
    5: "The Lord has become like an enemy. He has swallowed up Israel. He has swallowed up all its palaces. He has destroyed its strongholds and multiplied in the daughter of Judah mourning and moaning.",
    6: "And He has violently treated His tabernacle like a garden booth. He has destroyed His appointed meeting place. The LORD has caused to be forgotten the appointed feast and sabbath in Zion, and He has despised king and priest in the indignation of His anger.",
    7: "The Lord has rejected His altar, He has abandoned His sanctuary. He has delivered into the hand of the enemy the walls of her palaces. They have made a noise in the house of the LORD as in the day of an appointed feast.",
    8: "The LORD determined to destroy the wall of the daughter of Zion. He has stretched out a line — He has not restrained His hand from destroying, and He has caused rampart and wall to lament. They have languished together.",
    9: "Her gates have sunk into the ground. He has destroyed and broken her bars. Her king and her princes are among the nations. The law is no more. Also, her prophets find no vision from the LORD.",
    10: "The elders of the daughter of Zion sit on the ground, they are silent. They have thrown dust on their heads — they have girded themselves with sackcloth. The virgins of Jerusalem have bowed their heads to the ground.",
    11: "My eyes fail because of tears. My spirit is greatly troubled. My heart is poured out on the earth, because of the destruction of the daughter of my people. When little ones and infants faint in the streets of the city.",
    12: "They say to their mothers, \"Where is grain and wine?\" — as they faint like a wounded man in the streets of the city, as their life is poured out on their mothers' bosom.",
    13: "How shall I admonish you? To what shall I compare you, O daughter of Jerusalem? To what shall I liken you as I comfort you, O virgin daughter of Zion? For your ruin is as vast as the sea — who can heal you?",
    14: "Your prophets have seen for you false and foolish visions. And they have not exposed your iniquity so as to restore you from captivity — but they have seen for you false and misleading oracles.",
    15: "All who pass along the way clap their hands in derision at you. They hiss and shake their heads at the daughter of Jerusalem: \"Is this the city of which they said, 'The perfection of beauty — a joy to all the earth'?\"",
    16: "All your enemies have opened their mouths wide against you. They hiss and gnash their teeth. They say, \"We have swallowed her up! Surely this is the day for which we waited — we have reached it, we have seen it.\"",
    17: "The LORD has done what He purposed. He has accomplished His word which He commanded from days of old. He has thrown down without sparing. And He has caused the enemy to rejoice over you. He has exalted the might of your adversaries.",
    18: "Their heart cried out to the Lord, \"O wall of the daughter of Zion, let your tears run down like a river day and night. Give yourself no relief — let your eyes have no rest.",
    19: "Arise, cry aloud in the night at the beginning of the night watches. Pour out your heart like water before the presence of the Lord. Lift up your hands to Him for the life of your little ones, who are faint because of hunger at the head of every street.\"",
    20: "See, O LORD, and look! With whom have You dealt thus? Should women eat their offspring, the little ones who were born healthy? Should priest and prophet be slain in the sanctuary of the Lord?",
    21: "On the ground in the streets lie young and old. My virgins and my young men have fallen by the sword. You have slain them in the day of Your anger — You have slaughtered, not sparing.",
    22: "You called as in the day of an appointed feast my terrors on every side. And there was no one who escaped or survived in the day of the LORD's anger. Those whom I bore and reared, my enemy annihilated them.",
}
ch3 = {
    1: "I am the man who has seen affliction because of the rod of His wrath.",
    2: "He has driven me and made me walk in darkness, and not in light.",
    3: "Surely against me He has turned His hand repeatedly all the day.",
    4: "He has caused my flesh and my skin to waste away. He has broken my bones.",
    5: "He has besieged and encompassed me with bitterness and hardship.",
    6: "In dark places He has made me dwell, like those who have long been dead.",
    7: "He has walled me in so that I cannot go out. He has made my chain heavy.",
    8: "Even when I cry out and call for help, He shuts out my prayer.",
    9: "He has blocked my ways with hewn stone. He has made my paths crooked.",
    10: "He is to me like a bear lying in wait, like a lion in secret places.",
    11: "He has turned aside my ways and torn me to pieces. He has made me desolate.",
    12: "He bent His bow and set me as a target for the arrow.",
    13: "He made the arrows of His quiver to enter into my inward parts.",
    14: "I have become a laughingstock to all my people, their mocking song all the day.",
    15: "He has filled me with bitterness. He has made me drunk with wormwood.",
    16: "And He has broken my teeth with gravel. He has made me cower in the dust.",
    17: "And my soul has been rejected from peace. I have forgotten happiness.",
    18: "So I say, \"My strength has perished — and so has my hope from the LORD.\"",
    19: "Remember my affliction and my wandering, the wormwood and bitterness.",
    20: "Surely my soul remembers — and is bowed down within me.",
    21: "This I recall to my mind — therefore I have hope.",
    22: "The LORD's lovingkindnesses indeed never cease — for His compassions never fail.",
    23: "They are new every morning. Great is Your faithfulness.",
    24: "\"The LORD is my portion,\" says my soul. \"Therefore I have hope in Him.\"",
    25: "The LORD is good to those who wait for Him, to the person who seeks Him.",
    26: "It is good that he waits silently for the salvation of the LORD.",
    27: "It is good for a man that he should bear the yoke in his youth.",
    28: "Let him sit alone and be silent, since He has laid it on him.",
    29: "Let him put his mouth in the dust — perhaps there is hope.",
    30: "Let him give his cheek to the smiter. Let him be filled with reproach.",
    31: "For the Lord will not reject forever.",
    32: "For if He causes grief, then He will have compassion according to His abundant lovingkindness.",
    33: "For He does not afflict willingly, or grieve the sons of men.",
    34: "To crush under His feet all the prisoners of the land,",
    35: "to deprive a man of justice in the presence of the Most High,",
    36: "to defraud a man in his lawsuit — of these things the Lord does not approve.",
    37: "Who is there who speaks and it comes to pass, unless the Lord has commanded it?",
    38: "Is it not from the mouth of the Most High that both good and ill go forth?",
    39: "Why should any living mortal, or any man, offer complaint in view of his sins?",
    40: "Let us examine and probe our ways, and let us return to the LORD.",
    41: "We lift up our heart and hands toward God in heaven.",
    42: "We have transgressed and rebelled — You have not pardoned.",
    43: "You have covered Yourself with anger and pursued us. You have slain and have not spared.",
    44: "You have covered Yourself with a cloud, so that no prayer can pass through.",
    45: "You have made us mere offscouring and refuse in the midst of the peoples.",
    46: "All our enemies have opened their mouths against us.",
    47: "Panic and pitfall have befallen us, devastation and destruction.",
    48: "My eyes run down with streams of water because of the destruction of the daughter of my people.",
    49: "My eyes pour down unceasingly, without stopping,",
    50: "until the LORD looks down and sees from heaven.",
    51: "My eyes bring pain to my soul because of all the daughters of my city.",
    52: "My enemies without cause hunted me down like a bird.",
    53: "They have silenced me in the pit, and have placed a stone on me.",
    54: "Waters flowed over my head. I said, \"I am cut off!\"",
    55: "I called on Your name, O LORD, out of the lowest pit.",
    56: "You have heard my voice — do not hide Your ear from my prayer for relief, from my cry for help.",
    57: "You drew near when I called on You. You said, \"Do not fear!\"",
    58: "O Lord, You have pleaded my soul's cause. You have redeemed my life.",
    59: "O LORD, You have seen my oppression — judge my case.",
    60: "You have seen all their vengeance, all their schemes against me.",
    61: "You have heard their reproach, O LORD — all their schemes against me.",
    62: "The lips of my assailants and their whispering are against me all day long.",
    63: "Look on their sitting and their rising — I am their mocking song.",
    64: "You will recompense them, O LORD, according to the work of their hands.",
    65: "You will give them hardness of heart. Your curse will be on them.",
    66: "You will pursue them in anger and destroy them from under the heavens of the LORD!",
}
ch4 = {
    1: "How dark the gold has become! How the pure gold has changed! The sacred stones are poured out at the corner of every street.",
    2: "The precious sons of Zion, weighed against fine gold — how they are regarded as earthen jars, the work of a potter's hands!",
    3: "Even jackals offer the breast, they nurse their young. But the daughter of my people has become cruel like ostriches in the wilderness.",
    4: "The tongue of the infant cleaves to the roof of its mouth because of thirst. The little ones ask for bread, but no one breaks it for them.",
    5: "Those who ate delicacies are desolate in the streets. Those reared in purple embrace ash pits.",
    6: "For the iniquity of the daughter of my people is greater than the sin of Sodom, which was overthrown as in a moment, and no hands were turned toward her.",
    7: "Her consecrated ones were purer than snow, they were whiter than milk. They were more ruddy in body than corals. Their polishing was like lapis lazuli.",
    8: "Their appearance is blacker than soot. They are not recognized in the streets. Their skin is shriveled on their bones — it is withered, it has become like wood.",
    9: "Better are those slain with the sword than those slain with hunger — who pine away, being stricken for lack of the fruits of the field.",
    10: "The hands of compassionate women boiled their own children. They became food for them because of the destruction of the daughter of my people.",
    11: "The LORD has accomplished His wrath. He has poured out His fierce anger. And He has kindled a fire in Zion which has consumed its foundations.",
    12: "The kings of the earth did not believe — nor did any of the inhabitants of the world — that the adversary and the enemy could enter the gates of Jerusalem.",
    13: "Because of the sins of her prophets and the iniquities of her priests, who have shed in her midst the blood of the righteous.",
    14: "They wandered blind in the streets. They were defiled with blood, so that no one could touch their garments.",
    15: "\"Depart! Unclean!\" — they cried of themselves. \"Depart! Depart! Do not touch!\" So they fled and wandered. Men among the nations said, \"They shall not continue to dwell with us.\"",
    16: "The presence of the LORD has scattered them. He will not continue to regard them. They did not honor the priests. They did not favor the elders.",
    17: "Yet our eyes failed, looking for help was useless. In our watching we have watched for a nation that could not save.",
    18: "They hunted our steps so that we could not walk in our streets. Our end drew near — our days were finished, for our end had come.",
    19: "Our pursuers were swifter than the eagles of the sky. They chased us on the mountains. They waited in ambush for us in the wilderness.",
    20: "The breath of our nostrils, the LORD's anointed, was captured in their pits — of whom we had said, \"Under his shadow we shall live among the nations.\"",
    21: "Rejoice and be glad, O daughter of Edom, who dwells in the land of Uz! But the cup will pass to you as well. You will be drunk and make yourself naked.",
    22: "The punishment of your iniquity has been completed, O daughter of Zion — He will exile you no longer. But He will punish your iniquity, O daughter of Edom. He will expose your sins!",
}
ch5 = {
    1: "Remember, O LORD, what has befallen us. Look, and see our reproach!",
    2: "Our inheritance has been turned over to strangers — our houses to aliens.",
    3: "We have become orphans without a father. Our mothers are like widows.",
    4: "We have to pay for our drinking water — our wood comes to us at a price.",
    5: "Our pursuers are at our necks. We are worn out — there is no rest for us.",
    6: "We have submitted to Egypt and Assyria to get enough bread.",
    7: "Our fathers sinned, and are no more. It is we who have borne their iniquities.",
    8: "Slaves rule over us — there is no one to deliver us from their hand.",
    9: "We get our bread at the risk of our lives, because of the sword in the wilderness.",
    10: "Our skin has become as hot as an oven, because of the burning heat of famine.",
    11: "They ravished the women in Zion — the virgins in the cities of Judah.",
    12: "Princes were hung by their hands. Elders were not respected.",
    13: "Young men worked at the grinding mill. And youths stumbled under loads of wood.",
    14: "Elders are gone from the gate. Young men from their music.",
    15: "The joy of our hearts has ceased. Our dancing has been turned into mourning.",
    16: "The crown has fallen from our head. Woe to us, for we have sinned!",
    17: "Because of this our heart is faint. Because of these things our eyes are dim.",
    18: "Because of Mount Zion which lies desolate — foxes prowl in it.",
    19: "You, O LORD, rule forever. Your throne is from generation to generation.",
    20: "Why do You forget us forever? Why do You forsake us so long?",
    21: "Restore us to You, O LORD, that we may be restored. Renew our days as of old —",
    22: "unless You have utterly rejected us, and are exceedingly angry with us.",
}

CHAPTERS = {1:ch1,2:ch2,3:ch3,4:ch4,5:ch5}

def main():
    new_entries = {f"25_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Lamentations verses authored: {len(new_entries)}")
    with open(MOOP_PATH) as f:
        moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f:
        json.dump(moop, f, ensure_ascii=False)
    print("moop-translation.json updated.")

if __name__ == "__main__":
    main()
