"""MBT Acts 1-9 — Pentecost, early church, Stephen, Saul. 336 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch1 = {
    1: "The first account I composed, Theophilus, about all that Jesus began to do and teach,",
    2: "until the day when He was taken up — after He had given orders by the Holy Spirit to the apostles whom He had chosen.",
    3: "To these He also presented Himself alive, after His suffering, by many convincing proofs — appearing to them over a period of forty days, and speaking of the things concerning the kingdom of God.",
    4: "And gathering them together, He commanded them not to leave Jerusalem — but to wait for what the Father had promised, \"Which,\" He said, \"you heard of from Me.",
    5: "For John baptized with water — but you will be baptized with the Holy Spirit not many days from now.\"",
    6: "So when they had come together, they were asking Him, saying, \"Lord, is it at this time You are restoring the kingdom to Israel?\"",
    7: "He said to them, \"It is not for you to know times or epochs which the Father has fixed by His own authority.",
    8: "But you will receive power when the Holy Spirit has come upon you — and you shall be My witnesses both in Jerusalem, and in all Judea and Samaria, and even to the remotest part of the earth.\"",
    9: "And after He had said these things, He was lifted up while they were looking on — and a cloud received Him out of their sight.",
    10: "And as they were gazing intently into the sky while He was going, behold — two men in white clothing stood beside them.",
    11: "Who said, \"Men of Galilee, why do you stand looking into the sky? This Jesus, who has been taken up from you into heaven, will come in just the same way as you have watched Him go into heaven.\"",
    12: "Then they returned to Jerusalem from the mount called Olivet — which is near Jerusalem, a Sabbath day's journey away.",
    13: "And when they had entered the city, they went up to the upper room where they were staying — Peter and John and James and Andrew, Philip and Thomas, Bartholomew and Matthew, James the son of Alphaeus, and Simon the Zealot, and Judas the son of James.",
    14: "These all with one mind were continually devoting themselves to prayer — along with the women, and Mary the mother of Jesus, and with His brothers.",
    15: "At this time Peter stood up in the midst of the brothers (a gathering of about one hundred and twenty persons was there together) and said,",
    16: "\"Brothers, the Scripture had to be fulfilled — which the Holy Spirit foretold by the mouth of David concerning Judas, who became a guide to those who arrested Jesus.",
    17: "For he was counted among us, and received his share in this ministry.\"",
    18: "(Now this man acquired a field with the price of his wickedness — and falling headlong, he burst open in the middle, and all his intestines gushed out.",
    19: "And it became known to all who were living in Jerusalem — so that in their own language, that field was called Hakeldama, that is, Field of Blood.)",
    20: "\"For it is written in the book of Psalms: 'Let his homestead be made desolate, and let no one dwell in it.' And, 'Let another man take his office.'",
    21: "Therefore, it is necessary that of the men who have accompanied us all the time that the Lord Jesus went in and out among us —",
    22: "beginning with the baptism of John until the day that He was taken up from us — one of these must become a witness with us of His resurrection.\"",
    23: "And so they put forward two men: Joseph called Barsabbas (who was also called Justus), and Matthias.",
    24: "And they prayed and said, \"You, Lord, who know the hearts of all men — show us which one of these two You have chosen,",
    25: "to occupy this ministry and apostleship, from which Judas turned aside to go to his own place.\"",
    26: "And they drew lots for them — and the lot fell to Matthias. And he was added to the eleven apostles.",
}
ch2 = {
    1: "And when the day of Pentecost had come, they were all together in one place.",
    2: "And suddenly there came from heaven a noise like a violent rushing wind — and it filled the whole house where they were sitting.",
    3: "And there appeared to them tongues as of fire, distributing themselves — and they rested on each one of them.",
    4: "And they were all filled with the Holy Spirit, and began to speak with other tongues — as the Spirit was giving them utterance.",
    5: "Now there were Jews living in Jerusalem — devout men from every nation under heaven.",
    6: "And when this sound occurred, the crowd came together — and were bewildered, because each one of them was hearing them speak in his own language.",
    7: "And they were amazed and astonished, saying, \"Why, are not all these who are speaking Galileans?",
    8: "And how is it that we each hear them in our own language to which we were born?",
    9: "Parthians and Medes and Elamites — and residents of Mesopotamia, Judea and Cappadocia, Pontus and Asia,",
    10: "Phrygia and Pamphylia, Egypt and the districts of Libya around Cyrene, and visitors from Rome — both Jews and proselytes,",
    11: "Cretans and Arabs — we hear them in our own tongues speaking of the mighty deeds of God.\"",
    12: "And they all continued in amazement and great perplexity, saying to one another, \"What does this mean?\"",
    13: "But others were mocking and saying, \"They are full of sweet wine.\"",
    14: "But Peter, taking his stand with the eleven, raised his voice and declared to them: \"Men of Judea, and all you who live in Jerusalem — let this be known to you, and give heed to my words.",
    15: "For these men are not drunk, as you suppose — for it is only the third hour of the day.",
    16: "But this is what was spoken of through the prophet Joel:",
    17: "'And it shall be in the last days, God says, that I will pour forth of My Spirit upon all mankind. And your sons and your daughters shall prophesy. And your young men shall see visions, and your old men shall dream dreams.",
    18: "Even on My bondservants, both men and women, I will in those days pour forth of My Spirit, and they shall prophesy.",
    19: "And I will grant wonders in the sky above, and signs on the earth below — blood and fire and vapor of smoke.",
    20: "The sun will be turned into darkness, and the moon into blood, before the great and glorious day of the Lord shall come.",
    21: "And it shall be that everyone who calls on the name of the Lord will be saved.'",
    22: "Men of Israel, listen to these words: Jesus the Nazarene, a man attested to you by God with miracles and wonders and signs which God performed through Him in your midst — just as you yourselves know.",
    23: "This Man, delivered over by the predetermined plan and foreknowledge of God, you nailed to a cross by the hands of godless men, and put Him to death.",
    24: "But God raised Him up again — putting an end to the agony of death, since it was impossible for Him to be held in its power.",
    25: "For David says of Him: 'I saw the Lord always in My presence — for He is at My right hand, so that I will not be shaken.",
    26: "Therefore My heart was glad and My tongue exulted; moreover My flesh also will live in hope —",
    27: "because You will not abandon My soul to Hades, nor allow Your Holy One to undergo decay.",
    28: "You have made known to Me the ways of life. You will make Me full of gladness with Your presence.'",
    29: "Brothers, I may confidently say to you regarding the patriarch David — that he both died and was buried, and his tomb is with us to this day.",
    30: "And so, because he was a prophet, and knew that God had sworn to him with an oath to seat one of his descendants on his throne —",
    31: "he looked ahead and spoke of the resurrection of the Christ, that He was neither abandoned to Hades, nor did His flesh suffer decay.",
    32: "This Jesus, God raised up again — to which we are all witnesses.",
    33: "Therefore, having been exalted to the right hand of God, and having received from the Father the promise of the Holy Spirit — He has poured forth this which you both see and hear.",
    34: "For it was not David who ascended into heaven — but he himself says: 'The Lord said to my Lord: Sit at My right hand,",
    35: "until I make Your enemies a footstool for Your feet.'",
    36: "Therefore let all the house of Israel know for certain that God has made Him both Lord and Christ — this Jesus whom you crucified.\"",
    37: "Now when they heard this, they were pierced to the heart — and said to Peter and the rest of the apostles, \"Brothers, what shall we do?\"",
    38: "Peter said to them, \"Repent, and let each of you be baptized in the name of Jesus Christ for the forgiveness of your sins. And you will receive the gift of the Holy Spirit.",
    39: "For the promise is for you, and your children, and for all who are far off — as many as the Lord our God will call to Himself.\"",
    40: "And with many other words he solemnly testified, and kept on exhorting them, saying, \"Be saved from this perverse generation!\"",
    41: "So then, those who had received his word were baptized — and that day there were added about three thousand souls.",
    42: "They were continually devoting themselves to the apostles' teaching, and to fellowship, to the breaking of bread, and to prayer.",
    43: "Everyone kept feeling a sense of awe — and many wonders and signs were taking place through the apostles.",
    44: "And all those who had believed were together — and had all things in common.",
    45: "And they began selling their property and possessions, and were sharing them with all — as anyone might have need.",
    46: "Day by day continuing with one mind in the temple, and breaking bread from house to house — they were taking their meals together with gladness and sincerity of heart.",
    47: "Praising God, and having favor with all the people. And the Lord was adding to their number day by day those who were being saved.",
}
ch3 = {
    1: "Now Peter and John were going up to the temple at the ninth hour, the hour of prayer.",
    2: "And a man who had been lame from his mother's womb was being carried along — whom they used to set down every day at the gate of the temple which is called Beautiful, in order to beg alms of those who were entering the temple.",
    3: "When he saw Peter and John about to go into the temple, he began asking to receive alms.",
    4: "But Peter, along with John, fixed his gaze on him and said, \"Look at us!\"",
    5: "And he began to give them his attention — expecting to receive something from them.",
    6: "But Peter said, \"I do not possess silver and gold — but what I do have I give to you. In the name of Jesus Christ the Nazarene — walk!\"",
    7: "And seizing him by the right hand, he raised him up. And immediately his feet and his ankles were strengthened.",
    8: "And with a leap he stood upright, and began to walk. And he entered the temple with them — walking and leaping and praising God.",
    9: "And all the people saw him walking and praising God.",
    10: "And they were taking note of him as being the one who used to sit at the Beautiful Gate of the temple to beg alms — and they were filled with wonder and amazement at what had happened to him.",
    11: "While he was clinging to Peter and John, all the people ran together to them at the so-called portico of Solomon — full of amazement.",
    12: "But when Peter saw this, he replied to the people: \"Men of Israel, why are you amazed at this — or why do you gaze at us, as if by our own power or piety we had made him walk?",
    13: "The God of Abraham, Isaac, and Jacob, the God of our fathers, has glorified His servant Jesus — the One whom you delivered up, and disowned in the presence of Pilate, when he had decided to release Him.",
    14: "But you disowned the Holy and Righteous One, and asked for a murderer to be granted to you.",
    15: "But you put to death the Author of life — whom God raised from the dead, a fact to which we are witnesses.",
    16: "And on the basis of faith in His name, it is the name of Jesus which has strengthened this man whom you see and know. And the faith which comes through Him has given him this perfect health in the presence of you all.",
    17: "And now, brothers, I know that you acted in ignorance — just as your rulers did also.",
    18: "But the things which God announced beforehand by the mouth of all the prophets — that His Christ would suffer — He has thus fulfilled.",
    19: "Therefore repent and return — so that your sins may be wiped away, in order that times of refreshing may come from the presence of the Lord.",
    20: "And that He may send Jesus, the Christ appointed for you,",
    21: "whom heaven must receive until the period of restoration of all things — about which God spoke by the mouth of His holy prophets from ancient time.",
    22: "Moses said: 'The Lord God will raise up for you a prophet like me from your brothers. To Him you shall give heed in everything He says to you.",
    23: "And it will be that every soul that does not heed that prophet shall be utterly destroyed from among the people.'",
    24: "And likewise, all the prophets who have spoken — from Samuel and his successors onward — also announced these days.",
    25: "It is you who are the sons of the prophets and of the covenant which God made with your fathers, saying to Abraham: 'And in your seed all the families of the earth shall be blessed.'",
    26: "For you first, God raised up His Servant — and sent Him to bless you, by turning every one of you from your wicked ways.\"",
}
ch4 = {
    1: "As they were speaking to the people, the priests and the captain of the temple guard, and the Sadducees, came up to them —",
    2: "being greatly disturbed because they were teaching the people, and proclaiming in Jesus the resurrection from the dead.",
    3: "And they laid hands on them, and put them in jail until the next day — for it was already evening.",
    4: "But many of those who had heard the message believed — and the number of the men came to be about five thousand.",
    5: "On the next day, their rulers and elders and scribes were gathered together in Jerusalem.",
    6: "And Annas the high priest was there, and Caiaphas, and John, and Alexander, and all who were of high priestly descent.",
    7: "And when they had placed them in the center, they began to inquire: \"By what power, or in what name, have you done this?\"",
    8: "Then Peter, filled with the Holy Spirit, said to them: \"Rulers and elders of the people —",
    9: "if we are on trial today for a benefit done to a sick man, as to how this man has been made well —",
    10: "let it be known to all of you, and to all the people of Israel: that by the name of Jesus Christ the Nazarene, whom you crucified, whom God raised from the dead — by this name this man stands here before you in good health.",
    11: "He is the stone which was rejected by you, the builders — but which became the chief cornerstone.",
    12: "And there is salvation in no one else — for there is no other name under heaven that has been given among men by which we must be saved.\"",
    13: "Now as they observed the confidence of Peter and John, and understood that they were uneducated and untrained men, they were amazed — and began to recognize them as having been with Jesus.",
    14: "And seeing the man who had been healed standing with them, they had nothing to say in reply.",
    15: "But when they had ordered them to leave the Council, they began to confer with one another,",
    16: "saying, \"What shall we do with these men? For the fact that a noteworthy miracle has taken place through them is apparent to all who live in Jerusalem — and we cannot deny it.",
    17: "But so that it will not spread any further among the people, let us warn them to speak no longer to any man in this name.\"",
    18: "And when they had summoned them, they commanded them not to speak or teach at all in the name of Jesus.",
    19: "But Peter and John answered and said to them, \"Whether it is right in the sight of God to give heed to you rather than to God, you be the judge.",
    20: "For we cannot stop speaking about what we have seen and heard.\"",
    21: "And when they had threatened them further, they let them go (finding no basis on which to punish them) — on account of the people, because they were all glorifying God for what had happened.",
    22: "For the man was more than forty years old on whom this miracle of healing had been performed.",
    23: "And when they had been released, they went to their own companions — and reported all that the chief priests and the elders had said to them.",
    24: "And when they heard this, they lifted their voices to God with one accord and said: \"O Lord, it is You who made the heaven, and the earth, and the sea, and all that is in them —",
    25: "who by the Holy Spirit, through the mouth of our father David Your servant, said: 'Why did the Gentiles rage, and the peoples devise futile things?",
    26: "The kings of the earth took their stand, and the rulers were gathered together against the Lord, and against His Christ.'",
    27: "For truly in this city there were gathered together against Your holy Servant Jesus, whom You anointed — both Herod and Pontius Pilate, along with the Gentiles and the peoples of Israel,",
    28: "to do whatever Your hand and Your purpose predestined to occur.",
    29: "And now, Lord, take note of their threats — and grant that Your bondservants may speak Your word with all confidence,",
    30: "while You extend Your hand to heal — and signs and wonders take place through the name of Your holy servant Jesus.\"",
    31: "And when they had prayed, the place where they had gathered together was shaken — and they were all filled with the Holy Spirit, and began to speak the word of God with boldness.",
    32: "And the congregation of those who believed were of one heart and soul — and not one of them claimed that anything belonging to him was his own. But all things were common property to them.",
    33: "And with great power the apostles were giving testimony to the resurrection of the Lord Jesus — and abundant grace was upon them all.",
    34: "For there was not a needy person among them. For all who were owners of land or houses would sell them, and bring the proceeds of the sales,",
    35: "and lay them at the apostles' feet — and they would be distributed to each, as any had need.",
    36: "Now Joseph, a Levite of Cyprian birth, who was also called Barnabas by the apostles (which translated means Son of Encouragement) —",
    37: "owned a tract of land. He sold it, brought the money, and laid it at the apostles' feet.",
}
ch5 = {
    1: "But a man named Ananias, with his wife Sapphira, sold a piece of property.",
    2: "And he kept back some of the price for himself, with his wife's full knowledge — and bringing a portion of it, he laid it at the apostles' feet.",
    3: "But Peter said, \"Ananias, why has Satan filled your heart to lie to the Holy Spirit, and to keep back some of the price of the land?",
    4: "While it remained unsold, did it not remain your own? And after it was sold, was it not under your control? Why is it that you have conceived this deed in your heart? You have not lied to men, but to God.\"",
    5: "And as he heard these words, Ananias fell down and breathed his last. And great fear came upon all who heard of it.",
    6: "And the young men got up and covered him up — and after carrying him out, they buried him.",
    7: "Now there elapsed an interval of about three hours — and his wife came in, not knowing what had happened.",
    8: "And Peter responded to her, \"Tell me whether you sold the land for such and such a price?\" And she said, \"Yes, that was the price.\"",
    9: "Then Peter said to her, \"Why is it that you have agreed together to put the Spirit of the Lord to the test? Behold, the feet of those who have buried your husband are at the door — and they will carry you out as well.\"",
    10: "And immediately she fell at his feet, and breathed her last. And the young men came in and found her dead — and they carried her out and buried her beside her husband.",
    11: "And great fear came over the whole church — and over all who heard of these things.",
    12: "At the hands of the apostles, many signs and wonders were taking place among the people. And they were all together in Solomon's portico.",
    13: "But none of the rest dared to associate with them — however, the people held them in high esteem.",
    14: "And all the more believers in the Lord — multitudes of men and women — were constantly added to their number.",
    15: "To such an extent that they even carried the sick out into the streets, and laid them on cots and pallets — so that when Peter came by, at least his shadow might fall on any one of them.",
    16: "And also the people from the cities in the vicinity of Jerusalem were coming together — bringing people who were sick or afflicted with unclean spirits, and they were all being healed.",
    17: "But the high priest rose up — along with all his associates (that is the sect of the Sadducees) — and they were filled with jealousy.",
    18: "And they laid hands on the apostles, and put them in a public jail.",
    19: "But during the night, an angel of the Lord opened the gates of the prison — and taking them out, he said,",
    20: "\"Go, stand and speak to the people in the temple the whole message of this Life.\"",
    21: "And upon hearing this, they entered into the temple about daybreak — and began to teach. Now when the high priest and his associates had come, they called the Council together — even all the Senate of the sons of Israel — and sent orders to the prison house for them to be brought.",
    22: "But the officers who came did not find them in the prison. And they returned and reported back,",
    23: "saying, \"We found the prison house locked quite securely, and the guards standing at the doors. But when we had opened up, we found no one inside.\"",
    24: "Now when the captain of the temple guard and the chief priests heard these words, they were greatly perplexed about them — as to what would come of this.",
    25: "But someone came and reported to them, \"Behold, the men whom you put in prison are standing in the temple and teaching the people!\"",
    26: "Then the captain went along with the officers and proceeded to bring them back without violence (for they were afraid of the people, that they might be stoned).",
    27: "And when they had brought them, they stood them before the Council. And the high priest questioned them,",
    28: "saying, \"We gave you strict orders not to continue teaching in this name. And behold, you have filled Jerusalem with your teaching — and intend to bring this man's blood upon us.\"",
    29: "But Peter and the apostles answered and said, \"We must obey God rather than men.",
    30: "The God of our fathers raised up Jesus, whom you had put to death by hanging Him on a cross.",
    31: "He is the one whom God exalted to His right hand as a Prince and a Savior — to grant repentance to Israel, and forgiveness of sins.",
    32: "And we are witnesses of these things — and so is the Holy Spirit, whom God has given to those who obey Him.\"",
    33: "But when they heard this, they were cut to the quick — and intended to kill them.",
    34: "But a Pharisee named Gamaliel, a teacher of the Law, respected by all the people, stood up in the Council — and gave orders to put the men outside for a short time.",
    35: "And he said to them, \"Men of Israel, take care what you propose to do with these men.",
    36: "For some time ago Theudas rose up, claiming to be somebody. And a group of about four hundred men joined up with him. But he was killed — and all who followed him were dispersed and came to nothing.",
    37: "After this man, Judas of Galilee rose up in the days of the census, and drew away some people after him. He too perished — and all those who followed him were scattered.",
    38: "And so in the present case, I say to you: stay away from these men, and let them alone. For if this plan or action is of men, it will be overthrown.",
    39: "But if it is of God, you will not be able to overthrow them — or else you may even be found fighting against God!\"",
    40: "And they took his advice. And after calling the apostles in, they flogged them and ordered them not to speak in the name of Jesus — and then released them.",
    41: "So they went on their way from the presence of the Council — rejoicing that they had been considered worthy to suffer shame for His name.",
    42: "And every day, in the temple and from house to house, they kept right on teaching and preaching Jesus as the Christ.",
}
ch6 = {
    1: "Now at this time, while the disciples were increasing in number, a complaint arose on the part of the Hellenistic Jews against the native Hebrews — because their widows were being overlooked in the daily serving of food.",
    2: "So the twelve summoned the congregation of the disciples, and said, \"It is not desirable for us to neglect the word of God in order to serve tables.",
    3: "Therefore, brothers, select from among you seven men of good reputation — full of the Spirit and of wisdom, whom we may put in charge of this task.",
    4: "But we will devote ourselves to prayer, and to the ministry of the word.\"",
    5: "And the statement found approval with the whole congregation. And they chose Stephen — a man full of faith and of the Holy Spirit — and Philip, Prochorus, Nicanor, Timon, Parmenas, and Nicolas, a proselyte from Antioch.",
    6: "And these they brought before the apostles. And after praying, they laid their hands on them.",
    7: "The word of God kept on spreading. And the number of the disciples continued to increase greatly in Jerusalem — and a great many of the priests were becoming obedient to the faith.",
    8: "And Stephen, full of grace and power, was performing great wonders and signs among the people.",
    9: "But some men from what was called the Synagogue of the Freedmen — including both Cyrenians and Alexandrians, and some from Cilicia and Asia — rose up and argued with Stephen.",
    10: "But they were unable to cope with the wisdom and the Spirit with which he was speaking.",
    11: "Then they secretly induced men to say, \"We have heard him speak blasphemous words against Moses and against God.\"",
    12: "And they stirred up the people, the elders, and the scribes — and they came up to him, and dragged him away, and brought him before the Council.",
    13: "And they put forward false witnesses who said, \"This man incessantly speaks against this holy place, and the Law.",
    14: "For we have heard him say that this Nazarene, Jesus, will destroy this place — and alter the customs which Moses handed down to us.\"",
    15: "And fixing their gaze on him, all who were sitting in the Council saw his face like the face of an angel.",
}
ch7 = {
    1: "And the high priest said, \"Are these things so?\"",
    2: "And he said: \"Hear me, brothers and fathers! The God of glory appeared to our father Abraham when he was in Mesopotamia, before he lived in Haran.",
    3: "And He said to him, 'Leave your country and your relatives, and come into the land that I will show you.'",
    4: "Then he departed from the land of the Chaldeans and settled in Haran. And from there, after his father died, God removed him into this country in which you are now living.",
    5: "But He gave him no inheritance in it — not even a foot of ground. And yet, even when he had no child, He promised that He would give it to him as a possession, and to his descendants after him.",
    6: "And God spoke to this effect: that his descendants would be aliens in a foreign land, and that they would be enslaved and mistreated for four hundred years.",
    7: "'And whatever nation to which they will be in bondage, I Myself will judge,' said God. 'And after that they will come out, and serve Me in this place.'",
    8: "And He gave him the covenant of circumcision. And so Abraham became the father of Isaac, and circumcised him on the eighth day. And Isaac became the father of Jacob, and Jacob, of the twelve patriarchs.",
    9: "And the patriarchs became jealous of Joseph, and sold him into Egypt. And yet God was with him,",
    10: "and rescued him from all his afflictions, and granted him favor and wisdom in the sight of Pharaoh, king of Egypt — and he made him governor over Egypt and all his household.",
    11: "Now a famine came over all Egypt and Canaan, with great affliction — and our fathers could find no food.",
    12: "But when Jacob heard that there was grain in Egypt, he sent our fathers there the first time.",
    13: "And on the second visit, Joseph made himself known to his brothers — and Joseph's family was disclosed to Pharaoh.",
    14: "Then Joseph sent word and invited Jacob his father, and all his relatives, to come to him — seventy-five persons in all.",
    15: "And Jacob went down to Egypt — and there he and our fathers died.",
    16: "And from there they were removed to Shechem, and laid in the tomb which Abraham had purchased for a sum of money from the sons of Hamor in Shechem.",
    17: "But as the time of the promise was approaching which God had assured to Abraham — the people increased and multiplied in Egypt,",
    18: "until there arose another king over Egypt who knew nothing about Joseph.",
    19: "It was he who took shrewd advantage of our race, and mistreated our fathers — so that they would expose their infants, and they would not survive.",
    20: "It was at this time that Moses was born — and he was lovely in the sight of God. And he was nurtured three months in his father's home.",
    21: "And after he had been set outside, Pharaoh's daughter took him away, and nurtured him as her own son.",
    22: "And Moses was educated in all the learning of the Egyptians — and he was a man of power in words and deeds.",
    23: "But when he was approaching the age of forty, it entered his mind to visit his brothers, the sons of Israel.",
    24: "And when he saw one of them being treated unjustly, he defended him — and took vengeance for the oppressed by striking down the Egyptian.",
    25: "And he supposed that his brothers understood that God was granting them deliverance through him — but they did not understand.",
    26: "And on the following day, he appeared to them as they were fighting together — and he tried to reconcile them in peace, saying, 'Men, you are brothers — why do you injure one another?'",
    27: "But the one who was injuring his neighbor pushed him away, saying, 'Who made you a ruler and judge over us?",
    28: "You do not mean to kill me as you killed the Egyptian yesterday, do you?'",
    29: "And at this remark, Moses fled — and became an alien in the land of Midian, where he became the father of two sons.",
    30: "And after forty years had passed, an angel appeared to him in the wilderness of Mount Sinai — in the flame of a burning thorn bush.",
    31: "When Moses saw it, he marveled at the sight. And as he approached to look more closely, there came the voice of the Lord:",
    32: "'I am the God of your fathers — the God of Abraham, and Isaac, and Jacob.' And Moses shook with fear, and would not venture to look.",
    33: "But the Lord said to him: 'Take off the sandals from your feet — for the place on which you are standing is holy ground.",
    34: "I have certainly seen the oppression of My people in Egypt, and have heard their groans — and I have come down to deliver them. Come now, and I will send you to Egypt.'",
    35: "This Moses, whom they disowned saying, 'Who made you a ruler and a judge?' — is the very one whom God sent as a ruler and a deliverer, with the help of the angel who appeared to him in the thorn bush.",
    36: "This man led them out — performing wonders and signs in the land of Egypt, and in the Red Sea, and in the wilderness for forty years.",
    37: "This is the Moses who said to the sons of Israel: 'God will raise up for you a prophet like me from your brothers.'",
    38: "This is the one who was in the congregation in the wilderness, together with the angel who was speaking to him on Mount Sinai — and who was with our fathers. And he received living oracles to pass on to you.",
    39: "And our fathers were unwilling to be obedient to him — but repudiated him, and in their hearts turned back to Egypt,",
    40: "saying to Aaron, 'Make for us gods who will go before us. For this Moses who led us out of the land of Egypt — we do not know what has happened to him.'",
    41: "And at that time they made a calf, and brought a sacrifice to the idol — and were rejoicing in the works of their hands.",
    42: "But God turned away, and delivered them up to serve the host of heaven — as it is written in the book of the prophets: 'It was not to Me that you offered victims and sacrifices forty years in the wilderness, was it, O house of Israel?",
    43: "You also took along the tabernacle of Moloch, and the star of the god Rompha — the images which you made to worship them. I also will remove you beyond Babylon.'",
    44: "Our fathers had the tabernacle of testimony in the wilderness — just as He who spoke to Moses directed him to make it according to the pattern which he had seen.",
    45: "And having received it in their turn, our fathers brought it in with Joshua upon dispossessing the nations whom God drove out before our fathers — until the time of David.",
    46: "And David found favor in God's sight, and asked that he might find a dwelling place for the God of Jacob.",
    47: "But it was Solomon who built a house for Him.",
    48: "However, the Most High does not dwell in houses made by human hands — as the prophet says:",
    49: "'Heaven is My throne, and earth is the footstool of My feet. What kind of house will you build for Me?' says the Lord. 'Or what place is there for My repose?",
    50: "Was it not My hand which made all these things?'",
    51: "You men who are stiff-necked, and uncircumcised in heart and ears — you are always resisting the Holy Spirit. You are doing just as your fathers did.",
    52: "Which one of the prophets did your fathers not persecute? They killed those who had previously announced the coming of the Righteous One — whose betrayers and murderers you have now become.",
    53: "You who received the law as ordained by angels — and yet did not keep it.\"",
    54: "Now when they heard this, they were cut to the quick — and they began gnashing their teeth at him.",
    55: "But being full of the Holy Spirit, he gazed intently into heaven and saw the glory of God — and Jesus standing at the right hand of God.",
    56: "And he said, \"Behold, I see the heavens opened up, and the Son of Man standing at the right hand of God.\"",
    57: "But they cried out with a loud voice, and covered their ears, and they rushed upon him with one impulse.",
    58: "And when they had driven him out of the city, they began stoning him — and the witnesses laid aside their robes at the feet of a young man named Saul.",
    59: "And they went on stoning Stephen, as he called on the Lord, and said, \"Lord Jesus, receive my spirit!\"",
    60: "And falling on his knees, he cried out with a loud voice, \"Lord, do not hold this sin against them!\" And having said this, he fell asleep.",
}
ch8 = {
    1: "And Saul was in hearty agreement with putting him to death. And on that day a great persecution arose against the church in Jerusalem — and they were all scattered throughout the regions of Judea and Samaria, except the apostles.",
    2: "And some devout men buried Stephen, and made loud lamentation over him.",
    3: "But Saul began ravaging the church — entering house after house, and dragging off men and women, he would put them in prison.",
    4: "Therefore, those who had been scattered went about preaching the word.",
    5: "And Philip went down to the city of Samaria, and began proclaiming Christ to them.",
    6: "And the multitudes with one accord were giving attention to what was said by Philip — as they heard and saw the signs which he was performing.",
    7: "For in the case of many who had unclean spirits, they were coming out of them shouting with a loud voice. And many who had been paralyzed and lame were healed.",
    8: "And there was much rejoicing in that city.",
    9: "Now there was a certain man named Simon, who formerly was practicing magic in the city — and astonishing the people of Samaria, claiming to be someone great.",
    10: "And they all, from smallest to greatest, were giving attention to him, saying, \"This man is what is called the Great Power of God.\"",
    11: "And they were giving him attention because he had for a long time astonished them with his magic arts.",
    12: "But when they believed Philip preaching the good news about the kingdom of God and the name of Jesus Christ, they were being baptized — both men and women.",
    13: "And even Simon himself believed. And after being baptized, he continued on with Philip — and as he observed signs and great miracles taking place, he was constantly amazed.",
    14: "Now when the apostles in Jerusalem heard that Samaria had received the word of God, they sent them Peter and John.",
    15: "Who came down and prayed for them — that they might receive the Holy Spirit.",
    16: "For He had not yet fallen upon any of them. They had simply been baptized in the name of the Lord Jesus.",
    17: "Then they began laying their hands on them — and they were receiving the Holy Spirit.",
    18: "Now when Simon saw that the Spirit was bestowed through the laying on of the apostles' hands, he offered them money,",
    19: "saying, \"Give this authority to me as well — so that everyone on whom I lay my hands may receive the Holy Spirit.\"",
    20: "But Peter said to him, \"May your silver perish with you — because you thought you could obtain the gift of God with money!",
    21: "You have no part or portion in this matter — for your heart is not right before God.",
    22: "Therefore repent of this wickedness of yours, and pray the Lord that, if possible, the intention of your heart may be forgiven you.",
    23: "For I see that you are in the gall of bitterness — and in the bondage of iniquity.\"",
    24: "But Simon answered and said, \"Pray to the Lord for me yourselves — so that nothing of what you have said may come upon me.\"",
    25: "And so, when they had solemnly testified and spoken the word of the Lord, they started back to Jerusalem — and were preaching the gospel to many villages of the Samaritans.",
    26: "But an angel of the Lord spoke to Philip, saying, \"Get up and go south to the road that descends from Jerusalem to Gaza.\" (This is a desert road.)",
    27: "And he got up and went. And there was an Ethiopian eunuch, a court official of Candace, queen of the Ethiopians — who was in charge of all her treasure. And he had come to Jerusalem to worship.",
    28: "And he was returning, and sitting in his chariot, and was reading the prophet Isaiah.",
    29: "And the Spirit said to Philip, \"Go up and join this chariot.\"",
    30: "And when Philip had run up, he heard him reading Isaiah the prophet, and said, \"Do you understand what you are reading?\"",
    31: "And he said, \"Well, how could I, unless someone guides me?\" And he invited Philip to come up and sit with him.",
    32: "Now the passage of Scripture which he was reading was this: \"He was led as a sheep to slaughter — and as a lamb before its shearer is silent, so He does not open His mouth.",
    33: "In humiliation His judgment was taken away. Who will relate His generation? For His life is removed from the earth.\"",
    34: "And the eunuch answered Philip and said, \"Please tell me — of whom does the prophet say this? Of himself, or of someone else?\"",
    35: "And Philip opened his mouth — and beginning from this Scripture, he preached Jesus to him.",
    36: "And as they went along the road they came to some water — and the eunuch said, \"Look! Water! What prevents me from being baptized?\"",
    37: "And Philip said, \"If you believe with all your heart, you may.\" And he answered and said, \"I believe that Jesus Christ is the Son of God.\"",
    38: "And he ordered the chariot to stop. And they both went down into the water — Philip as well as the eunuch — and he baptized him.",
    39: "And when they came up out of the water, the Spirit of the Lord snatched Philip away — and the eunuch saw him no more, but went on his way rejoicing.",
    40: "But Philip found himself at Azotus. And as he passed through, he kept preaching the gospel to all the cities — until he came to Caesarea.",
}
ch9 = {
    1: "Now Saul, still breathing threats and murder against the disciples of the Lord, went to the high priest,",
    2: "and asked for letters from him to the synagogues at Damascus — so that if he found any belonging to the Way, both men and women, he might bring them bound to Jerusalem.",
    3: "And as he was traveling, it happened that he was approaching Damascus, when suddenly a light from heaven flashed around him.",
    4: "And he fell to the ground, and heard a voice saying to him, \"Saul, Saul, why are you persecuting Me?\"",
    5: "And he said, \"Who are You, Lord?\" And He said, \"I am Jesus, whom you are persecuting.",
    6: "But get up and enter the city — and it will be told you what you must do.\"",
    7: "And the men who traveled with him stood speechless — hearing the voice, but seeing no one.",
    8: "And Saul got up from the ground — and though his eyes were open, he could see nothing. And leading him by the hand, they brought him into Damascus.",
    9: "And he was three days without sight — and neither ate nor drank.",
    10: "Now there was a certain disciple at Damascus, named Ananias. And the Lord said to him in a vision, \"Ananias.\" And he said, \"Behold, here am I, Lord.\"",
    11: "And the Lord said to him, \"Get up and go to the street called Straight — and inquire at the house of Judas for a man from Tarsus named Saul. For behold, he is praying.",
    12: "And he has seen in a vision a man named Ananias come in and lay his hands on him, so that he might regain his sight.\"",
    13: "But Ananias answered, \"Lord, I have heard from many about this man — how much harm he did to Your saints at Jerusalem.",
    14: "And here he has authority from the chief priests to bind all who call upon Your name.\"",
    15: "But the Lord said to him, \"Go — for he is a chosen instrument of Mine, to bear My name before the Gentiles, and kings, and the sons of Israel.",
    16: "For I will show him how much he must suffer for My name's sake.\"",
    17: "And Ananias departed and entered the house. And after laying his hands on him, said, \"Brother Saul, the Lord Jesus — who appeared to you on the road by which you were coming — has sent me, so that you may regain your sight, and be filled with the Holy Spirit.\"",
    18: "And immediately there fell from his eyes something like scales — and he regained his sight, and arose, and was baptized.",
    19: "And he took food, and was strengthened. Now for several days he was with the disciples who were at Damascus.",
    20: "And immediately he began to proclaim Jesus in the synagogues — saying, \"He is the Son of God.\"",
    21: "And all those hearing him continued to be amazed, and were saying, \"Is this not he who in Jerusalem destroyed those who called on this name — and who had come here for the purpose of bringing them bound before the chief priests?\"",
    22: "But Saul kept increasing in strength — and confounding the Jews who lived at Damascus, by proving that this Jesus is the Christ.",
    23: "And when many days had elapsed, the Jews plotted together to do away with him.",
    24: "But their plot became known to Saul. And they were also watching the gates day and night — so that they might put him to death.",
    25: "But his disciples took him by night, and let him down through an opening in the wall — lowering him in a basket.",
    26: "And when he had come to Jerusalem, he was trying to associate with the disciples — and they were all afraid of him, not believing that he was a disciple.",
    27: "But Barnabas took hold of him, and brought him to the apostles — and described to them how he had seen the Lord on the road, and that He had talked to him, and how at Damascus he had spoken out boldly in the name of Jesus.",
    28: "And he was with them, moving about freely in Jerusalem — speaking out boldly in the name of the Lord.",
    29: "And he was talking and arguing with the Hellenistic Jews — but they were attempting to put him to death.",
    30: "But when the brothers learned of it, they brought him down to Caesarea — and sent him away to Tarsus.",
    31: "So the church throughout all Judea and Galilee and Samaria enjoyed peace, being built up. And going on in the fear of the Lord and in the comfort of the Holy Spirit — it continued to increase.",
    32: "Now as Peter was traveling through all those parts, he came down also to the saints who lived at Lydda.",
    33: "And there he found a certain man named Aeneas, who had been bedridden eight years — for he was paralyzed.",
    34: "And Peter said to him, \"Aeneas, Jesus Christ heals you. Get up and make your bed.\" And immediately he got up.",
    35: "And all who lived at Lydda and Sharon saw him — and they turned to the Lord.",
    36: "Now in Joppa there was a certain disciple named Tabitha (which translated in Greek is called Dorcas — meaning Gazelle). This woman was abounding with deeds of kindness, and charity, which she continually did.",
    37: "And it happened at that time that she fell sick, and died. And when they had washed her body, they laid it in an upper room.",
    38: "And since Lydda was near Joppa, the disciples, having heard that Peter was there, sent two men to him, urging him, \"Do not delay to come to us.\"",
    39: "And Peter arose and went with them. And when he had come, they brought him into the upper room. And all the widows stood beside him, weeping, and showing all the tunics and garments that Dorcas used to make while she was with them.",
    40: "But Peter sent them all out — and kneeling down, he prayed. And turning to the body, he said, \"Tabitha, arise.\" And she opened her eyes — and when she saw Peter, she sat up.",
    41: "And he gave her his hand, and raised her up. And calling the saints and widows, he presented her alive.",
    42: "And it became known all over Joppa — and many believed in the Lord.",
    43: "And it came about that he stayed many days in Joppa with a certain tanner, Simon.",
}
CHAPTERS = {1: ch1, 2: ch2, 3: ch3, 4: ch4, 5: ch5, 6: ch6, 7: ch7, 8: ch8, 9: ch9}

def main():
    new_entries = {f"44_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Acts 1-9 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Acts 1-9 verses")

if __name__ == "__main__":
    main()
