"""MBT Matthew 22-28 — Final week, passion, resurrection. 343 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch22 = {
    1: "And Jesus answered and spoke to them again in parables, saying,",
    2: "\"The kingdom of heaven may be compared to a king, who gave a wedding feast for his son.",
    3: "And he sent out his slaves to call those who had been invited to the wedding feast — and they were unwilling to come.",
    4: "Again he sent out other slaves saying, 'Tell those who have been invited, \"Behold, I have prepared my dinner. My oxen and my fattened livestock are all butchered, and everything is ready. Come to the wedding feast.\"'",
    5: "But they paid no attention and went their way — one to his own farm, another to his business.",
    6: "And the rest seized his slaves and mistreated them and killed them.",
    7: "But the king was enraged — and he sent his armies, and destroyed those murderers, and set their city on fire.",
    8: "Then he said to his slaves, 'The wedding is ready, but those who were invited were not worthy.",
    9: "Go therefore to the main highways, and as many as you find there, invite to the wedding feast.'",
    10: "And those slaves went out into the streets, and gathered together all they found, both evil and good — and the wedding hall was filled with dinner guests.",
    11: "But when the king came in to look over the dinner guests, he saw there a man not dressed in wedding clothes.",
    12: "And he said to him, 'Friend, how did you come in here without wedding clothes?' And he was speechless.",
    13: "Then the king said to the servants, 'Bind him hand and foot, and cast him into the outer darkness. In that place there shall be weeping and gnashing of teeth.'",
    14: "For many are called, but few are chosen.\"",
    15: "Then the Pharisees went and counseled together how they might trap Him in what He said.",
    16: "And they sent their disciples to Him, along with the Herodians, saying, \"Teacher, we know that You are truthful and teach the way of God in truth — and defer to no one. For You are not partial to any.",
    17: "Tell us therefore, what do You think? Is it lawful to give a poll-tax to Caesar, or not?\"",
    18: "But Jesus perceived their malice, and said, \"Why are you testing Me, you hypocrites?",
    19: "Show Me the coin used for the poll-tax.\" And they brought Him a denarius.",
    20: "And He said to them, \"Whose likeness and inscription is this?\"",
    21: "They said to Him, \"Caesar's.\" Then He said to them, \"Then render to Caesar the things that are Caesar's — and to God the things that are God's.\"",
    22: "And hearing this, they marveled. And leaving Him, they went away.",
    23: "On that day some Sadducees (who say there is no resurrection) came to Him and questioned Him,",
    24: "saying, \"Teacher, Moses said, 'If a man dies, having no children, his brother as next of kin shall marry his wife, and raise up an offspring to his brother.'",
    25: "Now there were seven brothers with us. And the first married and died, and having no offspring left his wife to his brother.",
    26: "So also the second, and the third, down to the seventh.",
    27: "And last of all, the woman died.",
    28: "In the resurrection therefore whose wife of the seven shall she be? For they all had her.\"",
    29: "But Jesus answered and said to them, \"You are mistaken — not understanding the Scriptures, or the power of God.",
    30: "For in the resurrection they neither marry, nor are given in marriage — but are like angels in heaven.",
    31: "But regarding the resurrection of the dead, have you not read what was spoken to you by God, saying,",
    32: "'I am the God of Abraham, and the God of Isaac, and the God of Jacob'? He is not the God of the dead — but of the living.\"",
    33: "And when the multitudes heard this, they were astonished at His teaching.",
    34: "But when the Pharisees heard that He had put the Sadducees to silence, they gathered themselves together.",
    35: "And one of them, a lawyer, asked Him a question, testing Him,",
    36: "\"Teacher, which is the great commandment in the Law?\"",
    37: "And He said to him, \"'You shall love the Lord your God with all your heart, and with all your soul, and with all your mind.'",
    38: "This is the great and foremost commandment.",
    39: "The second is like it — 'You shall love your neighbor as yourself.'",
    40: "On these two commandments depend the whole Law and the Prophets.\"",
    41: "Now while the Pharisees were gathered together, Jesus asked them a question,",
    42: "saying, \"What do you think about the Christ? Whose son is He?\" They said to Him, \"The son of David.\"",
    43: "He said to them, \"Then how does David in the Spirit call Him 'Lord,' saying,",
    44: "'The Lord said to my Lord, \"Sit at My right hand, until I put Your enemies beneath Your feet\"'?",
    45: "If David then calls Him 'Lord,' how is He his son?\"",
    46: "And no one was able to answer Him a word. Nor did anyone dare from that day on to ask Him another question.",
}
ch23 = {
    1: "Then Jesus spoke to the multitudes and to His disciples,",
    2: "saying, \"The scribes and the Pharisees have seated themselves in the chair of Moses.",
    3: "Therefore all that they tell you, do and observe — but do not do according to their deeds. For they say things, and do not do them.",
    4: "And they tie up heavy loads, and lay them on men's shoulders — but they themselves are unwilling to move them with so much as a finger.",
    5: "But they do all their deeds to be noticed by men. For they broaden their phylacteries, and lengthen the tassels of their garments.",
    6: "And they love the place of honor at banquets, and the chief seats in the synagogues,",
    7: "and respectful greetings in the market places, and being called by men, 'Rabbi.'",
    8: "But do not be called Rabbi — for One is your Teacher, and you are all brothers.",
    9: "And do not call anyone on earth your father — for One is your Father, He who is in heaven.",
    10: "And do not be called leaders — for One is your Leader, the Christ.",
    11: "But the greatest among you shall be your servant.",
    12: "And whoever exalts himself shall be humbled — and whoever humbles himself shall be exalted.",
    13: "But woe to you, scribes and Pharisees, hypocrites — because you shut off the kingdom of heaven from men. For you do not enter in yourselves, nor do you allow those who are entering to go in.",
    14: "(Woe to you, scribes and Pharisees, hypocrites — because you devour widows' houses, even while for a pretense you make long prayers. Therefore you shall receive greater condemnation.)",
    15: "Woe to you, scribes and Pharisees, hypocrites — because you travel about on sea and land to make one proselyte. And when he becomes one, you make him twice as much a son of hell as yourselves.",
    16: "Woe to you, blind guides, who say, 'Whoever swears by the temple, that is nothing. But whoever swears by the gold of the temple, he is obligated.'",
    17: "You fools and blind men — which is more important, the gold, or the temple that sanctified the gold?",
    18: "And, 'Whoever swears by the altar, that is nothing. But whoever swears by the offering upon it, he is obligated.'",
    19: "You blind men — which is more important, the offering, or the altar that sanctifies the offering?",
    20: "Therefore he who swears by the altar, swears both by the altar and by everything on it.",
    21: "And he who swears by the temple, swears both by the temple and by Him who dwells within it.",
    22: "And he who swears by heaven, swears both by the throne of God and by Him who sits upon it.",
    23: "Woe to you, scribes and Pharisees, hypocrites — because you pay tithe of mint and dill and cummin, and have neglected the weightier provisions of the Law: justice and mercy and faithfulness. But these are the things you should have done — without neglecting the others.",
    24: "You blind guides — who strain out a gnat and swallow a camel!",
    25: "Woe to you, scribes and Pharisees, hypocrites — because you clean the outside of the cup and of the dish, but inside they are full of robbery and self-indulgence.",
    26: "You blind Pharisee — first clean the inside of the cup and of the dish, so that the outside of it may become clean also.",
    27: "Woe to you, scribes and Pharisees, hypocrites — because you are like whitewashed tombs which on the outside appear beautiful, but inside they are full of dead men's bones and all uncleanness.",
    28: "Even so you too outwardly appear righteous to men — but inwardly you are full of hypocrisy and lawlessness.",
    29: "Woe to you, scribes and Pharisees, hypocrites — because you build the tombs of the prophets and adorn the monuments of the righteous,",
    30: "and say, 'If we had been living in the days of our fathers, we would not have been partners with them in shedding the blood of the prophets.'",
    31: "Consequently you bear witness against yourselves, that you are sons of those who murdered the prophets.",
    32: "Fill up then the measure of the guilt of your fathers.",
    33: "You serpents, you brood of vipers — how shall you escape the sentence of hell?",
    34: "Therefore, behold, I am sending you prophets and wise men and scribes — some of them you will kill and crucify, and some of them you will scourge in your synagogues, and persecute from city to city.",
    35: "That upon you may fall the guilt of all the righteous blood shed on earth, from the blood of righteous Abel to the blood of Zechariah, the son of Berechiah, whom you murdered between the temple and the altar.",
    36: "Truly I say to you, all these things shall come upon this generation.",
    37: "O Jerusalem, Jerusalem — who kills the prophets and stones those who are sent to her! How often I wanted to gather your children together, the way a hen gathers her chicks under her wings — and you were unwilling.",
    38: "Behold, your house is being left to you desolate.",
    39: "For I say to you, from now on you shall not see Me until you say, 'Blessed is He who comes in the name of the Lord!'\"",
}
ch24 = {
    1: "And Jesus came out from the temple and was going away — when His disciples came up to point out the temple buildings to Him.",
    2: "And He answered and said to them, \"Do you not see all these things? Truly I say to you, not one stone here shall be left upon another, which will not be torn down.\"",
    3: "And as He was sitting on the Mount of Olives, the disciples came to Him privately, saying, \"Tell us, when will these things be? And what will be the sign of Your coming, and of the end of the age?\"",
    4: "And Jesus answered and said to them, \"See to it that no one misleads you.",
    5: "For many will come in My name, saying, 'I am the Christ' — and will mislead many.",
    6: "And you will be hearing of wars and rumors of wars. See that you are not frightened — for those things must take place. But that is not yet the end.",
    7: "For nation will rise against nation, and kingdom against kingdom — and in various places there will be famines and earthquakes.",
    8: "But all these things are merely the beginning of birth pangs.",
    9: "Then they will deliver you up to tribulation, and will kill you. And you will be hated by all nations on account of My name.",
    10: "And at that time many will fall away and will deliver up one another — and hate one another.",
    11: "And many false prophets will arise, and will mislead many.",
    12: "And because lawlessness is increased, most people's love will grow cold.",
    13: "But the one who endures to the end, he shall be saved.",
    14: "And this gospel of the kingdom shall be preached in the whole world for a witness to all the nations — and then the end shall come.",
    15: "Therefore when you see the abomination of desolation, which was spoken of through Daniel the prophet, standing in the holy place — let the reader understand —",
    16: "then let those who are in Judea flee to the mountains.",
    17: "Let him who is on the housetop not go down to get the things out that are in his house.",
    18: "And let him who is in the field not turn back to get his cloak.",
    19: "But woe to those who are with child, and to those who are nursing babies in those days!",
    20: "But pray that your flight may not be in the winter — or on a Sabbath.",
    21: "For then there will be a great tribulation, such as has not occurred since the beginning of the world until now — nor ever shall.",
    22: "And unless those days had been cut short, no life would have been saved. But for the sake of the elect those days shall be cut short.",
    23: "Then if anyone says to you, 'Behold, here is the Christ,' or, 'There He is' — do not believe him.",
    24: "For false Christs and false prophets will arise and will show great signs and wonders — so as to mislead, if possible, even the elect.",
    25: "Behold, I have told you in advance.",
    26: "If therefore they say to you, 'Behold, He is in the wilderness' — do not go forth, or, 'Behold, He is in the inner rooms' — do not believe them.",
    27: "For just as the lightning comes from the east, and flashes even to the west, so shall the coming of the Son of Man be.",
    28: "Wherever the corpse is, there the vultures will gather.",
    29: "But immediately after the tribulation of those days the sun will be darkened, and the moon will not give its light, and the stars will fall from the sky, and the powers of the heavens will be shaken.",
    30: "And then the sign of the Son of Man will appear in the sky. And then all the tribes of the earth will mourn. And they will see the Son of Man coming on the clouds of the sky with power and great glory.",
    31: "And He will send forth His angels with a great trumpet — and they will gather together His elect from the four winds, from one end of the sky to the other.",
    32: "Now learn the parable from the fig tree. When its branch has already become tender, and puts forth its leaves, you know that summer is near.",
    33: "Even so you too, when you see all these things, recognize that He is near — right at the door.",
    34: "Truly I say to you, this generation will not pass away until all these things take place.",
    35: "Heaven and earth will pass away — but My words shall not pass away.",
    36: "But of that day and hour no one knows — not even the angels of heaven, nor the Son, but the Father alone.",
    37: "For the coming of the Son of Man will be just like the days of Noah.",
    38: "For as in those days which were before the flood, they were eating and drinking, marrying and giving in marriage, until the day that Noah entered the ark.",
    39: "And they did not understand until the flood came and took them all away. So shall the coming of the Son of Man be.",
    40: "Then there shall be two men in the field — one will be taken, and one will be left.",
    41: "Two women will be grinding at the mill — one will be taken, and one will be left.",
    42: "Therefore be on the alert — for you do not know which day your Lord is coming.",
    43: "But be sure of this — that if the head of the house had known at what time of the night the thief was coming, he would have been on the alert, and would not have allowed his house to be broken into.",
    44: "For this reason you be ready too — for the Son of Man is coming at an hour when you do not think He will.",
    45: "Who then is the faithful and sensible slave whom his master put in charge of his household to give them their food at the proper time?",
    46: "Blessed is that slave whom his master finds so doing when he comes.",
    47: "Truly I say to you, that he will put him in charge of all his possessions.",
    48: "But if that evil slave says in his heart, 'My master is not coming for a long time,'",
    49: "and shall begin to beat his fellow slaves and eat and drink with drunkards,",
    50: "the master of that slave will come on a day when he does not expect him, and at an hour which he does not know,",
    51: "and shall cut him in pieces, and assign him a place with the hypocrites. In that place there shall be weeping and gnashing of teeth.",
}
ch25 = {
    1: "Then the kingdom of heaven will be comparable to ten virgins, who took their lamps, and went out to meet the bridegroom.",
    2: "And five of them were foolish, and five were prudent.",
    3: "For when the foolish took their lamps, they took no oil with them.",
    4: "But the prudent took oil in flasks along with their lamps.",
    5: "Now while the bridegroom was delaying, they all got drowsy and began to sleep.",
    6: "But at midnight there was a shout, 'Behold, the bridegroom! Come out to meet him!'",
    7: "Then all those virgins rose, and trimmed their lamps.",
    8: "And the foolish said to the prudent, 'Give us some of your oil — for our lamps are going out.'",
    9: "But the prudent answered, saying, 'No, there will not be enough for us and you too. Go instead to the dealers and buy some for yourselves.'",
    10: "And while they were going away to make the purchase, the bridegroom came. And those who were ready went in with him to the wedding feast. And the door was shut.",
    11: "And later the other virgins also came, saying, 'Lord, lord, open up for us.'",
    12: "But he answered and said, 'Truly I say to you, I do not know you.'",
    13: "Be on the alert then — for you do not know the day nor the hour.",
    14: "For it is just like a man about to go on a journey, who called his own slaves, and entrusted his possessions to them.",
    15: "And to one he gave five talents, to another, two, and to another, one — each according to his own ability. And he went on his journey.",
    16: "Immediately the one who had received the five talents went and traded with them, and gained five more talents.",
    17: "In the same manner the one who had received the two talents gained two more.",
    18: "But he who received the one talent went away and dug in the ground, and hid his master's money.",
    19: "Now after a long time the master of those slaves came and settled accounts with them.",
    20: "And the one who had received the five talents came up and brought five more talents, saying, 'Master, you entrusted five talents to me. See, I have gained five more talents.'",
    21: "His master said to him, 'Well done, good and faithful slave. You were faithful with a few things — I will put you in charge of many things. Enter into the joy of your master.'",
    22: "The one also who had received the two talents came up and said, 'Master, you entrusted two talents to me. See, I have gained two more talents.'",
    23: "His master said to him, 'Well done, good and faithful slave. You were faithful with a few things — I will put you in charge of many things. Enter into the joy of your master.'",
    24: "And the one also who had received the one talent came up and said, 'Master, I knew you to be a hard man, reaping where you did not sow, and gathering where you scattered no seed.",
    25: "And I was afraid, and went away and hid your talent in the ground. See, you have what is yours.'",
    26: "But his master answered and said to him, 'You wicked, lazy slave. You knew that I reap where I did not sow, and gather where I scattered no seed?",
    27: "Then you ought to have put my money in the bank, and on my arrival I would have received my money back with interest.",
    28: "Therefore take away the talent from him, and give it to the one who has the ten talents.'",
    29: "For to everyone who has shall more be given, and he shall have an abundance. But from the one who does not have, even what he does have shall be taken away.",
    30: "And cast out the worthless slave into the outer darkness. In that place there shall be weeping and gnashing of teeth.",
    31: "But when the Son of Man comes in His glory, and all the angels with Him, then He will sit on His glorious throne.",
    32: "And all the nations will be gathered before Him. And He will separate them from one another, as the shepherd separates the sheep from the goats.",
    33: "And He will put the sheep on His right, and the goats on the left.",
    34: "Then the King will say to those on His right, 'Come, you who are blessed of My Father — inherit the kingdom prepared for you from the foundation of the world.",
    35: "For I was hungry, and you gave Me something to eat. I was thirsty, and you gave Me drink. I was a stranger, and you invited Me in.",
    36: "I was naked, and you clothed Me. I was sick, and you visited Me. I was in prison, and you came to Me.'",
    37: "Then the righteous will answer Him, saying, 'Lord, when did we see You hungry, and feed You — or thirsty, and give You drink?",
    38: "And when did we see You a stranger, and invite You in — or naked, and clothe You?",
    39: "And when did we see You sick, or in prison, and come to You?'",
    40: "And the King will answer and say to them, 'Truly I say to you, to the extent that you did it to one of these brothers of Mine, even the least of them — you did it to Me.'",
    41: "Then He will also say to those on His left, 'Depart from Me, accursed ones, into the eternal fire which has been prepared for the devil and his angels.",
    42: "For I was hungry, and you gave Me nothing to eat. I was thirsty, and you gave Me nothing to drink.",
    43: "I was a stranger, and you did not invite Me in — naked, and you did not clothe Me — sick, and in prison, and you did not visit Me.'",
    44: "Then they themselves also will answer, saying, 'Lord, when did we see You hungry, or thirsty, or a stranger, or naked, or sick, or in prison, and did not take care of You?'",
    45: "Then He will answer them, saying, 'Truly I say to you, to the extent that you did not do it to one of the least of these — you did not do it to Me.'",
    46: "And these will go away into eternal punishment — but the righteous into eternal life.\"",
}
ch26 = {
    1: "And it came about that when Jesus had finished all these words, He said to His disciples,",
    2: "\"You know that after two days the Passover is coming, and the Son of Man is to be delivered up for crucifixion.\"",
    3: "Then the chief priests and the elders of the people were gathered together in the court of the high priest, named Caiaphas.",
    4: "And they plotted together to seize Jesus by stealth, and kill Him.",
    5: "But they were saying, \"Not during the festival — lest a riot occur among the people.\"",
    6: "Now when Jesus was in Bethany, at the home of Simon the leper,",
    7: "a woman came to Him with an alabaster vial of very costly perfume, and she poured it upon His head as He reclined at the table.",
    8: "But the disciples were indignant when they saw this, and said, \"Why this waste?",
    9: "For this perfume might have been sold for a high price, and the money given to the poor.\"",
    10: "But Jesus, aware of this, said to them, \"Why do you bother the woman? For she has done a good deed to Me.",
    11: "For the poor you have with you always — but you do not always have Me.",
    12: "For when she poured this perfume upon My body, she did it to prepare Me for burial.",
    13: "Truly I say to you, wherever this gospel is preached in the whole world, what this woman has done shall also be spoken of in memory of her.\"",
    14: "Then one of the twelve, named Judas Iscariot, went to the chief priests,",
    15: "and said, \"What are you willing to give me to deliver Him up to you?\" And they weighed out to him thirty pieces of silver.",
    16: "And from then on he began looking for a good opportunity to betray Him.",
    17: "Now on the first day of Unleavened Bread the disciples came to Jesus, saying, \"Where do You want us to prepare for You to eat the Passover?\"",
    18: "And He said, \"Go into the city to a certain man, and say to him, 'The Teacher says, \"My time is at hand. I am to keep the Passover at your house with My disciples.\"'\"",
    19: "And the disciples did as Jesus had directed them. And they prepared the Passover.",
    20: "Now when evening had come, He was reclining at the table with the twelve disciples.",
    21: "And as they were eating, He said, \"Truly I say to you that one of you will betray Me.\"",
    22: "And being deeply grieved, they each one began to say to Him, \"Surely not I, Lord?\"",
    23: "And He answered and said, \"He who dipped his hand with Me in the bowl — he will betray Me.",
    24: "The Son of Man is to go, just as it is written of Him. But woe to that man by whom the Son of Man is betrayed! It would have been good for that man if he had not been born.\"",
    25: "And Judas, who was betraying Him, answered and said, \"Surely it is not I, Rabbi?\" He said to him, \"You have said it yourself.\"",
    26: "And while they were eating, Jesus took some bread, and after a blessing, He broke it and gave it to the disciples, and said, \"Take, eat — this is My body.\"",
    27: "And when He had taken a cup and given thanks, He gave it to them, saying, \"Drink from it, all of you.",
    28: "For this is My blood of the covenant, which is poured out for many for forgiveness of sins.",
    29: "But I say to you, I will not drink of this fruit of the vine from now on until that day when I drink it new with you in My Father's kingdom.\"",
    30: "And after singing a hymn, they went out to the Mount of Olives.",
    31: "Then Jesus said to them, \"You will all fall away because of Me this night. For it is written, 'I will strike down the shepherd, and the sheep of the flock shall be scattered.'",
    32: "But after I have been raised, I will go before you to Galilee.\"",
    33: "But Peter answered and said to Him, \"Even though all may fall away because of You, I will never fall away.\"",
    34: "Jesus said to him, \"Truly I say to you that this very night, before a rooster crows, you shall deny Me three times.\"",
    35: "Peter said to Him, \"Even if I have to die with You, I will not deny You.\" And all the disciples said the same too.",
    36: "Then Jesus came with them to a place called Gethsemane, and said to His disciples, \"Sit here while I go over there and pray.\"",
    37: "And He took with Him Peter and the two sons of Zebedee, and began to be grieved and distressed.",
    38: "Then He said to them, \"My soul is deeply grieved, to the point of death. Remain here, and keep watch with Me.\"",
    39: "And He went a little beyond them, and fell on His face and prayed, saying, \"My Father, if it is possible, let this cup pass from Me. Yet not as I will, but as You will.\"",
    40: "And He came to the disciples and found them sleeping, and said to Peter, \"So, you men could not keep watch with Me for one hour?",
    41: "Keep watching and praying, that you may not enter into temptation. The spirit is willing, but the flesh is weak.\"",
    42: "He went away again a second time, and prayed, saying, \"My Father, if this cannot pass away unless I drink it, Your will be done.\"",
    43: "And again He came and found them sleeping — for their eyes were heavy.",
    44: "And He left them again, and went away and prayed a third time, saying the same thing once more.",
    45: "Then He came to the disciples, and said to them, \"Are you still sleeping and resting? Behold, the hour is at hand, and the Son of Man is being betrayed into the hands of sinners.",
    46: "Arise — let us be going. Behold, the one who betrays Me is at hand!\"",
    47: "And while He was still speaking, behold, Judas, one of the twelve, came up — accompanied by a great multitude with swords and clubs, from the chief priests and elders of the people.",
    48: "Now he who was betraying Him gave them a sign, saying, \"Whomever I shall kiss, He is the one — seize Him.\"",
    49: "And immediately he went to Jesus and said, \"Hail, Rabbi!\" and kissed Him.",
    50: "And Jesus said to him, \"Friend, do what you have come for.\" Then they came and laid hands on Jesus, and seized Him.",
    51: "And behold, one of those who were with Jesus reached and drew out his sword, and struck the slave of the high priest, and cut off his ear.",
    52: "Then Jesus said to him, \"Put your sword back into its place. For all those who take up the sword shall perish by the sword.",
    53: "Or do you think that I cannot appeal to My Father, and He will at once put at My disposal more than twelve legions of angels?",
    54: "How then shall the Scriptures be fulfilled, that it must happen this way?\"",
    55: "At that time Jesus said to the multitudes, \"Have you come out with swords and clubs to arrest Me as against a robber? Every day I used to sit in the temple teaching, and you did not seize Me.",
    56: "But all this has taken place that the Scriptures of the prophets may be fulfilled.\" Then all the disciples left Him and fled.",
    57: "And those who had seized Jesus led Him away to Caiaphas, the high priest, where the scribes and the elders were gathered together.",
    58: "But Peter also followed Him at a distance as far as the courtyard of the high priest, and entered in, and sat down with the officers to see the outcome.",
    59: "Now the chief priests and the whole Council kept trying to obtain false testimony against Jesus, in order that they might put Him to death.",
    60: "And they did not find any, even though many false witnesses came forward. But later on two came forward,",
    61: "and said, \"This man stated, 'I am able to destroy the temple of God, and to rebuild it in three days.'\"",
    62: "And the high priest stood up and said to Him, \"Do You make no answer? What is it that these men are testifying against You?\"",
    63: "But Jesus kept silent. And the high priest said to Him, \"I adjure You by the living God, that You tell us whether You are the Christ, the Son of God.\"",
    64: "Jesus said to him, \"You have said it yourself. Nevertheless I tell you, hereafter you shall see the Son of Man sitting at the right hand of Power, and coming on the clouds of heaven.\"",
    65: "Then the high priest tore his robes, saying, \"He has blasphemed! What further need do we have of witnesses? Behold, you have now heard the blasphemy.",
    66: "What do you think?\" They answered and said, \"He is deserving of death!\"",
    67: "Then they spat in His face and beat Him with their fists. And others slapped Him,",
    68: "and said, \"Prophesy to us, You Christ — who is the one who hit You?\"",
    69: "Now Peter was sitting outside in the courtyard. And a certain servant-girl came to him and said, \"You too were with Jesus the Galilean.\"",
    70: "But he denied it before them all, saying, \"I do not know what you are talking about.\"",
    71: "And when he had gone out to the gateway, another servant-girl saw him and said to those who were there, \"This man was with Jesus of Nazareth.\"",
    72: "And again he denied it with an oath, \"I do not know the man.\"",
    73: "And a little later the bystanders came up and said to Peter, \"Surely you too are one of them. For the way you talk gives you away.\"",
    74: "Then he began to curse and swear, \"I do not know the man!\" And immediately a rooster crowed.",
    75: "And Peter remembered the word which Jesus had said, \"Before a rooster crows, you will deny Me three times.\" And he went out and wept bitterly.",
}
ch27 = {
    1: "Now when morning had come, all the chief priests and the elders of the people took counsel against Jesus to put Him to death.",
    2: "And they bound Him, and led Him away, and delivered Him up to Pilate the governor.",
    3: "Then when Judas, who had betrayed Him, saw that He had been condemned, he felt remorse — and returned the thirty pieces of silver to the chief priests and elders,",
    4: "saying, \"I have sinned by betraying innocent blood.\" But they said, \"What is that to us? See to that yourself!\"",
    5: "And he threw the pieces of silver into the sanctuary and departed. And he went away and hanged himself.",
    6: "And the chief priests took the pieces of silver and said, \"It is not lawful to put them into the temple treasury — since it is the price of blood.\"",
    7: "And they counseled together and with the money bought the Potter's Field as a burial place for strangers.",
    8: "For this reason that field has been called the Field of Blood to this day.",
    9: "Then that which was spoken through Jeremiah the prophet was fulfilled, saying, \"And they took the thirty pieces of silver, the price of the One whose price had been set by the sons of Israel.",
    10: "And they gave them for the Potter's Field — as the Lord directed me.\"",
    11: "Now Jesus stood before the governor, and the governor questioned Him, saying, \"Are You the King of the Jews?\" And Jesus said to him, \"It is as you say.\"",
    12: "And while He was being accused by the chief priests and elders, He made no answer.",
    13: "Then Pilate said to Him, \"Do You not hear how many things they testify against You?\"",
    14: "And He did not answer him with regard to even a single charge — so the governor was quite amazed.",
    15: "Now at the feast the governor was accustomed to release for the multitude any one prisoner whom they wanted.",
    16: "And they were holding at that time a notorious prisoner, called Barabbas.",
    17: "When therefore they were gathered together, Pilate said to them, \"Whom do you want me to release for you? Barabbas, or Jesus who is called Christ?\"",
    18: "For he knew that because of envy they had delivered Him up.",
    19: "And while he was sitting on the judgment seat, his wife sent to him, saying, \"Have nothing to do with that righteous Man. For last night I suffered greatly in a dream because of Him.\"",
    20: "But the chief priests and the elders persuaded the multitudes to ask for Barabbas, and to put Jesus to death.",
    21: "But the governor answered and said to them, \"Which of the two do you want me to release for you?\" And they said, \"Barabbas.\"",
    22: "Pilate said to them, \"Then what shall I do with Jesus who is called Christ?\" They all said, \"Let Him be crucified!\"",
    23: "And he said, \"Why, what evil has He done?\" But they kept shouting all the more, saying, \"Let Him be crucified!\"",
    24: "And when Pilate saw that he was accomplishing nothing, but rather that a riot was starting, he took water and washed his hands in front of the multitude, saying, \"I am innocent of this Man's blood — see to that yourselves.\"",
    25: "And all the people answered and said, \"His blood be on us and on our children!\"",
    26: "Then he released Barabbas for them — but Jesus he scourged and delivered up to be crucified.",
    27: "Then the soldiers of the governor took Jesus into the Praetorium, and gathered the whole Roman cohort around Him.",
    28: "And they stripped Him, and put a scarlet robe on Him.",
    29: "And after weaving a crown of thorns, they put it on His head — and a reed in His right hand. And kneeling down before Him, they mocked Him, saying, \"Hail, King of the Jews!\"",
    30: "And they spat on Him, and took the reed and began to beat Him on the head.",
    31: "And after they had mocked Him, they took His robe off and put His garments on Him, and led Him away to crucify Him.",
    32: "And as they were coming out, they found a man of Cyrene named Simon, whom they pressed into service to bear His cross.",
    33: "And when they had come to a place called Golgotha, which means Place of a Skull,",
    34: "they gave Him wine to drink mingled with gall. And after tasting it, He was unwilling to drink.",
    35: "And when they had crucified Him, they divided up His garments among themselves by casting lots.",
    36: "And sitting down, they began to keep watch over Him there.",
    37: "And they put up above His head the charge against Him which read, \"This is Jesus the King of the Jews.\"",
    38: "At that time two robbers were crucified with Him — one on the right and one on the left.",
    39: "And those passing by were hurling abuse at Him, wagging their heads,",
    40: "and saying, \"You who are going to destroy the temple and rebuild it in three days, save Yourself! If You are the Son of God, come down from the cross!\"",
    41: "In the same way the chief priests also, along with the scribes and elders, were mocking Him and saying,",
    42: "\"He saved others — He cannot save Himself. He is the King of Israel — let Him now come down from the cross, and we shall believe in Him.",
    43: "He trusts in God — let Him deliver Him now, if He takes pleasure in Him. For He said, 'I am the Son of God.'\"",
    44: "And the robbers also who had been crucified with Him were casting the same insult at Him.",
    45: "Now from the sixth hour darkness fell upon all the land until the ninth hour.",
    46: "And about the ninth hour Jesus cried out with a loud voice, saying, \"Eli, Eli, lama sabachthani?\" — that is, \"My God, My God, why have You forsaken Me?\"",
    47: "And some of those who were standing there, when they heard it, began saying, \"This man is calling for Elijah.\"",
    48: "And immediately one of them ran, and taking a sponge, he filled it with sour wine, and put it on a reed, and gave Him a drink.",
    49: "But the rest of them said, \"Let us see whether Elijah will come to save Him.\"",
    50: "And Jesus cried out again with a loud voice, and yielded up His spirit.",
    51: "And behold, the veil of the temple was torn in two from top to bottom. And the earth shook — and the rocks were split.",
    52: "And the tombs were opened — and many bodies of the saints who had fallen asleep were raised.",
    53: "And coming out of the tombs after His resurrection they entered the holy city and appeared to many.",
    54: "Now the centurion, and those who were with him keeping guard over Jesus, when they saw the earthquake and the things that were happening, became very frightened, and said, \"Truly this was the Son of God!\"",
    55: "And many women were there looking on from a distance, who had followed Jesus from Galilee, ministering to Him.",
    56: "Among them was Mary Magdalene, along with Mary the mother of James and Joseph, and the mother of the sons of Zebedee.",
    57: "And when it was evening, there came a rich man from Arimathea, named Joseph, who himself had also become a disciple of Jesus.",
    58: "This man went to Pilate and asked for the body of Jesus. Then Pilate ordered it to be given over to him.",
    59: "And Joseph took the body and wrapped it in a clean linen cloth,",
    60: "and laid it in his own new tomb, which he had hewn out in the rock. And he rolled a large stone against the entrance of the tomb and went away.",
    61: "And Mary Magdalene was there, and the other Mary, sitting opposite the grave.",
    62: "Now on the next day, which is the one after the preparation, the chief priests and the Pharisees gathered together with Pilate,",
    63: "and said, \"Sir, we remember that when He was still alive that deceiver said, 'After three days I am to rise again.'",
    64: "Therefore, give orders for the grave to be made secure until the third day — lest the disciples come and steal Him away, and say to the people, 'He has risen from the dead.' And the last deception will be worse than the first.\"",
    65: "Pilate said to them, \"You have a guard — go, make it as secure as you know how.\"",
    66: "And they went and made the grave secure, and along with the guard they set a seal on the stone.",
}
ch28 = {
    1: "Now after the Sabbath, as it began to dawn toward the first day of the week, Mary Magdalene and the other Mary came to look at the grave.",
    2: "And behold, a severe earthquake had occurred — for an angel of the Lord descended from heaven, and came and rolled away the stone, and sat upon it.",
    3: "And his appearance was like lightning, and his garment as white as snow.",
    4: "And the guards shook for fear of him, and became like dead men.",
    5: "And the angel answered and said to the women, \"Do not be afraid. For I know that you are looking for Jesus who has been crucified.",
    6: "He is not here — for He has risen, just as He said. Come, see the place where He was lying.",
    7: "And go quickly and tell His disciples that He has risen from the dead — and behold, He is going before you into Galilee. There you will see Him. Behold, I have told you.\"",
    8: "And they departed quickly from the tomb with fear and great joy, and ran to report it to His disciples.",
    9: "And behold, Jesus met them and said, \"Greetings!\" And they came up and took hold of His feet and worshiped Him.",
    10: "Then Jesus said to them, \"Do not be afraid. Go and take word to My brothers to leave for Galilee, and there they shall see Me.\"",
    11: "Now while they were on their way, behold, some of the guard came into the city and reported to the chief priests all that had happened.",
    12: "And when they had assembled with the elders and counseled together, they gave a large sum of money to the soldiers,",
    13: "and said, \"You are to say, 'His disciples came by night and stole Him away while we were asleep.'",
    14: "And if this should come to the governor's ears, we will win him over and keep you out of trouble.\"",
    15: "And they took the money and did as they had been instructed. And this story was widely spread among the Jews — and is to this day.",
    16: "But the eleven disciples proceeded to Galilee, to the mountain which Jesus had designated.",
    17: "And when they saw Him, they worshiped Him — but some were doubtful.",
    18: "And Jesus came up and spoke to them, saying, \"All authority has been given to Me in heaven and on earth.",
    19: "Go therefore and make disciples of all the nations, baptizing them in the name of the Father and the Son and the Holy Spirit —",
    20: "teaching them to observe all that I commanded you. And lo, I am with you always — even to the end of the age.\"",
}

CHAPTERS = {22:ch22,23:ch23,24:ch24,25:ch25,26:ch26,27:ch27,28:ch28}

def main():
    new_entries = {f"40_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Matthew 22-28 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Matthew 22-28 verses")

if __name__ == "__main__":
    main()
