"""MBT Matthew 1-7 — Birth narrative through Sermon on the Mount. 201 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch1 = {
    1: "The book of the genealogy of Jesus Christ, the Son of David, the Son of Abraham.",
    2: "Abraham was the father of Isaac. And Isaac was the father of Jacob. And Jacob was the father of Judah and his brothers.",
    3: "And Judah was the father of Perez and Zerah by Tamar. And Perez was the father of Hezron. And Hezron was the father of Ram.",
    4: "And Ram was the father of Amminadab. And Amminadab was the father of Nahshon. And Nahshon was the father of Salmon.",
    5: "And Salmon was the father of Boaz by Rahab. And Boaz was the father of Obed by Ruth. And Obed was the father of Jesse.",
    6: "And Jesse was the father of David the king. And David was the father of Solomon by her who had been the wife of Uriah.",
    7: "And Solomon was the father of Rehoboam. And Rehoboam was the father of Abijah. And Abijah was the father of Asa.",
    8: "And Asa was the father of Jehoshaphat. And Jehoshaphat was the father of Joram. And Joram was the father of Uzziah.",
    9: "And Uzziah was the father of Jotham. And Jotham was the father of Ahaz. And Ahaz was the father of Hezekiah.",
    10: "And Hezekiah was the father of Manasseh. And Manasseh was the father of Amon. And Amon was the father of Josiah.",
    11: "And Josiah was the father of Jeconiah and his brothers, at the time of the deportation to Babylon.",
    12: "And after the deportation to Babylon, Jeconiah was the father of Shealtiel. And Shealtiel was the father of Zerubbabel.",
    13: "And Zerubbabel was the father of Abiud. And Abiud was the father of Eliakim. And Eliakim was the father of Azor.",
    14: "And Azor was the father of Zadok. And Zadok was the father of Achim. And Achim was the father of Eliud.",
    15: "And Eliud was the father of Eleazar. And Eleazar was the father of Matthan. And Matthan was the father of Jacob.",
    16: "And Jacob was the father of Joseph the husband of Mary — of whom was born Jesus, who is called Christ.",
    17: "So all the generations from Abraham to David are fourteen generations — and from David to the deportation to Babylon, fourteen generations — and from the deportation to Babylon to the Christ, fourteen generations.",
    18: "Now the birth of Jesus Christ was as follows. When His mother Mary had been betrothed to Joseph, before they came together, she was found to be with child by the Holy Spirit.",
    19: "And Joseph her husband, being a righteous man, and not willing to disgrace her, planned to send her away secretly.",
    20: "But while he was thinking about these things, behold, an angel of the Lord appeared to him in a dream, saying, \"Joseph, son of David, do not be afraid to take Mary as your wife — for that which is conceived in her is of the Holy Spirit.",
    21: "And she will bear a Son — and you shall call His name Jesus, for it is He who will save His people from their sins.\"",
    22: "Now all this took place that what was spoken by the Lord through the prophet might be fulfilled, saying,",
    23: "\"Behold, the virgin shall be with child, and shall bear a Son — and they shall call His name Immanuel,\" which translated means, \"God with us.\"",
    24: "And Joseph arose from his sleep, and did as the angel of the Lord had commanded him — and took her as his wife,",
    25: "and kept her a virgin until she gave birth to a Son. And he called His name Jesus.",
}
ch2 = {
    1: "Now after Jesus was born in Bethlehem of Judea, in the days of Herod the king, behold, magi from the east arrived in Jerusalem,",
    2: "saying, \"Where is He who has been born King of the Jews? For we saw His star in the east, and have come to worship Him.\"",
    3: "And when Herod the king heard it, he was troubled — and all Jerusalem with him.",
    4: "And gathering together all the chief priests and scribes of the people, he began to inquire of them where the Christ was to be born.",
    5: "And they said to him, \"In Bethlehem of Judea — for so it has been written by the prophet:",
    6: "'And you, Bethlehem, land of Judah, are by no means least among the leaders of Judah — for out of you shall come forth a Ruler, who will shepherd My people Israel.'\"",
    7: "Then Herod secretly called the magi, and ascertained from them the time the star appeared.",
    8: "And he sent them to Bethlehem, and said, \"Go and make careful search for the Child. And when you have found Him, report to me, that I too may come and worship Him.\"",
    9: "And having heard the king, they went their way — and behold, the star which they had seen in the east went on before them, until it came and stood over where the Child was.",
    10: "And when they saw the star, they rejoiced exceedingly with great joy.",
    11: "And they came into the house and saw the Child with Mary His mother. And they fell down and worshiped Him. And opening their treasures, they presented to Him gifts of gold, and frankincense, and myrrh.",
    12: "And having been warned by God in a dream not to return to Herod, they departed for their own country by another way.",
    13: "Now when they had departed, behold, an angel of the Lord appeared to Joseph in a dream, saying, \"Arise and take the Child and His mother, and flee to Egypt — and remain there until I tell you. For Herod is going to search for the Child to destroy Him.\"",
    14: "And he arose and took the Child and His mother by night, and departed for Egypt.",
    15: "And he was there until the death of Herod — that what was spoken by the Lord through the prophet might be fulfilled, saying, \"Out of Egypt I called My Son.\"",
    16: "Then when Herod saw that he had been tricked by the magi, he became very enraged. And he sent and slew all the boys who were in Bethlehem and in all its environs, from two years old and under — according to the time which he had ascertained from the magi.",
    17: "Then that which was spoken through Jeremiah the prophet was fulfilled, saying,",
    18: "\"A voice was heard in Ramah — weeping and great mourning. Rachel weeping for her children. And she refused to be comforted, because they were no more.\"",
    19: "But when Herod was dead, behold, an angel of the Lord appeared in a dream to Joseph in Egypt, saying,",
    20: "\"Arise and take the Child and His mother, and go into the land of Israel. For those who sought the Child's life are dead.\"",
    21: "And he arose and took the Child and His mother, and came into the land of Israel.",
    22: "But when he heard that Archelaus was reigning over Judea in place of his father Herod, he was afraid to go there. And being warned by God in a dream, he departed for the regions of Galilee,",
    23: "and came and resided in a city called Nazareth — that what was spoken through the prophets might be fulfilled, \"He shall be called a Nazarene.\"",
}
ch3 = {
    1: "Now in those days John the Baptist came, preaching in the wilderness of Judea, saying,",
    2: "\"Repent — for the kingdom of heaven is at hand.\"",
    3: "For this is the one referred to by Isaiah the prophet, saying, \"The voice of one crying in the wilderness — 'Prepare the way of the Lord. Make His paths straight!'\"",
    4: "Now John himself had a garment of camel's hair, and a leather belt about his waist — and his food was locusts and wild honey.",
    5: "Then Jerusalem was going out to him, and all Judea, and all the district around the Jordan.",
    6: "And they were being baptized by him in the Jordan river, as they confessed their sins.",
    7: "But when he saw many of the Pharisees and Sadducees coming for baptism, he said to them, \"You brood of vipers! Who warned you to flee from the wrath to come?",
    8: "Therefore bring forth fruit in keeping with your repentance.",
    9: "And do not suppose that you can say to yourselves, 'We have Abraham for our father.' For I say to you that God is able from these stones to raise up children to Abraham.",
    10: "And the axe is already laid at the root of the trees. Therefore every tree that does not bear good fruit is cut down and thrown into the fire.",
    11: "As for me, I baptize you with water for repentance — but He who is coming after me is mightier than I, and I am not fit to remove His sandals. He Himself will baptize you with the Holy Spirit and fire.",
    12: "And His winnowing fork is in His hand, and He will thoroughly clear His threshing floor — and He will gather His wheat into the barn, but He will burn up the chaff with unquenchable fire.\"",
    13: "Then Jesus arrived from Galilee at the Jordan, coming to John to be baptized by him.",
    14: "But John tried to prevent Him, saying, \"I have need to be baptized by You — and do You come to me?\"",
    15: "But Jesus answering said to him, \"Permit it at this time — for in this way it is fitting for us to fulfill all righteousness.\" Then he permitted Him.",
    16: "And after being baptized, Jesus went up immediately from the water — and behold, the heavens were opened, and he saw the Spirit of God descending as a dove, and coming upon Him.",
    17: "And behold, a voice out of the heavens, saying, \"This is My beloved Son, in whom I am well-pleased.\"",
}
ch4 = {
    1: "Then Jesus was led up by the Spirit into the wilderness to be tempted by the devil.",
    2: "And after He had fasted forty days and forty nights, He then became hungry.",
    3: "And the tempter came and said to Him, \"If You are the Son of God, command that these stones become bread.\"",
    4: "But He answered and said, \"It is written, 'Man shall not live on bread alone, but on every word that proceeds out of the mouth of God.'\"",
    5: "Then the devil took Him into the holy city, and set Him on the pinnacle of the temple.",
    6: "And he said to Him, \"If You are the Son of God, throw Yourself down — for it is written, 'He will give His angels charge concerning You. And on their hands they will bear You up, lest You strike Your foot against a stone.'\"",
    7: "Jesus said to him, \"On the other hand, it is written, 'You shall not put the Lord your God to the test.'\"",
    8: "Again, the devil took Him to a very high mountain, and showed Him all the kingdoms of the world, and their glory.",
    9: "And he said to Him, \"All these things will I give You, if You fall down and worship me.\"",
    10: "Then Jesus said to him, \"Be gone, Satan! For it is written, 'You shall worship the Lord your God, and serve Him only.'\"",
    11: "Then the devil left Him — and behold, angels came and began to minister to Him.",
    12: "Now when He heard that John had been taken into custody, He withdrew into Galilee.",
    13: "And leaving Nazareth, He came and settled in Capernaum, which is by the sea, in the region of Zebulun and Naphtali.",
    14: "This was to fulfill what was spoken through Isaiah the prophet:",
    15: "\"The land of Zebulun and the land of Naphtali, by the way of the sea, beyond the Jordan, Galilee of the Gentiles —",
    16: "the people who were sitting in darkness saw a great light. And to those who were sitting in the land and shadow of death, upon them a light dawned.\"",
    17: "From that time Jesus began to preach and say, \"Repent — for the kingdom of heaven is at hand.\"",
    18: "And walking by the Sea of Galilee, He saw two brothers — Simon, who was called Peter, and Andrew his brother — casting a net into the sea. For they were fishermen.",
    19: "And He said to them, \"Follow Me — and I will make you fishers of men.\"",
    20: "And they immediately left the nets and followed Him.",
    21: "And going on from there He saw two other brothers — James the son of Zebedee, and John his brother — in the boat with Zebedee their father, mending their nets. And He called them.",
    22: "And they immediately left the boat and their father, and followed Him.",
    23: "And Jesus was going about in all Galilee, teaching in their synagogues and proclaiming the gospel of the kingdom, and healing every kind of disease and every kind of sickness among the people.",
    24: "And the news about Him went out into all Syria. And they brought to Him all who were ill, taken with various diseases and pains, demoniacs, epileptics, paralytics — and He healed them.",
    25: "And great multitudes followed Him from Galilee, and Decapolis, and Jerusalem, and Judea, and from beyond the Jordan.",
}
ch5 = {
    1: "And when He saw the multitudes, He went up on the mountain. And after He sat down, His disciples came to Him.",
    2: "And opening His mouth, He began to teach them, saying:",
    3: "\"Blessed are the poor in spirit — for theirs is the kingdom of heaven.",
    4: "Blessed are those who mourn — for they shall be comforted.",
    5: "Blessed are the gentle — for they shall inherit the earth.",
    6: "Blessed are those who hunger and thirst for righteousness — for they shall be satisfied.",
    7: "Blessed are the merciful — for they shall receive mercy.",
    8: "Blessed are the pure in heart — for they shall see God.",
    9: "Blessed are the peacemakers — for they shall be called sons of God.",
    10: "Blessed are those who have been persecuted for the sake of righteousness — for theirs is the kingdom of heaven.",
    11: "Blessed are you when men cast insults at you, and persecute you, and say all kinds of evil against you falsely, on account of Me.",
    12: "Rejoice and be glad — for your reward in heaven is great. For so they persecuted the prophets who were before you.",
    13: "You are the salt of the earth. But if the salt has become tasteless, how will it be made salty again? It is good for nothing anymore, except to be thrown out and trampled under foot by men.",
    14: "You are the light of the world. A city set on a hill cannot be hidden.",
    15: "Nor do men light a lamp, and put it under the peck-measure — but on the lampstand. And it gives light to all who are in the house.",
    16: "Let your light shine before men in such a way that they may see your good works, and glorify your Father who is in heaven.",
    17: "Do not think that I came to abolish the Law or the Prophets. I did not come to abolish — but to fulfill.",
    18: "For truly I say to you — until heaven and earth pass away, not the smallest letter or stroke shall pass away from the Law, until all is accomplished.",
    19: "Whoever then annuls one of the least of these commandments, and so teaches others, shall be called least in the kingdom of heaven. But whoever keeps and teaches them, he shall be called great in the kingdom of heaven.",
    20: "For I say to you, that unless your righteousness surpasses that of the scribes and Pharisees, you shall not enter the kingdom of heaven.",
    21: "You have heard that the ancients were told, 'You shall not commit murder' — and 'Whoever commits murder shall be liable to the court.'",
    22: "But I say to you, that everyone who is angry with his brother shall be liable to the court. And whoever shall say to his brother, 'Raca,' shall be liable to the supreme court. And whoever shall say, 'You fool,' shall be guilty enough to go into the fiery hell.",
    23: "Therefore, if you are presenting your offering at the altar, and there remember that your brother has something against you,",
    24: "leave your offering there before the altar — and go your way. First be reconciled to your brother — and then come and present your offering.",
    25: "Make friends quickly with your opponent at law while you are with him on the way — lest your opponent deliver you to the judge, and the judge to the officer, and you be thrown into prison.",
    26: "Truly I say to you, you shall not come out of there, until you have paid up the last cent.",
    27: "You have heard that it was said, 'You shall not commit adultery.'",
    28: "But I say to you, that everyone who looks on a woman to lust for her has committed adultery with her already in his heart.",
    29: "And if your right eye makes you stumble, tear it out, and throw it from you. For it is better for you that one of the parts of your body perish, than for your whole body to be thrown into hell.",
    30: "And if your right hand makes you stumble, cut it off, and throw it from you. For it is better for you that one of the parts of your body perish, than for your whole body to go into hell.",
    31: "And it was said, 'Whoever sends his wife away, let him give her a certificate of divorce.'",
    32: "But I say to you, that everyone who divorces his wife, except for the cause of unchastity, makes her commit adultery — and whoever marries a divorced woman commits adultery.",
    33: "Again, you have heard that the ancients were told, 'You shall not make false vows, but shall fulfill your vows to the Lord.'",
    34: "But I say to you, make no oath at all — either by heaven, for it is the throne of God,",
    35: "or by the earth, for it is the footstool of His feet, or by Jerusalem, for it is the city of the great King.",
    36: "Nor shall you make an oath by your head — for you cannot make one hair white or black.",
    37: "But let your statement be, 'Yes, yes' or 'No, no.' And anything beyond these is of evil.",
    38: "You have heard that it was said, 'An eye for an eye, and a tooth for a tooth.'",
    39: "But I say to you, do not resist him who is evil. But whoever slaps you on your right cheek, turn the other to him also.",
    40: "And if anyone wants to sue you and take your shirt, let him have your coat also.",
    41: "And whoever shall force you to go one mile, go with him two.",
    42: "Give to him who asks of you, and do not turn away from him who wants to borrow from you.",
    43: "You have heard that it was said, 'You shall love your neighbor, and hate your enemy.'",
    44: "But I say to you, love your enemies — and pray for those who persecute you.",
    45: "In order that you may be sons of your Father who is in heaven. For He causes His sun to rise on the evil and the good, and sends rain on the righteous and the unrighteous.",
    46: "For if you love those who love you, what reward have you? Do not even the tax-gatherers do the same?",
    47: "And if you greet your brothers only, what do you do more than others? Do not even the Gentiles do the same?",
    48: "Therefore you are to be perfect, as your heavenly Father is perfect.",
}
ch6 = {
    1: "Beware of practicing your righteousness before men to be noticed by them. Otherwise you have no reward with your Father who is in heaven.",
    2: "When therefore you give alms, do not sound a trumpet before you, as the hypocrites do in the synagogues and in the streets, that they may be honored by men. Truly I say to you, they have their reward in full.",
    3: "But when you give alms, do not let your left hand know what your right hand is doing —",
    4: "that your alms may be in secret. And your Father who sees in secret will reward you.",
    5: "And when you pray, you are not to be as the hypocrites — for they love to stand and pray in the synagogues and on the street corners, in order to be seen by men. Truly I say to you, they have their reward in full.",
    6: "But you, when you pray, go into your inner room, and when you have shut your door, pray to your Father who is in secret. And your Father who sees in secret will reward you.",
    7: "And when you are praying, do not use meaningless repetition, as the Gentiles do. For they suppose that they will be heard for their many words.",
    8: "Therefore do not be like them. For your Father knows what you need, before you ask Him.",
    9: "Pray, then, in this way: 'Our Father who is in heaven, hallowed be Your name.",
    10: "Your kingdom come. Your will be done, on earth as it is in heaven.",
    11: "Give us this day our daily bread.",
    12: "And forgive us our debts, as we also have forgiven our debtors.",
    13: "And do not lead us into temptation, but deliver us from evil. (For Yours is the kingdom, and the power, and the glory, forever. Amen.)'",
    14: "For if you forgive men for their transgressions, your heavenly Father will also forgive you.",
    15: "But if you do not forgive men, then your Father will not forgive your transgressions.",
    16: "And whenever you fast, do not put on a gloomy face, as the hypocrites do — for they neglect their appearance in order to be seen fasting by men. Truly I say to you, they have their reward in full.",
    17: "But you, when you fast, anoint your head, and wash your face —",
    18: "so that you may not be seen fasting by men, but by your Father who is in secret. And your Father, who sees in secret, will reward you.",
    19: "Do not lay up for yourselves treasures upon earth, where moth and rust destroy, and where thieves break in and steal.",
    20: "But lay up for yourselves treasures in heaven, where neither moth nor rust destroys, and where thieves do not break in or steal.",
    21: "For where your treasure is, there will your heart be also.",
    22: "The lamp of the body is the eye. If therefore your eye is clear, your whole body will be full of light.",
    23: "But if your eye is bad, your whole body will be full of darkness. If therefore the light that is in you is darkness, how great is the darkness!",
    24: "No one can serve two masters. For either he will hate the one and love the other, or he will hold to one and despise the other. You cannot serve God and mammon.",
    25: "For this reason I say to you, do not be anxious for your life, as to what you shall eat, or what you shall drink — nor for your body, as to what you shall put on. Is not life more than food, and the body than clothing?",
    26: "Look at the birds of the air, that they do not sow, neither do they reap, nor gather into barns. And yet your heavenly Father feeds them. Are you not worth much more than they?",
    27: "And which of you by being anxious can add a single cubit to his life's span?",
    28: "And why are you anxious about clothing? Observe how the lilies of the field grow — they do not toil, nor do they spin.",
    29: "Yet I say to you, that even Solomon in all his glory did not clothe himself like one of these.",
    30: "But if God so arrays the grass of the field, which is alive today, and tomorrow is thrown into the furnace, will He not much more do so for you, O men of little faith?",
    31: "Do not be anxious then, saying, 'What shall we eat?' or 'What shall we drink?' or 'With what shall we clothe ourselves?'",
    32: "For all these things the Gentiles eagerly seek. For your heavenly Father knows that you need all these things.",
    33: "But seek first His kingdom and His righteousness — and all these things shall be added to you.",
    34: "Therefore do not be anxious for tomorrow. For tomorrow will care for itself. Each day has enough trouble of its own.",
}
ch7 = {
    1: "Do not judge — lest you be judged.",
    2: "For in the way you judge, you will be judged. And by your standard of measure, it will be measured to you.",
    3: "And why do you look at the speck that is in your brother's eye, but do not notice the log that is in your own eye?",
    4: "Or how can you say to your brother, 'Let me take the speck out of your eye,' and behold, the log is in your own eye?",
    5: "You hypocrite — first take the log out of your own eye. And then you will see clearly to take the speck out of your brother's eye.",
    6: "Do not give what is holy to dogs, and do not throw your pearls before swine — lest they trample them under their feet, and turn and tear you to pieces.",
    7: "Ask — and it shall be given to you. Seek — and you shall find. Knock — and it shall be opened to you.",
    8: "For everyone who asks receives. And he who seeks finds. And to him who knocks, it shall be opened.",
    9: "Or what man is there among you, when his son shall ask him for a loaf, will give him a stone?",
    10: "Or if he shall ask for a fish, he will not give him a snake, will he?",
    11: "If you then, being evil, know how to give good gifts to your children, how much more shall your Father who is in heaven give what is good to those who ask Him!",
    12: "Therefore, however you want people to treat you — so treat them. For this is the Law and the Prophets.",
    13: "Enter by the narrow gate. For the gate is wide, and the way is broad, that leads to destruction — and many are those who enter by it.",
    14: "For the gate is small, and the way is narrow, that leads to life — and few are those who find it.",
    15: "Beware of the false prophets, who come to you in sheep's clothing — but inwardly are ravenous wolves.",
    16: "You will know them by their fruits. Grapes are not gathered from thorn bushes, nor figs from thistles, are they?",
    17: "Even so, every good tree bears good fruit — but the bad tree bears bad fruit.",
    18: "A good tree cannot produce bad fruit, nor can a bad tree produce good fruit.",
    19: "Every tree that does not bear good fruit is cut down and thrown into the fire.",
    20: "So then, you will know them by their fruits.",
    21: "Not everyone who says to Me, 'Lord, Lord,' will enter the kingdom of heaven — but he who does the will of My Father who is in heaven.",
    22: "Many will say to Me on that day, 'Lord, Lord, did we not prophesy in Your name, and in Your name cast out demons, and in Your name perform many miracles?'",
    23: "And then I will declare to them, 'I never knew you. Depart from Me, you who practice lawlessness.'",
    24: "Therefore everyone who hears these words of Mine, and acts upon them, may be compared to a wise man, who built his house upon the rock.",
    25: "And the rain descended, and the floods came, and the winds blew, and burst against that house. And yet it did not fall — for it had been founded upon the rock.",
    26: "And everyone who hears these words of Mine, and does not act upon them, will be like a foolish man, who built his house upon the sand.",
    27: "And the rain descended, and the floods came, and the winds blew, and burst against that house. And it fell. And great was its fall.",
    28: "And the result was that when Jesus had finished these words, the multitudes were amazed at His teaching —",
    29: "for He was teaching them as one having authority, and not as their scribes.",
}

CHAPTERS = {1:ch1,2:ch2,3:ch3,4:ch4,5:ch5,6:ch6,7:ch7}

def main():
    new_entries = {f"40_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Matthew 1-7 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Matthew 1-7 verses")

if __name__ == "__main__":
    main()
