"""MBT Acts 20-28 — Paul's farewell, arrest, trials, Rome. 304 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch20 = {
    1: "And after the uproar had ceased, Paul sent for the disciples — and after exhorting them and taking his leave of them, he departed to go to Macedonia.",
    2: "And when he had gone through those districts and had given them much exhortation, he came to Greece.",
    3: "And there he spent three months. And when a plot was formed against him by the Jews as he was about to set sail for Syria, he decided to return through Macedonia.",
    4: "And he was accompanied by Sopater of Berea, the son of Pyrrhus — and by Aristarchus and Secundus of the Thessalonians, and Gaius of Derbe, and Timothy, and Tychicus and Trophimus of Asia.",
    5: "But these had gone on ahead and were waiting for us at Troas.",
    6: "And we sailed from Philippi after the days of Unleavened Bread, and came to them at Troas within five days — where we spent seven days.",
    7: "And on the first day of the week, when we were gathered together to break bread, Paul began talking to them, intending to depart the next day — and he prolonged his message until midnight.",
    8: "And there were many lamps in the upper room where we were gathered together.",
    9: "And there was a certain young man named Eutychus sitting on the window sill, sinking into a deep sleep — and as Paul kept on talking, he was overcome by sleep and fell down from the third floor, and was picked up dead.",
    10: "But Paul went down and fell upon him, and after embracing him said, \"Do not be troubled — for his life is in him.\"",
    11: "And when he had gone back up and had broken the bread and eaten, he talked with them a long while — until daybreak — and then left.",
    12: "And they took away the boy alive — and were greatly comforted.",
    13: "But we, going ahead to the ship, set sail for Assos — intending from there to take Paul on board. For so he had arranged it, intending himself to go by land.",
    14: "And when he met us at Assos, we took him on board and came to Mitylene.",
    15: "And sailing from there, we arrived the following day opposite Chios — and the next day we crossed over to Samos, and the day following we came to Miletus.",
    16: "For Paul had decided to sail past Ephesus, so that he would not have to spend time in Asia — for he was hurrying, if possible, to be in Jerusalem the day of Pentecost.",
    17: "And from Miletus he sent to Ephesus and called to himself the elders of the church.",
    18: "And when they had come to him, he said to them: \"You yourselves know, from the first day that I set foot in Asia, how I was with you the whole time —",
    19: "serving the Lord with all humility and with tears, and with trials which came upon me through the plots of the Jews.",
    20: "How I did not shrink from declaring to you anything that was profitable — and teaching you publicly and from house to house.",
    21: "Solemnly testifying to both Jews and Greeks of repentance toward God, and faith in our Lord Jesus Christ.",
    22: "And now, behold, bound by the Spirit, I am on my way to Jerusalem — not knowing what will happen to me there.",
    23: "Except that the Holy Spirit solemnly testifies to me in every city, saying that bonds and afflictions await me.",
    24: "But I do not consider my life of any account as dear to myself — so that I may finish my course, and the ministry which I received from the Lord Jesus, to testify solemnly of the gospel of the grace of God.",
    25: "And now, behold, I know that all of you, among whom I went about preaching the kingdom, will see my face no more.",
    26: "Therefore, I testify to you this day, that I am innocent of the blood of all men.",
    27: "For I did not shrink from declaring to you the whole purpose of God.",
    28: "Be on guard for yourselves, and for all the flock — among which the Holy Spirit has made you overseers — to shepherd the church of God, which He purchased with His own blood.",
    29: "I know that after my departure savage wolves will come in among you, not sparing the flock.",
    30: "And from among your own selves men will arise, speaking perverse things — to draw away the disciples after them.",
    31: "Therefore be on the alert, remembering that night and day for a period of three years I did not cease to admonish each one with tears.",
    32: "And now I commend you to God and to the word of His grace — which is able to build you up and to give you the inheritance among all those who are sanctified.",
    33: "I have coveted no one's silver or gold or clothes.",
    34: "You yourselves know that these hands ministered to my own needs, and to the men who were with me.",
    35: "In everything I showed you that by working hard in this manner you must help the weak — and remember the words of the Lord Jesus, that He Himself said: 'It is more blessed to give than to receive.'\"",
    36: "And when he had said these things, he knelt down and prayed with them all.",
    37: "And they began to weep aloud, and embraced Paul and were kissing him —",
    38: "grieving especially over the word which he had spoken — that they would not see his face again. And they were accompanying him to the ship.",
}
ch21 = {
    1: "And it came about that when we had parted from them and had set sail, we ran a straight course to Cos — and the next day to Rhodes, and from there to Patara.",
    2: "And having found a ship crossing over to Phoenicia, we went aboard and set sail.",
    3: "And when we came in sight of Cyprus, leaving it on the left, we kept sailing to Syria — and landed at Tyre. For the ship was to unload its cargo there.",
    4: "And after looking up the disciples, we stayed there seven days. And they kept telling Paul, through the Spirit, not to set foot in Jerusalem.",
    5: "And when our days there were ended, we departed and started on our journey — while they all, with wives and children, escorted us until we were out of the city. And after kneeling down on the beach and praying, we said farewell to one another.",
    6: "Then we went on board the ship, and they returned home again.",
    7: "And when we had finished the voyage from Tyre, we arrived at Ptolemais — and after greeting the brothers, we stayed with them for a day.",
    8: "And on the next day we departed and came to Caesarea — and entering the house of Philip the evangelist, who was one of the seven, we stayed with him.",
    9: "Now this man had four virgin daughters who were prophetesses.",
    10: "And as we were staying there for some days, a certain prophet named Agabus came down from Judea.",
    11: "And coming to us, he took Paul's belt and bound his own feet and hands, and said, \"This is what the Holy Spirit says: 'In this way the Jews at Jerusalem will bind the man who owns this belt — and deliver him into the hands of the Gentiles.'\"",
    12: "And when we had heard this, we as well as the local residents began begging him not to go up to Jerusalem.",
    13: "Then Paul answered, \"What are you doing, weeping and breaking my heart? For I am ready not only to be bound, but even to die at Jerusalem for the name of the Lord Jesus.\"",
    14: "And since he would not be persuaded, we fell silent, remarking, \"The will of the Lord be done.\"",
    15: "And after these days we got ready and started on our way up to Jerusalem.",
    16: "And some of the disciples from Caesarea also came with us — taking us to Mnason of Cyprus, a disciple of long standing, with whom we were to lodge.",
    17: "And when we had come to Jerusalem, the brothers received us gladly.",
    18: "And now on the following day, Paul went in with us to James — and all the elders were present.",
    19: "And after he had greeted them, he began to relate one by one the things which God had done among the Gentiles through his ministry.",
    20: "And when they heard it they began glorifying God — and they said to him, \"You see, brother, how many thousands there are among the Jews of those who have believed — and they are all zealous for the Law.",
    21: "And they have been told about you, that you are teaching all the Jews who are among the Gentiles to forsake Moses — telling them not to circumcise their children, nor to walk according to the customs.",
    22: "What, then, is to be done? They will certainly hear that you have come.",
    23: "Therefore do this that we tell you: we have four men who are under a vow.",
    24: "Take them and purify yourself along with them, and pay their expenses in order that they may shave their heads. And all will know that there is nothing to the things which they have been told about you — but that you yourself also walk orderly, keeping the Law.",
    25: "But concerning the Gentiles who have believed, we wrote, having decided that they should abstain from meat sacrificed to idols, and from blood, and from what is strangled, and from fornication.\"",
    26: "Then Paul took the men, and the next day, purifying himself along with them, went into the temple — giving notice of the completion of the days of purification, until the sacrifice was offered for each one of them.",
    27: "And when the seven days were almost over, the Jews from Asia, upon seeing him in the temple, began to stir up all the multitude and laid hands on him,",
    28: "crying out: \"Men of Israel, come to our aid! This is the man who preaches to all men everywhere against our people, and the Law, and this place. And besides, he has even brought Greeks into the temple and has defiled this holy place.\"",
    29: "(For they had previously seen Trophimus the Ephesian in the city with him, and they supposed that Paul had brought him into the temple.)",
    30: "And all the city was provoked — and the people rushed together. And taking hold of Paul, they dragged him out of the temple — and immediately the doors were shut.",
    31: "And while they were seeking to kill him, a report came up to the commander of the Roman cohort that all Jerusalem was in confusion.",
    32: "And at once he took along some soldiers and centurions and ran down to them. And when they saw the commander and the soldiers, they stopped beating Paul.",
    33: "Then the commander came up and took hold of him, and ordered him to be bound with two chains — and began asking who he was and what he had done.",
    34: "But among the crowd some were shouting one thing and some another. And when he could not find out the facts on account of the uproar, he ordered him to be brought into the barracks.",
    35: "And when he got to the stairs, it so happened that he was carried by the soldiers because of the violence of the mob.",
    36: "For the multitude of the people kept following behind, crying out, \"Away with him!\"",
    37: "And as Paul was about to be brought into the barracks, he said to the commander, \"May I say something to you?\" And he said, \"Do you know Greek?",
    38: "Then you are not the Egyptian who some time ago stirred up a revolt and led the four thousand men of the Assassins out into the wilderness?\"",
    39: "But Paul said, \"I am a Jew of Tarsus in Cilicia, a citizen of no insignificant city — and I beg you, allow me to speak to the people.\"",
    40: "And when he had given him permission, Paul, standing on the stairs, motioned to the people with his hand. And when there was a great hush, he spoke to them in the Hebrew dialect, saying:",
}
ch22 = {
    1: "\"Brothers and fathers — hear my defense which I now offer to you.\"",
    2: "And when they heard that he was addressing them in the Hebrew dialect, they became even more quiet — and he said:",
    3: "\"I am a Jew, born in Tarsus of Cilicia, but brought up in this city — educated under Gamaliel, strictly according to the law of our fathers, being zealous for God, just as you all are today.",
    4: "And I persecuted this Way to the death — binding and putting both men and women into prisons.",
    5: "As also the high priest and all the Council of the elders can testify. From them I also received letters to the brothers — and I started off for Damascus in order to bring even those who were there to Jerusalem as prisoners, to be punished.",
    6: "And it came about that as I was on my way, approaching Damascus about noontime — a very bright light suddenly flashed from heaven all around me.",
    7: "And I fell to the ground, and heard a voice saying to me, 'Saul, Saul, why are you persecuting Me?'",
    8: "And I answered, 'Who are You, Lord?' And He said to me, 'I am Jesus the Nazarene, whom you are persecuting.'",
    9: "And those who were with me beheld the light, to be sure, but did not understand the voice of the One who was speaking to me.",
    10: "And I said, 'What shall I do, Lord?' And the Lord said to me, 'Arise and go on into Damascus — and there you will be told of all that has been appointed for you to do.'",
    11: "But since I could not see because of the brightness of that light, I was led by the hand by those who were with me — and came into Damascus.",
    12: "And a certain Ananias, a man who was devout by the standard of the Law, and well spoken of by all the Jews who lived there,",
    13: "came to me, and standing near said to me, 'Brother Saul, receive your sight!' And at that very moment I looked up at him.",
    14: "And he said, 'The God of our fathers has appointed you to know His will — and to see the Righteous One, and to hear an utterance from His mouth.",
    15: "For you will be a witness for Him to all men of what you have seen and heard.",
    16: "And now why do you delay? Arise — and be baptized, and wash away your sins, calling on His name.'",
    17: "And it came about, when I returned to Jerusalem and was praying in the temple, that I fell into a trance —",
    18: "and I saw Him saying to me: 'Make haste, and get out of Jerusalem quickly, because they will not accept your testimony about Me.'",
    19: "And I said, 'Lord, they themselves understand that in one synagogue after another I used to imprison and beat those who believed in You.",
    20: "And when the blood of Your witness Stephen was being shed, I also was standing by, approving — and watching out for the cloaks of those who were slaying him.'",
    21: "And He said to me, 'Go! For I will send you far away to the Gentiles.'\"",
    22: "And they listened to him up to this statement, and then they raised their voices and said, \"Away with such a fellow from the earth! For he should not be allowed to live!\"",
    23: "And as they were crying out and throwing off their cloaks and tossing dust into the air,",
    24: "the commander ordered him to be brought into the barracks, stating that he should be examined by scourging — so that he might find out the reason why they were shouting against him that way.",
    25: "And when they stretched him out with thongs, Paul said to the centurion who was standing by, \"Is it lawful for you to scourge a man who is a Roman, and uncondemned?\"",
    26: "And when the centurion heard this, he went to the commander and told him, saying, \"What are you about to do? For this man is a Roman.\"",
    27: "And the commander came and said to him, \"Tell me, are you a Roman?\" And he said, \"Yes.\"",
    28: "And the commander answered, \"I acquired this citizenship with a large sum of money.\" And Paul said, \"But I was actually born a citizen.\"",
    29: "Therefore those who were about to examine him immediately let go of him. And the commander also was afraid when he found out that he was a Roman, and because he had put him in chains.",
    30: "But on the next day, wishing to know for certain why he had been accused by the Jews, he released him — and ordered the chief priests and all the Council to assemble. And he brought Paul down and set him before them.",
}
ch23 = {
    1: "And Paul, looking intently at the Council, said, \"Brothers, I have lived my life with a perfectly good conscience before God up to this day.\"",
    2: "And the high priest Ananias commanded those standing beside him to strike him on the mouth.",
    3: "Then Paul said to him, \"God is going to strike you, you whitewashed wall! And do you sit to try me according to the Law — and in violation of the Law order me to be struck?\"",
    4: "But the bystanders said, \"Do you revile God's high priest?\"",
    5: "And Paul said, \"I was not aware, brothers, that he was high priest — for it is written: 'You shall not speak evil of a ruler of your people.'\"",
    6: "But perceiving that one part were Sadducees and the other Pharisees, Paul began crying out in the Council, \"Brothers, I am a Pharisee, a son of Pharisees. I am on trial for the hope and resurrection of the dead!\"",
    7: "And as he said this, there arose a dissension between the Pharisees and Sadducees — and the assembly was divided.",
    8: "For the Sadducees say that there is no resurrection, nor an angel, nor a spirit — but the Pharisees acknowledge them all.",
    9: "And there arose a great uproar. And some of the scribes of the Pharisaic party stood up and began to argue heatedly, saying, \"We find nothing wrong with this man. Suppose a spirit or an angel has spoken to him?\"",
    10: "And as a great dissension was developing, the commander was afraid Paul would be torn to pieces by them — and ordered the troops to go down and take him away from them by force, and bring him into the barracks.",
    11: "But on the following night the Lord stood at his side and said, \"Take courage. For as you have solemnly witnessed to My cause at Jerusalem, so you must witness also at Rome.\"",
    12: "And when it was day, the Jews formed a conspiracy and bound themselves under an oath, saying that they would neither eat nor drink until they had killed Paul.",
    13: "And there were more than forty who formed this plot.",
    14: "And they came to the chief priests and the elders, and said, \"We have bound ourselves under a solemn oath to taste nothing until we have killed Paul.",
    15: "Now therefore, you and the Council notify the commander to bring him down to you, as though you were going to determine his case by a more thorough investigation — and we for our part are ready to slay him before he comes near the place.\"",
    16: "But the son of Paul's sister heard of their ambush, and he came and entered the barracks and told Paul.",
    17: "And Paul called one of the centurions to him and said, \"Lead this young man to the commander — for he has something to report to him.\"",
    18: "So he took him and led him to the commander, and said, \"Paul the prisoner called me to him and asked me to lead this young man to you, since he has something to tell you.\"",
    19: "And the commander took him by the hand, and stepping aside, began to inquire of him privately, \"What is it that you have to report to me?\"",
    20: "And he said, \"The Jews have agreed to ask you to bring Paul down tomorrow to the Council, as though they were going to inquire somewhat more thoroughly about him.",
    21: "Therefore do not listen to them — for more than forty of them are lying in wait for him, who have bound themselves under a curse not to eat or drink until they slay him. And now they are ready and waiting for the promise from you.\"",
    22: "Therefore the commander let the young man go, instructing him: \"Tell no one that you have notified me of these things.\"",
    23: "And he called to him two of the centurions, and said, \"Get ready by the third hour of the night two hundred soldiers — and seventy horsemen, and two hundred spearmen, to proceed to Caesarea.",
    24: "Also provide mounts to put Paul on, and bring him safely to Felix the governor.\"",
    25: "And he wrote a letter having this form:",
    26: "\"Claudius Lysias, to the most excellent governor Felix — greetings.",
    27: "When this man was seized by the Jews and was about to be slain by them, I came upon them with the troops and rescued him — having learned that he was a Roman.",
    28: "And wanting to ascertain the charge for which they were accusing him, I brought him down to their Council.",
    29: "And I found him to be accused over questions about their Law — but under no accusation deserving death or imprisonment.",
    30: "And when I was informed that there would be a plot against the man, I sent him to you at once — also instructing his accusers to bring charges against him before you.\"",
    31: "So the soldiers, in accordance with their orders, took Paul and brought him by night to Antipatris.",
    32: "But the next day, leaving the horsemen to go on with him, they returned to the barracks.",
    33: "And when these had come to Caesarea and delivered the letter to the governor, they also presented Paul to him.",
    34: "And when he had read it, he asked from what province he was — and when he learned that he was from Cilicia,",
    35: "he said, \"I will give you a hearing after your accusers arrive also.\" And he gave orders for him to be kept in Herod's Praetorium.",
}
ch24 = {
    1: "And after five days the high priest Ananias came down with some elders, with a certain attorney named Tertullus — and they brought charges to the governor against Paul.",
    2: "And after Paul had been summoned, Tertullus began to accuse him, saying to the governor: \"Since we have through you attained much peace, and since by your providence reforms are being carried out for this nation,",
    3: "we acknowledge this in every way and everywhere, most excellent Felix, with all thankfulness.",
    4: "But that I may not weary you any further, I beg you to grant us, by your kindness, a brief hearing.",
    5: "For we have found this man a real pest — and a fellow who stirs up dissension among all the Jews throughout the world, and a ringleader of the sect of the Nazarenes.",
    6: "And he even tried to desecrate the temple — and then we arrested him.",
    7: "(Verse traditionally numbered — included in transmission.)",
    8: "By examining him yourself concerning all these matters, you will be able to ascertain the things of which we accuse him.\"",
    9: "And the Jews also joined in the attack, asserting that these things were so.",
    10: "And when the governor had nodded for him to speak, Paul responded: \"Knowing that for many years you have been a judge to this nation, I cheerfully make my defense.",
    11: "Since you can take note of the fact that no more than twelve days ago I went up to Jerusalem to worship.",
    12: "And neither in the temple, nor in the synagogues, nor in the city itself did they find me carrying on a discussion with anyone, or causing a riot.",
    13: "Nor can they prove to you the charges of which they now accuse me.",
    14: "But this I admit to you, that according to the Way which they call a sect, I do serve the God of our fathers — believing everything that is in accordance with the Law, and that is written in the Prophets.",
    15: "Having a hope in God, which these men cherish themselves — that there shall certainly be a resurrection of both the righteous and the wicked.",
    16: "In view of this, I also do my best to maintain always a blameless conscience both before God and before men.",
    17: "Now after several years I came to bring alms to my nation, and to present offerings.",
    18: "In which they found me occupied in the temple, having been purified — without any crowd or uproar. But there were certain Jews from Asia,",
    19: "who ought to have been present before you, and to make accusation, should they have anything against me.",
    20: "Or else let these men themselves tell what misdeed they found when I stood before the Council,",
    21: "other than for this one statement which I shouted out while standing among them: 'For the resurrection of the dead I am on trial before you today!'\"",
    22: "But Felix, having a more exact knowledge about the Way, put them off, saying, \"When Lysias the commander comes down, I will decide your case.\"",
    23: "And he gave orders to the centurion for him to be kept in custody and yet have some freedom — and not to prevent any of his friends from ministering to him.",
    24: "But some days later, Felix arrived with Drusilla his wife, who was a Jewess — and sent for Paul, and heard him speak about faith in Christ Jesus.",
    25: "And as he was discussing righteousness, self-control, and the judgment to come, Felix became frightened and said, \"Go away for the present, and when I find time, I will summon you.\"",
    26: "At the same time he was also hoping that money would be given him by Paul — therefore he also used to send for him quite often, and converse with him.",
    27: "But after two years had passed, Felix was succeeded by Porcius Festus — and wishing to do the Jews a favor, Felix left Paul imprisoned.",
}
ch25 = {
    1: "Festus therefore, having arrived in the province, three days later went up to Jerusalem from Caesarea.",
    2: "And the chief priests and the leading men of the Jews brought charges against Paul — and they were urging him,",
    3: "requesting a concession against Paul — that he might have him brought to Jerusalem. (At the same time, setting an ambush to kill him on the way.)",
    4: "Festus then answered that Paul was being kept in custody at Caesarea — and that he himself was about to leave shortly.",
    5: "\"Therefore,\" he said, \"let the influential men among you go down with me — and if there is anything wrong about the man, let them prosecute him.\"",
    6: "And after he had spent not more than eight or ten days among them, he went down to Caesarea — and on the next day he took his seat on the tribunal, and ordered Paul to be brought.",
    7: "And after Paul arrived, the Jews who had come down from Jerusalem stood around him — bringing many and serious charges against him, which they could not prove.",
    8: "And Paul said in his own defense: \"I have committed no offense either against the Law of the Jews, or against the temple, or against Caesar.\"",
    9: "But Festus, wishing to do the Jews a favor, answered Paul and said, \"Are you willing to go up to Jerusalem and stand trial before me on these charges?\"",
    10: "But Paul said: \"I am standing before Caesar's tribunal, where I ought to be tried. I have done no wrong to the Jews, as you also very well know.",
    11: "If, then, I am a wrongdoer, and have committed anything worthy of death, I do not refuse to die. But if none of those things is true of which these men accuse me — no one can hand me over to them. I appeal to Caesar.\"",
    12: "Then Festus, when he had conferred with his council, answered, \"You have appealed to Caesar. To Caesar you shall go.\"",
    13: "Now after several days had passed, King Agrippa and Bernice arrived at Caesarea, having come to pay their respects to Festus.",
    14: "And while they were spending many days there, Festus laid Paul's case before the king, saying, \"There is a certain man left as a prisoner by Felix.",
    15: "And when I was at Jerusalem, the chief priests and the elders of the Jews brought charges against him — asking for a sentence of condemnation against him.",
    16: "And I answered them that it is not the custom of the Romans to hand over any man before the accused meets his accusers face to face — and has an opportunity to make his defense against the charges.",
    17: "Therefore, when they had assembled here, without delay I took my seat on the tribunal the next day and ordered the man to be brought.",
    18: "And when the accusers stood up, they began bringing charges against him — not of such crimes as I was expecting.",
    19: "But they simply had some points of disagreement with him about their own religion, and about a certain dead man, Jesus — whom Paul asserted to be alive.",
    20: "And being at a loss how to investigate such matters, I asked whether he was willing to go to Jerusalem and there stand trial on these matters.",
    21: "But when Paul appealed to be held in custody for the Emperor's decision, I ordered him to be kept in custody until I send him to Caesar.\"",
    22: "And Agrippa said to Festus, \"I also would like to hear the man myself.\" \"Tomorrow,\" he said, \"you shall hear him.\"",
    23: "And so on the next day, when Agrippa came together with Bernice amid great pomp, and entered the auditorium — accompanied by the commanders and the prominent men of the city — at the command of Festus, Paul was brought in.",
    24: "And Festus said: \"King Agrippa, and all you gentlemen here present with us — you behold this man about whom all the people of the Jews appealed to me, both at Jerusalem and here, loudly declaring that he ought not to live any longer.",
    25: "But I found that he had committed nothing worthy of death. And since he himself appealed to the Emperor, I decided to send him.",
    26: "But I have nothing definite about him to write to my lord. Therefore I have brought him before you all — and especially before you, King Agrippa — so that, after the investigation has taken place, I may have something to write.",
    27: "For it seems absurd to me, in sending a prisoner, not to indicate also the charges against him.\"",
}
ch26 = {
    1: "And Agrippa said to Paul, \"You are permitted to speak for yourself.\" Then Paul stretched out his hand and proceeded to make his defense:",
    2: "\"In regard to all the things of which I am accused by the Jews, I consider myself fortunate, King Agrippa, that I am about to make my defense before you today.",
    3: "Especially because you are an expert in all customs and questions among the Jews — therefore I beg you to listen to me patiently.",
    4: "So then, all Jews know my manner of life from my youth up — which from the beginning was spent among my own nation, and at Jerusalem.",
    5: "Since they have known about me for a long time — if they are willing to testify — that I lived as a Pharisee according to the strictest sect of our religion.",
    6: "And now I am standing trial for the hope of the promise made by God to our fathers —",
    7: "the promise to which our twelve tribes hope to attain — as they earnestly serve God night and day. And for this hope, O King, I am being accused by the Jews.",
    8: "Why is it considered incredible among you people if God does raise the dead?",
    9: "So then, I thought to myself that I had to do many things hostile to the name of Jesus of Nazareth.",
    10: "And this is just what I did in Jerusalem. Not only did I lock up many of the saints in prisons, having received authority from the chief priests — but also when they were being put to death, I cast my vote against them.",
    11: "And as I punished them often in all the synagogues, I tried to force them to blaspheme. And being furiously enraged at them, I kept pursuing them even to foreign cities.",
    12: "While thus engaged, as I was journeying to Damascus with the authority and commission of the chief priests,",
    13: "at midday, O King, I saw on the way a light from heaven, brighter than the sun, shining all around me and those who were journeying with me.",
    14: "And when we had all fallen to the ground, I heard a voice saying to me in the Hebrew dialect: 'Saul, Saul, why are you persecuting Me? It is hard for you to kick against the goads.'",
    15: "And I said, 'Who are You, Lord?' And the Lord said, 'I am Jesus whom you are persecuting.",
    16: "But arise, and stand on your feet. For this purpose I have appeared to you — to appoint you a minister and a witness, not only to the things which you have seen, but also to the things in which I will appear to you.",
    17: "Delivering you from the Jewish people, and from the Gentiles — to whom I am sending you,",
    18: "to open their eyes — so that they may turn from darkness to light, and from the power of Satan to God, in order that they may receive forgiveness of sins, and an inheritance among those who have been sanctified by faith in Me.'",
    19: "Consequently, King Agrippa, I did not prove disobedient to the heavenly vision.",
    20: "But kept declaring both to those of Damascus first, and also at Jerusalem, and then throughout all the region of Judea, and even to the Gentiles — that they should repent and turn to God, performing deeds appropriate to repentance.",
    21: "For this reason some Jews seized me in the temple and tried to put me to death.",
    22: "And so, having obtained help from God, I stand to this day testifying both to small and great — stating nothing but what the Prophets and Moses said was going to take place.",
    23: "That the Christ was to suffer, and that by reason of His resurrection from the dead He would be the first to proclaim light both to the Jewish people and to the Gentiles.\"",
    24: "And while Paul was saying this in his defense, Festus said in a loud voice, \"Paul, you are out of your mind! Your great learning is driving you mad.\"",
    25: "But Paul said, \"I am not out of my mind, most excellent Festus — but I utter words of sober truth.",
    26: "For the king knows about these matters — and to him I speak with confidence, since I am persuaded that none of these things escape his notice. For this has not been done in a corner.",
    27: "King Agrippa, do you believe the Prophets? I know that you do.\"",
    28: "And Agrippa replied to Paul, \"In a short time you will persuade me to become a Christian.\"",
    29: "And Paul said, \"I would to God, that whether in a short or long time, not only you, but also all who hear me this day, might become such as I am — except for these chains.\"",
    30: "And the king arose, and the governor, and Bernice — and those who were sitting with them.",
    31: "And when they had withdrawn, they began talking to one another, saying, \"This man is not doing anything worthy of death or imprisonment.\"",
    32: "And Agrippa said to Festus, \"This man might have been set free if he had not appealed to Caesar.\"",
}
ch27 = {
    1: "And when it was decided that we should sail for Italy, they proceeded to deliver Paul and some other prisoners to a centurion of the Augustan cohort, named Julius.",
    2: "And embarking in an Adramyttian ship, which was about to sail to the regions along the coast of Asia, we put out to sea — accompanied by Aristarchus, a Macedonian of Thessalonica.",
    3: "And the next day we put in at Sidon. And Julius treated Paul with consideration, and allowed him to go to his friends and receive care.",
    4: "And from there we put out to sea and sailed under the shelter of Cyprus — because the winds were contrary.",
    5: "And when we had sailed through the sea along the coast of Cilicia and Pamphylia, we landed at Myra in Lycia.",
    6: "And there the centurion found an Alexandrian ship sailing for Italy — and he put us aboard it.",
    7: "And when we had sailed slowly for a good many days, and with difficulty had arrived off Cnidus — since the wind did not permit us to go farther, we sailed under the shelter of Crete, off Salmone.",
    8: "And with difficulty sailing past it, we came to a certain place called Fair Havens — near which was the city of Lasea.",
    9: "And when considerable time had passed, and the voyage was now dangerous, since even the fast was already over, Paul began to admonish them,",
    10: "and said to them, \"Men, I perceive that the voyage will certainly be with damage and great loss — not only of the cargo and the ship, but also of our lives.\"",
    11: "But the centurion was more persuaded by the pilot and the captain of the ship, than by what was being said by Paul.",
    12: "And because the harbor was not suitable for wintering, the majority reached a decision to put out to sea from there — if somehow they could reach Phoenix, a harbor of Crete, looking northeast and southeast, and spend the winter there.",
    13: "And when a moderate south wind came up, supposing that they had attained their purpose, they weighed anchor and began sailing along Crete, close inshore.",
    14: "But before very long there rushed down from the land a violent wind, called Euraquilo.",
    15: "And when the ship was caught in it, and could not face the wind, we gave way to it and let ourselves be driven along.",
    16: "And running under the shelter of a small island called Clauda, we were scarcely able to get the ship's boat under control.",
    17: "And after they had hoisted it up, they used supporting cables in undergirding the ship. And fearing that they might run aground on the shallows of Syrtis, they let down the sea anchor — and so let themselves be driven along.",
    18: "And the next day as we were being violently storm-tossed, they began to jettison the cargo.",
    19: "And on the third day they threw the ship's tackle overboard with their own hands.",
    20: "And since neither sun nor stars appeared for many days, and no small storm was assailing us — from then on all hope of our being saved was gradually abandoned.",
    21: "And when they had gone a long time without food, then Paul stood up in their midst and said: \"Men, you ought to have followed my advice, and not have set sail from Crete, and incurred this damage and loss.",
    22: "And yet now I urge you to keep up your courage — for there shall be no loss of life among you, but only of the ship.",
    23: "For this very night an angel of the God to whom I belong, and whom I serve, stood before me —",
    24: "saying, 'Do not be afraid, Paul. You must stand before Caesar. And behold, God has granted you all those who are sailing with you.'",
    25: "Therefore, keep up your courage, men — for I believe God that it will turn out exactly as I have been told.",
    26: "But we must run aground on a certain island.\"",
    27: "But when the fourteenth night had come, as we were being driven about in the Adriatic Sea, about midnight the sailors began to surmise that they were approaching some land.",
    28: "And they took soundings, and found it to be twenty fathoms. And a little farther on they took another sounding, and found it to be fifteen fathoms.",
    29: "And fearing that we might run aground somewhere on the rocks, they cast four anchors from the stern, and wished for daybreak.",
    30: "And as the sailors were trying to escape from the ship, and had let down the ship's boat into the sea — on the pretense that they were going to lay out anchors from the bow,",
    31: "Paul said to the centurion and to the soldiers, \"Unless these men remain in the ship, you yourselves cannot be saved.\"",
    32: "Then the soldiers cut away the ropes of the ship's boat, and let it fall away.",
    33: "And until the day was about to dawn, Paul was encouraging them all to take some food, saying, \"Today is the fourteenth day that you have been constantly watching and going without eating, having taken nothing.",
    34: "Therefore I encourage you to take some food — for this is for your preservation. For not a hair from the head of any of you shall perish.\"",
    35: "And having said this, he took bread and gave thanks to God in the presence of all — and he broke it and began to eat.",
    36: "And all of them were encouraged, and they themselves also took food.",
    37: "And all of us in the ship were two hundred and seventy-six persons.",
    38: "And when they had eaten enough, they began to lighten the ship by throwing out the wheat into the sea.",
    39: "And when day came, they could not recognize the land — but they did observe a certain bay with a beach, and they resolved to drive the ship onto it if they could.",
    40: "And casting off the anchors, they left them in the sea while at the same time they were loosening the ropes of the rudders. And hoisting the foresail to the wind, they were heading for the beach.",
    41: "But striking a reef where two seas met, they ran the vessel aground — and the prow stuck fast and remained immovable. But the stern began to be broken up by the force of the waves.",
    42: "And the soldiers' counsel was to kill the prisoners — so that none of them should swim away and escape.",
    43: "But the centurion, wanting to bring Paul safely through, kept them from their intention — and commanded that those who could swim should jump overboard first and get to land.",
    44: "And the rest should follow — some on planks, and others on various things from the ship. And thus it happened that they all were brought safely to land.",
}
ch28 = {
    1: "And when they had been brought safely through, then we found out that the island was called Malta.",
    2: "And the natives showed us extraordinary kindness — for because of the rain that had set in, and because of the cold, they kindled a fire and received us all.",
    3: "But when Paul had gathered a bundle of sticks and laid them on the fire, a viper came out because of the heat and fastened itself on his hand.",
    4: "And when the natives saw the creature hanging from his hand, they began saying to one another, \"Undoubtedly this man is a murderer — and though he has been saved from the sea, justice has not allowed him to live.\"",
    5: "However he shook the creature off into the fire and suffered no harm.",
    6: "But they were expecting that he was about to swell up, or suddenly fall down dead. But after they had waited a long time and had seen nothing unusual happen to him, they changed their minds and began to say that he was a god.",
    7: "Now in the neighborhood of that place were lands belonging to the leading man of the island, named Publius — who welcomed us and entertained us courteously three days.",
    8: "And it came about that the father of Publius was lying in bed, afflicted with recurrent fever and dysentery. And Paul went in to see him — and after he had prayed, he laid his hands on him and healed him.",
    9: "And after this had happened, the rest of the people on the island who had diseases were coming to him and getting cured.",
    10: "And they also honored us with many marks of respect — and when we were setting sail, they supplied us with all we needed.",
    11: "And at the end of three months we set sail on an Alexandrian ship which had wintered at the island — and which had the Twin Brothers for its figurehead.",
    12: "And after we put in at Syracuse, we stayed there for three days.",
    13: "And from there we sailed around and arrived at Rhegium — and a day later a south wind sprang up, and on the second day we came to Puteoli.",
    14: "There we found some brothers, and were invited to stay with them for seven days — and thus we came to Rome.",
    15: "And the brothers, when they heard about us, came from there as far as the Market of Appius and the Three Inns to meet us. And when Paul saw them, he thanked God and took courage.",
    16: "And when we entered Rome, Paul was allowed to stay by himself, with the soldier who was guarding him.",
    17: "And it came about that after three days he called together those who were the leading men of the Jews — and when they had come together, he began saying to them: \"Brothers, though I had done nothing against our people, or the customs of our fathers, yet I was delivered as a prisoner from Jerusalem into the hands of the Romans.",
    18: "And when they had examined me, they were willing to release me — because there was no ground for putting me to death.",
    19: "But when the Jews objected, I was forced to appeal to Caesar — not that I had any accusation against my nation.",
    20: "For this reason therefore, I requested to see you and to speak with you — for I am wearing this chain for the sake of the hope of Israel.\"",
    21: "And they said to him, \"We have neither received letters from Judea concerning you, nor have any of the brothers come here and reported or spoken anything bad about you.",
    22: "But we desire to hear from you what your views are — for concerning this sect, it is known to us that it is spoken against everywhere.\"",
    23: "And when they had set a day for him, they came to him at his lodging in large numbers — and he was explaining to them by solemnly testifying about the kingdom of God, and trying to persuade them concerning Jesus, from both the Law of Moses and from the Prophets, from morning until evening.",
    24: "And some were being persuaded by the things spoken — but others would not believe.",
    25: "And when they did not agree with one another, they began leaving after Paul had spoken one parting word: \"The Holy Spirit rightly spoke through Isaiah the prophet to your fathers,",
    26: "saying: 'Go to this people and say, You will keep on hearing, but will not understand — and you will keep on seeing, but will not perceive.",
    27: "For the heart of this people has become dull, and with their ears they scarcely hear, and they have closed their eyes — lest they should see with their eyes, and hear with their ears, and understand with their heart, and return, and I should heal them.'",
    28: "Therefore let it be known to you, that this salvation of God has been sent to the Gentiles — they will also listen.\"",
    29: "(Some manuscripts add at this point: \"And when he had said these things, the Jews departed, having a great dispute among themselves.\")",
    30: "And he stayed two full years in his own rented quarters — and was welcoming all who came to him,",
    31: "preaching the kingdom of God, and teaching concerning the Lord Jesus Christ with all openness, unhindered.",
}
CHAPTERS = {20: ch20, 21: ch21, 22: ch22, 23: ch23, 24: ch24,
            25: ch25, 26: ch26, 27: ch27, 28: ch28}

def main():
    new_entries = {f"44_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Acts 20-28 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Acts 20-28 verses")

if __name__ == "__main__":
    main()
