"""MBT Hebrews — 13 chapters, 303 verses. Book ID 58."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch1 = {
    1: "God, after He spoke long ago to the fathers in the prophets — in many parts and in many ways —",
    2: "in these last days has spoken to us in His Son. He appointed Him heir of all things, through whom He also made the world.",
    3: "And He is the radiance of His glory, and the exact representation of His nature — and He upholds all things by the word of His power. When He had made purification of sins, He sat down at the right hand of the Majesty on high.",
    4: "Having become as much better than the angels, as He has inherited a more excellent name than they.",
    5: "For to which of the angels did He ever say, \"You are My Son, today I have begotten You\"? And again, \"I will be a Father to Him, and He shall be a Son to Me\"?",
    6: "And when He again brings the firstborn into the world, He says, \"And let all the angels of God worship Him.\"",
    7: "And of the angels He says, \"He makes His angels winds, and His ministers a flame of fire.\"",
    8: "But of the Son He says, \"Your throne, O God, is forever and ever — and the scepter of righteousness is the scepter of His kingdom.",
    9: "You have loved righteousness and hated lawlessness — therefore God, Your God, has anointed You with the oil of gladness above Your companions.\"",
    10: "And, \"In the beginning, O Lord, You laid the foundation of the earth — and the heavens are the works of Your hands.",
    11: "They will perish, but You remain — and they all will become old like a garment;",
    12: "and like a robe You will roll them up; like a garment they will also be changed. But You are the same — and Your years will not come to an end.\"",
    13: "But to which of the angels has He ever said, \"Sit at My right hand, until I make Your enemies a footstool for Your feet\"?",
    14: "Are they not all ministering spirits — sent out to render service for the sake of those who will inherit salvation?",
}
ch2 = {
    1: "For this reason we must pay much closer attention to what we have heard — so that we do not drift away from it.",
    2: "For if the word spoken through angels proved unalterable, and every transgression and disobedience received a just penalty,",
    3: "how will we escape if we neglect so great a salvation? — which at the first was spoken through the Lord, and was confirmed to us by those who heard,",
    4: "while God also testified along with them — both by signs and wonders, and by various miracles, and by gifts of the Holy Spirit, distributed according to His will.",
    5: "For He did not subject to angels the world to come — concerning which we are speaking.",
    6: "But one has testified somewhere, saying, \"What is man, that You remember him? Or the son of man, that You are concerned about him?",
    7: "You made him for a little while lower than the angels. You crowned him with glory and honor — and appointed him over the works of Your hands.",
    8: "You have put all things in subjection under his feet.\" For in subjecting all things to him, He left nothing that is not subject to him. But now we do not yet see all things subjected to him.",
    9: "But we do see Him — Jesus, who was made for a little while lower than the angels — namely, Jesus, because of the suffering of death, crowned with glory and honor; so that by the grace of God, He might taste death for everyone.",
    10: "For it was fitting for Him — for whom are all things, and through whom are all things — in bringing many sons to glory, to perfect the author of their salvation through sufferings.",
    11: "For both He who sanctifies and those who are sanctified are all from one Father — for which reason He is not ashamed to call them brothers,",
    12: "saying, \"I will declare Your name to My brothers — in the midst of the assembly I will sing Your praise.\"",
    13: "And again, \"I will put My trust in Him.\" And again, \"Behold, I and the children whom God has given Me.\"",
    14: "Therefore, since the children share in flesh and blood — He Himself likewise also partook of the same — so that through death He might render powerless him who had the power of death, that is, the devil.",
    15: "And free those who through fear of death were subject to slavery all their lives.",
    16: "For assuredly He does not give help to angels — but He gives help to the descendants of Abraham.",
    17: "Therefore He had to be made like His brothers in all things — so that He might become a merciful and faithful high priest in things pertaining to God, to make propitiation for the sins of the people.",
    18: "For since He Himself was tempted in that which He has suffered — He is able to come to the aid of those who are tempted.",
}
ch3 = {
    1: "Therefore, holy brothers — partakers of a heavenly calling — consider Jesus, the Apostle and High Priest of our confession.",
    2: "He was faithful to Him who appointed Him — as Moses also was in all His house.",
    3: "For He has been counted worthy of more glory than Moses, by just so much as the builder of the house has more honor than the house.",
    4: "For every house is built by someone — but the builder of all things is God.",
    5: "And Moses was faithful in all God's house, as a servant — for a testimony of those things which were to be spoken later.",
    6: "But Christ was faithful as a Son over His house — whose house we are, if we hold fast our confidence and the boast of our hope firm until the end.",
    7: "Therefore, just as the Holy Spirit says: \"Today, if you hear His voice,",
    8: "do not harden your hearts as when they provoked Me — as in the day of trial in the wilderness,",
    9: "where your fathers tried Me by testing Me — and saw My works for forty years.",
    10: "Therefore I was angry with this generation — and said, 'They always go astray in their heart, and they did not know My ways.'",
    11: "As I swore in My wrath: 'They shall not enter My rest.'\"",
    12: "Take care, brothers, that there not be in any one of you an evil, unbelieving heart that falls away from the living God.",
    13: "But encourage one another day after day — as long as it is still called \"Today\" — so that none of you will be hardened by the deceitfulness of sin.",
    14: "For we have become partakers of Christ — if we hold fast the beginning of our assurance firm until the end.",
    15: "While it is said, \"Today if you hear His voice, do not harden your hearts, as when they provoked Me.\"",
    16: "For who provoked Him when they had heard? Indeed, was it not all those who came out of Egypt led by Moses?",
    17: "And with whom was He angry for forty years? Was it not with those who sinned — whose bodies fell in the wilderness?",
    18: "And to whom did He swear that they would not enter His rest, but to those who were disobedient?",
    19: "So we see that they were not able to enter because of unbelief.",
}
ch4 = {
    1: "Therefore, let us fear if, while a promise remains of entering His rest, any one of you may seem to have come short of it.",
    2: "For indeed we have had good news preached to us, just as they also did. But the word they heard did not profit them — because it was not united by faith in those who heard.",
    3: "For we who have believed enter that rest — just as He has said, \"As I swore in My wrath, they shall not enter My rest\" — although His works were finished from the foundation of the world.",
    4: "For He has said somewhere concerning the seventh day: \"And God rested on the seventh day from all His works.\"",
    5: "And again in this passage, \"They shall not enter My rest.\"",
    6: "Therefore, since it remains for some to enter it — and those who formerly had good news preached to them did not enter because of disobedience —",
    7: "He again fixes a certain day, \"Today,\" saying through David — after so long a time — just as has been said before: \"Today if you hear His voice, do not harden your hearts.\"",
    8: "For if Joshua had given them rest, He would not have spoken of another day after that.",
    9: "So there remains a Sabbath rest for the people of God.",
    10: "For the one who has entered His rest has himself also rested from his works — as God did from His.",
    11: "Therefore let us be diligent to enter that rest — so that no one will fall by following the same example of disobedience.",
    12: "For the word of God is living and active, and sharper than any two-edged sword — piercing as far as the division of soul and spirit, of both joints and marrow — and able to judge the thoughts and intentions of the heart.",
    13: "And there is no creature hidden from His sight — but all things are open and laid bare to the eyes of Him with whom we have to do.",
    14: "Therefore, since we have a great High Priest who has passed through the heavens — Jesus the Son of God — let us hold fast our confession.",
    15: "For we do not have a High Priest who cannot sympathize with our weaknesses — but One who has been tempted in all things as we are, yet without sin.",
    16: "Therefore let us draw near with confidence to the throne of grace — so that we may receive mercy and find grace to help in time of need.",
}
ch5 = {
    1: "For every high priest taken from among men is appointed on behalf of men in things pertaining to God — to offer both gifts and sacrifices for sins.",
    2: "He can deal gently with the ignorant and misguided — since he himself also is beset with weakness.",
    3: "And because of it, he is obligated to offer sacrifices for sins, as for the people, so also for himself.",
    4: "And no one takes the honor to himself — but he receives it when he is called by God, even as Aaron was.",
    5: "So also Christ did not glorify Himself so as to become a high priest — but He who said to Him, \"You are My Son; today I have begotten You.\"",
    6: "Just as He says also in another passage, \"You are a priest forever, according to the order of Melchizedek.\"",
    7: "In the days of His flesh, He offered up both prayers and supplications, with loud crying and tears, to the One able to save Him from death — and He was heard because of His piety.",
    8: "Although He was a Son, He learned obedience from the things which He suffered.",
    9: "And having been made perfect, He became to all those who obey Him the source of eternal salvation —",
    10: "being designated by God as a high priest according to the order of Melchizedek.",
    11: "Concerning him we have much to say — and it is hard to explain, since you have become dull of hearing.",
    12: "For though by this time you ought to be teachers, you have need again for someone to teach you the elementary principles of the oracles of God. And you have come to need milk and not solid food.",
    13: "For everyone who partakes only of milk is unaccustomed to the word of righteousness — for he is an infant.",
    14: "But solid food is for the mature — who because of practice have their senses trained to discern good and evil.",
}
ch6 = {
    1: "Therefore leaving the elementary teaching about the Christ, let us press on to maturity — not laying again a foundation of repentance from dead works, and of faith toward God,",
    2: "of instruction about washings, and laying on of hands, and the resurrection of the dead, and eternal judgment.",
    3: "And this we will do, if God permits.",
    4: "For in the case of those who have once been enlightened — and have tasted the heavenly gift, and have been made partakers of the Holy Spirit,",
    5: "and have tasted the good word of God, and the powers of the age to come,",
    6: "and then have fallen away — it is impossible to renew them again to repentance, since they again crucify to themselves the Son of God, and put Him to open shame.",
    7: "For ground that drinks the rain which often falls on it, and brings forth vegetation useful to those for whose sake it is also tilled — receives a blessing from God.",
    8: "But if it yields thorns and thistles, it is worthless and close to being cursed — and it ends up being burned.",
    9: "But, beloved, we are convinced of better things concerning you — and things that accompany salvation, though we are speaking in this way.",
    10: "For God is not unjust so as to forget your work and the love which you have shown toward His name — in having ministered to the saints, and in still ministering.",
    11: "And we desire that each one of you show the same diligence — so as to realize the full assurance of hope until the end.",
    12: "So that you will not be sluggish — but imitators of those who through faith and patience inherit the promises.",
    13: "For when God made the promise to Abraham — since He could swear by no one greater, He swore by Himself,",
    14: "saying, \"I will surely bless you, and I will surely multiply you.\"",
    15: "And so, having patiently waited, he obtained the promise.",
    16: "For men swear by one greater than themselves — and with them an oath given as confirmation is an end of every dispute.",
    17: "In the same way, God, desiring even more to show to the heirs of the promise the unchangeableness of His purpose, interposed with an oath —",
    18: "so that by two unchangeable things, in which it is impossible for God to lie, we who have taken refuge would have strong encouragement to take hold of the hope set before us.",
    19: "This hope we have as an anchor of the soul — both sure and steadfast, and one which enters within the veil,",
    20: "where Jesus has entered as a forerunner for us — having become a high priest forever according to the order of Melchizedek.",
}
ch7 = {
    1: "For this Melchizedek — king of Salem, priest of the Most High God — who met Abraham as he was returning from the slaughter of the kings, and blessed him,",
    2: "to whom Abraham also apportioned a tenth of all the spoils — was first of all, by translation of his name, king of righteousness; and then also king of Salem, which is king of peace.",
    3: "Without father, without mother, without genealogy — having neither beginning of days nor end of life — but made like the Son of God, he remains a priest perpetually.",
    4: "Now observe how great this man was, to whom Abraham, the patriarch, gave a tenth of the choicest spoils.",
    5: "And those indeed of the sons of Levi who receive the priest's office have commandment in the Law to collect a tenth from the people — that is, from their brothers, although these are descended from Abraham.",
    6: "But the one whose genealogy is not traced from them collected a tenth from Abraham — and blessed the one who had the promises.",
    7: "But without any dispute, the lesser is blessed by the greater.",
    8: "And in this case mortal men receive tithes — but in that case, one receives them, of whom it is witnessed that he lives on.",
    9: "And, so to speak, through Abraham even Levi — who received tithes — paid tithes,",
    10: "for he was still in the loins of his father when Melchizedek met him.",
    11: "Now if perfection had been through the Levitical priesthood — for on the basis of it the people received the Law — what further need was there for another priest to arise according to the order of Melchizedek, and not be designated according to the order of Aaron?",
    12: "For when the priesthood is changed, of necessity there takes place a change of law also.",
    13: "For the One concerning whom these things are spoken belongs to another tribe — from which no one has officiated at the altar.",
    14: "For it is evident that our Lord was descended from Judah — a tribe with reference to which Moses spoke nothing concerning priests.",
    15: "And this is clearer still — if another priest arises according to the likeness of Melchizedek,",
    16: "who has become such not on the basis of a law of physical requirement — but according to the power of an indestructible life.",
    17: "For it is attested of Him, \"You are a priest forever according to the order of Melchizedek.\"",
    18: "For, on the one hand, there is a setting aside of a former commandment — because of its weakness and uselessness",
    19: "(for the Law made nothing perfect) — and on the other hand, there is the bringing in of a better hope, through which we draw near to God.",
    20: "And inasmuch as it was not without an oath",
    21: "(for they indeed became priests without an oath, but He with an oath through the One who said to Him: \"The Lord has sworn, and will not change His mind: 'You are a priest forever' \") —",
    22: "so much the more also, Jesus has become the guarantee of a better covenant.",
    23: "And the former priests, on the one hand, existed in greater numbers because they were prevented by death from continuing.",
    24: "But Jesus, on the other hand, because He continues forever, holds His priesthood permanently.",
    25: "Therefore He is able also to save forever those who draw near to God through Him — since He always lives to make intercession for them.",
    26: "For it was fitting for us to have such a high priest — holy, innocent, undefiled, separated from sinners, and exalted above the heavens.",
    27: "Who does not need daily, like those high priests, to offer up sacrifices, first for His own sins, and then for the sins of the people — because this He did once for all when He offered up Himself.",
    28: "For the Law appoints men as high priests who are weak — but the word of the oath, which came after the Law, appoints a Son, made perfect forever.",
}
ch8 = {
    1: "Now the main point in what has been said is this: we have such a high priest — One who has taken His seat at the right hand of the throne of the Majesty in the heavens,",
    2: "a minister in the sanctuary and in the true tabernacle — which the Lord pitched, not man.",
    3: "For every high priest is appointed to offer both gifts and sacrifices — therefore it is necessary that this priest also have something to offer.",
    4: "Now if He were on earth, He would not be a priest at all — since there are those who offer the gifts according to the Law,",
    5: "who serve a copy and shadow of the heavenly things. As Moses was warned by God when he was about to erect the tabernacle: \"See,\" He says, \"that you make all things according to the pattern which was shown you on the mountain.\"",
    6: "But now He has obtained a more excellent ministry — by as much as He is also the mediator of a better covenant, which has been enacted on better promises.",
    7: "For if that first covenant had been faultless, there would have been no occasion sought for a second.",
    8: "For finding fault with them, He says: \"Behold, days are coming, says the Lord — when I will effect a new covenant with the house of Israel and with the house of Judah.",
    9: "Not like the covenant which I made with their fathers — on the day when I took them by the hand to lead them out of the land of Egypt. For they did not continue in My covenant, and I did not care for them, says the Lord.",
    10: "For this is the covenant that I will make with the house of Israel after those days, says the Lord: I will put My laws into their minds, and I will write them on their hearts. And I will be their God, and they shall be My people.",
    11: "And they shall not teach everyone his fellow citizen, and everyone his brother, saying, 'Know the Lord' — for all will know Me, from the least to the greatest of them.",
    12: "For I will be merciful to their iniquities, and I will remember their sins no more.\"",
    13: "When He said, \"A new covenant,\" He has made the first obsolete. But whatever is becoming obsolete and growing old is ready to disappear.",
}
ch9 = {
    1: "Now even the first covenant had regulations of divine worship and the earthly sanctuary.",
    2: "For there was a tabernacle prepared — the outer one — in which were the lampstand, and the table, and the consecrated bread; this is called the holy place.",
    3: "And behind the second veil there was a tabernacle, which is called the Holy of Holies —",
    4: "having a golden altar of incense, and the ark of the covenant covered on all sides with gold; in which was a golden jar holding the manna, and Aaron's rod which budded, and the tablets of the covenant.",
    5: "And above it were the cherubim of glory, overshadowing the mercy seat — but of these things we cannot now speak in detail.",
    6: "Now when these things have been so prepared, the priests are continually entering the outer tabernacle, performing the divine worship.",
    7: "But into the second, only the high priest enters — once a year, not without taking blood, which he offers for himself, and for the sins of the people committed in ignorance.",
    8: "The Holy Spirit is signifying this: that the way into the holy place has not yet been disclosed — while the outer tabernacle is still standing.",
    9: "Which is a symbol for the present time — according to which both gifts and sacrifices are offered, which cannot make the worshiper perfect in conscience —",
    10: "since they relate only to food and drink and various washings — regulations for the body imposed until a time of reformation.",
    11: "But when Christ appeared as a high priest of the good things to come — He entered through the greater and more perfect tabernacle, not made with hands, that is, not of this creation;",
    12: "and not through the blood of goats and calves, but through His own blood — He entered the holy place once for all, having obtained eternal redemption.",
    13: "For if the blood of goats and bulls — and the ashes of a heifer sprinkling those who have been defiled — sanctify for the cleansing of the flesh,",
    14: "how much more will the blood of Christ — who through the eternal Spirit offered Himself without blemish to God — cleanse your conscience from dead works to serve the living God?",
    15: "And for this reason He is the mediator of a new covenant — so that, since a death has taken place for the redemption of the transgressions that were committed under the first covenant, those who have been called may receive the promise of the eternal inheritance.",
    16: "For where a covenant is, there must of necessity be the death of the one who made it.",
    17: "For a covenant is valid only when men are dead — for it is never in force while the one who made it lives.",
    18: "Therefore, even the first covenant was not inaugurated without blood.",
    19: "For when every commandment had been spoken by Moses to all the people according to the Law, he took the blood of calves and goats, with water, and scarlet wool, and hyssop — and sprinkled both the book itself and all the people,",
    20: "saying, \"This is the blood of the covenant which God commanded you.\"",
    21: "And in the same way he sprinkled both the tabernacle and all the vessels of the ministry with the blood.",
    22: "And according to the Law, one may almost say all things are cleansed with blood — and without shedding of blood there is no forgiveness.",
    23: "Therefore it was necessary for the copies of the things in the heavens to be cleansed with these — but the heavenly things themselves with better sacrifices than these.",
    24: "For Christ did not enter a holy place made with hands — a mere copy of the true one — but into heaven itself, now to appear in the presence of God for us.",
    25: "Nor was it that He would offer Himself often — as the high priest enters the holy place year by year with blood that is not his own.",
    26: "Otherwise He would have needed to suffer often since the foundation of the world. But now once at the consummation of the ages, He has been manifested to put away sin by the sacrifice of Himself.",
    27: "And inasmuch as it is appointed for men to die once — and after this comes judgment —",
    28: "so Christ also, having been offered once to bear the sins of many, will appear a second time for salvation, without reference to sin, to those who eagerly await Him.",
}
ch10 = {
    1: "For the Law, since it has only a shadow of the good things to come, and not the very form of things — can never, by the same sacrifices which they offer continually year by year, make perfect those who draw near.",
    2: "Otherwise, would they not have ceased to be offered? — because the worshipers, having once been cleansed, would no longer have had consciousness of sins.",
    3: "But in those sacrifices there is a reminder of sins year by year.",
    4: "For it is impossible for the blood of bulls and goats to take away sins.",
    5: "Therefore, when He comes into the world, He says: \"Sacrifice and offering You have not desired — but a body You have prepared for Me.",
    6: "In whole burnt offerings and sacrifices for sin You have taken no pleasure.",
    7: "Then I said, 'Behold, I have come (in the scroll of the book it is written of Me) to do Your will, O God.'\"",
    8: "After saying above, \"Sacrifices and offerings and whole burnt offerings and sacrifices for sin You have not desired — nor have You taken pleasure in them\" (which are offered according to the Law),",
    9: "then He said, \"Behold, I have come to do Your will.\" He takes away the first in order to establish the second.",
    10: "By this will we have been sanctified — through the offering of the body of Jesus Christ once for all.",
    11: "And every priest stands daily ministering and offering time after time the same sacrifices, which can never take away sins.",
    12: "But He, having offered one sacrifice for sins for all time, sat down at the right hand of God —",
    13: "from then on waiting until His enemies are made a footstool for His feet.",
    14: "For by one offering He has perfected for all time those who are sanctified.",
    15: "And the Holy Spirit also testifies to us. For after saying,",
    16: "\"This is the covenant that I will make with them after those days, says the Lord: I will put My laws upon their hearts, and on their mind I will write them.\"",
    17: "He then says, \"And their sins and their lawless deeds I will remember no more.\"",
    18: "Now where there is forgiveness of these things, there is no longer any offering for sin.",
    19: "Therefore, brothers — since we have confidence to enter the holy place by the blood of Jesus,",
    20: "by a new and living way which He inaugurated for us through the veil — that is, His flesh —",
    21: "and since we have a great priest over the house of God,",
    22: "let us draw near with a sincere heart, in full assurance of faith — having our hearts sprinkled clean from an evil conscience, and our bodies washed with pure water.",
    23: "Let us hold fast the confession of our hope without wavering — for He who promised is faithful.",
    24: "And let us consider how to stir up one another to love and good deeds —",
    25: "not forsaking our own assembling together, as is the habit of some — but encouraging one another, and all the more as you see the day drawing near.",
    26: "For if we go on sinning willfully after receiving the knowledge of the truth, there no longer remains a sacrifice for sins —",
    27: "but a terrifying expectation of judgment, and the fury of a fire which will consume the adversaries.",
    28: "Anyone who has set aside the Law of Moses dies without mercy on the testimony of two or three witnesses.",
    29: "How much severer punishment do you think he will deserve who has trampled underfoot the Son of God — and has regarded as unclean the blood of the covenant by which he was sanctified — and has insulted the Spirit of grace?",
    30: "For we know Him who said, \"Vengeance is Mine — I will repay.\" And again, \"The Lord will judge His people.\"",
    31: "It is a terrifying thing to fall into the hands of the living God.",
    32: "But remember the former days, when, after being enlightened, you endured a great conflict of sufferings.",
    33: "Partly by being made a public spectacle through reproaches and tribulations — and partly by becoming sharers with those who were so treated.",
    34: "For you showed sympathy to the prisoners — and accepted joyfully the seizure of your property — knowing that you have for yourselves a better and lasting possession.",
    35: "Therefore, do not throw away your confidence — which has a great reward.",
    36: "For you have need of endurance, so that when you have done the will of God, you may receive what was promised.",
    37: "For yet in a very little while, He who is coming will come, and will not delay.",
    38: "But My righteous one shall live by faith. And if he shrinks back, My soul has no pleasure in him.",
    39: "But we are not of those who shrink back to destruction — but of those who have faith to the preserving of the soul.",
}
ch11 = {
    1: "Now faith is the assurance of things hoped for — the conviction of things not seen.",
    2: "For by it the men of old gained approval.",
    3: "By faith we understand that the worlds were prepared by the word of God — so that what is seen was not made out of things which are visible.",
    4: "By faith Abel offered to God a better sacrifice than Cain — through which he was attested to be righteous; God testifying about his gifts. And through faith, though he is dead, he still speaks.",
    5: "By faith Enoch was taken up — so that he would not see death; and he was not found, because God took him up. For he obtained the witness, before his being taken up, that he was pleasing to God.",
    6: "And without faith it is impossible to please Him — for he who comes to God must believe that He is, and that He is a rewarder of those who seek Him.",
    7: "By faith Noah, being warned by God about things not yet seen — in reverence prepared an ark for the salvation of his household. By this he condemned the world, and became an heir of the righteousness which is according to faith.",
    8: "By faith Abraham, when he was called, obeyed by going out to a place which he was to receive for an inheritance — and he went out, not knowing where he was going.",
    9: "By faith he lived as an alien in the land of promise, as in a foreign land — dwelling in tents with Isaac and Jacob, fellow heirs of the same promise.",
    10: "For he was looking for the city which has foundations — whose architect and builder is God.",
    11: "By faith even Sarah herself received ability to conceive, even beyond the proper time of life — since she considered Him faithful who had promised.",
    12: "Therefore, also from one man — and him as good as dead at that — there were born descendants as many as the stars of heaven in number, and innumerable as the sand which is by the seashore.",
    13: "All these died in faith, without receiving the promises — but having seen them and welcomed them from a distance, and having confessed that they were strangers and exiles on the earth.",
    14: "For those who say such things make it clear that they are seeking a country of their own.",
    15: "And indeed if they had been thinking of that country from which they went out, they would have had opportunity to return.",
    16: "But as it is, they desire a better country — that is, a heavenly one. Therefore God is not ashamed to be called their God — for He has prepared a city for them.",
    17: "By faith Abraham, when he was tested, offered up Isaac — and he who had received the promises was offering up his only begotten son.",
    18: "It was he to whom it was said, \"In Isaac your descendants shall be called.\"",
    19: "He considered that God is able to raise people even from the dead — from which he also received him back as a type.",
    20: "By faith Isaac blessed Jacob and Esau, even regarding things to come.",
    21: "By faith Jacob, as he was dying, blessed each of the sons of Joseph — and worshiped, leaning on the top of his staff.",
    22: "By faith Joseph, when he was dying, made mention of the exodus of the sons of Israel, and gave orders concerning his bones.",
    23: "By faith Moses, when he was born, was hidden for three months by his parents — because they saw he was a beautiful child; and they were not afraid of the king's edict.",
    24: "By faith Moses, when he had grown up, refused to be called the son of Pharaoh's daughter —",
    25: "choosing rather to endure ill-treatment with the people of God, than to enjoy the passing pleasures of sin.",
    26: "Considering the reproach of Christ greater riches than the treasures of Egypt — for he was looking to the reward.",
    27: "By faith he left Egypt, not fearing the wrath of the king — for he endured, as seeing Him who is unseen.",
    28: "By faith he kept the Passover and the sprinkling of the blood — so that he who destroyed the firstborn would not touch them.",
    29: "By faith they passed through the Red Sea as on dry land — and the Egyptians, when they attempted it, were drowned.",
    30: "By faith the walls of Jericho fell down, after they had been encircled for seven days.",
    31: "By faith Rahab the prostitute did not perish along with those who were disobedient — after she had welcomed the spies in peace.",
    32: "And what more shall I say? For time will fail me if I tell of Gideon, Barak, Samson, Jephthah, of David and Samuel, and the prophets —",
    33: "who by faith conquered kingdoms, performed acts of righteousness, obtained promises, shut the mouths of lions,",
    34: "quenched the power of fire, escaped the edge of the sword. From weakness they were made strong; they became mighty in war, put foreign armies to flight.",
    35: "Women received back their dead by resurrection. And others were tortured, not accepting their release — so that they might obtain a better resurrection.",
    36: "And others experienced mockings and scourgings, and even chains and imprisonment.",
    37: "They were stoned, they were sawn in two, they were tempted, they were put to death with the sword. They went about in sheepskins, in goatskins, being destitute, afflicted, ill-treated —",
    38: "men of whom the world was not worthy. Wandering in deserts and mountains, and in caves and holes in the ground.",
    39: "And all these, having gained approval through their faith, did not receive what was promised —",
    40: "because God had provided something better for us, so that apart from us they would not be made perfect.",
}
ch12 = {
    1: "Therefore, since we have so great a cloud of witnesses surrounding us — let us also lay aside every encumbrance and the sin which so easily entangles us, and let us run with endurance the race that is set before us,",
    2: "fixing our eyes on Jesus — the author and perfecter of faith — who, for the joy set before Him, endured the cross, despising the shame, and has sat down at the right hand of the throne of God.",
    3: "For consider Him who has endured such hostility by sinners against Himself — so that you will not grow weary and lose heart.",
    4: "You have not yet resisted to the point of bloodshed in your striving against sin.",
    5: "And you have forgotten the exhortation which is addressed to you as sons: \"My son, do not regard lightly the discipline of the Lord — nor faint when you are reproved by Him.",
    6: "For those whom the Lord loves, He disciplines — and He scourges every son whom He receives.\"",
    7: "It is for discipline that you endure. God deals with you as with sons — for what son is there whom his father does not discipline?",
    8: "But if you are without discipline — of which all have become partakers — then you are illegitimate children, and not sons.",
    9: "Furthermore, we had earthly fathers to discipline us, and we respected them — shall we not much rather be subject to the Father of spirits, and live?",
    10: "For they disciplined us for a short time as seemed best to them — but He disciplines us for our good, so that we may share His holiness.",
    11: "All discipline for the moment seems not to be joyful, but sorrowful — yet to those who have been trained by it, afterwards it yields the peaceful fruit of righteousness.",
    12: "Therefore, strengthen the hands that are weak and the knees that are feeble.",
    13: "And make straight paths for your feet — so that the limb which is lame may not be put out of joint, but rather be healed.",
    14: "Pursue peace with all men — and the sanctification without which no one will see the Lord.",
    15: "See to it that no one comes short of the grace of God — that no root of bitterness springing up causes trouble, and by it many be defiled.",
    16: "That there be no immoral or godless person like Esau, who sold his own birthright for a single meal.",
    17: "For you know that even afterwards, when he desired to inherit the blessing, he was rejected — for he found no place for repentance, though he sought for it with tears.",
    18: "For you have not come to a mountain that can be touched, and to a blazing fire — and to darkness and gloom and whirlwind,",
    19: "and to the blast of a trumpet and the sound of words — which sound was such that those who heard begged that no further word be spoken to them.",
    20: "For they could not bear the command, \"If even a beast touches the mountain, it will be stoned.\"",
    21: "And so terrible was the sight, that Moses said, \"I am full of fear and trembling.\"",
    22: "But you have come to Mount Zion and to the city of the living God — the heavenly Jerusalem — and to myriads of angels in festal assembly,",
    23: "and to the church of the firstborn who are enrolled in heaven, and to God, the Judge of all, and to the spirits of the righteous made perfect,",
    24: "and to Jesus, the mediator of a new covenant — and to the sprinkled blood, which speaks better than the blood of Abel.",
    25: "See to it that you do not refuse Him who is speaking. For if those did not escape when they refused him who warned them on earth, much less will we escape who turn away from Him who warns from heaven.",
    26: "And His voice shook the earth then. But now He has promised, saying, \"Yet once more I will shake not only the earth, but also the heavens.\"",
    27: "And this expression, \"Yet once more,\" denotes the removing of those things which can be shaken, as of created things — so that those things which cannot be shaken may remain.",
    28: "Therefore, since we receive a kingdom which cannot be shaken — let us show gratitude, by which we may offer to God an acceptable service with reverence and awe.",
    29: "For our God is a consuming fire.",
}
ch13 = {
    1: "Let love of the brothers continue.",
    2: "Do not neglect to show hospitality to strangers — for by this some have entertained angels without knowing it.",
    3: "Remember the prisoners, as though in prison with them — and those who are ill-treated, since you yourselves also are in the body.",
    4: "Marriage is to be held in honor among all — and the marriage bed is to be undefiled. For fornicators and adulterers God will judge.",
    5: "Make sure that your character is free from the love of money. Be content with what you have — for He Himself has said, \"I will never desert you, nor will I ever forsake you.\"",
    6: "So that we confidently say, \"The Lord is my helper — I will not be afraid. What can man do to me?\"",
    7: "Remember those who led you — who spoke the word of God to you. And considering the result of their conduct, imitate their faith.",
    8: "Jesus Christ is the same yesterday and today — and forever.",
    9: "Do not be carried away by varied and strange teachings. For it is good for the heart to be strengthened by grace — not by foods, through which those who were so occupied were not benefited.",
    10: "We have an altar from which those who serve the tabernacle have no right to eat.",
    11: "For the bodies of those animals whose blood is brought into the holy place by the high priest as an offering for sin, are burned outside the camp.",
    12: "Therefore Jesus also — that He might sanctify the people through His own blood — suffered outside the gate.",
    13: "So, let us go out to Him outside the camp — bearing His reproach.",
    14: "For here we do not have a lasting city — but we are seeking the city which is to come.",
    15: "Through Him then, let us continually offer up a sacrifice of praise to God — that is, the fruit of lips that give thanks to His name.",
    16: "And do not neglect doing good and sharing — for with such sacrifices God is pleased.",
    17: "Obey your leaders, and submit to them — for they keep watch over your souls, as those who will give an account. Let them do this with joy and not with grief — for this would be unprofitable for you.",
    18: "Pray for us. For we are sure that we have a good conscience — desiring to conduct ourselves honorably in all things.",
    19: "And I urge you all the more to do this — so that I may be restored to you the sooner.",
    20: "Now the God of peace, who brought up from the dead the great Shepherd of the sheep through the blood of the eternal covenant — that is, Jesus our Lord —",
    21: "equip you in every good thing to do His will — working in us that which is pleasing in His sight, through Jesus Christ. To Him be the glory forever and ever. Amen.",
    22: "But I urge you, brothers — bear with this word of exhortation, for I have written to you briefly.",
    23: "Take notice that our brother Timothy has been released — with whom, if he comes soon, I will see you.",
    24: "Greet all of your leaders, and all the saints. Those from Italy greet you.",
    25: "Grace be with you all. Amen.",
}
CHAPTERS = {1: ch1, 2: ch2, 3: ch3, 4: ch4, 5: ch5, 6: ch6, 7: ch7,
            8: ch8, 9: ch9, 10: ch10, 11: ch11, 12: ch12, 13: ch13}

def main():
    new_entries = {f"58_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Hebrews total verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Hebrews verses")

if __name__ == "__main__":
    main()
