"""MBT Luke 1-6 — Infancy narrative through Sermon on the Plain. 302 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch1 = {
    1: "Inasmuch as many have undertaken to compile an account of the things accomplished among us,",
    2: "just as those who from the beginning were eyewitnesses and servants of the word have handed them down to us —",
    3: "it seemed fitting for me as well, having investigated everything carefully from the beginning, to write it out for you in consecutive order, most excellent Theophilus,",
    4: "so that you might know the exact truth about the things you have been taught.",
    5: "In the days of Herod, king of Judea, there was a certain priest named Zacharias, of the division of Abijah. And he had a wife from the daughters of Aaron, and her name was Elizabeth.",
    6: "And they were both righteous in the sight of God, walking blamelessly in all the commandments and requirements of the Lord.",
    7: "And they had no child, because Elizabeth was barren — and they were both advanced in years.",
    8: "Now it came about, while he was performing his priestly service before God in the appointed order of his division,",
    9: "according to the custom of the priestly office, he was chosen by lot to enter the temple of the Lord and burn incense.",
    10: "And the whole multitude of the people were in prayer outside at the hour of the incense offering.",
    11: "And an angel of the Lord appeared to him, standing to the right of the altar of incense.",
    12: "And Zacharias was troubled when he saw the angel, and fear gripped him.",
    13: "But the angel said to him, \"Do not be afraid, Zacharias — for your petition has been heard. And your wife Elizabeth will bear you a son. And you shall name him John.",
    14: "And you will have joy and gladness. And many will rejoice at his birth.",
    15: "For he will be great in the sight of the Lord. And he will drink no wine or liquor. And he will be filled with the Holy Spirit while yet in his mother's womb.",
    16: "And he will turn many of the sons of Israel back to the Lord their God.",
    17: "And it is he who will go as a forerunner before Him in the spirit and power of Elijah — to turn the hearts of the fathers back to the children, and the disobedient to the attitude of the righteous — to make ready a people prepared for the Lord.\"",
    18: "And Zacharias said to the angel, \"How shall I know this for certain? For I am an old man, and my wife is advanced in years.\"",
    19: "And the angel answered and said to him, \"I am Gabriel, who stands in the presence of God. And I have been sent to speak to you, and to bring you this good news.",
    20: "And behold, you shall be silent and unable to speak, until the day when these things take place — because you did not believe my words, which shall be fulfilled in their proper time.\"",
    21: "And the people were waiting for Zacharias, and were wondering at his delay in the temple.",
    22: "But when he came out, he was unable to speak to them. And they realized that he had seen a vision in the temple. And he kept making signs to them, and remained mute.",
    23: "And it came about, when the days of his priestly service were ended, that he went back home.",
    24: "And after these days Elizabeth his wife became pregnant. And she kept herself in seclusion for five months, saying,",
    25: "\"This is the way the Lord has dealt with me in the days when He looked with favor upon me, to take away my disgrace among men.\"",
    26: "Now in the sixth month the angel Gabriel was sent from God to a city in Galilee, called Nazareth,",
    27: "to a virgin engaged to a man whose name was Joseph, of the descendants of David. And the virgin's name was Mary.",
    28: "And coming in, he said to her, \"Hail, favored one! The Lord is with you.\"",
    29: "But she was greatly troubled at this statement, and kept pondering what kind of salutation this might be.",
    30: "And the angel said to her, \"Do not be afraid, Mary. For you have found favor with God.",
    31: "And behold, you will conceive in your womb, and bear a son, and you shall name Him Jesus.",
    32: "He will be great, and will be called the Son of the Most High. And the Lord God will give Him the throne of His father David.",
    33: "And He will reign over the house of Jacob forever. And His kingdom will have no end.\"",
    34: "And Mary said to the angel, \"How can this be, since I am a virgin?\"",
    35: "And the angel answered and said to her, \"The Holy Spirit will come upon you, and the power of the Most High will overshadow you. And for that reason the holy offspring shall be called the Son of God.",
    36: "And behold, even your relative Elizabeth has also conceived a son in her old age. And she who was called barren is now in her sixth month.",
    37: "For nothing will be impossible with God.\"",
    38: "And Mary said, \"Behold, the bondslave of the Lord — be it done to me according to your word.\" And the angel departed from her.",
    39: "Now at this time Mary arose, and went with haste to the hill country, to a city of Judah,",
    40: "and entered the house of Zacharias and greeted Elizabeth.",
    41: "And it came about that when Elizabeth heard Mary's greeting, the baby leaped in her womb. And Elizabeth was filled with the Holy Spirit.",
    42: "And she cried out with a loud voice, and said, \"Blessed are you among women — and blessed is the fruit of your womb!",
    43: "And how has it happened to me, that the mother of my Lord should come to me?",
    44: "For behold, when the sound of your greeting reached my ears, the baby leaped in my womb for joy.",
    45: "And blessed is she who believed that there would be a fulfillment of what had been spoken to her by the Lord.\"",
    46: "And Mary said: \"My soul exalts the Lord,",
    47: "and my spirit has rejoiced in God my Savior.",
    48: "For He has had regard for the humble state of His bondslave. For behold, from this time on all generations will count me blessed.",
    49: "For the Mighty One has done great things for me — and holy is His name.",
    50: "And His mercy is upon generation after generation toward those who fear Him.",
    51: "He has done mighty deeds with His arm. He has scattered those who were proud in the thoughts of their heart.",
    52: "He has brought down rulers from their thrones — and has exalted those who were humble.",
    53: "He has filled the hungry with good things, and sent away the rich empty-handed.",
    54: "He has given help to Israel His servant, in remembrance of His mercy,",
    55: "as He spoke to our fathers — to Abraham and his offspring forever.\"",
    56: "And Mary stayed with her about three months, and then returned to her home.",
    57: "Now the time had come for Elizabeth to give birth, and she brought forth a son.",
    58: "And her neighbors and her relatives heard that the Lord had displayed His great mercy toward her — and they were rejoicing with her.",
    59: "And it came about that on the eighth day they came to circumcise the child. And they were going to call him Zacharias, after his father.",
    60: "And his mother answered and said, \"No indeed — but he shall be called John.\"",
    61: "And they said to her, \"There is no one among your relatives who is called by that name.\"",
    62: "And they made signs to his father, as to what he wanted him called.",
    63: "And he asked for a tablet, and wrote as follows, \"His name is John.\" And they were all astonished.",
    64: "And at once his mouth was opened and his tongue loosed, and he began to speak in praise of God.",
    65: "And fear came on all those living around them. And all these matters were being talked about in all the hill country of Judea.",
    66: "And all who heard them kept them in mind, saying, \"What then will this child turn out to be?\" For the hand of the Lord was certainly with him.",
    67: "And his father Zacharias was filled with the Holy Spirit, and prophesied, saying:",
    68: "\"Blessed be the Lord God of Israel, for He has visited us and accomplished redemption for His people,",
    69: "and has raised up a horn of salvation for us in the house of David His servant —",
    70: "as He spoke by the mouth of His holy prophets from of old.",
    71: "Salvation from our enemies — and from the hand of all who hate us.",
    72: "To show mercy toward our fathers, and to remember His holy covenant —",
    73: "the oath which He swore to Abraham our father,",
    74: "to grant us that we, being delivered from the hand of our enemies, might serve Him without fear,",
    75: "in holiness and righteousness before Him all our days.",
    76: "And you, child, will be called the prophet of the Most High. For you will go on before the Lord to prepare His ways,",
    77: "to give to His people the knowledge of salvation by the forgiveness of their sins.",
    78: "Because of the tender mercy of our God, with which the Sunrise from on high shall visit us,",
    79: "to shine upon those who sit in darkness and the shadow of death — to guide our feet into the way of peace.\"",
    80: "And the child continued to grow, and to become strong in spirit, and he lived in the deserts until the day of his public appearance to Israel.",
}
ch2 = {
    1: "Now it came about in those days that a decree went out from Caesar Augustus, that a census be taken of all the inhabited earth.",
    2: "This was the first census taken while Quirinius was governor of Syria.",
    3: "And all were proceeding to register for the census, everyone to his own city.",
    4: "And Joseph also went up from Galilee, from the city of Nazareth, to Judea, to the city of David, which is called Bethlehem — because he was of the house and family of David,",
    5: "in order to register, along with Mary, who was engaged to him, and was with child.",
    6: "And it came about that while they were there, the days were completed for her to give birth.",
    7: "And she gave birth to her first-born Son. And she wrapped Him in cloths, and laid Him in a manger — because there was no room for them in the inn.",
    8: "And in the same region there were some shepherds staying out in the fields, and keeping watch over their flock by night.",
    9: "And an angel of the Lord suddenly stood before them, and the glory of the Lord shone around them. And they were terribly frightened.",
    10: "And the angel said to them, \"Do not be afraid. For behold, I bring you good news of a great joy which shall be for all the people.",
    11: "For today in the city of David there has been born for you a Savior, who is Christ the Lord.",
    12: "And this will be a sign for you — you will find a baby wrapped in cloths, and lying in a manger.\"",
    13: "And suddenly there appeared with the angel a multitude of the heavenly host praising God, and saying,",
    14: "\"Glory to God in the highest — and on earth peace among men with whom He is pleased.\"",
    15: "And it came about, when the angels had gone away from them into heaven, that the shepherds began saying to one another, \"Let us go straight to Bethlehem then, and see this thing that has happened, which the Lord has made known to us.\"",
    16: "And they came in haste, and found their way to Mary and Joseph, and the baby as He lay in the manger.",
    17: "And when they had seen this, they made known the statement which had been told them about this Child.",
    18: "And all who heard it wondered at the things which were told them by the shepherds.",
    19: "But Mary treasured up all these things, pondering them in her heart.",
    20: "And the shepherds went back, glorifying and praising God for all that they had heard and seen, just as had been told them.",
    21: "And when eight days were completed before His circumcision, His name was then called Jesus — the name given by the angel before He was conceived in the womb.",
    22: "And when the days for their purification according to the law of Moses were completed, they brought Him up to Jerusalem to present Him to the Lord —",
    23: "(as it is written in the law of the Lord, \"Every first-born male that opens the womb shall be called holy to the Lord\"),",
    24: "and to offer a sacrifice according to what was said in the law of the Lord, \"A pair of turtledoves, or two young pigeons.\"",
    25: "And behold, there was a man in Jerusalem whose name was Simeon. And this man was righteous and devout, looking for the consolation of Israel — and the Holy Spirit was upon him.",
    26: "And it had been revealed to him by the Holy Spirit that he would not see death before he had seen the Lord's Christ.",
    27: "And he came in the Spirit into the temple. And when the parents brought in the child Jesus, to carry out for Him the custom of the Law,",
    28: "then he took Him into his arms, and blessed God, and said,",
    29: "\"Now, Lord, You are letting Your bondservant depart in peace, according to Your word.",
    30: "For my eyes have seen Your salvation,",
    31: "which You have prepared in the presence of all peoples —",
    32: "a light of revelation to the Gentiles, and the glory of Your people Israel.\"",
    33: "And His father and mother were amazed at the things which were being said about Him.",
    34: "And Simeon blessed them, and said to Mary His mother, \"Behold, this Child is appointed for the fall and rise of many in Israel, and for a sign to be opposed —",
    35: "and a sword will pierce even your own soul — to the end that thoughts from many hearts may be revealed.\"",
    36: "And there was a prophetess, Anna the daughter of Phanuel, of the tribe of Asher. She was advanced in years, having lived with a husband seven years after her marriage,",
    37: "and then as a widow to the age of eighty-four. And she never left the temple, serving night and day with fastings and prayers.",
    38: "And at that very hour she came up and began giving thanks to God, and continued to speak of Him to all those who were looking for the redemption of Jerusalem.",
    39: "And when they had performed everything according to the Law of the Lord, they returned to Galilee, to their own city of Nazareth.",
    40: "And the Child continued to grow and become strong, increasing in wisdom. And the grace of God was upon Him.",
    41: "And His parents used to go to Jerusalem every year at the Feast of the Passover.",
    42: "And when He became twelve, they went up there according to the custom of the Feast.",
    43: "And as they were returning, after spending the full number of days, the boy Jesus stayed behind in Jerusalem. But His parents were unaware of it,",
    44: "but supposed Him to be in the caravan, and went a day's journey. And they began looking for Him among their relatives and acquaintances.",
    45: "And when they did not find Him, they returned to Jerusalem, looking for Him.",
    46: "And it came about that after three days they found Him in the temple, sitting in the midst of the teachers, both listening to them and asking them questions.",
    47: "And all who heard Him were amazed at His understanding and His answers.",
    48: "And when they saw Him, they were astonished. And His mother said to Him, \"Son, why have You treated us this way? Behold, Your father and I have been anxiously looking for You.\"",
    49: "And He said to them, \"Why is it that you were looking for Me? Did you not know that I had to be in My Father's house?\"",
    50: "And they did not understand the statement which He had made to them.",
    51: "And He went down with them, and came to Nazareth — and He continued in subjection to them. And His mother treasured all these things in her heart.",
    52: "And Jesus kept increasing in wisdom and stature, and in favor with God and men.",
}
ch3 = {
    1: "Now in the fifteenth year of the reign of Tiberius Caesar, when Pontius Pilate was governor of Judea — and Herod was tetrarch of Galilee, and his brother Philip was tetrarch of the region of Ituraea and Trachonitis, and Lysanias was tetrarch of Abilene,",
    2: "in the high priesthood of Annas and Caiaphas — the word of God came to John, the son of Zacharias, in the wilderness.",
    3: "And he came into all the district around the Jordan, preaching a baptism of repentance for the forgiveness of sins,",
    4: "as it is written in the book of the words of Isaiah the prophet: \"The voice of one crying in the wilderness, 'Make ready the way of the Lord — make His paths straight.",
    5: "Every ravine shall be filled up, and every mountain and hill shall be brought low. And the crooked shall become straight, and the rough roads smooth.",
    6: "And all flesh shall see the salvation of God.'\"",
    7: "He therefore began saying to the multitudes who were going out to be baptized by him, \"You brood of vipers — who warned you to flee from the wrath to come?",
    8: "Therefore bring forth fruits in keeping with your repentance. And do not begin to say to yourselves, 'We have Abraham for our father' — for I say to you that God is able from these stones to raise up children to Abraham.",
    9: "And also the axe is already laid at the root of the trees. Every tree therefore that does not bear good fruit is cut down and thrown into the fire.\"",
    10: "And the multitudes were questioning him, saying, \"Then what shall we do?\"",
    11: "And he would answer and say to them, \"Let the man who has two tunics share with him who has none. And let him who has food do likewise.\"",
    12: "And some tax-gatherers also came to be baptized, and they said to him, \"Teacher, what shall we do?\"",
    13: "And he said to them, \"Collect no more than what you have been ordered to.\"",
    14: "And some soldiers were questioning him, saying, \"And what about us, what shall we do?\" And he said to them, \"Do not take money from anyone by force, or accuse anyone falsely, and be content with your wages.\"",
    15: "Now while the people were in a state of expectation, and all were wondering in their hearts about John, as to whether he might be the Christ —",
    16: "John answered and said to them all, \"As for me, I baptize you with water. But One is coming who is mightier than I — and I am not even fit to untie the thong of His sandals. He Himself will baptize you with the Holy Spirit and fire.",
    17: "And His winnowing fork is in His hand, to thoroughly clear His threshing floor, and to gather the wheat into His barn. But He will burn up the chaff with unquenchable fire.\"",
    18: "So with many other exhortations also he preached the gospel to the people.",
    19: "But when Herod the tetrarch was reproved by him on account of Herodias, his brother's wife — and on account of all the wicked things which Herod had done,",
    20: "he added this also to them all — he locked John up in prison.",
    21: "Now it came about, when all the people were baptized, that Jesus also was baptized, and while He was praying, heaven was opened,",
    22: "and the Holy Spirit descended upon Him in bodily form like a dove. And a voice came out of heaven, \"Thou art My beloved Son, in Thee I am well-pleased.\"",
    23: "And when He began His ministry, Jesus Himself was about thirty years of age, being supposedly the son of Joseph, the son of Eli,",
    24: "the son of Matthat, the son of Levi, the son of Melchi, the son of Jannai, the son of Joseph,",
    25: "the son of Mattathias, the son of Amos, the son of Nahum, the son of Hesli, the son of Naggai,",
    26: "the son of Maath, the son of Mattathias, the son of Semein, the son of Josech, the son of Joda,",
    27: "the son of Joanan, the son of Rhesa, the son of Zerubbabel, the son of Shealtiel, the son of Neri,",
    28: "the son of Melchi, the son of Addi, the son of Cosam, the son of Elmadam, the son of Er,",
    29: "the son of Jesus, the son of Eliezer, the son of Jorim, the son of Matthat, the son of Levi,",
    30: "the son of Simeon, the son of Judah, the son of Joseph, the son of Jonam, the son of Eliakim,",
    31: "the son of Melea, the son of Menna, the son of Mattatha, the son of Nathan, the son of David,",
    32: "the son of Jesse, the son of Obed, the son of Boaz, the son of Salmon, the son of Nahshon,",
    33: "the son of Amminadab, the son of Admin, the son of Ram, the son of Hezron, the son of Perez, the son of Judah,",
    34: "the son of Jacob, the son of Isaac, the son of Abraham, the son of Terah, the son of Nahor,",
    35: "the son of Serug, the son of Reu, the son of Peleg, the son of Heber, the son of Shelah,",
    36: "the son of Cainan, the son of Arphaxad, the son of Shem, the son of Noah, the son of Lamech,",
    37: "the son of Methuselah, the son of Enoch, the son of Jared, the son of Mahalaleel, the son of Cainan,",
    38: "the son of Enosh, the son of Seth, the son of Adam, the son of God.",
}
ch4 = {
    1: "And Jesus, full of the Holy Spirit, returned from the Jordan and was led about by the Spirit in the wilderness",
    2: "for forty days, being tempted by the devil. And He ate nothing during those days. And when they had ended, He became hungry.",
    3: "And the devil said to Him, \"If You are the Son of God, tell this stone to become bread.\"",
    4: "And Jesus answered him, \"It is written, 'Man shall not live on bread alone.'\"",
    5: "And he led Him up and showed Him all the kingdoms of the world in a moment of time.",
    6: "And the devil said to Him, \"I will give You all this domain and its glory — for it has been handed over to me, and I give it to whomever I wish.",
    7: "Therefore if You worship before me, it shall all be Yours.\"",
    8: "And Jesus answered and said to him, \"It is written, 'You shall worship the Lord your God, and serve Him only.'\"",
    9: "And he led Him to Jerusalem and had Him stand on the pinnacle of the temple, and said to Him, \"If You are the Son of God, throw Yourself down from here.",
    10: "For it is written, 'He will give His angels charge concerning You to guard You.'",
    11: "And, 'On their hands they will bear You up, lest You strike Your foot against a stone.'\"",
    12: "And Jesus answered and said to him, \"It is said, 'You shall not put the Lord your God to the test.'\"",
    13: "And when the devil had finished every temptation, he departed from Him until an opportune time.",
    14: "And Jesus returned to Galilee in the power of the Spirit. And news about Him spread through all the surrounding district.",
    15: "And He began teaching in their synagogues and was praised by all.",
    16: "And He came to Nazareth, where He had been brought up. And as was His custom, He entered the synagogue on the Sabbath, and stood up to read.",
    17: "And the book of the prophet Isaiah was handed to Him. And He opened the book, and found the place where it was written,",
    18: "\"The Spirit of the Lord is upon Me, because He anointed Me to preach the gospel to the poor. He has sent Me to proclaim release to the captives, and recovery of sight to the blind — to set free those who are oppressed,",
    19: "to proclaim the favorable year of the Lord.\"",
    20: "And He closed the book, and gave it back to the attendant, and sat down. And the eyes of all in the synagogue were fixed upon Him.",
    21: "And He began to say to them, \"Today this Scripture has been fulfilled in your hearing.\"",
    22: "And all were speaking well of Him, and wondering at the gracious words which were falling from His lips. And they were saying, \"Is this not Joseph's son?\"",
    23: "And He said to them, \"No doubt you will quote this proverb to Me: 'Physician, heal yourself! Whatever we heard was done at Capernaum, do here in your hometown as well.'\"",
    24: "And He said, \"Truly I say to you — no prophet is welcome in his hometown.",
    25: "But I say to you in truth — there were many widows in Israel in the days of Elijah, when the sky was shut up for three years and six months, when a great famine came over all the land.",
    26: "And yet Elijah was sent to none of them — but only to Zarephath, in the land of Sidon, to a woman who was a widow.",
    27: "And there were many lepers in Israel in the time of Elisha the prophet — and none of them was cleansed, but only Naaman the Syrian.\"",
    28: "And all in the synagogue were filled with rage as they heard these things.",
    29: "And they rose up and cast Him out of the city, and led Him to the brow of the hill on which their city had been built, in order to throw Him down the cliff.",
    30: "But passing through their midst, He went His way.",
    31: "And He came down to Capernaum, a city of Galilee. And He was teaching them on the Sabbath.",
    32: "And they were amazed at His teaching, for His message was with authority.",
    33: "And there was a man in the synagogue possessed by the spirit of an unclean demon. And he cried out with a loud voice,",
    34: "\"Ha! What do we have to do with You, Jesus of Nazareth? Have You come to destroy us? I know who You are — the Holy One of God!\"",
    35: "And Jesus rebuked him, saying, \"Be quiet — and come out of him!\" And when the demon had thrown him down in their midst, he came out of him without doing him any harm.",
    36: "And amazement came upon them all, and they began discussing with one another saying, \"What is this message? For with authority and power He commands the unclean spirits, and they come out.\"",
    37: "And the report about Him was getting out into every locality of the surrounding district.",
    38: "And He arose and left the synagogue, and entered Simon's home. Now Simon's mother-in-law was suffering from a high fever, and they made request of Him on her behalf.",
    39: "And standing over her, He rebuked the fever, and it left her. And she immediately arose and waited on them.",
    40: "And while the sun was setting, all who had any sick with various diseases brought them to Him. And laying His hands on every one of them, He was healing them.",
    41: "And demons also were coming out of many, crying out and saying, \"You are the Son of God!\" And rebuking them, He would not allow them to speak — because they knew Him to be the Christ.",
    42: "And when day came, He departed and went to a lonely place. And the multitudes were searching for Him, and came to Him, and tried to keep Him from going away from them.",
    43: "But He said to them, \"I must preach the kingdom of God to the other cities also — for I was sent for this purpose.\"",
    44: "And He kept on preaching in the synagogues of Judea.",
}
ch5 = {
    1: "Now it came about that while the multitude were pressing around Him and listening to the word of God, He was standing by the lake of Gennesaret.",
    2: "And He saw two boats lying at the edge of the lake. But the fishermen had gotten out of them, and were washing their nets.",
    3: "And He got into one of the boats, which was Simon's, and asked him to put out a little way from the land. And He sat down and began teaching the multitudes from the boat.",
    4: "And when He had finished speaking, He said to Simon, \"Put out into the deep water, and let down your nets for a catch.\"",
    5: "And Simon answered and said, \"Master, we worked hard all night and caught nothing. But at Your bidding I will let down the nets.\"",
    6: "And when they had done this, they enclosed a great quantity of fish — and their nets began to break.",
    7: "And they signaled to their partners in the other boat, for them to come and help them. And they came, and filled both of the boats, so that they began to sink.",
    8: "But when Simon Peter saw that, he fell down at Jesus' feet, saying, \"Depart from me, for I am a sinful man, O Lord!\"",
    9: "For amazement had seized him and all his companions, because of the catch of fish which they had taken.",
    10: "And so also James and John, sons of Zebedee, who were partners with Simon. And Jesus said to Simon, \"Do not fear — from now on you will be catching men.\"",
    11: "And when they had brought their boats to land, they left everything and followed Him.",
    12: "And it came about that while He was in one of the cities, behold, there was a man full of leprosy. And when he saw Jesus, he fell on his face and implored Him, saying, \"Lord, if You are willing, You can make me clean.\"",
    13: "And He stretched out His hand and touched him, saying, \"I am willing — be cleansed.\" And immediately the leprosy left him.",
    14: "And He ordered him to tell no one — \"But go and show yourself to the priest, and make an offering for your cleansing, just as Moses commanded, for a testimony to them.\"",
    15: "But the news about Him was spreading even farther. And great multitudes were gathering to hear Him and to be healed of their sicknesses.",
    16: "But He Himself would often slip away to the wilderness and pray.",
    17: "And it came about, one day, that He was teaching, and there were some Pharisees and teachers of the law sitting there, who had come from every village of Galilee and Judea and from Jerusalem. And the power of the Lord was present for Him to perform healing.",
    18: "And behold, some men were carrying on a bed a man who was paralyzed. And they were trying to bring him in and to set him down in front of Him.",
    19: "And not finding any way to bring him in because of the crowd, they went up on the roof and let him down through the tiles with his stretcher, into the middle of the crowd, in front of Jesus.",
    20: "And seeing their faith, He said, \"Friend, your sins are forgiven you.\"",
    21: "And the scribes and the Pharisees began to reason, saying, \"Who is this man who speaks blasphemies? Who can forgive sins, but God alone?\"",
    22: "But Jesus, aware of their reasonings, answered and said to them, \"Why are you reasoning in your hearts?",
    23: "Which is easier, to say, 'Your sins have been forgiven you,' or to say, 'Rise up and walk'?",
    24: "But, in order that you may know that the Son of Man has authority on earth to forgive sins\" — He said to the paralytic — \"I say to you, rise up, and take up your stretcher and go home.\"",
    25: "And at once he rose up before them, and took up what he had been lying on, and went home, glorifying God.",
    26: "And they were all seized with astonishment and began glorifying God. And they were filled with fear, saying, \"We have seen remarkable things today!\"",
    27: "And after that He went out, and noticed a tax-gatherer named Levi, sitting in the tax office. And He said to him, \"Follow Me.\"",
    28: "And he left everything behind, and rose and began to follow Him.",
    29: "And Levi gave a big reception for Him in his house. And there was a great crowd of tax-gatherers and other people who were reclining at the table with them.",
    30: "And the Pharisees and their scribes began grumbling at His disciples, saying, \"Why do you eat and drink with the tax-gatherers and sinners?\"",
    31: "And Jesus answered and said to them, \"It is not those who are well who need a physician, but those who are sick.",
    32: "I have not come to call the righteous, but sinners — to repentance.\"",
    33: "And they said to Him, \"The disciples of John often fast and offer prayers — the disciples of the Pharisees also do the same. But Yours eat and drink.\"",
    34: "And Jesus said to them, \"You cannot make the attendants of the bridegroom fast while the bridegroom is with them, can you?",
    35: "But the days will come, and when the bridegroom is taken away from them, then they will fast in those days.\"",
    36: "And He was also telling them a parable: \"No one tears a piece from a new garment and puts it on an old garment. Otherwise he will both tear the new, and the piece from the new will not match the old.",
    37: "And no one puts new wine into old wineskins. Otherwise the new wine will burst the skins, and it will be spilled out, and the skins will be ruined.",
    38: "But new wine must be put into fresh wineskins.",
    39: "And no one, after drinking old wine, wishes for new — for he says, 'The old is good enough.'\"",
}
ch6 = {
    1: "Now it came about that on a certain Sabbath He was passing through some grainfields. And His disciples were picking and eating the heads of grain, rubbing them in their hands.",
    2: "But some of the Pharisees said, \"Why do you do what is not lawful on the Sabbath?\"",
    3: "And Jesus answering them said, \"Have you not even read what David did when he was hungry, he and those who were with him —",
    4: "how he entered the house of God, and took and ate the consecrated bread which is not lawful for any to eat except the priests alone, and gave it to his companions?\"",
    5: "And He was saying to them, \"The Son of Man is Lord of the Sabbath.\"",
    6: "And it came about on another Sabbath, that He entered the synagogue and was teaching. And there was a man there whose right hand was withered.",
    7: "And the scribes and the Pharisees were watching Him closely, to see if He healed on the Sabbath, in order that they might find reason to accuse Him.",
    8: "But He knew what they were thinking, and He said to the man with the withered hand, \"Rise and come forward!\" And he rose and came forward.",
    9: "And Jesus said to them, \"I ask you, is it lawful to do good or to do harm on the Sabbath, to save a life or to destroy it?\"",
    10: "And after looking around at them all, He said to him, \"Stretch out your hand!\" And he did so. And his hand was restored.",
    11: "But they themselves were filled with rage, and discussed together what they might do to Jesus.",
    12: "And it was at this time that He went off to the mountain to pray. And He spent the whole night in prayer to God.",
    13: "And when day came, He called His disciples to Him. And chose twelve of them, whom He also named as apostles:",
    14: "Simon, whom He also named Peter, and Andrew his brother; and James and John; and Philip and Bartholomew;",
    15: "and Matthew and Thomas; James the son of Alphaeus, and Simon who was called the Zealot;",
    16: "Judas the son of James, and Judas Iscariot, who became a traitor.",
    17: "And He descended with them, and stood on a level place. And there was a great multitude of His disciples, and a great throng of people from all Judea and Jerusalem, and the coastal region of Tyre and Sidon —",
    18: "who had come to hear Him, and to be healed of their diseases. And those who were troubled with unclean spirits were being cured.",
    19: "And all the multitude were trying to touch Him — for power was coming from Him and healing them all.",
    20: "And turning His gaze on His disciples, He began to say, \"Blessed are you who are poor — for yours is the kingdom of God.",
    21: "Blessed are you who hunger now — for you shall be satisfied. Blessed are you who weep now — for you shall laugh.",
    22: "Blessed are you when men hate you, and ostracize you, and cast insults at you, and spurn your name as evil, for the sake of the Son of Man.",
    23: "Be glad in that day, and leap for joy — for behold, your reward is great in heaven. For in the same way their fathers used to treat the prophets.",
    24: "But woe to you who are rich — for you are receiving your comfort in full.",
    25: "Woe to you who are well-fed now — for you shall be hungry. Woe to you who laugh now — for you shall mourn and weep.",
    26: "Woe to you when all men speak well of you — for in the same way their fathers used to treat the false prophets.",
    27: "But I say to you who hear — love your enemies, do good to those who hate you,",
    28: "bless those who curse you, pray for those who mistreat you.",
    29: "Whoever hits you on the cheek, offer him the other also. And whoever takes away your coat, do not withhold your shirt from him either.",
    30: "Give to everyone who asks of you. And whoever takes away what is yours, do not demand it back.",
    31: "And just as you want people to treat you, treat them in the same way.",
    32: "And if you love those who love you, what credit is that to you? For even sinners love those who love them.",
    33: "And if you do good to those who do good to you, what credit is that to you? For even sinners do the same.",
    34: "And if you lend to those from whom you expect to receive, what credit is that to you? Even sinners lend to sinners, in order to receive back the same amount.",
    35: "But love your enemies, and do good, and lend, expecting nothing in return. And your reward will be great, and you will be sons of the Most High. For He Himself is kind to ungrateful and evil men.",
    36: "Be merciful, just as your Father is merciful.",
    37: "And do not judge, and you will not be judged. And do not condemn, and you will not be condemned. Pardon, and you will be pardoned.",
    38: "Give, and it will be given to you — good measure, pressed down, shaken together, running over, they will pour into your lap. For whatever measure you deal out to others, it will be dealt to you in return.\"",
    39: "And He also spoke a parable to them: \"A blind man cannot guide a blind man, can he? Will they not both fall into a pit?",
    40: "A pupil is not above his teacher — but everyone, after he has been fully trained, will be like his teacher.",
    41: "And why do you look at the speck that is in your brother's eye, but do not notice the log that is in your own eye?",
    42: "Or how can you say to your brother, 'Brother, let me take out the speck that is in your eye,' when you yourself do not see the log that is in your own eye? You hypocrite — first take the log out of your own eye, and then you will see clearly to take out the speck that is in your brother's eye.",
    43: "For there is no good tree which produces bad fruit — nor on the other hand, a bad tree which produces good fruit.",
    44: "For each tree is known by its own fruit. For men do not gather figs from thorns, nor do they pick grapes from a briar bush.",
    45: "The good man, out of the good treasure of his heart, brings forth what is good. And the evil man, out of the evil treasure, brings forth what is evil. For his mouth speaks from that which fills his heart.",
    46: "And why do you call Me, 'Lord, Lord,' and do not do what I say?",
    47: "Everyone who comes to Me, and hears My words and acts upon them, I will show you whom he is like.",
    48: "He is like a man building a house, who dug deep and laid a foundation upon the rock. And when a flood rose, the torrent burst against that house and could not shake it, because it had been well built.",
    49: "But the one who has heard, and has not acted accordingly, is like a man who built a house upon the ground, without any foundation — and the torrent burst against it, and immediately it collapsed. And the ruin of that house was great.\"",
}

CHAPTERS = {1:ch1,2:ch2,3:ch3,4:ch4,5:ch5,6:ch6}

def main():
    new_entries = {f"42_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Luke 1-6 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Luke 1-6 verses")

if __name__ == "__main__":
    main()
