"""MBT Matthew 15-21 — Caesarea confession through Triumphal Entry. 239 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch15 = {
    1: "Then some Pharisees and scribes came to Jesus from Jerusalem, saying,",
    2: "\"Why do Your disciples transgress the tradition of the elders? For they do not wash their hands when they eat bread.\"",
    3: "And He answered and said to them, \"And why do you yourselves transgress the commandment of God for the sake of your tradition?",
    4: "For God said, 'Honor your father and mother,' and, 'He who speaks evil of father or mother, let him be put to death.'",
    5: "But you say, 'Whoever shall say to his father or mother, \"Anything of mine you might have been helped by has been given to God\" —",
    6: "he is not to honor his father or mother.' And thus you invalidated the word of God for the sake of your tradition.",
    7: "You hypocrites — rightly did Isaiah prophesy of you, saying,",
    8: "'This people honors Me with their lips — but their heart is far away from Me.",
    9: "But in vain do they worship Me — teaching as doctrines the precepts of men.'\"",
    10: "And after He called the multitude to Him, He said to them, \"Hear, and understand.",
    11: "Not what enters into the mouth defiles the man — but what proceeds out of the mouth, this defiles the man.\"",
    12: "Then the disciples came and said to Him, \"Do You know that the Pharisees were offended when they heard this statement?\"",
    13: "But He answered and said, \"Every plant which My heavenly Father did not plant shall be rooted up.",
    14: "Let them alone — they are blind guides of the blind. And if a blind man guides a blind man, both will fall into a pit.\"",
    15: "And Peter answered and said to Him, \"Explain the parable to us.\"",
    16: "And He said, \"Are you still lacking in understanding also?",
    17: "Do you not understand, that everything that goes into the mouth passes into the stomach, and is eliminated?",
    18: "But the things that proceed out of the mouth come from the heart — and those defile the man.",
    19: "For out of the heart come evil thoughts, murders, adulteries, fornications, thefts, false witness, slanders.",
    20: "These are the things which defile the man — but to eat with unwashed hands does not defile the man.\"",
    21: "And Jesus went away from there, and withdrew into the district of Tyre and Sidon.",
    22: "And behold, a Canaanite woman came out from that region, and began to cry out, saying, \"Have mercy on me, O Lord, Son of David — my daughter is cruelly demon-possessed.\"",
    23: "But He did not answer her a word. And His disciples came and kept asking Him, saying, \"Send her away — for she is shouting out after us.\"",
    24: "But He answered and said, \"I was sent only to the lost sheep of the house of Israel.\"",
    25: "But she came and began to bow down before Him, saying, \"Lord, help me!\"",
    26: "And He answered and said, \"It is not good to take the children's bread and throw it to the dogs.\"",
    27: "But she said, \"Yes, Lord — but even the dogs feed on the crumbs which fall from their masters' table.\"",
    28: "Then Jesus answered and said to her, \"O woman, your faith is great. Be it done for you as you wish.\" And her daughter was healed at once.",
    29: "And departing from there, Jesus went along by the Sea of Galilee — and having gone up to the mountain, He was sitting there.",
    30: "And great multitudes came to Him, bringing with them those who were lame, crippled, blind, dumb, and many others. And they laid them down at His feet — and He healed them.",
    31: "So that the multitude marveled, as they saw the dumb speaking, the crippled restored, and the lame walking, and the blind seeing. And they glorified the God of Israel.",
    32: "And Jesus called His disciples to Him and said, \"I feel compassion for the multitude, because they have remained with Me now three days — and have nothing to eat. And I do not wish to send them away hungry, lest they faint on the way.\"",
    33: "And the disciples said to Him, \"Where would we get so many loaves in a desolate place to satisfy such a great multitude?\"",
    34: "And Jesus said to them, \"How many loaves do you have?\" And they said, \"Seven — and a few small fish.\"",
    35: "And He directed the multitude to sit down on the ground.",
    36: "And He took the seven loaves and the fish — and giving thanks, He broke them and started giving them to the disciples. And the disciples in turn gave them to the multitudes.",
    37: "And they all ate, and were satisfied. And they picked up what was left over of the broken pieces — seven large baskets full.",
    38: "And those who ate were four thousand men — besides women and children.",
    39: "And sending away the multitudes, He got into the boat and came to the region of Magadan.",
}
ch16 = {
    1: "And the Pharisees and Sadducees came up — and testing Him, they asked Him to show them a sign from heaven.",
    2: "But He answered and said to them, \"When it is evening, you say, 'It will be fair weather, for the sky is red.'",
    3: "And in the morning, 'There will be a storm today, for the sky is red and threatening.' Do you know how to discern the appearance of the sky — but cannot discern the signs of the times?",
    4: "An evil and adulterous generation seeks after a sign — and a sign will not be given it, except the sign of Jonah.\" And He left them, and went away.",
    5: "And the disciples came to the other side, and had forgotten to take bread.",
    6: "And Jesus said to them, \"Watch out — and beware of the leaven of the Pharisees and Sadducees.\"",
    7: "And they began to discuss this among themselves, saying, \"It is because we took no bread.\"",
    8: "But Jesus, aware of this, said, \"You men of little faith — why do you discuss among yourselves that you have no bread?",
    9: "Do you not yet understand or remember the five loaves of the five thousand — and how many baskets full you took up?",
    10: "Or the seven loaves of the four thousand — and how many large baskets full you took up?",
    11: "How is it that you do not understand that I did not speak to you concerning bread? But beware of the leaven of the Pharisees and Sadducees.\"",
    12: "Then they understood that He did not say to beware of the leaven of bread — but of the teaching of the Pharisees and Sadducees.",
    13: "Now when Jesus came into the district of Caesarea Philippi, He began asking His disciples, saying, \"Who do people say that the Son of Man is?\"",
    14: "And they said, \"Some say John the Baptist — and others, Elijah. But still others, Jeremiah, or one of the prophets.\"",
    15: "He said to them, \"But who do you say that I am?\"",
    16: "And Simon Peter answered and said, \"You are the Christ, the Son of the living God.\"",
    17: "And Jesus answered and said to him, \"Blessed are you, Simon Barjona — because flesh and blood did not reveal this to you, but My Father who is in heaven.",
    18: "And I also say to you that you are Peter — and upon this rock I will build My church. And the gates of Hades shall not overpower it.",
    19: "I will give you the keys of the kingdom of heaven — and whatever you shall bind on earth shall have been bound in heaven, and whatever you shall loose on earth shall have been loosed in heaven.\"",
    20: "Then He warned the disciples that they should tell no one that He was the Christ.",
    21: "From that time Jesus Christ began to show His disciples that He must go to Jerusalem, and suffer many things from the elders and chief priests and scribes — and be killed, and be raised up on the third day.",
    22: "And Peter took Him aside, and began to rebuke Him, saying, \"God forbid it, Lord! This shall never happen to You.\"",
    23: "But He turned and said to Peter, \"Get behind Me, Satan! You are a stumbling block to Me — for you are not setting your mind on God's interests, but man's.\"",
    24: "Then Jesus said to His disciples, \"If anyone wishes to come after Me, let him deny himself, and take up his cross, and follow Me.",
    25: "For whoever wishes to save his life shall lose it — but whoever loses his life for My sake shall find it.",
    26: "For what will a man be profited, if he gains the whole world, and forfeits his soul? Or what will a man give in exchange for his soul?",
    27: "For the Son of Man is going to come in the glory of His Father with His angels — and will then recompense every man according to his deeds.",
    28: "Truly I say to you, there are some of those who are standing here who shall not taste death until they see the Son of Man coming in His kingdom.\"",
}
ch17 = {
    1: "And six days later Jesus took with Him Peter and James and John his brother, and led them up to a high mountain by themselves.",
    2: "And He was transfigured before them — and His face shone like the sun, and His garments became as white as light.",
    3: "And behold, Moses and Elijah appeared to them, talking with Him.",
    4: "And Peter answered and said to Jesus, \"Lord, it is good for us to be here. If You wish, I will make three tabernacles here — one for You, and one for Moses, and one for Elijah.\"",
    5: "While he was still speaking, behold, a bright cloud overshadowed them — and behold, a voice out of the cloud, saying, \"This is My beloved Son — with whom I am well-pleased. Listen to Him!\"",
    6: "And when the disciples heard this, they fell on their faces and were much afraid.",
    7: "And Jesus came to them and touched them and said, \"Arise — and do not be afraid.\"",
    8: "And lifting up their eyes, they saw no one — except Jesus Himself alone.",
    9: "And as they were coming down from the mountain, Jesus commanded them, saying, \"Tell the vision to no one until the Son of Man has risen from the dead.\"",
    10: "And His disciples asked Him, saying, \"Why then do the scribes say that Elijah must come first?\"",
    11: "And He answered and said, \"Elijah is coming, and will restore all things.",
    12: "But I say to you, that Elijah already came — and they did not recognize him, but did to him whatever they wished. So also the Son of Man is going to suffer at their hands.\"",
    13: "Then the disciples understood that He had spoken to them about John the Baptist.",
    14: "And when they came to the multitude, a man came up to Him, falling on his knees before Him, and saying,",
    15: "\"Lord, have mercy on my son — for he is a lunatic, and is very ill. For he often falls into the fire, and often into the water.",
    16: "And I brought him to Your disciples — and they could not cure him.\"",
    17: "And Jesus answered and said, \"O unbelieving and perverted generation, how long shall I be with you? How long shall I put up with you? Bring him here to Me.\"",
    18: "And Jesus rebuked him, and the demon came out of him — and the boy was cured at once.",
    19: "Then the disciples came to Jesus privately, and said, \"Why could we not cast it out?\"",
    20: "And He said to them, \"Because of the littleness of your faith. For truly I say to you, if you have faith as a mustard seed, you shall say to this mountain, 'Move from here to there,' and it shall move — and nothing shall be impossible to you.",
    21: "(But this kind does not go out except by prayer and fasting.)\"",
    22: "And while they were gathering together in Galilee, Jesus said to them, \"The Son of Man is going to be delivered into the hands of men.",
    23: "And they will kill Him, and He will be raised on the third day.\" And they were deeply grieved.",
    24: "And when they had come to Capernaum, those who collected the two-drachma tax came to Peter, and said, \"Does your teacher not pay the two-drachma tax?\"",
    25: "He said, \"Yes.\" And when he came into the house, Jesus spoke to him first, saying, \"What do you think, Simon? From whom do the kings of the earth collect customs or poll-tax? From their sons, or from strangers?\"",
    26: "And upon his saying, \"From strangers,\" Jesus said to him, \"Consequently the sons are exempt.",
    27: "But, lest we give them offense, go to the sea, and throw in a hook, and take the first fish that comes up. And when you open its mouth, you will find a stater. Take that and give it to them for you and Me.\"",
}
ch18 = {
    1: "At that time the disciples came to Jesus, saying, \"Who then is greatest in the kingdom of heaven?\"",
    2: "And He called a child to Himself and set him before them,",
    3: "and said, \"Truly I say to you — unless you are converted and become like children, you shall not enter the kingdom of heaven.",
    4: "Whoever then humbles himself as this child — he is the greatest in the kingdom of heaven.",
    5: "And whoever receives one such child in My name receives Me.",
    6: "But whoever causes one of these little ones who believe in Me to stumble — it is better for him that a heavy millstone be hung around his neck, and that he be drowned in the depths of the sea.",
    7: "Woe to the world because of its stumbling blocks. For it is inevitable that stumbling blocks come — but woe to that man through whom the stumbling block comes!",
    8: "And if your hand or your foot causes you to stumble, cut it off and throw it from you. It is better for you to enter life crippled or lame, than having two hands or two feet, to be cast into the eternal fire.",
    9: "And if your eye causes you to stumble, pluck it out, and throw it from you. It is better for you to enter life with one eye, than having two eyes, to be cast into the fiery hell.",
    10: "See that you do not despise one of these little ones — for I say to you, that their angels in heaven continually behold the face of My Father who is in heaven.",
    11: "(For the Son of Man has come to save that which was lost.)",
    12: "What do you think? If any man has a hundred sheep, and one of them has gone astray, does he not leave the ninety-nine on the mountains, and go and search for the one that is straying?",
    13: "And if it turns out that he finds it, truly I say to you, he rejoices over it more than over the ninety-nine which have not gone astray.",
    14: "Thus it is not the will of your Father who is in heaven that one of these little ones perish.",
    15: "And if your brother sins, go and reprove him in private. If he listens to you, you have won your brother.",
    16: "But if he does not listen to you, take one or two more with you — so that by the mouth of two or three witnesses every fact may be confirmed.",
    17: "And if he refuses to listen to them, tell it to the church. And if he refuses to listen even to the church, let him be to you as a Gentile and a tax-gatherer.",
    18: "Truly I say to you, whatever you shall bind on earth shall have been bound in heaven — and whatever you loose on earth shall have been loosed in heaven.",
    19: "Again I say to you, that if two of you agree on earth about anything that they may ask, it shall be done for them by My Father who is in heaven.",
    20: "For where two or three have gathered together in My name, there I am in their midst.\"",
    21: "Then Peter came and said to Him, \"Lord, how often shall my brother sin against me and I forgive him? Up to seven times?\"",
    22: "Jesus said to him, \"I do not say to you, up to seven times — but up to seventy times seven.",
    23: "For this reason the kingdom of heaven may be compared to a certain king who wished to settle accounts with his slaves.",
    24: "And when he had begun to settle them, there was brought to him one who owed him ten thousand talents.",
    25: "But since he did not have the means to repay, his lord commanded him to be sold, along with his wife and children and all that he had — and repayment to be made.",
    26: "The slave therefore fell down and prostrated himself before him, saying, 'Have patience with me — and I will repay you everything.'",
    27: "And the lord of that slave felt compassion, and released him, and forgave him the debt.",
    28: "But that slave went out, and found one of his fellow slaves who owed him a hundred denarii. And he seized him and began to choke him, saying, 'Pay back what you owe.'",
    29: "So his fellow slave fell down and began to entreat him, saying, 'Have patience with me — and I will repay you.'",
    30: "He was unwilling however — but went and threw him in prison until he should pay back what was owed.",
    31: "So when his fellow slaves saw what had happened, they were deeply grieved, and came and reported to their lord all that had happened.",
    32: "Then summoning him, his lord said to him, 'You wicked slave — I forgave you all that debt because you entreated me.",
    33: "Should you not also have had mercy on your fellow slave — even as I had mercy on you?'",
    34: "And his lord, moved with anger, handed him over to the torturers, until he should repay all that was owed him.",
    35: "So shall My heavenly Father also do to you, if each of you does not forgive his brother from your heart.\"",
}
ch19 = {
    1: "And it came about that when Jesus had finished these words, He departed from Galilee, and came into the region of Judea beyond the Jordan.",
    2: "And great multitudes followed Him, and He healed them there.",
    3: "And some Pharisees came to Him, testing Him and saying, \"Is it lawful for a man to divorce his wife for any cause at all?\"",
    4: "And He answered and said, \"Have you not read, that He who created them from the beginning made them male and female,",
    5: "and said, 'For this cause a man shall leave his father and mother, and shall cleave to his wife — and the two shall become one flesh'?",
    6: "Consequently they are no longer two, but one flesh. What therefore God has joined together, let no man separate.\"",
    7: "They said to Him, \"Why then did Moses command to give her a certificate and divorce her?\"",
    8: "He said to them, \"Because of your hardness of heart Moses permitted you to divorce your wives — but from the beginning it has not been this way.",
    9: "And I say to you, whoever divorces his wife, except for immorality, and marries another woman commits adultery.\"",
    10: "The disciples said to Him, \"If the relationship of the man with his wife is like this, it is better not to marry.\"",
    11: "But He said to them, \"Not all men can accept this statement — but only those to whom it has been given.",
    12: "For there are eunuchs who were born that way from their mother's womb. And there are eunuchs who were made eunuchs by men. And there are also eunuchs who made themselves eunuchs for the sake of the kingdom of heaven. He who is able to accept this, let him accept it.\"",
    13: "Then some children were brought to Him so that He might lay His hands on them and pray — and the disciples rebuked them.",
    14: "But Jesus said, \"Let the children alone, and do not hinder them from coming to Me — for the kingdom of heaven belongs to such as these.\"",
    15: "And after laying His hands on them, He departed from there.",
    16: "And behold, one came to Him and said, \"Teacher, what good thing shall I do that I may obtain eternal life?\"",
    17: "And He said to him, \"Why are you asking Me about what is good? There is only One who is good. But if you wish to enter into life, keep the commandments.\"",
    18: "He said to Him, \"Which ones?\" And Jesus said, \"You shall not commit murder. You shall not commit adultery. You shall not steal. You shall not bear false witness.",
    19: "Honor your father and mother. And you shall love your neighbor as yourself.\"",
    20: "The young man said to Him, \"All these things I have kept. What am I still lacking?\"",
    21: "Jesus said to him, \"If you wish to be complete, go and sell your possessions and give to the poor — and you shall have treasure in heaven. And come, follow Me.\"",
    22: "But when the young man heard this statement, he went away grieved — for he was one who owned much property.",
    23: "And Jesus said to His disciples, \"Truly I say to you — it is hard for a rich man to enter the kingdom of heaven.",
    24: "And again I say to you, it is easier for a camel to go through the eye of a needle, than for a rich man to enter the kingdom of God.\"",
    25: "And when the disciples heard this, they were very astonished and said, \"Then who can be saved?\"",
    26: "And looking upon them Jesus said to them, \"With men this is impossible — but with God all things are possible.\"",
    27: "Then Peter answered and said to Him, \"Behold, we have left everything and followed You. What then will there be for us?\"",
    28: "And Jesus said to them, \"Truly I say to you, that you who have followed Me, in the regeneration when the Son of Man will sit on His glorious throne — you also shall sit upon twelve thrones, judging the twelve tribes of Israel.",
    29: "And everyone who has left houses or brothers or sisters or father or mother or children or farms for My name's sake, shall receive many times as much, and shall inherit eternal life.",
    30: "But many who are first will be last — and the last, first.",
}
ch20 = {
    1: "For the kingdom of heaven is like a landowner, who went out early in the morning to hire laborers for his vineyard.",
    2: "And when he had agreed with the laborers for a denarius for the day, he sent them into his vineyard.",
    3: "And he went out about the third hour, and saw others standing idle in the market place.",
    4: "And to those he said, 'You too go into the vineyard, and whatever is right I will give you.' And so they went.",
    5: "Again he went out about the sixth and the ninth hour, and did the same thing.",
    6: "And about the eleventh hour he went out, and found others standing. And he said to them, 'Why have you been standing here idle all day long?'",
    7: "They said to him, 'Because no one hired us.' He said to them, 'You too go into the vineyard.'",
    8: "And when evening had come, the owner of the vineyard said to his foreman, 'Call the laborers, and pay them their wages, beginning with the last group to the first.'",
    9: "And when those hired about the eleventh hour came, each one received a denarius.",
    10: "And when those hired first came, they thought that they would receive more — but each of them also received a denarius.",
    11: "And when they received it, they grumbled at the landowner,",
    12: "saying, 'These last men have worked only one hour, and you have made them equal to us who have borne the burden and the scorching heat of the day.'",
    13: "But he answered and said to one of them, 'Friend, I am doing you no wrong. Did you not agree with me for a denarius?",
    14: "Take what is yours and go your way — but I wish to give to this last man the same as to you.",
    15: "Is it not lawful for me to do what I wish with what is my own? Or is your eye envious because I am generous?'",
    16: "Thus the last shall be first, and the first last.\"",
    17: "And as Jesus was about to go up to Jerusalem, He took the twelve disciples aside by themselves, and on the way He said to them,",
    18: "\"Behold, we are going up to Jerusalem — and the Son of Man will be delivered to the chief priests and scribes. And they will condemn Him to death,",
    19: "and will deliver Him up to the Gentiles to mock and scourge and crucify Him. And on the third day He will be raised up.\"",
    20: "Then the mother of the sons of Zebedee came to Him with her sons, bowing down, and making a request of Him.",
    21: "And He said to her, \"What do you wish?\" She said to Him, \"Command that in Your kingdom these two sons of mine may sit, one on Your right and one on Your left.\"",
    22: "But Jesus answered and said, \"You do not know what you are asking for. Are you able to drink the cup that I am about to drink?\" They said to Him, \"We are able.\"",
    23: "He said to them, \"My cup you shall drink — but to sit on My right and on My left, this is not Mine to give. But it is for those for whom it has been prepared by My Father.\"",
    24: "And hearing this, the ten became indignant with the two brothers.",
    25: "But Jesus called them to Himself, and said, \"You know that the rulers of the Gentiles lord it over them, and their great men exercise authority over them.",
    26: "It is not so among you, but whoever wishes to become great among you shall be your servant.",
    27: "And whoever wishes to be first among you shall be your slave —",
    28: "just as the Son of Man did not come to be served, but to serve, and to give His life a ransom for many.\"",
    29: "And as they were going out from Jericho, a great multitude followed Him.",
    30: "And behold, two blind men sitting by the road, hearing that Jesus was passing by, cried out, \"Lord, have mercy on us, Son of David!\"",
    31: "And the multitude sternly told them to be quiet. But they cried out all the more, \"Lord, Son of David, have mercy on us!\"",
    32: "And Jesus stopped and called them, and said, \"What do you want Me to do for you?\"",
    33: "They said to Him, \"Lord, we want our eyes to be opened.\"",
    34: "And moved with compassion, Jesus touched their eyes. And immediately they regained their sight and followed Him.",
}
ch21 = {
    1: "And when they had approached Jerusalem, and had come to Bethphage, to the Mount of Olives, then Jesus sent two disciples,",
    2: "saying to them, \"Go into the village opposite you, and immediately you will find a donkey tied there and a colt with her. Untie them and bring them to Me.",
    3: "And if anyone says something to you, you shall say, 'The Lord has need of them' — and immediately he will send them.\"",
    4: "Now this took place that what was spoken through the prophet might be fulfilled, saying,",
    5: "\"Say to the daughter of Zion, 'Behold your King is coming to you, gentle, and mounted on a donkey — even on a colt, the foal of a beast of burden.'\"",
    6: "And the disciples went and did just as Jesus had directed them.",
    7: "And they brought the donkey and the colt, and laid on them their garments, on which He sat.",
    8: "And most of the multitude spread their garments in the road, and others were cutting branches from the trees, and spreading them in the road.",
    9: "And the multitudes going before Him, and those who followed after were crying out, saying, \"Hosanna to the Son of David! Blessed is He who comes in the name of the Lord! Hosanna in the highest!\"",
    10: "And when He had entered Jerusalem, all the city was stirred, saying, \"Who is this?\"",
    11: "And the multitudes were saying, \"This is the prophet Jesus, from Nazareth in Galilee.\"",
    12: "And Jesus entered the temple and cast out all those who were buying and selling in the temple, and overturned the tables of the money changers and the seats of those who were selling doves.",
    13: "And He said to them, \"It is written, 'My house shall be called a house of prayer' — but you are making it a robbers' den.\"",
    14: "And the blind and the lame came to Him in the temple, and He healed them.",
    15: "But when the chief priests and the scribes saw the wonderful things that He had done, and the children who were shouting in the temple and saying, \"Hosanna to the Son of David,\" they became indignant.",
    16: "And said to Him, \"Do You hear what these are saying?\" And Jesus said to them, \"Yes. Have you never read, 'Out of the mouth of infants and nursing babes Thou hast prepared praise for Thyself'?\"",
    17: "And He left them and went out of the city to Bethany, and lodged there.",
    18: "Now in the morning, when He returned to the city, He became hungry.",
    19: "And seeing a lone fig tree by the road, He came to it, and found nothing on it except leaves only. And He said to it, \"No longer shall there ever be any fruit from you.\" And at once the fig tree withered.",
    20: "And seeing this, the disciples marveled, saying, \"How did the fig tree wither at once?\"",
    21: "And Jesus answered and said to them, \"Truly I say to you — if you have faith, and do not doubt, you shall not only do what was done to the fig tree, but even if you say to this mountain, 'Be taken up and cast into the sea,' it shall happen.",
    22: "And all things you ask in prayer, believing, you shall receive.\"",
    23: "And when He had come into the temple, the chief priests and the elders of the people came to Him as He was teaching, and said, \"By what authority are You doing these things — and who gave You this authority?\"",
    24: "And Jesus answered and said to them, \"I will ask you one thing too. And if you tell Me the answer, then I will also tell you by what authority I do these things.",
    25: "The baptism of John was from what source — from heaven or from men?\" And they began reasoning among themselves, saying, \"If we say, 'From heaven,' He will say to us, 'Then why did you not believe him?'",
    26: "But if we say, 'From men,' we fear the multitude — for they all hold John to be a prophet.\"",
    27: "And answering Jesus, they said, \"We do not know.\" He also said to them, \"Neither will I tell you by what authority I do these things.",
    28: "But what do you think? A man had two sons. And he came to the first and said, 'Son, go work today in the vineyard.'",
    29: "And he answered and said, 'I will, sir' — and he did not go.",
    30: "And he came to the second and said the same thing. But he answered and said, 'I will not.' Yet he afterward regretted it and went.",
    31: "Which of the two did the will of his father?\" They said, \"The latter.\" Jesus said to them, \"Truly I say to you, that the tax-gatherers and harlots will get into the kingdom of God before you.",
    32: "For John came to you in the way of righteousness, and you did not believe him. But the tax-gatherers and harlots did believe him. And you, seeing this, did not even feel remorse afterward — so as to believe him.",
    33: "Listen to another parable. There was a landowner, who planted a vineyard, and put a wall around it, and dug a wine press in it, and built a tower, and rented it out to vine-growers, and went on a journey.",
    34: "And when the harvest time approached, he sent his slaves to the vine-growers to receive his produce.",
    35: "And the vine-growers took his slaves, and beat one, and killed another, and stoned a third.",
    36: "Again he sent another group of slaves larger than the first. And they did the same thing to them.",
    37: "But afterward he sent his son to them, saying, 'They will respect my son.'",
    38: "But when the vine-growers saw the son, they said among themselves, 'This is the heir. Come — let us kill him, and seize his inheritance.'",
    39: "And they took him, and threw him out of the vineyard, and killed him.",
    40: "Therefore when the owner of the vineyard comes, what will he do to those vine-growers?\"",
    41: "They said to Him, \"He will bring those wretches to a wretched end, and will rent out the vineyard to other vine-growers, who will pay him the proceeds at the proper seasons.\"",
    42: "Jesus said to them, \"Did you never read in the Scriptures, 'The stone which the builders rejected, this became the chief corner stone. This came about from the Lord, and it is marvelous in our eyes'?",
    43: "Therefore I say to you, the kingdom of God will be taken away from you, and be given to a nation producing the fruit of it.",
    44: "And he who falls on this stone will be broken to pieces. But on whomever it falls, it will scatter him like dust.\"",
    45: "And when the chief priests and the Pharisees heard His parables, they understood that He was speaking about them.",
    46: "And although they sought to seize Him, they feared the multitudes, because they held Him to be a prophet.",
}

CHAPTERS = {15:ch15,16:ch16,17:ch17,18:ch18,19:ch19,20:ch20,21:ch21}

def main():
    new_entries = {f"40_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Matthew 15-21 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Matthew 15-21 verses")

if __name__ == "__main__":
    main()
