"""Backfill Job 35-42 — the missing tail of Job (Elihu's final speech +
the LORD's answer from the whirlwind + Job's restoration). 219 verses.

Style: NKJV-faithful with reverential caps to match Job 1-34 already in
moop-translation.json. This is NOT a full MBT rewrite — it's
infrastructure to close the gap so the chronological plan's references
to Job 35-42 don't hit an API fallback.
"""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

# Job 35 (16 verses) — Elihu's third speech
ch35 = {
    1: "Moreover Elihu answered and said:",
    2: "“Do you think this is right? Do you say, ‘My righteousness is more than God’s’?",
    3: "For you say, ‘What advantage will it be to You? What profit shall I have, more than if I had sinned?’",
    4: "“I will answer you, And your companions with you.",
    5: "Look to the heavens and see; And behold the clouds — They are higher than you.",
    6: "If you sin, what do you accomplish against Him? Or, if your transgressions are multiplied, what do you do to Him?",
    7: "If you are righteous, what do you give Him? Or what does He receive from your hand?",
    8: "Your wickedness affects a man such as you, And your righteousness a son of man.",
    9: "“Because of the multitude of oppressions they cry out; They cry out for help because of the arm of the mighty.",
    10: "But no one says, ‘Where is God my Maker, Who gives songs in the night,",
    11: "Who teaches us more than the beasts of the earth, And makes us wiser than the birds of heaven?’",
    12: "There they cry out, but He does not answer, Because of the pride of evil men.",
    13: "Surely God will not listen to empty talk, Nor will the Almighty regard it.",
    14: "Although you say you do not see Him, Yet justice is before Him, and you must wait for Him.",
    15: "And now, because He has not punished in His anger, Nor taken much notice of folly,",
    16: "Therefore Job opens his mouth in vain; He multiplies words without knowledge.”",
}
# Job 36 (33 verses) — Elihu's fourth speech, part 1
ch36 = {
    1: "Elihu also proceeded and said:",
    2: "“Bear with me a little, and I will show you That there are yet words to speak on God’s behalf.",
    3: "I will fetch my knowledge from afar; I will ascribe righteousness to my Maker.",
    4: "For truly my words are not false; One who is perfect in knowledge is with you.",
    5: "“Behold, God is mighty, but despises no one; He is mighty in strength of understanding.",
    6: "He does not preserve the life of the wicked, But gives justice to the oppressed.",
    7: "He does not withdraw His eyes from the righteous; But they are on the throne with kings, For He has seated them forever, And they are exalted.",
    8: "And if they are bound in fetters, Held in the cords of affliction,",
    9: "Then He tells them their work and their transgressions — That they have acted defiantly.",
    10: "He also opens their ear to instruction, And commands that they turn from iniquity.",
    11: "If they obey and serve Him, They shall spend their days in prosperity, And their years in pleasures.",
    12: "But if they do not obey, They shall perish by the sword, And they shall die without knowledge.",
    13: "“But the hypocrites in heart store up wrath; They do not cry for help when He binds them.",
    14: "They die in youth, And their life ends among the perverted persons.",
    15: "He delivers the poor in their affliction, And opens their ears in oppression.",
    16: "“Indeed He would have brought you out of dire distress, Into a broad place where there is no restraint; And what is set on your table would be full of richness.",
    17: "But you are filled with the judgment due the wicked; Judgment and justice take hold of you.",
    18: "Because there is wrath, beware lest He take you away with one blow; For a large ransom would not help you avoid it.",
    19: "Will your riches, Or all the mighty forces, Keep you from distress?",
    20: "Do not desire the night, When people are cut off in their place.",
    21: "Take heed, do not turn to iniquity, For you have chosen this rather than affliction.",
    22: "“Behold, God is exalted by His power; Who teaches like Him?",
    23: "Who has assigned Him His way, Or who has said, ‘You have done wrong’?",
    24: "“Remember to magnify His work, Of which men have sung.",
    25: "Everyone has seen it; Man looks on it from afar.",
    26: "“Behold, God is great, and we do not know Him; Nor can the number of His years be discovered.",
    27: "For He draws up drops of water, Which distill as rain from the mist,",
    28: "Which the clouds drop down And pour abundantly on man.",
    29: "Indeed, can anyone understand the spreading of clouds, The thunder from His canopy?",
    30: "Look, He scatters His light upon it, And covers the depths of the sea.",
    31: "For by these He judges the peoples; He gives food in abundance.",
    32: "He covers His hands with lightning, And commands it to strike.",
    33: "His thunder declares it, The cattle also, concerning the rising storm.",
}
# Job 37 (24 verses) — Elihu's fourth speech, part 2
ch37 = {
    1: "“At this also my heart trembles, And leaps from its place.",
    2: "Hear attentively the thunder of His voice, And the rumbling that comes from His mouth.",
    3: "He sends it forth under the whole heaven, His lightning to the ends of the earth.",
    4: "After it a voice roars; He thunders with His majestic voice, And He does not restrain them when His voice is heard.",
    5: "God thunders marvelously with His voice; He does great things which we cannot comprehend.",
    6: "For He says to the snow, ‘Fall on the earth’; Likewise to the gentle rain and the heavy rain of His strength.",
    7: "He seals the hand of every man, That all men may know His work.",
    8: "The beasts go into dens, And remain in their lairs.",
    9: "From the chamber of the south comes the whirlwind, And cold from the scattering winds of the north.",
    10: "By the breath of God ice is given, And the broad waters are frozen.",
    11: "Also with moisture He saturates the thick clouds; He scatters His bright clouds.",
    12: "And they swirl about, being turned by His guidance, That they may do whatever He commands them On the face of the whole earth.",
    13: "He causes it to come, Whether for correction, Or for His land, Or for mercy.",
    14: "“Listen to this, O Job; Stand still and consider the wondrous works of God.",
    15: "Do you know when God dispatches them, And causes the light of His cloud to shine?",
    16: "Do you know how the clouds are balanced, Those wondrous works of Him who is perfect in knowledge?",
    17: "Why are your garments hot, When He quiets the earth by the south wind?",
    18: "With Him, have you spread out the skies, Strong as a cast metal mirror?",
    19: "“Teach us what we should say to Him, For we can prepare nothing because of the darkness.",
    20: "Should He be told that I wish to speak? If a man were to speak, surely he would be swallowed up.",
    21: "Even now men cannot look at the light when it is bright in the skies, When the wind has passed and cleared them.",
    22: "He comes from the north as golden splendor; With God is awesome majesty.",
    23: "As for the Almighty, we cannot find Him; He is excellent in power, In judgment and abundant justice; He does not oppress.",
    24: "Therefore men fear Him; He shows no partiality to any who are wise of heart.”",
}
# Job 38 (41 verses) — The LORD answers Job out of the whirlwind, part 1
ch38 = {
    1: "Then the LORD answered Job out of the whirlwind, and said:",
    2: "“Who is this who darkens counsel By words without knowledge?",
    3: "Now prepare yourself like a man; I will question you, and you shall answer Me.",
    4: "“Where were you when I laid the foundations of the earth? Tell Me, if you have understanding.",
    5: "Who determined its measurements? Surely you know! Or who stretched the line upon it?",
    6: "To what were its foundations fastened? Or who laid its cornerstone,",
    7: "When the morning stars sang together, And all the sons of God shouted for joy?",
    8: "“Or who shut in the sea with doors, When it burst forth and issued from the womb;",
    9: "When I made the clouds its garment, And thick darkness its swaddling band;",
    10: "When I fixed My limit for it, And set bars and doors;",
    11: "When I said, ‘This far you may come, but no farther, And here your proud waves must stop’?",
    12: "“Have you commanded the morning since your days began, And caused the dawn to know its place,",
    13: "That it might take hold of the ends of the earth, And the wicked be shaken out of it?",
    14: "It takes on form like clay under a seal, And stands out like a garment.",
    15: "From the wicked their light is withheld, And the upraised arm is broken.",
    16: "“Have you entered the springs of the sea? Or have you walked in search of the depths?",
    17: "Have the gates of death been revealed to you? Or have you seen the doors of the shadow of death?",
    18: "Have you comprehended the breadth of the earth? Tell Me, if you know all this.",
    19: "“Where is the way to the dwelling of light? And darkness, where is its place,",
    20: "That you may take it to its territory, That you may know the paths to its home?",
    21: "Do you know it, because you were born then, Or because the number of your days is great?",
    22: "“Have you entered the treasury of snow, Or have you seen the treasury of hail,",
    23: "Which I have reserved for the time of trouble, For the day of battle and war?",
    24: "By what way is light diffused, Or the east wind scattered over the earth?",
    25: "“Who has divided a channel for the overflowing water, Or a path for the thunderbolt,",
    26: "To cause it to rain on a land where there is no one, A wilderness in which there is no man;",
    27: "To satisfy the desolate waste, And cause to spring forth the growth of tender grass?",
    28: "Has the rain a father? Or who has begotten the drops of dew?",
    29: "From whose womb comes the ice? And the frost of heaven, who gives it birth?",
    30: "The waters harden like stone, And the surface of the deep is frozen.",
    31: "“Can you bind the cluster of the Pleiades, Or loose the belt of Orion?",
    32: "Can you bring out Mazzaroth in its season? Or can you guide the Great Bear with its cubs?",
    33: "Do you know the ordinances of the heavens? Can you set their dominion over the earth?",
    34: "“Can you lift up your voice to the clouds, That an abundance of water may cover you?",
    35: "Can you send out lightnings, that they may go, And say to you, ‘Here we are!’?",
    36: "Who has put wisdom in the mind? Or who has given understanding to the heart?",
    37: "Who can number the clouds by wisdom? Or who can pour out the bottles of heaven,",
    38: "When the dust hardens in clumps, And the clods cling together?",
    39: "“Can you hunt the prey for the lion, Or satisfy the appetite of the young lions,",
    40: "When they crouch in their dens, Or lurk in their lairs to lie in wait?",
    41: "Who provides food for the raven, When its young ones cry to God, And wander about for lack of food?",
}
# Job 39 (30 verses)
ch39 = {
    1: "“Do you know the time when the wild mountain goats bear young? Or can you mark when the deer gives birth?",
    2: "Can you number the months that they fulfill? Or do you know the time when they bear young?",
    3: "They bow down, They bring forth their young, They deliver their offspring.",
    4: "Their young ones are healthy, They grow strong with grain; They depart and do not return to them.",
    5: "“Who set the wild donkey free? Who loosed the bonds of the onager,",
    6: "Whose home I have made the wilderness, And the barren land his dwelling?",
    7: "He scorns the tumult of the city; He does not heed the shouts of the driver.",
    8: "The range of the mountains is his pasture, And he searches after every green thing.",
    9: "“Will the wild ox be willing to serve you? Will he bed by your manger?",
    10: "Can you bind the wild ox in the furrow with ropes? Or will he plow the valleys behind you?",
    11: "Will you trust him because his strength is great? Or will you leave your labor to him?",
    12: "Will you trust him to bring home your grain, And gather it to your threshing floor?",
    13: "“The wings of the ostrich wave proudly, But are her wings and pinions like the kindly stork’s?",
    14: "For she leaves her eggs on the ground, And warms them in the dust;",
    15: "She forgets that a foot may crush them, Or that a wild beast may break them.",
    16: "She treats her young harshly, as though they were not hers; Her labor is in vain, without concern,",
    17: "Because God deprived her of wisdom, And did not endow her with understanding.",
    18: "When she lifts herself on high, She scorns the horse and its rider.",
    19: "“Have you given the horse strength? Have you clothed his neck with thunder?",
    20: "Can you frighten him like a locust? His majestic snorting strikes terror.",
    21: "He paws in the valley, and rejoices in his strength; He gallops into the clash of arms.",
    22: "He mocks at fear, and is not frightened; Nor does he turn back from the sword.",
    23: "The quiver rattles against him, The glittering spear and javelin.",
    24: "He devours the distance with fierceness and rage; Nor does he come to a halt because the trumpet has sounded.",
    25: "At the blast of the trumpet he says, ‘Aha!’ He smells the battle from afar, The thunder of captains and shouting.",
    26: "“Does the hawk fly by your wisdom, And spread its wings toward the south?",
    27: "Does the eagle mount up at your command, And make its nest on high?",
    28: "On the rock it dwells and resides, On the crag of the rock and the stronghold.",
    29: "From there it spies out the prey; Its eyes observe from afar.",
    30: "Its young ones suck up blood; And where the slain are, there it is.”",
}
# Job 40 (24 verses)
ch40 = {
    1: "Moreover the LORD answered Job, and said:",
    2: "“Shall the one who contends with the Almighty correct Him? He who rebukes God, let him answer it.”",
    3: "Then Job answered the LORD and said:",
    4: "“Behold, I am vile; What shall I answer You? I lay my hand over my mouth.",
    5: "Once I have spoken, but I will not answer; Yes, twice, but I will proceed no further.”",
    6: "Then the LORD answered Job out of the whirlwind, and said:",
    7: "“Now prepare yourself like a man; I will question you, and you shall answer Me:",
    8: "“Would you indeed annul My judgment? Would you condemn Me that you may be justified?",
    9: "Have you an arm like God? Or can you thunder with a voice like His?",
    10: "Then adorn yourself with majesty and splendor, And array yourself with glory and beauty.",
    11: "Disperse the rage of your wrath; Look on everyone who is proud, and humble him.",
    12: "Look on everyone who is proud, and bring him low; Tread down the wicked in their place.",
    13: "Hide them in the dust together, Bind their faces in hidden darkness.",
    14: "Then I will also confess to you That your own right hand can save you.",
    15: "“Look now at the behemoth, which I made along with you; He eats grass like an ox.",
    16: "See now, his strength is in his hips, And his power is in his stomach muscles.",
    17: "He moves his tail like a cedar; The sinews of his thighs are tightly knit.",
    18: "His bones are like beams of bronze, His ribs like bars of iron.",
    19: "He is the first of the ways of God; Only He who made him can bring near His sword.",
    20: "Surely the mountains yield food for him, And all the beasts of the field play there.",
    21: "He lies under the lotus trees, In a covert of reeds and marsh.",
    22: "The lotus trees cover him with their shade; The willows by the brook surround him.",
    23: "Indeed the river may rage, Yet he is not disturbed; He is confident, though the Jordan gushes into his mouth,",
    24: "Though he takes it in his eyes, Or one pierces his nose with a snare.",
}
# Job 41 (34 verses) — Leviathan
ch41 = {
    1: "“Can you draw out Leviathan with a hook, Or snare his tongue with a line which you lower?",
    2: "Can you put a reed through his nose, Or pierce his jaw with a hook?",
    3: "Will he make many supplications to you? Will he speak softly to you?",
    4: "Will he make a covenant with you? Will you take him as a servant forever?",
    5: "Will you play with him as with a bird, Or will you leash him for your maidens?",
    6: "Will your companions make a banquet of him? Will they apportion him among the merchants?",
    7: "Can you fill his skin with harpoons, Or his head with fishing spears?",
    8: "Lay your hand on him; Remember the battle — Never do it again!",
    9: "Indeed, any hope of overcoming him is false; Shall one not be overwhelmed at the sight of him?",
    10: "No one is so fierce that he would dare stir him up. Who then is able to stand against Me?",
    11: "Who has preceded Me, that I should pay him? Everything under heaven is Mine.",
    12: "“I will not conceal his limbs, His mighty power, or his graceful proportions.",
    13: "Who can remove his outer coat? Who can approach him with a double bridle?",
    14: "Who can open the doors of his face, With his terrible teeth all around?",
    15: "His rows of scales are his pride, Shut up tightly as with a seal;",
    16: "One is so near another That no air can come between them;",
    17: "They are joined one to another, They stick together and cannot be parted.",
    18: "His sneezings flash forth light, And his eyes are like the eyelids of the morning.",
    19: "Out of his mouth go burning lights; Sparks of fire shoot out.",
    20: "Smoke goes out of his nostrils, As from a boiling pot and burning rushes.",
    21: "His breath kindles coals, And a flame goes out of his mouth.",
    22: "Strength dwells in his neck, And sorrow dances before him.",
    23: "The folds of his flesh are joined together; They are firm on him and cannot be moved.",
    24: "His heart is as hard as stone, Even as hard as the lower millstone.",
    25: "When he raises himself up, the mighty are afraid; Because of his crashings they are beside themselves.",
    26: "Though the sword reaches him, it cannot avail; Nor does spear, dart, or javelin.",
    27: "He regards iron as straw, And bronze as rotten wood.",
    28: "The arrow cannot make him flee; Slingstones become like stubble to him.",
    29: "Darts are regarded as straw; He laughs at the threat of javelins.",
    30: "His undersides are like sharp potsherds; He spreads pointed marks in the mire.",
    31: "He makes the deep boil like a pot; He makes the sea like a pot of ointment.",
    32: "He leaves a shining wake behind him; One would think the deep had white hair.",
    33: "On earth there is nothing like him, Which is made without fear.",
    34: "He beholds every high thing; He is king over all the children of pride.”",
}
# Job 42 (17 verses) — Job's repentance and restoration
ch42 = {
    1: "Then Job answered the LORD and said:",
    2: "“I know that You can do everything, And that no purpose of Yours can be withheld from You.",
    3: "You asked, ‘Who is this who hides counsel without knowledge?’ Therefore I have uttered what I did not understand, Things too wonderful for me, which I did not know.",
    4: "Listen, please, and let me speak; You said, ‘I will question you, and you shall answer Me.’",
    5: "“I have heard of You by the hearing of the ear, But now my eye sees You.",
    6: "Therefore I abhor myself, And repent in dust and ashes.”",
    7: "And so it was, after the LORD had spoken these words to Job, that the LORD said to Eliphaz the Temanite, “My wrath is aroused against you and your two friends, for you have not spoken of Me what is right, as My servant Job has.",
    8: "Now therefore, take for yourselves seven bulls and seven rams, go to My servant Job, and offer up for yourselves a burnt offering; and My servant Job shall pray for you. For I will accept him, lest I deal with you according to your folly; because you have not spoken of Me what is right, as My servant Job has.”",
    9: "So Eliphaz the Temanite and Bildad the Shuhite and Zophar the Naamathite went and did as the LORD commanded them; for the LORD had accepted Job.",
    10: "And the LORD restored Job’s losses when he prayed for his friends. Indeed the LORD gave Job twice as much as he had before.",
    11: "Then all his brothers, all his sisters, and all those who had been his acquaintances before, came to him and ate food with him in his house; and they consoled him and comforted him for all the adversity that the LORD had brought upon him. Each one gave him a piece of silver and each a ring of gold.",
    12: "Now the LORD blessed the latter days of Job more than his beginning; for he had fourteen thousand sheep, six thousand camels, one thousand yoke of oxen, and one thousand female donkeys.",
    13: "He also had seven sons and three daughters.",
    14: "And he called the name of the first Jemimah, the name of the second Keziah, and the name of the third Keren-Happuch.",
    15: "In all the land were found no women so beautiful as the daughters of Job; and their father gave them an inheritance among their brothers.",
    16: "After this Job lived one hundred and forty years, and saw his children and grandchildren for four generations.",
    17: "So Job died, old and full of days.",
}

CHAPTERS = {35: ch35, 36: ch36, 37: ch37, 38: ch38, 39: ch39, 40: ch40, 41: ch41, 42: ch42}

def main():
    new_entries = {f"18_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Job 35-42 verses authored: {len(new_entries)}")
    with open(MOOP_PATH) as f: moop = json.load(f)
    before = sum(1 for k in moop if k.startswith('18_'))
    moop.update(new_entries)
    after = sum(1 for k in moop if k.startswith('18_'))
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"Job entries in moop-translation.json: {before} -> {after}")

if __name__ == "__main__":
    main()
