"""MBT Mark 1-8 — the urgent gospel: 'immediately', signs, growing
opposition, the turn at Caesarea Philippi. 323 verses."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch1 = {
    1: "The beginning of the gospel of Jesus Christ, the Son of God.",
    2: "As it is written in Isaiah the prophet: \"Behold, I send My messenger before Your face, who will prepare Your way —",
    3: "the voice of one crying in the wilderness: 'Prepare the way of the Lord — make His paths straight.'\"",
    4: "John came baptizing in the wilderness, and preaching a baptism of repentance for the forgiveness of sins.",
    5: "And all the country of Judea, and all the people of Jerusalem, were going out to him — and they were being baptized by him in the Jordan river, confessing their sins.",
    6: "And John was clothed with camel's hair, and a leather belt around his waist — and he ate locusts and wild honey.",
    7: "And he was preaching: \"After me comes One mightier than I, the strap of whose sandals I am not worthy to stoop down and untie.",
    8: "I baptized you with water — but He will baptize you with the Holy Spirit.\"",
    9: "And it happened in those days that Jesus came from Nazareth of Galilee, and was baptized by John in the Jordan.",
    10: "And immediately, coming up out of the water, He saw the heavens being torn open — and the Spirit descending on Him like a dove.",
    11: "And a voice came from heaven: \"You are My beloved Son — in You I am well pleased.\"",
    12: "And immediately the Spirit drove Him out into the wilderness.",
    13: "And He was there in the wilderness forty days, being tempted by Satan — and He was with the wild beasts. And the angels were ministering to Him.",
    14: "Now after John was put in prison, Jesus came into Galilee — preaching the gospel of the kingdom of God,",
    15: "and saying, \"The time is fulfilled, and the kingdom of God is at hand. Repent — and believe in the gospel.\"",
    16: "And passing along by the Sea of Galilee, He saw Simon and Andrew, the brother of Simon, casting a net into the sea — for they were fishermen.",
    17: "And Jesus said to them, \"Follow Me, and I will make you become fishers of men.\"",
    18: "And immediately they left their nets and followed Him.",
    19: "And going on a little farther, He saw James the son of Zebedee, and John his brother, who were also in the boat mending the nets.",
    20: "And immediately He called them. And they left their father Zebedee in the boat with the hired servants, and went after Him.",
    21: "And they entered Capernaum. And immediately on the Sabbath He entered the synagogue and began to teach.",
    22: "And they were astonished at His teaching — for He was teaching them as one having authority, and not as the scribes.",
    23: "And immediately there was in their synagogue a man with an unclean spirit. And he cried out,",
    24: "saying, \"What have we to do with You, Jesus of Nazareth? Have You come to destroy us? I know who You are — the Holy One of God!\"",
    25: "But Jesus rebuked him, saying, \"Be silent, and come out of him!\"",
    26: "And the unclean spirit, throwing him into convulsions and crying out with a loud voice, came out of him.",
    27: "And they were all amazed, so that they questioned among themselves, saying, \"What is this? A new teaching with authority! He commands even the unclean spirits, and they obey Him.\"",
    28: "And immediately His fame spread everywhere throughout all the surrounding region of Galilee.",
    29: "And immediately, when they had come out of the synagogue, they entered the house of Simon and Andrew, with James and John.",
    30: "Now Simon's mother-in-law was lying sick with a fever. And immediately they spoke to Him about her.",
    31: "And He came and took her by the hand and lifted her up. And the fever left her, and she began to serve them.",
    32: "And at evening, when the sun set, they brought to Him all who were sick — and those who were demon-possessed.",
    33: "And the whole city was gathered together at the door.",
    34: "And He healed many who were sick with various diseases, and cast out many demons — and He would not permit the demons to speak, because they knew Him.",
    35: "And in the morning, while it was still very dark, He arose and went out and departed to a deserted place — and there He prayed.",
    36: "And Simon and those with him went searching for Him,",
    37: "and they found Him, and said to Him, \"Everyone is looking for You.\"",
    38: "And He said to them, \"Let us go on to the next towns, so that I may preach there also — for that is why I came forth.\"",
    39: "And He went into all of Galilee, preaching in their synagogues and casting out demons.",
    40: "And a leper came to Him, imploring Him, and kneeling, and saying to Him, \"If You are willing, You can make me clean.\"",
    41: "And Jesus, moved with compassion, stretched out His hand and touched him, and said to him, \"I am willing — be clean.\"",
    42: "And immediately the leprosy left him, and he was cleansed.",
    43: "And He sternly warned him, and immediately sent him away,",
    44: "and said to him, \"See that you say nothing to anyone — but go, show yourself to the priest, and offer for your cleansing the things which Moses commanded, as a testimony to them.\"",
    45: "But he went out and began to proclaim it freely, and to spread the news around — so that Jesus could no longer openly enter a city, but stayed outside in deserted places. And they came to Him from every direction.",
}

ch2 = {
    1: "And again He entered Capernaum after some days — and it was heard that He was in the house.",
    2: "And immediately many were gathered together, so that there was no longer any room — not even at the door. And He was preaching the word to them.",
    3: "And they came to Him, bringing a paralytic, carried by four men.",
    4: "And when they could not get near Him because of the crowd, they removed the roof where He was. And when they had broken through, they let down the pallet on which the paralytic was lying.",
    5: "And when Jesus saw their faith, He said to the paralytic, \"Son, your sins are forgiven you.\"",
    6: "But some of the scribes were sitting there, and reasoning in their hearts:",
    7: "\"Why does this man speak like this? He blasphemes! Who can forgive sins but God alone?\"",
    8: "And immediately Jesus, perceiving in His spirit that they reasoned thus within themselves, said to them, \"Why do you reason about these things in your hearts?",
    9: "Which is easier — to say to the paralytic, 'Your sins are forgiven you' — or to say, 'Arise, take up your pallet and walk'?",
    10: "But that you may know that the Son of Man has authority on earth to forgive sins\" — He said to the paralytic —",
    11: "\"I say to you: arise, take up your pallet, and go to your house.\"",
    12: "And immediately he arose, took up the pallet, and went out before them all — so that they were all amazed and glorified God, saying, \"We never saw anything like this!\"",
    13: "And He went out again by the sea — and all the multitude came to Him, and He was teaching them.",
    14: "As He passed by, He saw Levi the son of Alphaeus sitting at the tax booth, and He said to him, \"Follow Me.\" And he arose and followed Him.",
    15: "And it happened, as He was reclining at table in his house, that many tax collectors and sinners also reclined with Jesus and His disciples — for there were many, and they followed Him.",
    16: "And when the scribes of the Pharisees saw Him eating with the tax collectors and sinners, they said to His disciples, \"Why does He eat and drink with tax collectors and sinners?\"",
    17: "And when Jesus heard it, He said to them, \"Those who are well have no need of a physician, but those who are sick. I did not come to call the righteous, but sinners — to repentance.\"",
    18: "And the disciples of John and the Pharisees were fasting. And they came and said to Him, \"Why do the disciples of John and of the Pharisees fast — but Your disciples do not fast?\"",
    19: "And Jesus said to them, \"Can the wedding guests fast while the bridegroom is with them? As long as they have the bridegroom with them, they cannot fast.",
    20: "But the days will come when the bridegroom is taken from them — and then they will fast in those days.",
    21: "No one sews a patch of unshrunk cloth on an old garment — for the patch pulls away from it, the new from the old, and a worse tear is made.",
    22: "And no one puts new wine into old wineskins — or else the wine will burst the skins, and the wine is ruined, and the skins are ruined. But new wine must be put into fresh wineskins.\"",
    23: "And it came about that He was going through the grainfields on the Sabbath — and His disciples began to make their way along, picking heads of grain.",
    24: "And the Pharisees said to Him, \"Look — why do they do what is not lawful on the Sabbath?\"",
    25: "And He said to them, \"Have you never read what David did, when he was in need and was hungry, he and those with him?",
    26: "How he entered the house of God, in the time of Abiathar the high priest, and ate the bread of the Presence — which it is not lawful for anyone to eat except the priests — and also gave it to those who were with him?\"",
    27: "And He said to them, \"The Sabbath was made for man — and not man for the Sabbath.",
    28: "So the Son of Man is Lord even of the Sabbath.\"",
}

ch3 = {
    1: "And He entered again into the synagogue. And a man was there who had a withered hand.",
    2: "And they were watching Him closely, to see if He would heal him on the Sabbath — so that they might accuse Him.",
    3: "And He said to the man with the withered hand, \"Come forward.\"",
    4: "And He said to them, \"Is it lawful on the Sabbath to do good or to do harm? To save a life or to kill?\" But they were silent.",
    5: "And after looking around at them with anger — grieved at the hardness of their heart — He said to the man, \"Stretch out your hand.\" And he stretched it out, and his hand was restored.",
    6: "And the Pharisees went out and immediately began conspiring with the Herodians against Him, as to how they might destroy Him.",
    7: "And Jesus withdrew with His disciples to the sea — and a great multitude from Galilee followed.",
    8: "And from Judea, and from Jerusalem, and from Idumea, and beyond the Jordan, and from the region around Tyre and Sidon — a great multitude, hearing all that He was doing, came to Him.",
    9: "And He told His disciples to have a small boat ready for Him because of the multitude — so that they would not crush Him.",
    10: "For He had healed many — so that all who had afflictions pressed upon Him in order to touch Him.",
    11: "And whenever the unclean spirits saw Him, they fell down before Him and cried out, saying, \"You are the Son of God!\"",
    12: "And He sternly warned them that they should not make Him known.",
    13: "And He went up on the mountain and called to Him those He Himself wanted — and they came to Him.",
    14: "And He appointed twelve — that they might be with Him, and that He might send them out to preach,",
    15: "and to have authority to cast out the demons.",
    16: "And He appointed the twelve: Simon — to whom He gave the name Peter;",
    17: "and James the son of Zebedee, and John the brother of James — to whom He gave the name Boanerges, that is, Sons of Thunder;",
    18: "and Andrew, and Philip, and Bartholomew, and Matthew, and Thomas, and James the son of Alphaeus, and Thaddaeus, and Simon the Zealot;",
    19: "and Judas Iscariot — who also betrayed Him.",
    20: "And He came into a house, and again the multitude gathered — so that they could not even eat a meal.",
    21: "And when His own people heard of it, they went out to seize Him — for they were saying, \"He is out of His mind.\"",
    22: "And the scribes who came down from Jerusalem were saying, \"He has Beelzebul,\" and, \"By the prince of demons He casts out the demons.\"",
    23: "And He called them to Himself and was speaking to them in parables: \"How can Satan cast out Satan?",
    24: "If a kingdom is divided against itself, that kingdom cannot stand.",
    25: "And if a house is divided against itself, that house will not be able to stand.",
    26: "And if Satan has risen up against himself and is divided, he cannot stand — but is finished.",
    27: "But no one can enter the strong man's house and plunder his goods, unless he first binds the strong man — and then he will plunder his house.",
    28: "Truly, I say to you — all sins will be forgiven the sons of men, and whatever blasphemies they utter.",
    29: "But whoever blasphemes against the Holy Spirit never has forgiveness — but is guilty of an eternal sin\" —",
    30: "because they were saying, \"He has an unclean spirit.\"",
    31: "Then His mother and His brothers came. And standing outside, they sent to Him, calling Him.",
    32: "And a multitude was sitting around Him — and they said to Him, \"Behold, Your mother and Your brothers are outside seeking You.\"",
    33: "And He answered them, saying, \"Who is My mother, or My brothers?\"",
    34: "And looking around on those who sat about Him, He said, \"Behold, My mother and My brothers!",
    35: "For whoever does the will of God — he is My brother, and sister, and mother.\"",
}

ch4 = {
    1: "And He began again to teach by the sea. And a great multitude was gathered to Him, so that He got into a boat in the sea and sat down — and the whole multitude was on the land facing the sea.",
    2: "And He taught them many things in parables. And He said to them in His teaching:",
    3: "\"Listen! Behold, the sower went out to sow.",
    4: "And it came about, as he was sowing, that some seed fell beside the road — and the birds came and devoured it.",
    5: "And other seed fell on the rocky ground where it did not have much soil — and immediately it sprang up, because it had no depth of soil.",
    6: "And when the sun came up, it was scorched. And because it had no root, it withered away.",
    7: "And other seed fell among the thorns — and the thorns came up and choked it, and it yielded no crop.",
    8: "And other seed fell into the good soil — and as it grew up and increased, it yielded a crop: thirtyfold and sixtyfold and a hundredfold.\"",
    9: "And He was saying, \"He who has ears to hear, let him hear.\"",
    10: "And when He was alone, those around Him with the twelve began asking Him about the parables.",
    11: "And He was saying to them, \"To you has been granted the mystery of the kingdom of God — but to those outside, everything comes in parables.",
    12: "So that 'while seeing they may see, and not perceive — and while hearing they may hear, and not understand. Otherwise they might return and be forgiven.'\"",
    13: "And He said to them, \"Do you not understand this parable? How then will you understand all the parables?",
    14: "The sower sows the word.",
    15: "And these are the ones beside the road, where the word is sown — and when they hear, immediately Satan comes and takes away the word which has been sown in them.",
    16: "And in a similar way these are the ones on whom seed was sown on the rocky places — who, when they hear the word, immediately receive it with joy.",
    17: "And they have no firm root in themselves, but are only temporary — then when affliction or persecution arises because of the word, immediately they fall away.",
    18: "And others are the ones on whom seed was sown among the thorns — these are the ones who have heard the word,",
    19: "and the worries of the world, and the deceitfulness of riches, and the desires for other things enter in — and choke the word, and it becomes unfruitful.",
    20: "And those on whom seed was sown on the good ground — these are the ones who hear the word and accept it, and bear fruit: thirtyfold and sixtyfold and a hundredfold.\"",
    21: "And He was saying to them, \"A lamp is not brought to be put under a basket, or under a bed, is it? Is it not to be put on the lampstand?",
    22: "For nothing is hidden, except to be revealed — nor has anything been secret, but that it should come to light.",
    23: "If anyone has ears to hear, let him hear.\"",
    24: "And He was saying to them, \"Take care what you listen to. By your standard of measure it will be measured to you — and more will be added to you.",
    25: "For whoever has, to him more shall be given — and whoever does not have, even what he has shall be taken away from him.\"",
    26: "And He was saying, \"The kingdom of God is like a man who casts seed upon the soil —",
    27: "and he sleeps and rises night and day, and the seed sprouts up and grows — how, he himself does not know.",
    28: "The soil produces crops by itself — first the blade, then the head, then the mature grain in the head.",
    29: "But when the crop permits, he immediately puts in the sickle — because the harvest has come.\"",
    30: "And He said, \"How shall we picture the kingdom of God? Or with what parable shall we present it?",
    31: "It is like a mustard seed, which, when it is sown upon the soil, though it is smaller than all the seeds that are upon the soil —",
    32: "yet when it is sown, it grows up and becomes larger than all the garden plants — and forms large branches, with the result that the birds of the air can nest under its shade.\"",
    33: "And with many such parables He was speaking the word to them — as they were able to hear it.",
    34: "And He did not speak to them without a parable — but He was explaining everything privately to His own disciples.",
    35: "And on that day, when evening had come, He said to them, \"Let us go over to the other side.\"",
    36: "And leaving the multitude, they took Him along with them in the boat just as He was. And other boats were with Him.",
    37: "And there arose a fierce gale of wind — and the waves were breaking over the boat, so much that the boat was already filling up.",
    38: "And He Himself was in the stern, asleep on the cushion. And they woke Him up, and said to Him, \"Teacher, do You not care that we are perishing?\"",
    39: "And being aroused, He rebuked the wind and said to the sea, \"Hush — be still.\" And the wind died down, and it became perfectly calm.",
    40: "And He said to them, \"Why are you afraid? Have you still no faith?\"",
    41: "And they became very much afraid, and were saying to one another, \"Who then is this — that even the wind and the sea obey Him?\"",
}

ch5 = {
    1: "And they came to the other side of the sea, into the country of the Gerasenes.",
    2: "And when He had come out of the boat, immediately a man from the tombs with an unclean spirit met Him —",
    3: "and he had his dwelling among the tombs. And no one was able to bind him anymore, even with a chain.",
    4: "Because he had often been bound with shackles and chains, and the chains had been torn apart by him, and the shackles broken in pieces — and no one was strong enough to subdue him.",
    5: "And constantly, night and day, among the tombs and in the mountains, he was crying out and gashing himself with stones.",
    6: "And seeing Jesus from a distance, he ran up and bowed down before Him.",
    7: "And crying out with a loud voice, he said, \"What have I to do with You, Jesus, Son of the Most High God? I implore You by God — do not torment me!\"",
    8: "For He had been saying to him, \"Come out of the man, you unclean spirit!\"",
    9: "And He was asking him, \"What is your name?\" And he said to Him, \"My name is Legion — for we are many.\"",
    10: "And he began to implore Him earnestly not to send them out of the country.",
    11: "Now there was a big herd of swine feeding there on the mountain.",
    12: "And the demons implored Him, saying, \"Send us into the swine, so that we may enter them.\"",
    13: "And He gave them permission. And coming out, the unclean spirits entered the swine — and the herd rushed down the steep bank into the sea, about two thousand of them. And they were drowned in the sea.",
    14: "And their herdsmen ran away and reported it in the city and in the country. And the people came to see what it was that had happened.",
    15: "And they came to Jesus and observed the man who had been demon-possessed sitting down — clothed and in his right mind — the very man who had the legion. And they became frightened.",
    16: "And those who had seen it described to them how it had happened to the demon-possessed man — and the story of the swine.",
    17: "And they began to implore Him to depart from their region.",
    18: "And as He was getting into the boat, the man who had been demon-possessed was imploring Him that he might accompany Him.",
    19: "And He did not let him — but He said to him, \"Go home to your people — and report to them what great things the Lord has done for you, and how He had mercy on you.\"",
    20: "And he went away and began to proclaim in Decapolis what great things Jesus had done for him — and everyone was amazed.",
    21: "And when Jesus had crossed over again in the boat to the other side, a great multitude gathered around Him. And He was by the sea.",
    22: "And one of the synagogue officials named Jairus came up, and on seeing Him, fell at His feet,",
    23: "and implored Him earnestly, saying, \"My little daughter is at the point of death. Please come and lay Your hands on her, that she may be made well and live.\"",
    24: "And He went off with him. And a great multitude was following Him and pressing in on Him.",
    25: "And a woman who had had a hemorrhage for twelve years,",
    26: "and had endured much at the hands of many physicians, and had spent all that she had and was not helped at all, but rather had grown worse —",
    27: "after hearing about Jesus, came up in the crowd behind Him and touched His cloak.",
    28: "For she thought, \"If I just touch His garments, I shall get well.\"",
    29: "And immediately the flow of her blood was dried up. And she felt in her body that she was healed of her affliction.",
    30: "And immediately Jesus, perceiving in Himself that the power proceeding from Him had gone forth, turned around in the crowd and was saying, \"Who touched My garments?\"",
    31: "And His disciples said to Him, \"You see the multitude pressing in on You — and You say, 'Who touched Me?'\"",
    32: "And He looked around to see the woman who had done this.",
    33: "But the woman, fearing and trembling — knowing what had happened to her — came and fell down before Him, and told Him the whole truth.",
    34: "And He said to her, \"Daughter, your faith has made you well. Go in peace — and be healed of your affliction.\"",
    35: "While He was still speaking, they came from the house of the synagogue official, saying, \"Your daughter has died. Why trouble the Teacher anymore?\"",
    36: "But Jesus, overhearing what was being spoken, said to the synagogue official, \"Do not be afraid — only believe.\"",
    37: "And He allowed no one to accompany Him, except Peter and James, and John the brother of James.",
    38: "And they came to the house of the synagogue official — and He beheld a commotion, and people weeping and wailing loudly.",
    39: "And entering in, He said to them, \"Why make a commotion and weep? The child has not died — but is asleep.\"",
    40: "And they began laughing at Him. But putting them all out, He took the child's father and mother and His own companions, and entered the room where the child was.",
    41: "And taking the child by the hand, He said to her, \"Talitha kum!\" — which translated means, \"Little girl, I say to you, arise!\"",
    42: "And immediately the girl arose and began to walk — for she was twelve years old. And immediately they were completely astounded.",
    43: "And He gave them strict orders that no one should know about this — and He said that something should be given her to eat.",
}

ch6 = {
    1: "And He went out from there, and came into His hometown — and His disciples followed Him.",
    2: "And when the Sabbath had come, He began to teach in the synagogue. And the many listeners were astonished, saying, \"Where did this man get these things? And what is this wisdom given to Him — and such miracles as these performed by His hands?",
    3: "Is not this the carpenter, the son of Mary — and brother of James, and Joses, and Judas, and Simon? Are not His sisters here with us?\" And they took offense at Him.",
    4: "And Jesus said to them, \"A prophet is not without honor — except in his hometown, and among his own relatives, and in his own household.\"",
    5: "And He could do no miracle there — except that He laid His hands upon a few sick people, and healed them.",
    6: "And He wondered at their unbelief. And He was going around the villages teaching.",
    7: "And He summoned the twelve, and began to send them out in pairs — and He was giving them authority over the unclean spirits.",
    8: "And He instructed them that they should take nothing for their journey except a mere staff — no bread, no bag, no money in their belt,",
    9: "but to wear sandals, and not to put on two tunics.",
    10: "And He was saying to them, \"Wherever you enter a house, stay there until you leave town.",
    11: "And any place that does not receive you, or listen to you — as you go out from there, shake the dust off the soles of your feet as a testimony against them.\"",
    12: "And they went out and preached that men should repent.",
    13: "And they were casting out many demons, and were anointing with oil many sick people and healing them.",
    14: "And King Herod heard of it — for His name had become well known. And people were saying, \"John the Baptist has risen from the dead — and that is why these miraculous powers are at work in Him.\"",
    15: "But others were saying, \"He is Elijah.\" And others were saying, \"He is a prophet — like one of the prophets of old.\"",
    16: "But when Herod heard of it, he kept saying, \"John, whom I beheaded, has risen!\"",
    17: "For Herod himself had sent and had John arrested, and bound in prison on account of Herodias, the wife of his brother Philip — because he had married her.",
    18: "For John had been saying to Herod, \"It is not lawful for you to have your brother's wife.\"",
    19: "And Herodias had a grudge against him, and wanted to put him to death — and yet she could not;",
    20: "for Herod was afraid of John, knowing that he was a righteous and holy man — and he kept him safe. And when he heard him, he was very perplexed — but used to enjoy listening to him.",
    21: "And a strategic day came when Herod, on his birthday, gave a banquet for his lords and military commanders and the leading men of Galilee.",
    22: "And when the daughter of Herodias herself came in and danced, she pleased Herod and his dinner guests. And the king said to the girl, \"Ask me for whatever you want, and I will give it to you.\"",
    23: "And he vowed to her, \"Whatever you ask of me, I will give it to you — up to half of my kingdom!\"",
    24: "And she went out and said to her mother, \"What shall I ask for?\" And she said, \"The head of John the Baptist.\"",
    25: "And immediately she came in a hurry to the king, and asked, saying, \"I want you to give me right away the head of John the Baptist on a platter.\"",
    26: "And although the king was very sorry, yet because of his oaths and his dinner guests, he was unwilling to refuse her.",
    27: "And immediately the king sent an executioner — and commanded him to bring back his head. And he went and beheaded him in the prison,",
    28: "and brought his head on a platter, and gave it to the girl — and the girl gave it to her mother.",
    29: "And when his disciples heard about this, they came and took away his body — and laid it in a tomb.",
    30: "And the apostles gathered together with Jesus — and they reported to Him all that they had done and taught.",
    31: "And He said to them, \"Come away by yourselves to a deserted place — and rest a while.\" For there were many people coming and going, and they did not even have time to eat.",
    32: "And they went away in the boat to a deserted place by themselves.",
    33: "And the people saw them going, and many recognized them — and they ran there together on foot from all the cities, and got there ahead of them.",
    34: "And when He went ashore, He saw a great multitude — and He felt compassion for them, because they were like sheep without a shepherd. And He began to teach them many things.",
    35: "And when it was already quite late, His disciples came up to Him, saying, \"This place is deserted, and it is already quite late.",
    36: "Send them away — so that they may go into the surrounding countryside and villages and buy themselves something to eat.\"",
    37: "But He answered them, \"You give them something to eat!\" And they said to Him, \"Shall we go and spend two hundred denarii on bread and give them something to eat?\"",
    38: "And He said to them, \"How many loaves do you have? Go look!\" And when they found out, they said, \"Five — and two fish.\"",
    39: "And He commanded them all to recline by groups on the green grass.",
    40: "And they reclined in companies of hundreds and of fifties.",
    41: "And He took the five loaves and the two fish, and looking up to heaven, He blessed and broke the loaves, and kept giving them to the disciples to set before them. And He divided up the two fish among them all.",
    42: "And they all ate and were satisfied.",
    43: "And they picked up twelve full baskets of the broken pieces — and also of the fish.",
    44: "And those who ate the loaves were five thousand men.",
    45: "And immediately He made His disciples get into the boat and go ahead of Him to the other side to Bethsaida — while He Himself was sending the multitude away.",
    46: "And after bidding them farewell, He left for the mountain to pray.",
    47: "And when it was evening, the boat was in the middle of the sea — and He was alone on the land.",
    48: "And seeing them straining at the oars (for the wind was against them), at about the fourth watch of the night He came to them, walking on the sea — and He intended to pass by them.",
    49: "But when they saw Him walking on the sea, they supposed that it was a ghost — and they cried out.",
    50: "For they all saw Him and were frightened. But immediately He spoke with them and said to them, \"Take courage — it is I. Do not be afraid.\"",
    51: "And He got into the boat with them — and the wind stopped. And they were utterly astonished within themselves.",
    52: "For they had not gained any insight from the incident of the loaves — but their heart was hardened.",
    53: "And when they had crossed over, they came to land at Gennesaret, and moored to the shore.",
    54: "And when they had come out of the boat, immediately the people recognized Him,",
    55: "and ran about that whole country, and began to carry about on their pallets those who were sick — to the place they heard He was.",
    56: "And wherever He entered villages, or cities, or countryside, they were laying the sick in the market places — and imploring Him that they might just touch the fringe of His cloak. And as many as touched it were being healed.",
}

ch7 = {
    1: "And the Pharisees and some of the scribes, who had come from Jerusalem, gathered around Him.",
    2: "And they had seen that some of His disciples were eating their bread with impure hands — that is, unwashed.",
    3: "For the Pharisees and all the Jews do not eat unless they carefully wash their hands — observing the traditions of the elders.",
    4: "And when they come from the market place, they do not eat unless they cleanse themselves. And there are many other things which they have received in order to observe — such as the washing of cups and pitchers and copper pots.",
    5: "And the Pharisees and the scribes asked Him, \"Why do Your disciples not walk according to the tradition of the elders — but eat their bread with impure hands?\"",
    6: "And He said to them, \"Rightly did Isaiah prophesy of you hypocrites — as it is written: 'This people honors Me with their lips — but their heart is far away from Me.",
    7: "And in vain do they worship Me, teaching as doctrines the precepts of men.'",
    8: "Neglecting the commandment of God, you hold to the tradition of men.\"",
    9: "And He was also saying to them, \"You nicely set aside the commandment of God in order to keep your tradition.",
    10: "For Moses said, 'Honor your father and your mother,' and, 'He who speaks evil of father or mother, let him be put to death.'",
    11: "But you say, 'If a man says to his father or his mother, \"Whatever I have that would help you is Corban\"' — that is to say, given to God —",
    12: "you no longer permit him to do anything for his father or his mother.",
    13: "Thus you invalidate the word of God by your tradition which you have handed down — and you do many things such as that.\"",
    14: "And after He called the multitude to Him again, He began saying to them, \"Listen to Me, all of you — and understand.",
    15: "There is nothing outside the man which going into him can defile him — but the things which proceed out of the man are what defile the man.",
    16: "If anyone has ears to hear, let him hear.\"",
    17: "And when leaving the multitude, He had entered the house, His disciples questioned Him about the parable.",
    18: "And He said to them, \"Are you so lacking in understanding also? Do you not see that whatever goes into the man from outside cannot defile him —",
    19: "because it does not go into his heart, but into his stomach, and is eliminated?\" (Thus He declared all foods clean.)",
    20: "And He was saying, \"That which proceeds out of the man — that is what defiles the man.",
    21: "For from within, out of the heart of men, proceed the evil thoughts — fornications, thefts, murders, adulteries,",
    22: "deeds of coveting and wickedness, deceit, sensuality, envy, slander, pride, foolishness.",
    23: "All these evil things proceed from within — and defile the man.\"",
    24: "And from there He arose and went away to the region of Tyre. And when He had entered a house, He wanted no one to know of it — yet He could not escape notice.",
    25: "But immediately, after hearing of Him, a woman whose little daughter had an unclean spirit came and fell at His feet.",
    26: "Now the woman was a Greek, a Syrophoenician by nationality. And she kept asking Him to cast the demon out of her daughter.",
    27: "And He was saying to her, \"Let the children first be satisfied — for it is not good to take the children's bread and throw it to the little dogs.\"",
    28: "But she answered and said to Him, \"Yes, Lord — but even the little dogs under the table feed on the children's crumbs.\"",
    29: "And He said to her, \"Because of this answer, go your way — the demon has gone out of your daughter.\"",
    30: "And going back to her home, she found the child lying on the bed — the demon having gone out.",
    31: "And again, He went out from the region of Tyre, and came through Sidon to the Sea of Galilee, within the region of Decapolis.",
    32: "And they brought to Him one who was deaf and spoke with difficulty — and they implored Him to lay His hand upon him.",
    33: "And He took him aside from the multitude, by himself, and put His fingers into his ears. And after spitting, He touched his tongue with the saliva.",
    34: "And looking up to heaven with a deep sigh, He said to him, \"Ephphatha!\" — that is, \"Be opened!\"",
    35: "And his ears were opened — and the impediment of his tongue was removed, and he began speaking plainly.",
    36: "And He gave them orders not to tell anyone. But the more He ordered them, the more widely they continued to proclaim it.",
    37: "And they were utterly astonished, saying, \"He has done all things well — He makes even the deaf to hear, and the dumb to speak.\"",
}

ch8 = {
    1: "In those days, when there was again a great multitude and they had nothing to eat, He called His disciples to Him and said to them,",
    2: "\"I feel compassion for the multitude, because they have remained with Me now three days — and have nothing to eat.",
    3: "And if I send them away hungry to their home, they will faint on the way — and some of them have come from a great distance.\"",
    4: "And His disciples answered Him, \"Where will anyone be able to find enough bread here in this deserted place to satisfy these people?\"",
    5: "And He was asking them, \"How many loaves do you have?\" And they said, \"Seven.\"",
    6: "And He directed the multitude to recline on the ground. And taking the seven loaves and giving thanks, He broke them and started giving them to His disciples to serve to them — and they served them to the multitude.",
    7: "And they also had a few small fish — and after He had blessed them, He ordered these to be served as well.",
    8: "And they ate and were satisfied — and they picked up seven large baskets full of what was left over of the broken pieces.",
    9: "And about four thousand were there. And He sent them away.",
    10: "And immediately He entered the boat with His disciples, and came to the district of Dalmanutha.",
    11: "And the Pharisees came out and began to argue with Him, seeking from Him a sign from heaven — to test Him.",
    12: "And sighing deeply in His spirit, He said, \"Why does this generation seek for a sign? Truly I say to you — no sign shall be given to this generation.\"",
    13: "And leaving them, He again embarked and went away to the other side.",
    14: "And they had forgotten to take bread — and did not have more than one loaf in the boat with them.",
    15: "And He was giving orders to them, saying, \"Watch out! Beware of the leaven of the Pharisees, and the leaven of Herod.\"",
    16: "And they began to discuss with one another the fact that they had no bread.",
    17: "And Jesus, aware of this, said to them, \"Why do you discuss the fact that you have no bread? Do you not yet see or understand? Do you have a hardened heart?",
    18: "Having eyes, do you not see? And having ears, do you not hear? And do you not remember,",
    19: "when I broke the five loaves for the five thousand — how many baskets full of broken pieces you picked up?\" They said to Him, \"Twelve.\"",
    20: "\"And when I broke the seven for the four thousand — how many large baskets full of broken pieces did you pick up?\" And they said to Him, \"Seven.\"",
    21: "And He was saying to them, \"Do you not yet understand?\"",
    22: "And they came to Bethsaida. And they brought a blind man to Jesus, and entreated Him to touch him.",
    23: "And taking the blind man by the hand, He brought him out of the village. And after spitting on his eyes and laying His hands upon him, He asked him, \"Do you see anything?\"",
    24: "And he looked up and said, \"I see men — for I see them like trees, walking about.\"",
    25: "Then again He laid His hands upon his eyes — and he looked intently and was restored, and began to see everything clearly.",
    26: "And He sent him to his home, saying, \"Do not even enter the village.\"",
    27: "And Jesus went out, along with His disciples, to the villages of Caesarea Philippi. And on the way He questioned His disciples, saying to them, \"Who do people say that I am?\"",
    28: "And they told Him, saying, \"John the Baptist — and others say Elijah; but others, one of the prophets.\"",
    29: "And He continued by questioning them, \"But who do you say that I am?\" Peter answered and said to Him, \"You are the Christ.\"",
    30: "And He warned them to tell no one about Him.",
    31: "And He began to teach them that the Son of Man must suffer many things, and be rejected by the elders and the chief priests and the scribes — and be killed, and after three days rise again.",
    32: "And He was stating the matter plainly. And Peter took Him aside and began to rebuke Him.",
    33: "But turning around and seeing His disciples, He rebuked Peter and said, \"Get behind Me, Satan! For you are not setting your mind on God's interests, but man's.\"",
    34: "And He summoned the multitude with His disciples, and said to them, \"If anyone wishes to come after Me, let him deny himself, and take up his cross, and follow Me.",
    35: "For whoever wishes to save his life shall lose it — but whoever loses his life for My sake and the gospel's shall save it.",
    36: "For what does it profit a man to gain the whole world, and forfeit his soul?",
    37: "For what shall a man give in exchange for his soul?",
    38: "For whoever is ashamed of Me and My words in this adulterous and sinful generation — the Son of Man will also be ashamed of him when He comes in the glory of His Father with the holy angels.\"",
}

CHAPTERS = {1:ch1,2:ch2,3:ch3,4:ch4,5:ch5,6:ch6,7:ch7,8:ch8}

def main():
    new_entries = {f"41_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Mark 1-8 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Mark 1-8 verses")

if __name__ == "__main__":
    main()
