"""MBT Revelation 12-22 — Woman, Beast, Lamb on Zion, Bowls, Babylon's
Fall, Hallelujah, Millennium, New Jerusalem, the Return.
11 chapters, 210 verses. Book ID 66."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
MBT_PATH = ROOT / "docs" / "assets" / "mbt-nt-extra.json"
MOOP_PATH = ROOT / "docs" / "assets" / "moop-translation.json"

ch12 = {
    1: "And a great sign appeared in heaven: a woman clothed with the sun, with the moon under her feet — and on her head a crown of twelve stars.",
    2: "And she was with child — and she cried out in birth pains and in agony to give birth.",
    3: "And another sign appeared in heaven — and behold, a great fiery red dragon, having seven heads and ten horns, and on his heads were seven diadems.",
    4: "And his tail swept away a third of the stars of heaven — and threw them to the earth. And the dragon stood before the woman who was about to give birth, so that when she gave birth he might devour her child.",
    5: "And she gave birth to a son — a male child — who is going to rule all the nations with a rod of iron. And her child was caught up to God and to His throne.",
    6: "And the woman fled into the wilderness, where she has a place prepared by God — so that there they would feed her for one thousand two hundred and sixty days.",
    7: "And there was war in heaven: Michael and his angels waging war with the dragon. And the dragon and his angels waged war —",
    8: "and they did not prevail, nor was a place found for them any longer in heaven.",
    9: "And the great dragon was thrown down — that ancient serpent, who is called the devil and Satan, who deceives the whole inhabited world. He was thrown down to the earth — and his angels were thrown down with him.",
    10: "And I heard a loud voice in heaven, saying: \"Now have come the salvation, and the power, and the kingdom of our God — and the authority of His Christ. For the accuser of our brothers has been thrown down — the one who accuses them before our God day and night.",
    11: "And they overcame him by the blood of the Lamb, and by the word of their testimony — and they did not love their lives, even unto death.",
    12: "Therefore rejoice, O heavens — and you who dwell in them. Woe to the earth and the sea — for the devil has come down to you, having great wrath, knowing that he has only a short time.\"",
    13: "And when the dragon saw that he had been thrown down to the earth, he persecuted the woman who had given birth to the male child.",
    14: "And the two wings of the great eagle were given to the woman — so that she could fly into the wilderness to her place, where she is nourished for a time, and times, and half a time, away from the presence of the serpent.",
    15: "And the serpent poured out of his mouth water like a river after the woman — so that he might cause her to be swept away with the flood.",
    16: "And the earth came to the help of the woman: the earth opened its mouth and swallowed up the river that the dragon had poured out of his mouth.",
    17: "And the dragon was enraged at the woman — and went off to make war with the rest of her offspring: those who keep the commandments of God, and hold the testimony of Jesus.",
}
ch13 = {
    1: "And he stood on the sand of the sea. And I saw a beast coming up out of the sea, having ten horns and seven heads. And on his horns were ten diadems, and on his heads were blasphemous names.",
    2: "And the beast that I saw was like a leopard. His feet were like the feet of a bear, and his mouth like the mouth of a lion. And the dragon gave to him his power, and his throne, and great authority.",
    3: "And one of his heads appeared as if it had been slain to death — but his fatal wound was healed. And the whole earth marveled and followed after the beast.",
    4: "And they worshiped the dragon because he gave authority to the beast. And they worshiped the beast, saying, \"Who is like the beast? And who is able to wage war with him?\"",
    5: "And there was given to him a mouth speaking great things and blasphemies. And authority was given to him to act for forty-two months.",
    6: "And he opened his mouth in blasphemies against God — to blaspheme His name and His tabernacle, and those who dwell in heaven.",
    7: "And it was given to him to make war with the saints, and to overcome them. And authority was given to him over every tribe and people and tongue and nation.",
    8: "And all who dwell on the earth will worship him — everyone whose name has not been written, from the foundation of the world, in the Book of Life of the Lamb who has been slain.",
    9: "If anyone has an ear, let him hear:",
    10: "If anyone is destined for captivity, into captivity he goes. If anyone is to be killed with the sword, with the sword he must be killed. Here is the steadfastness and the faith of the saints.",
    11: "And I saw another beast coming up out of the earth — and he had two horns like a lamb, and he spoke like a dragon.",
    12: "And he exercises all the authority of the first beast in his presence. And he makes the earth and those who dwell in it to worship the first beast — whose fatal wound was healed.",
    13: "And he performs great signs — even making fire come down out of heaven to the earth in the sight of men.",
    14: "And he deceives those who dwell on the earth, because of the signs which it was given to him to perform in the presence of the beast — telling those who dwell on the earth to make an image to the beast who had the wound of the sword and yet lived.",
    15: "And it was given to him to give breath to the image of the beast — so that the image of the beast would even speak, and would cause as many as do not worship the image of the beast to be killed.",
    16: "And he causes all — the small and the great, and the rich and the poor, and the free and the slaves — to be given a mark on their right hand, or on their forehead;",
    17: "and that no one would be able to buy or to sell, except the one who has the mark — either the name of the beast, or the number of his name.",
    18: "Here is wisdom: let the one who has understanding calculate the number of the beast — for the number is that of a man, and his number is six hundred and sixty-six.",
}
ch14 = {
    1: "And I looked, and behold, the Lamb was standing on Mount Zion — and with Him a hundred and forty-four thousand, having His name and the name of His Father written on their foreheads.",
    2: "And I heard a voice from heaven, like the sound of many waters, and like the sound of loud thunder. And the voice I heard was like that of harpists playing on their harps.",
    3: "And they sing, as it were, a new song before the throne and before the four living creatures and the elders. And no one could learn the song except the hundred and forty-four thousand who had been redeemed from the earth.",
    4: "These are the ones who have not been defiled with women — for they are virgins. These are the ones who follow the Lamb wherever He goes. These have been redeemed from among men — firstfruits to God and to the Lamb.",
    5: "And in their mouth no lie was found. They are blameless.",
    6: "And I saw another angel flying in midheaven, having an eternal gospel to preach to those who live on the earth — and to every nation and tribe and tongue and people —",
    7: "saying with a loud voice: \"Fear God, and give Him glory — for the hour of His judgment has come. And worship the One who made the heaven, and the earth, and the sea, and the springs of waters.\"",
    8: "And another, a second angel, followed — saying, \"Fallen, fallen is Babylon the great — she who has made all the nations drink of the wine of the passion of her immorality.\"",
    9: "And another, a third angel, followed them — saying with a loud voice, \"If anyone worships the beast and his image, and receives a mark on his forehead or on his hand,",
    10: "he himself also will drink of the wine of the wrath of God — which is mixed full strength in the cup of His anger. And he will be tormented with fire and brimstone in the presence of the holy angels and in the presence of the Lamb.",
    11: "And the smoke of their torment goes up forever and ever. And they have no rest day and night — those who worship the beast and his image, and whoever receives the mark of his name.\"",
    12: "Here is the steadfastness of the saints — those who keep the commandments of God and the faith of Jesus.",
    13: "And I heard a voice from heaven, saying, \"Write: 'Blessed are the dead who die in the Lord from now on.' \" \"Yes,\" says the Spirit, \"so that they may rest from their labors — for their works follow with them.\"",
    14: "And I looked, and behold, a white cloud — and on the cloud was sitting One like a Son of Man, having on His head a golden crown, and in His hand a sharp sickle.",
    15: "And another angel came out of the temple, calling out with a loud voice to the One sitting on the cloud: \"Send Your sickle, and reap — for the hour to reap has come, because the harvest of the earth is ripe.\"",
    16: "And the One sitting on the cloud swung His sickle over the earth — and the earth was reaped.",
    17: "And another angel came out of the temple in heaven — also having a sharp sickle.",
    18: "And another angel came out of the altar — the one who has authority over the fire — and he called out with a loud voice to the one who had the sharp sickle, saying, \"Send your sharp sickle and gather the clusters of the vine of the earth — for her grapes are ripe.\"",
    19: "And the angel swung his sickle to the earth, and gathered the clusters from the vine of the earth — and threw them into the great winepress of the wrath of God.",
    20: "And the winepress was trodden outside the city. And blood came out of the winepress, up to the bridles of the horses, for a distance of about two hundred miles.",
}
ch15 = {
    1: "And I saw another sign in heaven — great and marvelous: seven angels having seven plagues, the last ones — for in them the wrath of God is finished.",
    2: "And I saw, as it were, a sea of glass mixed with fire — and those who came off victorious from the beast and from his image and from the number of his name, standing on the sea of glass, holding harps of God.",
    3: "And they sing the song of Moses, the bondservant of God, and the song of the Lamb, saying: \"Great and marvelous are Your works, O Lord God, the Almighty. Righteous and true are Your ways, O King of the nations.",
    4: "Who will not fear, O Lord — and glorify Your name? For You alone are holy. For all the nations will come and worship before You — for Your righteous acts have been revealed.\"",
    5: "And after these things I looked — and the temple of the tabernacle of the testimony in heaven was opened.",
    6: "And out of the temple came the seven angels who had the seven plagues — clothed in clean, bright linen, and girded around their chests with golden sashes.",
    7: "And one of the four living creatures gave to the seven angels seven golden bowls, full of the wrath of God — who lives forever and ever.",
    8: "And the temple was filled with smoke from the glory of God and from His power. And no one was able to enter the temple until the seven plagues of the seven angels were finished.",
}
ch16 = {
    1: "And I heard a loud voice from the temple, saying to the seven angels, \"Go and pour out the seven bowls of the wrath of God on the earth.\"",
    2: "And the first one went and poured out his bowl on the earth. And it became a foul and malignant sore on the people who had the mark of the beast and who worshiped his image.",
    3: "And the second angel poured out his bowl into the sea — and it became blood like that of a dead man. And every living thing in the sea died.",
    4: "And the third angel poured out his bowl into the rivers and the springs of waters — and they became blood.",
    5: "And I heard the angel of the waters saying, \"Righteous are You — the One who is, and the One who was, the Holy One — because You judged these things.",
    6: "For they poured out the blood of the saints and the prophets — and You have given them blood to drink. They deserve it.\"",
    7: "And I heard the altar saying, \"Yes, O Lord God, the Almighty — Your judgments are true and righteous.\"",
    8: "And the fourth angel poured out his bowl on the sun — and it was given to it to scorch men with fire.",
    9: "And the men were scorched with fierce heat. And they blasphemed the name of God, who has authority over these plagues — and they did not repent so as to give Him glory.",
    10: "And the fifth angel poured out his bowl on the throne of the beast — and his kingdom became darkened. And they were gnawing their tongues from pain,",
    11: "and they blasphemed the God of heaven because of their pains and their sores — and they did not repent of their deeds.",
    12: "And the sixth angel poured out his bowl on the great river, the Euphrates — and its water was dried up, so that the way might be prepared for the kings from the east.",
    13: "And I saw three unclean spirits, like frogs, coming out of the mouth of the dragon, and out of the mouth of the beast, and out of the mouth of the false prophet.",
    14: "For they are spirits of demons, performing signs — which go out to the kings of the whole inhabited world, to gather them together for the war of the great day of God Almighty.",
    15: "(\"Behold, I am coming like a thief. Blessed is the one who stays awake and keeps his garments — so that he will not walk about naked, and they see his shame.\")",
    16: "And they gathered them together to the place that in Hebrew is called Har-Magedon.",
    17: "And the seventh angel poured out his bowl into the air — and a loud voice came out of the temple from the throne, saying, \"It is done.\"",
    18: "And there were flashes of lightning and rumblings and peals of thunder. And there was a great earthquake — such as had not occurred since man came to be on the earth, so great an earthquake was it, and so mighty.",
    19: "And the great city was split into three parts — and the cities of the nations fell. And Babylon the great was remembered before God, to give her the cup of the wine of the fierceness of His wrath.",
    20: "And every island fled away — and the mountains were not found.",
    21: "And huge hailstones, about a hundred pounds each, came down from heaven upon men. And the men blasphemed God because of the plague of the hail — for the plague was extremely severe.",
}
ch17 = {
    1: "And one of the seven angels who had the seven bowls came and spoke with me, saying, \"Come — I will show you the judgment of the great prostitute who sits on many waters,",
    2: "with whom the kings of the earth committed sexual immorality — and those who dwell on the earth were made drunk with the wine of her immorality.\"",
    3: "And he carried me away in the Spirit into a wilderness. And I saw a woman sitting on a scarlet beast — full of blasphemous names, having seven heads and ten horns.",
    4: "And the woman was clothed in purple and scarlet, and adorned with gold, and precious stones, and pearls — having in her hand a golden cup full of abominations and the unclean things of her sexual immorality.",
    5: "And on her forehead was a name written: a mystery — \"Babylon the Great, the Mother of Prostitutes and of the Abominations of the Earth.\"",
    6: "And I saw the woman drunk with the blood of the saints and with the blood of the witnesses of Jesus. And when I saw her, I marveled with great amazement.",
    7: "And the angel said to me, \"Why did you marvel? I will tell you the mystery of the woman, and of the beast that carries her — the one having the seven heads and the ten horns.",
    8: "The beast that you saw was, and is not — and is about to come up out of the abyss, and is going to destruction. And those who dwell on the earth — whose names have not been written in the Book of Life from the foundation of the world — will marvel when they see the beast: that he was, and is not, and shall come.",
    9: "Here is the mind which has wisdom: the seven heads are seven mountains on which the woman sits.",
    10: "And they are seven kings — five have fallen, one is, and the other has not yet come. And when he comes, he must remain a little while.",
    11: "And the beast that was, and is not — he himself is also an eighth, and is one of the seven, and he goes to destruction.",
    12: "And the ten horns that you saw are ten kings, who have not yet received a kingdom — but they receive authority as kings, with the beast, for one hour.",
    13: "These have one mind — and they give their power and authority to the beast.",
    14: "These will wage war with the Lamb — and the Lamb will overcome them, because He is Lord of lords and King of kings. And those who are with Him are the called and chosen and faithful.\"",
    15: "And he said to me, \"The waters that you saw — where the prostitute sits — are peoples and multitudes and nations and tongues.",
    16: "And the ten horns that you saw, and the beast — these will hate the prostitute. And they will make her desolate and naked, and will eat her flesh, and will burn her up with fire.",
    17: "For God put it into their hearts to carry out His purpose — to be of one mind, and to give their kingdom to the beast, until the words of God are fulfilled.",
    18: "And the woman whom you saw is the great city — which has a kingdom over the kings of the earth.\"",
}
ch18 = {
    1: "After these things I saw another angel coming down out of heaven, having great authority. And the earth was illumined with his glory.",
    2: "And he cried out with a mighty voice, saying: \"Fallen, fallen is Babylon the great! She has become a dwelling place of demons — a haunt of every unclean spirit, and a haunt of every unclean and hateful bird.",
    3: "For all the nations have drunk of the wine of the passion of her immorality. And the kings of the earth have committed immorality with her — and the merchants of the earth have become rich by the wealth of her sensuality.\"",
    4: "And I heard another voice from heaven, saying: \"Come out of her, My people — so that you will not share in her sins, and so that you will not receive of her plagues.",
    5: "For her sins have piled up as high as heaven — and God has remembered her iniquities.",
    6: "Pay her back even as she has paid — and give back to her double according to her deeds. In the cup which she has mixed, mix twice as much for her.",
    7: "To the degree that she glorified herself and lived sensuously, to that degree give her torment and mourning. For in her heart she says, 'I sit as a queen — I am no widow, and I will never see mourning.'",
    8: "Therefore in one day her plagues will come — pestilence and mourning and famine. And she will be burned up with fire — for the Lord God who judges her is strong.\"",
    9: "And the kings of the earth — who committed immorality with her, and lived sensuously with her — will weep and lament for her, when they see the smoke of her burning.",
    10: "Standing far off because of the fear of her torment, they say, \"Woe, woe — the great city, Babylon, the strong city! For in one hour your judgment has come.\"",
    11: "And the merchants of the earth weep and mourn for her, because no one buys their cargoes anymore —",
    12: "cargoes of gold and silver and precious stones and pearls; of fine linen and purple and silk and scarlet; every kind of citron wood, every article of ivory, every article of most precious wood and bronze and iron and marble;",
    13: "and cinnamon and spice and incense and myrrh and frankincense; and wine and olive oil and fine flour and wheat; and cattle and sheep, horses and chariots — and slaves, and the souls of men.",
    14: "\"And the fruit you long for has gone from you. All things that were luxurious and splendid have passed away from you — and people will no longer find them.\"",
    15: "The merchants of these things — who became rich from her — will stand far off, because of the fear of her torment, weeping and mourning,",
    16: "saying, \"Woe, woe — the great city, clothed in fine linen and purple and scarlet, and adorned with gold and precious stones and pearls!",
    17: "For in one hour such great wealth has been laid waste!\" And every shipmaster, and every passenger and sailor, and as many as make their living by the sea, stood far off.",
    18: "And they were crying out as they saw the smoke of her burning, saying, \"What city is like the great city?\"",
    19: "And they threw dust on their heads, and were crying out, weeping and mourning, saying, \"Woe, woe — the great city, by which all who had ships at sea became rich by her wealth! For in one hour she has been laid waste!\"",
    20: "Rejoice over her, O heaven — and you saints and apostles and prophets — because God has pronounced your judgment against her.",
    21: "And a strong angel took up a stone like a great millstone — and threw it into the sea, saying: \"In this way Babylon, the great city, will be thrown down with violence — and will not be found any longer.",
    22: "And the sound of harpists and musicians and flute-players and trumpeters will not be heard in you any longer. And no craftsman of any craft will be found in you any longer. And the sound of a mill will not be heard in you any longer.",
    23: "And the light of a lamp will not shine in you any longer. And the voice of bridegroom and bride will not be heard in you any longer — because your merchants were the great men of the earth, because all the nations were deceived by your sorcery.",
    24: "And in her was found the blood of prophets and of saints — and of all who have been slain on the earth.\"",
}
ch19 = {
    1: "After these things I heard, as it were, a loud voice of a great multitude in heaven, saying: \"Hallelujah! The salvation, and the glory, and the power belong to our God —",
    2: "for true and righteous are His judgments. For He has judged the great prostitute who corrupted the earth with her immorality — and He has avenged the blood of His bondservants on her.\"",
    3: "And a second time they said, \"Hallelujah! Her smoke goes up forever and ever.\"",
    4: "And the twenty-four elders and the four living creatures fell down and worshiped God who sits on the throne, saying, \"Amen — Hallelujah!\"",
    5: "And a voice came from the throne, saying, \"Give praise to our God, all you His bondservants — those who fear Him, the small and the great.\"",
    6: "And I heard, as it were, the voice of a great multitude, and like the sound of many waters, and like the sound of mighty peals of thunder, saying: \"Hallelujah! For the Lord our God, the Almighty, has begun to reign.",
    7: "Let us rejoice and be glad and give the glory to Him — for the marriage of the Lamb has come, and His bride has made herself ready.",
    8: "And it was given to her to be clothed in fine linen, bright and clean — for the fine linen is the righteous deeds of the saints.\"",
    9: "And he said to me, \"Write: Blessed are those who are invited to the marriage supper of the Lamb.\" And he said to me, \"These are the true words of God.\"",
    10: "And I fell at his feet to worship him. And he said to me, \"See that you do not do that. I am a fellow servant of yours, and of your brothers who hold the testimony of Jesus. Worship God. For the testimony of Jesus is the spirit of prophecy.\"",
    11: "And I saw heaven opened — and behold, a white horse. And the One sitting on it is called Faithful and True. And in righteousness He judges and wages war.",
    12: "And His eyes are a flame of fire. And on His head are many diadems. And He has a name written on Him which no one knows except Himself.",
    13: "And He is clothed in a robe dipped in blood — and His name is called The Word of God.",
    14: "And the armies which are in heaven were following Him on white horses — clothed in fine linen, white and clean.",
    15: "And out of His mouth comes a sharp sword — so that with it He may strike down the nations. And He will rule them with a rod of iron — and He treads the winepress of the fierce wrath of God, the Almighty.",
    16: "And on His robe and on His thigh He has a name written: \"KING OF KINGS, AND LORD OF LORDS.\"",
    17: "And I saw an angel standing in the sun. And he cried out with a loud voice, saying to all the birds that fly in midheaven: \"Come, gather together for the great supper of God —",
    18: "so that you may eat the flesh of kings, and the flesh of commanders, and the flesh of mighty men, and the flesh of horses and those sitting on them — and the flesh of all men, both free men and slaves, both small and great.\"",
    19: "And I saw the beast and the kings of the earth and their armies, gathered together to wage war against the One sitting on the horse, and against His army.",
    20: "And the beast was seized — and with him the false prophet who performed the signs in his presence, by which he had deceived those who received the mark of the beast and those who worshiped his image. The two were thrown alive into the lake of fire that burns with brimstone.",
    21: "And the rest were killed by the sword which proceeded from the mouth of the One sitting on the horse — and all the birds were filled with their flesh.",
}
ch20 = {
    1: "And I saw an angel coming down from heaven, having the key of the abyss and a great chain in his hand.",
    2: "And he laid hold of the dragon — that ancient serpent, who is the devil and Satan — and bound him for a thousand years.",
    3: "And he threw him into the abyss, and shut it, and sealed it over him — so that he should deceive the nations no longer, until the thousand years were completed. After these things he must be released for a short time.",
    4: "And I saw thrones, and they sat on them — and judgment was given to them. And I saw the souls of those who had been beheaded because of the testimony of Jesus and because of the word of God — those who had not worshiped the beast or his image, and had not received the mark on their forehead and on their hand. And they came to life and reigned with Christ for a thousand years.",
    5: "The rest of the dead did not come to life until the thousand years were completed. This is the first resurrection.",
    6: "Blessed and holy is the one who has a part in the first resurrection. Over these the second death has no authority — but they will be priests of God and of Christ, and will reign with Him for a thousand years.",
    7: "And when the thousand years are completed, Satan will be released from his prison.",
    8: "And he will come out to deceive the nations which are in the four corners of the earth — Gog and Magog — to gather them together for the war. The number of them is as the sand of the seashore.",
    9: "And they came up over the breadth of the earth, and surrounded the camp of the saints and the beloved city. And fire came down from heaven and devoured them.",
    10: "And the devil who deceived them was thrown into the lake of fire and brimstone — where the beast and the false prophet are also. And they will be tormented day and night forever and ever.",
    11: "And I saw a great white throne, and the One sitting on it — from whose presence earth and heaven fled away, and no place was found for them.",
    12: "And I saw the dead, the great and the small, standing before the throne. And books were opened — and another book was opened, which is the Book of Life. And the dead were judged from the things written in the books, according to their deeds.",
    13: "And the sea gave up the dead which were in it, and Death and Hades gave up the dead which were in them. And they were judged, each one of them, according to their deeds.",
    14: "And Death and Hades were thrown into the lake of fire. This is the second death — the lake of fire.",
    15: "And if anyone's name was not found written in the Book of Life, he was thrown into the lake of fire.",
}
ch21 = {
    1: "And I saw a new heaven and a new earth — for the first heaven and the first earth had passed away, and there is no longer any sea.",
    2: "And I saw the holy city — new Jerusalem — coming down out of heaven from God, prepared as a bride adorned for her husband.",
    3: "And I heard a loud voice from the throne, saying, \"Behold, the tabernacle of God is among men — and He will dwell among them. And they will be His peoples, and God Himself will be among them and be their God.",
    4: "And He will wipe away every tear from their eyes — and there will no longer be any death; nor mourning, nor crying, nor pain. The first things have passed away.\"",
    5: "And the One sitting on the throne said, \"Behold, I am making all things new.\" And He said, \"Write — for these words are faithful and true.\"",
    6: "And He said to me, \"It is done. I am the Alpha and the Omega — the Beginning and the End. To the one who thirsts, I will give from the spring of the water of life freely.",
    7: "The one who overcomes will inherit these things, and I will be his God — and he will be My son.",
    8: "But for the cowardly, and unbelieving, and abominable, and murderers, and the sexually immoral, and sorcerers, and idolaters, and all liars — their part will be in the lake that burns with fire and brimstone, which is the second death.\"",
    9: "And one of the seven angels — those who had the seven bowls full of the seven last plagues — came and spoke with me, saying, \"Come — I will show you the bride, the wife of the Lamb.\"",
    10: "And he carried me away in the Spirit to a great and high mountain — and showed me the holy city, Jerusalem, coming down out of heaven from God,",
    11: "having the glory of God. Her brilliance was like a very precious stone — like a stone of crystal-clear jasper.",
    12: "It had a great and high wall, with twelve gates — and at the gates twelve angels. And on the gates names were written, which are those of the twelve tribes of the sons of Israel.",
    13: "On the east, three gates; on the north, three gates; on the south, three gates; and on the west, three gates.",
    14: "And the wall of the city had twelve foundation stones — and on them were the twelve names of the twelve apostles of the Lamb.",
    15: "And the one who spoke with me had a measuring rod of gold — to measure the city, its gates, and its wall.",
    16: "And the city is laid out as a square — and its length is as great as its width. And he measured the city with the rod, twelve thousand stadia. Its length and width and height are equal.",
    17: "And he measured its wall — one hundred and forty-four cubits — by the measure of a man, which is also that of an angel.",
    18: "And the material of its wall was jasper, and the city was pure gold — like clear glass.",
    19: "The foundation stones of the wall of the city were adorned with every kind of precious stone. The first foundation stone was jasper; the second, sapphire; the third, chalcedony; the fourth, emerald;",
    20: "the fifth, sardonyx; the sixth, sardius; the seventh, chrysolite; the eighth, beryl; the ninth, topaz; the tenth, chrysoprase; the eleventh, jacinth; the twelfth, amethyst.",
    21: "And the twelve gates were twelve pearls — each one of the gates was, separately, of one pearl. And the street of the city was pure gold, like transparent glass.",
    22: "And I saw no temple in it — for the Lord God, the Almighty, and the Lamb are its temple.",
    23: "And the city has no need of the sun or of the moon to shine on it — for the glory of God has illumined it, and its lamp is the Lamb.",
    24: "And the nations will walk by its light — and the kings of the earth will bring their glory into it.",
    25: "And in the daytime — for there will be no night there — its gates will not be shut.",
    26: "And they will bring the glory and the honor of the nations into it.",
    27: "And nothing unclean will ever enter it — nor anyone who practices abomination and lying — but only those whose names are written in the Lamb's Book of Life.",
}
ch22 = {
    1: "And he showed me a river of the water of life, clear as crystal — coming from the throne of God and of the Lamb,",
    2: "in the middle of its street. And on either side of the river was the tree of life, bearing twelve kinds of fruit, yielding its fruit every month. And the leaves of the tree were for the healing of the nations.",
    3: "And there will no longer be any curse — and the throne of God and of the Lamb will be in it. And His bondservants will serve Him.",
    4: "And they will see His face — and His name will be on their foreheads.",
    5: "And there will no longer be any night. And they will not have need of the light of a lamp, nor the light of the sun — because the Lord God will illumine them. And they will reign forever and ever.",
    6: "And he said to me, \"These words are faithful and true.\" And the Lord, the God of the spirits of the prophets, sent His angel to show to His bondservants the things which must shortly take place.",
    7: "\"And behold, I am coming quickly. Blessed is the one who keeps the words of the prophecy of this book.\"",
    8: "And I, John, am the one who heard and saw these things. And when I heard and saw, I fell down to worship at the feet of the angel who showed me these things.",
    9: "And he said to me, \"See that you do not do that. I am a fellow bondservant of yours, and of your brothers the prophets, and of those who keep the words of this book. Worship God.\"",
    10: "And he said to me, \"Do not seal up the words of the prophecy of this book — for the time is near.",
    11: "Let the one who does wrong still do wrong — and let the one who is filthy still be filthy. And let the one who is righteous still practice righteousness — and let the one who is holy still keep himself holy.\"",
    12: "\"Behold, I am coming quickly — and My reward is with Me, to give to each one as his work is.",
    13: "I am the Alpha and the Omega — the First and the Last, the Beginning and the End.",
    14: "Blessed are those who wash their robes — so that they may have the right to the tree of life, and may enter by the gates into the city.",
    15: "Outside are the dogs, and the sorcerers, and the sexually immoral, and the murderers, and the idolaters — and everyone who loves and practices a lie.",
    16: "I, Jesus, have sent My angel to testify these things to you for the churches. I am the Root and the Offspring of David — the bright morning star.\"",
    17: "And the Spirit and the bride say, \"Come.\" And let the one who hears say, \"Come.\" And let the one who is thirsty come — and let the one who wishes take the water of life freely.",
    18: "I testify to everyone who hears the words of the prophecy of this book: if anyone adds to them, God will add to him the plagues that are written in this book.",
    19: "And if anyone takes away from the words of the book of this prophecy, God will take away his part from the tree of life and from the holy city — those things which are written in this book.",
    20: "The One who testifies to these things says, \"Yes, I am coming quickly.\" Amen. Come, Lord Jesus.",
    21: "The grace of the Lord Jesus be with all the saints. Amen.",
}
CHAPTERS = {12: ch12, 13: ch13, 14: ch14, 15: ch15, 16: ch16, 17: ch17, 18: ch18,
            19: ch19, 20: ch20, 21: ch21, 22: ch22}

def main():
    new_entries = {f"66_{ch}_{v}": text for ch, verses in CHAPTERS.items() for v, text in verses.items()}
    print(f"Revelation 12-22 verses authored: {len(new_entries)}")
    with open(MBT_PATH) as f: existing = json.load(f)
    existing.update(new_entries)
    with open(MBT_PATH, "w") as f: json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"mbt-nt-extra.json: {len(existing)} total verses")
    with open(MOOP_PATH) as f: moop = json.load(f)
    moop.update(new_entries)
    with open(MOOP_PATH, "w") as f: json.dump(moop, f, ensure_ascii=False)
    print(f"moop-translation.json: merged {len(new_entries)} MBT Revelation 12-22 verses")

if __name__ == "__main__":
    main()
