name = "amen-counter"
main = "index.js"
compatibility_date = "2026-06-01"

routes = [
  { pattern = "usmcmin.org/api/amen*", zone_name = "usmcmin.org" },
  { pattern = "www.usmcmin.org/api/amen*", zone_name = "usmcmin.org" }
]

[[kv_namespaces]]
binding = "AMEN"
id = "5f6a78c08d3f471f97dc442b6cba8d87"
